### ISSUE TITLE
Hammerhead throw an error, when "xhr.onreadystatechange" property is broken.

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#1012]
We have faced with situation, when  getter and setter of property `xhr.onreadystatechange` are broken.
In cases without testcafe, it doesn't lead to a problem, when isn't using. But when we try to use testcafe, it tries to check this property [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/xhr.js#L112). It leads to problem, regardless of is used whether `xhr.onreadystatechange` on the original page or not.

[Example](https://github.com/getsentry/raven-js/issues/808), where another frameworks try to use this property

**Comment by LavrovArtem** [comment]
fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/1287
