### ISSUE TITLE
Inputs should not be cleared after reloading in Firefox

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1013]
Firefox preserves values and states of inputs after reloading, but under Hammerhead inputs get empty. E.g. checked checkbox should remains checked, and text inputs should have the same text.

**Comment by AndreyBelym** [comment]
It happens because Hammerhead adds `autocomplete="off"` attribute.

**Comment by miherlosev** [comment]
Need to investigate a possibility turn off autocomplete feature on browser level.
Maybe add flag to browser command line or something else.
