### ISSUE TITLE
"X-Frame-Options: ALLOW-FROM ..." prevents iframe from loading

### ISSUE THREAD

**Issue by nik-garmash** [DevExpress/testcafe-hammerhead#1017]
From what I see ALLOW-FROM can be used in two different cases:
1. To list specific origins where page can be loaded as an iframe
2. To perform some authorization, based on the request headers.

And the second case seems to be broken as hammerhead sends origin of the application under test but ALLOW-FROM header is tested against test-server's hostname in the browser.

Example:

1. Server example.com serves page and it has an authorization that this page can be rendered as an iframe only on subdomains *.example.com.
2. Application is served under app.example.com and tries to request page to display it within iframe, Origin header in request is "Origin: http://app.example.com".
3. Server looks for Origin header, it is a subdomain of example.com, so it copies Origin to X-Frame-Options header and sends "X-Frame-Options: ALLOW-FROM http://app.example.com"
4. Browser checks for same-origin of current domain and ALLOW-FROM header, everything is ok — iframe is rendered.

But when the application is under test, 4th step is broken because current domain (which serves testing-server) does not pass same-origin policy.

The solution might be to send test-server's domain as Origin when requesting iframes.
Does it sound like an issue to you, guys?

More info:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://tools.ietf.org/html/rfc7034

**Comment by churkin** [comment]
Hi @nik-garmash,
Thank you that have done this work, but I need some time to investigate this issue. I'll do it in the near future.

**Comment by miherlosev** [comment]
Yes, it is a bug.
I am fixing this in the linked pull request.
We can publish a new version if you need it.

**Comment by nik-garmash** [comment]
A new version would be great.
Thank you.
