### ISSUE TITLE
Array buffer allocation failed

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1019]
There is a problem in `brotli` module -  sometime it fails with error `Array buffer allocation failed`.
The problem presents in open source and paid versions.

I have reproduced this problem in Window10 with 1 CPU and 1Gb RAM.

![Error](https://cloud.githubusercontent.com/assets/4133518/22327205/130308d0-e3c7-11e6-9b59-28c055c7675b.png)

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
https://github.com/devongovett/brotli.js/issues/14

**Comment by churkin** [comment]
https://github.com/DevExpress/testcafe-hammerhead/pull/1047
