### ISSUE TITLE
Add the ability to set outside proxy url

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#1032]

**Comment by AlexanderMoskovkin** [comment]
@LavrovArtem please add the feature description here, how to use it

**Comment by LavrovArtem** [comment]
We can set external proxy settings by calling the `setExternalProxySettings` function from `Session` instance.
Arguments:
* url - string
* ignoreHosts - array with non-proxied hosts
Also we can call this function by pass third argument to the `openSession` function from `Proxy` instance.
The third argument is object that contains two properties `url` and `ignoreHosts`.
