### ISSUE TITLE
document.all property doesn't overridden

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#1046]
The issue is reproducing in playground.
https://www.screencast.com/t/KwMlQHC6NS

**Comment by miherlosev** [comment]
Initially, bug happens because `typeof document.all` equals `undefined`.
But, to completely support `document.all` instruction, we should instrument this property.

We decide to postpone fix to first user issue.


Script for reproduce:
```js
<html>
	<head>
	</head>
	<body>
		<script>
		    var allTags = document.all;
			
			for(var i = 0; i < allTags.length; i++)
				console.log(allTags[i]);
		</script>
	</body>
</html>
```

**Comment by miherlosev** [comment]
http://ya.ru/ 
http://yandex.com/ 
http://www.yandex.ru/
