### ISSUE TITLE
Wrong svg element processing in IE

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1083]
Reproduced in playground in IE11:

1) Open [DevExtreme Charts demo page](https://js.devexpress.com/Demos/WidgetsGallery/Demo/Charts/AjaxRequest/jQuery/Light/) in playground
2) Export chart image:
    a) click here: 
![2017-04-10_1625](https://cloud.githubusercontent.com/assets/12047804/24863664/743c0a3e-1e0a-11e7-9ecc-57aec84f7396.png)
    b) select "PNG file"
3) The `SyntaxError` error is appeared when the following code is called:
```js
var s = new DOMParser();
s.parseFromString(e, "image/svg+xml")
```
Without hammerhead processing `e` looks like:
```html
<svg xmlns="someurl" version="1.1">...</svg>
```
But with processing it looks like:
```html
<svg xmlns="someurl" version="1.1" xmlns:NS1="" NS1:xmlns:ns1="">...</svg>
```
It brokes the `parseFromString` function

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
This bug occurs in IE11 only.
Example for reproducing:
```javascript
var svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
var div = document.createElement('div');

svg.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
svg.setAttribute('xmlns:xlink', 'http://www.w3.org/1999/xlink');

var a = document.createElement('a');

a.href = '/path';
svg.appendChild(a);

div.appendChild(svg.cloneNode(true));
alert(div.innerHTML);
```
Without hammerhead:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:NS1="" NS1:xmlns:xlink="http://www.w3.org/1999/xlink"><a href="/path"></a></svg>`
With hammerhead:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:NS1="" NS1:ns1:xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:NS2="" NS2:xmlns:ns1=""><a href="/path" /></svg>`

**Comment by Farfurix** [comment]
This issue is relevant for all nested SVG element tags:
```javascript
const SVG_XLINK_HREF_TAGS = [
    'animate', 'animateColor', 'animateMotion', 'animateTransform', 'mpath', 'set', //animation elements
    'linearGradient', 'radialGradient', 'stop', //gradient elements
    'a', 'altglyph', 'color-profile', 'cursor', 'feimage', 'filter', '<font-face-uri', 'glyphref', 'image',
    'mpath', 'pattern', 'script', 'textpath', 'use', 'tref'
];
```
