### ISSUE TITLE
Service messages with cookies don't have time to come to server before new page is loaded

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1086]
It's simple example which reproduces this behouver:
```javascript
var http = require('http');

http.createServer(function(req, res) {
    switch (req.url) {
        case '/':
            return res.end(`
                <script>
                    document.cookie = 'hnet-lifetime=value';
                    document.cookie = 'hnet-session=value';

                    document.location.pathname = '/show-cookie';
                </script>
            `);
        case '/show-cookie':
            return res.end(req.headers.cookie);
        default:
            res.end('');
    }
}).listen(1993);
```
Without hammerhead:
![image](https://cloud.githubusercontent.com/assets/5373460/24951057/cd71257c-1f7b-11e7-9002-0d5a99bba985.png)
With hammerhead:
![image](https://cloud.githubusercontent.com/assets/5373460/24951144/15b96a74-1f7c-11e7-9c0a-3faddab392f4.png)

**Comment by inikulin** [comment]
https://developer.mozilla.org/ru/docs/Web/API/Navigator/sendBeacon - works in Edge, FF, Chrome

**Comment by brettveenstra** [comment]
Hello, would this be related to DevExpress/testcafe#1421?  We rely on HTTP Only cookies for using the new Roles feature

**Comment by LavrovArtem** [comment]
Hi @brettveenstra 
No, this issue isn't related to DevExpress/testcafe#1421

**Comment by LavrovArtem** [comment]
I'm working on this
