### ISSUE TITLE
Canvas rendered incorrectly after processing

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1087]
Reproduced in playground. 
Page: http://photo-mosaic-service.bluerobot.com/7683410f-0803-11e7-8bd8-42010af003a4/index.html
See https://github.com/DevExpress/testcafe/issues/1398 for details

**Comment by AndreyBelym** [comment]
Maybe related to https://isc.devexpress.com/Thread/WorkplaceDetails/T230389

**Comment by miherlosev** [comment]
Dublicate of https://github.com/DevExpress/testcafe-hammerhead/issues/850
