### ISSUE TITLE
Cannot read property 'origin' of undefined

### ISSUE THREAD

**Issue by choucalate** [DevExpress/testcafe-hammerhead#1090]
I'm trying out testcafe for the first day and I'm getting this error when running testcafe against something I'm running locally.

testcafe chrome tests/

1) Error on page "http://localhost:9000#/":
Uncaught Error: Cannot read property 'origin' of undefined

![image](https://cloud.githubusercontent.com/assets/2937080/25076243/ca9964d0-22d3-11e7-8744-c01b93288c91.png)

Not sure why it's happening though or if my setup is incorrect.  Any advice on how to fix it?

However, it seems to work on safari.

**Comment by miherlosev** [comment]
hi choucalate 
I am investigating your problem.

**Comment by miherlosev** [comment]
I've reproduced your problem only when tested page contains a script code that accesses an undefined variable in  the`window.addEventListener('message')` handler.

Something like:
```js
window.addEventListener('message', function (e) {
    var wrongVar = undefined;
 
    console.log(wrongVar.origin);
});
window.postMessage('message', '*');
```

Try to open your tested page in Google Chrome and inspect the DevTools Console Tab content.
If it contains errors, fix them or run `testcafe` with [skip-js-errors](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors) command line parameter.
If it doesn't contain errors, provide your test code, please.
We will investigate this in detail.

**Comment by choucalate** [comment]
Thanks @miherlosev I'll try that out and let you know if I run into anything!
