### ISSUE TITLE
request-credentials API example

### ISSUE THREAD

**Issue by brettveenstra** [DevExpress/testcafe-hammerhead#1094]
Do you have an example for how to control the `x-hammerhead|fetch|request-credentials` value?  Currently it says `omit` but for our scenario, we need to `include` credentials for most Requests

**Comment by miherlosev** [comment]
`omit` is the default value for the request's credentials mode (see 
https://fetch.spec.whatwg.org/#concept-request-credentials-mode).
You don't need to manually control the `x-hammerhead|fetch|request-credentials` header value. It is a service header and its value is automatically synchronized with Request' credentials mode value.
So, use a Request with the 'include' credentials mode as follows:
```js
      fetch('/someurl', {
          method:      'post',
          headers:     { 'Content-Type': 'application/json; charset=UTF-8' },
          credentials: 'include'
      })
```
See the examples in our tests - https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/fetch-test.js

**Comment by brettveenstra** [comment]
Thanks for pointing the tests out... it doesn't appear that the tests cover the `include` option.  Are you certain that works?

Perhaps that would address the issue DevExpress/testcase#1421 as well... that's the root of my question in the first place.  :smile:

**Comment by miherlosev** [comment]
> Are you certain that works?

I've created an example.
[i1094.zip](https://github.com/DevExpress/testcafe-hammerhead/files/946306/i1094.zip)
This example demonstrated that cookies set on the client were successfully sent to the server (with `credentials: include` options).

> Perhaps that would address the issue DevExpress/testcafe#1421 as well... that's the root of my question in the first place. 😄

I will investigate this issue.

**Comment by miherlosev** [comment]
I've fixed the issue related to the fetch method proxying mechanism (https://github.com/DevExpress/testcafe-hammerhead/issues/1116)
I guess it fixed your initial problem.
Check you issue with the latest testcafe version (0.16.0) and feel free to reopen this issue if the wrong behavior is reproduced.
