### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded when RegEx.prototype.test overriden in a client code

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1098]
Code for reproduce:
```js
<script>
        RegExp.prototype.test = function () {
            return [].length;
        };

        console.log(new RegExp('/\S/').test());
    </script>
```

**Comment by miherlosev** [comment]
I'm working on this

**Comment by link89** [comment]
Is there any progress for this issue? We have similar issue when using testcafe with a mobx based SPA.

**Comment by AlexSkorkin** [comment]
We will update this thread once we make progress.

**Comment by LavrovArtem** [comment]
This issue has already been fixed. @link89, please create a new issue if the problem is still reproducible.
