### ISSUE TITLE
Check a performance on a simple page with ASPxButtonEdit

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1104]
There is a page with the `ASPxButtonEdit` control:
```aspx
<%@ Page Language="C#" %>

    <!DOCTYPE html>

    <html xmlns="http://www.w3.org/1999/xhtml">

    <head runat="server">
        <title></title>
        <script>
            window.setInterval(() => {
                if (typeof buttonEdit === "undefined") alert('button edit is not initialized');
            }, 0);
        </script>
    </head>

    <body>
        <form id="form1" runat="server">
            <div>
                <dx:ASPxButtonEdit ID="buttonEdit" Theme="Material" runat="server">
                    <ClearButton DisplayMode="OnHover"></ClearButton>
                    <Buttons>
                        <dx:EditButton Text="123"></dx:EditButton>
                    </Buttons>
                </dx:ASPxButtonEdit>
                <div style="width:10px; height:10px; background-color: green;" id="pit_stop"></div>
            </div>
        </form>
    </body>

    </html>
```
(here is an internal url of the page: http://localhost/171/RegressionTestsSite/ASPxEditors/ASPxButtonEdit/T506391.aspx). You can run this locally by building asp team sources or ask some of a asp team memeber for a help)

In the head there is a script. It checks that the `buttonEdit` control is initialized after the timeout `0`.
It works properly on the original page (tested in Chrome). But under proxy the alert `button edit is no initialized` is appeared. It works properly if we increase the timeout to ~400.

So, it seems that rendering and initializing ASPxButtonEdit control takes less than 0ms on the original page and about 400ms in a proxied page.
It seems, it's too much. So we should check why it happens, where is the performance problem

**Comment by miherlosev** [comment]
I found the problem in your scripts https://www.screencast.com/t/Und0NedcK
Firstly, fix it. 
If problem will reproduced, then reopen this issue.
