### ISSUE TITLE
Performance slow down

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#1111]
Firefox profiler after testcafe qunit test execution
https://www.screencast.com/t/ujSwtpHN - current release version (10.6.8)
https://www.screencast.com/t/u3UMlLIomqow - previous version (10.6.7)

This slow-down appeared due to this commit
https://github.com/DevExpress/testcafe-hammerhead/commit/885436e6090d968e5c44ac7cb2deae9765865be5

**Comment by georgiy-abbasov** [comment]
In a nutshell - we implemented node collection wrapper, which provide live collections. It provides NodeList, which is already filtered from shadow ui elements. This object redefine its properties (and filter nodes), when there is an appeal to read its length property.

**Comment by miherlosev** [comment]
The  commit that causes a performance degradation was reverted - https://github.com/DevExpress/testcafe-hammerhead/commit/4cdff8a06ed42816402f65a8bf1615b565823f45
