### ISSUE TITLE
"Add topics" link at a GitHub repository doesn't work

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1129]
See details in the [TestCafe issue](https://github.com/DevExpress/testcafe/issues/1480).

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Cann't reproduce on the latest commit  29d63c6 in hammerhead playground.
Possible fix - https://github.com/DevExpress/testcafe-hammerhead/commit/29d63c61d8a9d077150ee8e5b6b86bd6c3921057
Need to check on the latest testcafe version

**Comment by miherlosev** [comment]
I put a latest hammerhead version to the current testcafe and all work good. So, issue is fixed.
