### ISSUE TITLE
Client html util cleanUpHtml doesn't clean `data-hammerhead-focused` attribute

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1143]
Here is `data-hammerhead-hovered` is removed: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/html.js#L158
Here should be `data-hammerhead-focused` removing too.

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by antunesfabio** [comment]
I am currently using testcafe version 0.21.0 and I am facing this issue as you can see on the screenshot below. Should I raise a new bug or can you reopen this issue?

![screen shot 2018-09-20 at 10 43 12](https://user-images.githubusercontent.com/11940807/45814284-10bdec80-bccd-11e8-9f91-70ef1aded3d6.png)

**Comment by AlexSkorkin** [comment]
It's unclear what issue you faced. In this thread, we have fixed the issue that the htmlUtil.cleanUpHtml method does not clear up the data-hammerhead-focused attribute. However, this attribute should be used when you are running a test and do not call the cleanUpHtml method. Since the cleanUpHtml method is private and you do seem to call it, would you please clarify what issue you faced with this attribute presence in your markup?

**Comment by antunesfabio** [comment]
Sure. I will try to explain the best I can - I believe the presence of this attribute in my markup is affecting the normal behaviour of the page and this is affecting most testcafe commands like `click`, `doubleClick`, `selectText`, `typeText`, etc.

On the link below, I am sharing a screen recording where I have the same page side to side, the one in the left is in debug mode with testcafe. To demonstrate the different behaviour, I attempt to click and doubleClick on both. You can see that on the right, a double click selects one word and a triple click selects a paragraph. In test cafe debug mode, one single click selects the entire paragraph immediately. And the `data-hammerhead-` attributes are the only difference which makes me think they are the cause. 

I am happy to send you a test script and access to this page if you want to do some debuging on your end.

https://drive.google.com/file/d/1V8LE0HTBiVpqxp6LEft__nWozcim6fyO/view?usp=sharing

**Comment by LavrovArtem** [comment]
Yes, please share your test and URL, so we can take a look.

**Comment by antunesfabio** [comment]
Sorry, I missed your reply.  I added you all to a private repo that only contains a test script that demonstrates the behaviour I am talking about. There you can also find the URL and user credentials.

**Comment by LavrovArtem** [comment]
Thank you for the provided information! Could you please create a new issue since this is not related to the original one? Thank you in advance.

**Comment by LavrovArtem** [comment]
I've debugged your site. Your problem related to [this issue](https://github.com/DevExpress/testcafe-hammerhead/issues/1769) and we will fix it soon. ([PR](https://github.com/DevExpress/testcafe-hammerhead/pull/1795))

**Comment by antunesfabio** [comment]
These are great news! Thank you very much.
