### ISSUE TITLE
Hammerhead crashes on the slack.com/signin page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1195]
Just open the https://slack.com/signin page in the playground

![2017-06-29_1435](https://user-images.githubusercontent.com/12047804/27685739-3ea43f1a-5cd8-11e7-84e9-0ae1e3591509.png)

**Comment by LavrovArtem** [comment]
Problem is `<meta name="referrer" content="no-referrer">` tag

**Comment by LavrovArtem** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/997

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
https://w3c.github.io/webappsec-referrer-policy/#referrer-policies
