### ISSUE TITLE
Transformer post-message-get can create invalid Javascript

### ISSUE THREAD

**Issue by LinusBorg** [DevExpress/testcafe-hammerhead#1197]
## Short Description

I encountered a bug with testcafe-hammerhead, or more precicely, this transform:

https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/script/transformers/post-message-get.js

This transform produces invalid Javascript when we have an object method of the name `postMessage` on a plain object, and that code is transpiled by babel (preset used:babel-preset-env) and bundled with webpack.

While the code runs well without testcafe, when accessed through testcafe running a fixture, it turns this:
```javascript
/* harmony default export */ __webpack_exports__["default"] = ({

  methods: {
    postMessage: function postMessage(event) {
      console.log('Hello!');
    }
  }
});
```

into this:

```javascript
/* harmony default export */ __webpack_exports__["default"] = ({

  methods: {
    postMessage: function  __get$PostMessage(null,postMessage)(event) {
      console.log('Hello!');
    }
  }
});
```

However, this doesn't seem to happen when the code is not bundled with webpack.

## Demo reproduction Repository

https://github.com/LinusBorg/testcafe-hammerhead-postMessage-bug

The repository's README has more information and detailed instructions about how to reproduce the behaviour.

**Comment by LavrovArtem** [comment]
Hi @LinusBorg,
Thanks for the detailed description. I'm working on this.

**Comment by LinusBorg** [comment]
Happy to help :)

Thanks for a great tool!

**Comment by LinusBorg** [comment]
I'll delete my repo. If you need it again, let me know.
