### ISSUE TITLE
Images with style = background-image: url("img.png"); aren't loaded 

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1212]

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Related only with Angular (4.1.0) and its directive `[style.background-image]`

**Comment by miherlosev** [comment]
Site for reproduce - [app.zip](https://github.com/DevExpress/testcafe-hammerhead/files/1241490/app.zip)

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by miherlosev** [comment]
`list-style-image`, `border-image` too

**Comment by LavrovArtem** [comment]
I know 😄 Also must be overridden `CSSStyleDeclaration.setProperty()` and `CSSStyleDeclaration.getPropertyValue()` methods.

**Comment by miherlosev** [comment]
Good. 
`getProperty/setProperty` for `MSStyleCSSProperties` and `CSS2Property`
