### ISSUE TITLE
Support web workers created by a Blob URL

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1221]
#### Example for reproducing:
```javascript
var log = function () {
    console.log(XMLHttpRequest.prototype.abort.toString());
};

var blob = new Blob(['(', log.toString(), ')()'], { type: 'application/javascript' })
var url = URL.createObjectURL(blob);

log();

new Worker(url);
```
#### Console output:

![image](https://user-images.githubusercontent.com/5373460/28175990-81e4e3f2-67fe-11e7-8118-de2b85eaaa16.png)

#### Reproduced on https://www.aol.com/
```bcb3266b-9cd7-40fe-835c-65e1c864088e:41 XMLHttpRequest cannot load https://b.aol.com/ping?ts=1499953831845&h=www.aol.com&v=60&r=&l=4057&k=1&m=1920x1080&bd=1903x442&tz=-180&ms=21418&da_pr=1&da_ar=16/9&t=AOL%20-%20News%2C%20Weather%2C%20Entertainment%2C%20Finance%20%26%20Lifestyle&dL_url=https%3A%2F%2Fwww.aol.com%2F&nm=scroll&dL_ch=us.aolportal&dL_dpt=acm%3A%20main&dL_sDpt=acm%3A%20main&cms_src=us-aol.com&cobrand=amp-nav-test-5-g&template=default.layout.twig&fv=26.0&ads_grp=953808191&dL_abp=0&dL_evft=amp-nav-test-5-g&dL_vid=video_novideo&kb=842&dL_crY=442&dL_crYP=6&dL_mxY=442&dL_mxYP=6&dL_inY=442&dL_inYP=6&dL_tscp=21&pgvis=1&txt=1&dL_r=https%3A%2F%2Fwww.aol.com%2F. The 'Access-Control-Allow-Origin' header has a value 'http://localhost' that is not equal to the supplied origin. Origin 'http://localhost:1401' is therefore not allowed access.```

**Comment by Farfurix** [comment]
One more issue: https://github.com/DevExpress/testcafe-hammerhead/issues/1970.
Project: https://github.com/ZhijieZhang/testcafe_sample.
Environment: Windows 10 / Firefox 67.0.

https://github.com/ZhijieZhang/testcafe_sample/blob/master/lib/core/pdf/PDFworker.js#L131:
```js
d=new XMLHttpRequest; // native XMLHttpRequest
d.open("GET",a.url,a.isAsync); // a.url === 'lean/PDFNetCWasm.br.js.mem'
var e=b&&d.overrideMimeType;
d.responseType=e?"text":"arraybuffer";
e&&d.overrideMimeType("text/plain; charset=x-user-defined");
d.send();
```

**Comment by bezua** [comment]
Hello,

Is there a chance to at least estimate delivery date for this guy?
Regards

**Comment by Dmitry-Ostashev** [comment]
@bezua At present, we cannot give you any precise time estimates.
