### ISSUE TITLE
Override 'hasAttribute' method only for HTMLInputElement.prototype

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1225]
We override `Element.hasAttribute` method only for case with `input autocomplete='off'`.
Instead of overrideing `Element.prototype.hasAttribute ` we can override only the `window.HTMLInputElement.prototype`.

It is performance optimization case.
Because the overriden method will be called only for inputs. For all elements will be used a native method.

**Comment by LavrovArtem** [comment]
Client code can override `Element.prototype.hasAttribute`
