### ISSUE TITLE
Implement the 'srcdoc' attribute processing in iframe element

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1237]
reproduced on https://www.wp.pl/

**Comment by LavrovArtem** [comment]
also http://www.daum.net/

**Comment by AndreyBelym** [comment]
See also https://github.com/DevExpress/testcafe/issues/3323.

**Comment by cvoege** [comment]
Is there any update on this?

**Comment by miherlosev** [comment]
At present, this bug is not fixed. We are going to fix it in the current development sprint.

**Comment by cvoege** [comment]
Thanks!! Do you have an ETA?

**Comment by Farfurix** [comment]
@cvoege 

Hello,
 
We are working on it in the current development sprint.
However, I cannot give any estimate at the moment. Please stay tuned for updates in this thread.

**Comment by cvoege** [comment]
Any update here? We still can't upgrade testcafe due to this bug

**Comment by Farfurix** [comment]
@cvoege 

Hello,

We are working on it. We will update this thread once we have any information to share.

**Comment by LavrovArtem** [comment]
A simple example that crashes Chrome with the `STATUS_ACCESS_VIOLATION` error:
```html
<iframe srcdoc="<script>document.write(123)</script>"></iframe>
```
