### ISSUE TITLE
Document can contains two ShadowUI root for the specified case

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1246]
see [comment](https://github.com/DevExpress/testcafe-hammerhead/pull/1243#issuecomment-317991689) for more details

Test `SVG elements' className is of the SVGAnimatedString type instead of string (GH-354)` from
`C:\Hammerhead_github\test\client\fixtures\sandbox\shadow-ui-test.js`

**Comment by miherlosev** [comment]
![Screenshot](https://user-images.githubusercontent.com/4133518/30218644-3a1097d8-94c2-11e7-9252-cdb9ade5c01a.png)

**Comment by LavrovArtem** [comment]
If we try to use
```javascript
setProperty(document.body, 'innerHTML', '<svg></svg>' + setProperty(document.body, 'innerHTML'));
```
instead of 
```javascript
setProperty(document.body, 'innerHTML', '<svg></svg>' + document.body.innerHTML);
```
then everything will be ok.
