### ISSUE TITLE
Exception when testing with PhantomJS

### ISSUE THREAD

**Issue by sudsy** [DevExpress/testcafe-hammerhead#1250]
I have seen that phantomjs support is deprecated, but I need to use it because it seems to closely mirror the behaviour of the googlebot. 

(For instance const declarations in certain situations seem to break both googlebot and phantomjs - I will write something up on this once I can demonstrate a clear case)

I am happy to put in a PR for this one if you would accept it.

Basically, on one of the pages I am testing I get  

```
Message: FocusEventConstructor is not a constructor (evaluating 'new
      p["default"].WindowFocusEvent(t,{bubbles:o,cancelable:!1,cancelBubble:!1,defaultPrevented:!1})')
```

Seems to come down to the feature detection on this [line](https://github.com/DevExpress/testcafe-hammerhead/blob/67618b251aa3fcf9958870b9fd0419804203c9d8/src/client/sandbox/event/simulator.js#L597):

**Comment by miherlosev** [comment]
We have researched the possibility to support PhantomJS.
There are several issues we need to take into account:
[Object.defineProperty]
https://github.com/ariya/phantomjs/issues/14310
https://github.com/ariya/phantomjs/issues/13895
[Psedo-selector `:focus`]
https://github.com/ariya/phantomjs/issues/10427
[WebWorker]
https://github.com/ariya/phantomjs/issues/13653
These problems affect many parts of our code and it takes huge work to fix them.
Are you sure you want to do it?

Also note that PhantomJS development is finished (https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ).
The good alternative to PhantomJS is Google Chrome in the [headless mode](https://www.chromestatus.com/feature/5678767817097216)
TestCafe ships with build-in support for headless testing. 
For more details, see the [Running Tests in Headless Mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browser-support.html#running-tests-in-headless-mode) article

**Comment by sudsy** [comment]
That sounds like a world of pain. Thanks for the heads up.

While I do need to do some testing on an old version of webkit to ensure compatibility with googlebot, the tests are fairly simple and could be managed by driving phantomjs directly.

Cheers,

Ben
