### ISSUE TITLE
Hammerhead memory leak in IE for live node collections

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1262]
Reproduces on tests from internal farm tasks: 
DashboardTests.v17.1.TestCafe - old testcafe
DashboardTests.v17.1.TestCafe.IE - new testcafe

Contact person: Denis Kuznetsov

**Comment by LavrovArtem** [comment]
I've investigated memory leak in IE and found out that one reason of this is `LiveNodeListFactory`.
![image](https://user-images.githubusercontent.com/5373460/29452059-a9e0646e-840d-11e7-9d65-874d37637d43.png)
I've created nine identical tests on https://demos.devexpress.com/Dashboard/?mode=viewer. After tests IE took up 1.5GB of memory when I run it on `0.17.1` version. But IE took up 1.2GB when I run tests on `0.17.0-alpha2` which do not contain `LiveNodeListFactory`.
Test example:
```javascript
import { Selector } from 'testcafe';

fixture `Dashboard`
	.page `https://demos.devexpress.com/Dashboard/?mode=viewer`

test('test', async t => {
	let listItem = new Selector('.dx-item.dx-list-item');

	await t
		.click(listItem.withText('Sales Overview'))
		.click(listItem.withText('Sales Performance'))
		.click(listItem.withText('Sales Details'))
		.click(listItem.withText('Revenue Analysis'))
		.click(listItem.withText('Human Resources'))
		.click(listItem.withText('Customer Support'))
		.click(listItem.withText('Revenue by Industry'))
		.click(listItem.withText('Energy Consumption'))
		.click(listItem.withText('Energy Statistics'));
});
```
