### ISSUE TITLE
Should proceess property accessors like "location.href = 'javascript:input.autocomplete="on"'"

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1292]

**Comment by LavrovArtem** [comment]
I think it related with https://github.com/DevExpress/testcafe-hammerhead/issues/1274

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/commit/b44385a152c45144b5a61815f23625012052067c
