### ISSUE TITLE
'Document.registerElement' should be overriden

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1317]
https://developer.mozilla.org/ru/docs/Web/API/Document/registerElement
We should override element constructor. 
`var elementConstructor = document.registerElement(tag-name, options);`

If we create element via `document.createElement` then it has overriden properties.
If we create its via registered element constructor then we does not override element properties.

**Comment by LavrovArtem** [comment]
Currently, all properties are overridden by changing descriptor and everything should works. If I'm not right please reopen this issue.
