### ISSUE TITLE
Wrong proxing of absolute path in Firefox

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1330]
This problem can be reproduced by running test:
```js
import path from 'path';

fixture `Fixture`
    .page `http://localhost/testcafe`;

test('Navigate to absolute file page', async t => {
    await t
        .navigateTo(path.join(__dirname, './some-page-in-the-same-dir.html'))
        .debug();
});
```
In TestCafe we just use `hammerhead.navigateTo` (see [here](https://github.com/DevExpress/testcafe/blob/master/src/client/driver/command-executors/execute-navigate-to.js#L14)) and it works in Chrome and doesn't work in Firefox

**Comment by miherlosev** [comment]
Need to add `file:///` protocol prefix before relative and absolute paths.
It already done for `page` directive (https://github.com/DevExpress/testcafe/blob/4d668941254d30cb9992fe4fcc65171f8f7db4f8/src/api/structure/testing-unit.js#L49)

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe/issues/1837
