### ISSUE TITLE
Don't update urlResolver if page already contains `base` tag

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1349]
We should not update `urlResolver` base path if page already contains `base` tag.
We should to emulate native browser behavior and consider only first one.

To reproduce the issue need to open  https://miherlosev.github.io/issue-pages/hammerhead/1349/folder/page.html url in hammerhead playground.
In console will displayed a resolved url
Without proxy: https://miherlosev.github.io/0.js
With proxy: https://miherlosev.github.io/issue-pages/hammerhead/1349/folder/0.js

Related to https://github.com/DevExpress/testcafe/issues/1912

**Comment by miherlosev** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
I'm working on this
