### ISSUE TITLE
Can't set the `nextSibling` properly of a plain object to null

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1351]
**Tested page:**
```js
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <input id="input" />
    <script>
        function MyClass () {
            this.nextSibling = document.getElementById('input');
        }

        var instance = new MyClass();

        instance.nextSibling = null;

        alert(instance.nextSibling);
    </script>
</body>
</html>
```

**Without hammerhead:** `alert(null)`.
**With hammerhead:** `alert(<input-element-description>)`.

**Reason:**
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/properties/index.js#L406

```js
nextSibling: {
  condition: node => node.nextSibling && domUtils.isDomElement(node.nextSibling),
  get:       node => domUtils.isShadowUIElement(node.nextSibling) ? null : node.nextSibling,
  set:       () => void 0
},
```

It seems we should add one more check to the condition like: `domUtils.isDomElement(node),`.
Additionally take a look at other properties. It possible there similar things there.

**Comment by miherlosev** [comment]
I'm working on this
