### ISSUE TITLE
'Refresh' header should be overriden

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1354]
related to https://github.com/DevExpress/testcafe/issues/1920

see header specification in https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

**Comment by miherlosev** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
The `refresh` header already overridden on client.
https://github.com/DevExpress/testcafe-hammerhead/blob/632f1344c0459217c8e96f1ee9bb672eb60e0978/src/processing/dom/index.js#L365-L371
