### ISSUE TITLE
Fix unstable qunit tests using "quarantine" mechanism in quint-harness

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#136]
see builds:
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/82572486
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/82124455
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/82108151
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/84298914
https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/builds/84291375

see discussion - https://github.com/superroma/testcafe-hammerhead/pull/128#issuecomment-143738164
Wait for functionality from https://github.com/AlexanderMoskovkin/qunit-harness/issues/6

**Comment by inikulin** [comment]
@miherlosev  Please, refer the discussion and add more info to the title and description. Hint: we should fix it using "quarantine" mechanism in quint-harness

**Comment by churkin** [comment]
@inikulin @AlexanderMoskovkin 

Guys, I propose to make a simple decision and cease to suffer with the unstable tests. 
```javascript
 window.wait = function (condition) {
        return new Promise(function (resolve) {
            var timeoutId = window.setTimeout(function () {
                window.clearInterval(intervalId);
                window.clearTimeout(timeoutId);
                ok(false, 'Timeout error');
            }, 1000);

            var intervalId = window.setInterval(function () {
                if (condition) {
                    window.clearInterval(intervalId);
                    window.clearTimeout(timeoutId);
                    resolve();
                }
            }, 50);
        });
    };
```
It should solve all the problems with the hammerhead tests. I suggest not to run the tests several times. If the virtual machine slows down, all 10 times the tests will not pass. If the test works through time, it is a bad test and we have to rewrite it.

**Comment by inikulin** [comment]
@churkin I like it, but I think we should increase general timeout to 3 seconds. @AlexanderMoskovkin We should implement it in harness I guess

**Comment by AlexanderMoskovkin** [comment]
agree. Maybe we should and the second optional agrument `ms` ? We will able to cover the scenarios when we should wait more long time

**Comment by inikulin** [comment]
@AlexanderMoskovkin Do we have them? I suppose what test which waits more than 3 seconds is a bad test

**Comment by AlexanderMoskovkin** [comment]
I hope no, we have not ))

**Comment by AlexanderMoskovkin** [comment]
The `wait` feature is availabe in the `qunit-harness v.0.2.0`. Here is an example how to use it:
```js
asyncTest('test with wait', function () {
    var resolved = false;

    window.setTimeout(function () {
        resolved = true;
    }, 50);

    window.QUnitGlobals.wait(function () {
        return resolved;
    }).then(function () {
        ok(true);
        start();
    });
});
```
The test will fail with the timeout error if condition returns 'false' within 3000 ms.

I suppose you can try to fix unstable tests.
I think you need not the [Add the `attempts` parameter to tests](https://github.com/AlexanderMoskovkin/qunit-harness/issues/6) feature yet and I can close it? /cc @miherlosev @churkin

**Comment by miherlosev** [comment]
We decide don't make "quarantine" mechanism.
We have a separate issue #280 to stabilize tests
