### ISSUE TITLE
Hammerhead duplicates internal fetch header values

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#1360]
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/fetch.js#L24

Need to chage

```javascript
  headers.append(XHR_HEADERS.origin, originHeaderValue);
  headers.append(XHR_HEADERS.fetchRequestCredentials, requestCredentials);
```
to

```javascript
  headers.set(XHR_HEADERS.origin, originHeaderValue);
  headers.set(XHR_HEADERS.fetchRequestCredentials, requestCredentials);
```

**Comment by ixrock** [comment]
Is it included in testcafe `v0.18.3`?

**Comment by AlexanderMoskovkin** [comment]
@ixrock, no. We'll provide you with a `dev` version with the fix soon

**Comment by AlexanderMoskovkin** [comment]
@ixrock, We've just published a `dev` build with the fix. You can install it with the command:
`npm install testcafe@0.18.4-dev20171109 -g`

Please let me know does it work properly now on your side.

**Comment by ixrock** [comment]
@AlexanderMoskovki works fine for me! Thanks.
