### ISSUE TITLE
ContentEditable elements with custom tag names are identified like not content editable

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#1366]
Based on the [discussion](https://testcafe-discuss.devexpress.com/t/typetext-into-richtextarea/553/5).

For example for element with the `<rich-text-area>` tag name.

The reason: take a look at [this line](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js#L45).

It marks `<rich-text-area>` as `always not content editable` but actually it should mark only `<area>` elements.

**Comment by miherlosev** [comment]
I'm working on this
