### ISSUE TITLE
Support script processing for native javascript modules

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1373]
Now, we use the default `sourceType` option value for acorn: `script`.

If we trying to parse a module code then we get an error `'import' and 'export' may appear only with 'sourceType: module' (1:0)`.
Need to recognize that the current code is a module code and apply an appropriate `acorn` settings.

**Comment by Wildhoney** [comment]
I'm a bit lost as to the status of this.

Is it awaiting release? As it doesn't appear to work in the latest alpha TestCafe (`0.22.1-alpha.3`).

**Comment by miherlosev** [comment]
@Wildhoney 

I'm not sure I properly understand you.
If you are talking about [this](https://developers.google.com/web/updates/2017/11/dynamic-import), then it's a same problem. If not, please create a separate issue and create a simple example to reproduce?
