### ISSUE TITLE
Refactor 'Code instrumentation' subsystem

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1379]
We will use a native getter from property descriptor.
It allows to drop server and client script processing, improves stack traces for client errors and etc.

It will be done after updating mobile browsers `Android 6.0+`  and `Safari 10+`.

**Comment by miherlosev** [comment]
- [x] `Safari 10`
- [ ] Android 6 (after `testcafe 1.0`)

**Comment by miherlosev** [comment]
Start from `data` property, it allows to fix https://github.com/DevExpress/testcafe-hammerhead/issues/1337

**Comment by LavrovArtem** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes

**Comment by LavrovArtem** [comment]
Done!
