### ISSUE TITLE
Websocket proxy missing cookies request header

### ISSUE THREAD

**Issue by iots09** [DevExpress/testcafe-hammerhead#1383]
Hello, to authenticate my websocket connection, the server reads the cookie header, which seems to be missing when using testcafe. Is there any way to send the cookie header? I am not sure if the proxy "picks up" the cookie later(magically), but the cookie is missing in the server.

testcafe version: `0.18.3`

ws native request:
`Accept:*/*`
`Accept-Encoding:gzip, deflate, br`
`Accept-Language:en-US,en;q=0.9,lv;q=0.8`
`Cache-Control:no-cache`
`Connection:keep-alive`
`Cookie:io=_ESRx5DB-WMyskWMAAAA; __stripe_sid=...; __stripe_mid=...; token=...`
`DNT:1`
`Host:test.localhost`
`Pragma:no-cache`
`Referer:http://test.localhost/`
`User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)` `Chrome/62.0.3202.62 Safari/537.36`

ws request with testcafe:
`Accept:*/*`
`Accept-Encoding:gzip, deflate`
`Accept-Language:en-US,en;q=0.9`
`Connection:keep-alive`
`Host:192.168.11.2:41145`
`Referer:http://192.168.11.2:41145/BklBe5ZQgz/http://test.localhost/`
`User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)` `Chrome/62.0.3202.62 Safari/537.36`
`x-hammerhead|xhr|cors-supported:true`
`x-hammerhead|xhr|origin:http://test.localhost`
`x-hammerhead|xhr|request-marker:true`
`x-hammerhead|xhr|with-credentials:true`

**Comment by miherlosev** [comment]
Hi, @iots09 
Cookies are stored in the proxy's memory.
Then a cookie is set on the client (`document.cookie = ...`) or server side (via `Set-Cookie` header) and we perform synchronization.
Proxy adds a `cookie` header before sending the request to the origin server.

If authentication failed, then it looks like a bug.
Could you, please, provide an example that we can reproduce on our side?

**Comment by iots09** [comment]
Hi, @miherlosev,
 thanks for the feedback. You are right, the cookie was actually sent.
 I was hasty to jump to conclusions. I have found the cause for my problem.
 I was directly checking the raw header names using `Cookie` name. But when using testcafe, the header name is `cookie` without capitalization of first letter.
 So my simple check failed, but otherwise it works. If you want to consider it a bug, the original header name was slightly modified.

**Comment by miherlosev** [comment]
It's not a bug. Nodejs http/https modules convert header names to lowercase.

The HTTP/1.1 spec states "Field names are case-insensitive." (http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html
