### ISSUE TITLE
Proxy breaks AMP validation

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1418]
https://validator.ampproject.org/#
https://www.ampproject.org/ru/

Page to reproduce https://amp.welt.de/amp/politik/deutschland/article167948204/Stossen-an-Grenzen-Kommunen-fordern-Stopp-der-Fluechtlingsverteilung.html#development=1

**Comment by Farfurix** [comment]
I'm working on it

**Comment by miherlosev** [comment]
AMP Validator uses regular expressions to match tags and attributes.
All proxy mechanisms that hide proxy stuff from client scripts don't work in this case.
To fix the bug, we need to come up with a way to create clearer markup.
