### ISSUE TITLE
Support of the new window simulation into iframe for the login via social networks purposes

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1428]
I've figured out that we have simple way to login via social networks. I've tried to log in to the site from an [issue #1385](https://github.com/DevExpress/testcafe-hammerhead/issues/1385) via a Facebook account and I've [got it](https://www.screencast.com/t/cNGnnhYdtu) in two steps:
* skipped the `x-frame-options` header because it disallowed a login page loading in an iframe.
 https://github.com/DevExpress/testcafe-hammerhead/blob/bf87b68374d88c6f9e409268c31c3422aba8295c/src/request-pipeline/header-transforms.js#L143-L143
* added the `patchAuth` ClientFunction into the test.
```js
const patchAuth = ClientFunction(() => {
    window.open = function (url) {
        var iframe = document.createElement('iframe');

        iframe.style.position = 'fixed';
        iframe.style.left = '200px';
        iframe.style.top = '150px';
        iframe.style.width = '400px';
        iframe.style.height = '300px';
        iframe.style['z-index'] = '99999999';;		
        iframe.src = url;
        iframe.id = 'auth-iframe';

        document.body.appendChild(iframe);
    };
});
```

**Final test:**
```js
fixture `fixture`
    .page `https://www.soudfa.com/signup`;

test('test', async t => {
    await patchAuth();

    await t
        .click('button.facebook')
        .switchToIframe('#auth-iframe')
        .typeText('#email', 'email***')
        .typeText('#pass', 'pass***')
        .click('#u_0_0')
        .wait(30e3);
});
```

**Comment by neilmatillano** [comment]
@LavrovArtem 

Tried this proposal but I am blocked with few errors:

_**const patchAuth = new ClientFunction(() => {**_
Error: TypeScript compilation failed.
Only a void function can be called with the 'new' keyword.
----------
Note that I already have this : import { Selector, Role, ClientFunction } from "testcafe"
So I removed the "new' keyword but I still get the error below.

For this line --  **_window.open = function (url) {_**
Error: TypeScript compilation failed.
/Users/admin/ark-e2e/tests/testCampaign_flow.ts (41, 9): Type '(url: string) => void' is not assignable to type '(url?: string, target?: string, features?: string, replace?: boolean) => Window'.
  Type 'void' is not assignable to type 'Window'.

**Comment by LavrovArtem** [comment]
Fixed type script test:
```ts
import { ClientFunction } from 'testcafe';

const patchAuth = ClientFunction(() => {
    window['op' + 'en'] = function (url) {
        var iframe = document.createElement('iframe');

        iframe.style.position = 'fixed';
        iframe.style.left = '200px';
        iframe.style.top = '150px';
        iframe.style.width = '400px';
        iframe.style.height = '300px';
        iframe.style['z-index'] = '99999999';;		
        iframe.src = url;
        iframe.id = 'auth-iframe';
		
        document.body.appendChild(iframe);
    };
});

fixture `fixture`
    .page `https://app.makemereach.com/`
	
test('test', async t => {
    await patchAuth();

    await t
        .click('.btn.btn-big.btn-fb')
        .switchToIframe('#auth-iframe')
        .typeText('#email', 'artjomlav@gmail.com')
        .typeText('#pass', 'Artem923')
        .click('#u_0_0')
        .wait(30e3);
});
```
But you also should find the `testcafe-hammerhead/lib/request-pipeline/header-transforms.js` file in the `node_modules` folder and replace current function of the `x-frame-options` property to the `skip` function (`'x-frame-options': skip,`).

**Comment by neilmatillano** [comment]
@LavrovArtem 

I followed all the steps including updating the transforms js, but I am getting this error when running testcafe locally

1) The specified selector does not match any element in the DOM tree.

      Browser: Chrome 63.0.3239 / Mac OS X 10.13.2

         65 |    const loginBtn = Selector("input[name=\"login\"]")
         66 |    const signupBtn = Selector(elementWithIdOrClassName("btn btn-big btn-main-color"))
         67 |
         68 |    await testController
         69 |        .click(loginSelector)
       > 70 |        .switchToIframe('#auth-iframe')

**Comment by LavrovArtem** [comment]
May be you loose a call of the `patchAuth` function.
```js
test('test', async t => {
    await patchAuth();  // <<<<<<<<< this

    await t
        .click('.btn.btn-big.btn-fb')
        .switchToIframe('#auth-iframe')
        .typeText('#email', 'email***')
        .typeText('#pass', 'pass***')
        .click('#u_0_0')
        .wait(30e3);
});
```

**Comment by neilmatillano** [comment]
yeah i forgot, added now but get another error.
Sorry this is a bit hard to debug on my side... I cant get any more info

Request failed with status code 500

      Browser: Chrome 63.0.3239 / Mac OS X 10.13.2

         68 |    const signupBtn = Selector(elementWithIdOrClassName("btn btn-big btn-main-color"))
         69 |
         70 |
         71 |    await testController
         72 |        .click(loginSelector)
       > 73 |        .switchToIframe('#auth-iframe')

**Comment by LavrovArtem** [comment]
The 500 failed code maybe related with `x-frame-options` replacement. Be convinced that you correctly replaced function in `/node_modules/testcafe/node_modules/testcafe-hammerhead/lib/request-pipeline/header-transforms.js`.

**Comment by neilmatillano** [comment]
@LavrovArtem , is there anyway to remember in the browser the login for facebook that I previously did so I don't need to login again when I run testcafe? I tried using chrome:userProfile but it didnt help.

**Comment by LavrovArtem** [comment]
Hi @neilmatillano,
The [User Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) feature should meet your need.

**Comment by neilmatillano** [comment]
@LavrovArtem , yes I tried this one but the problem is I still get redirected to the login page even after I saved the login.

**Comment by neilmatillano** [comment]
Or how about session cookies, is it supported in testcafe?

**Comment by LavrovArtem** [comment]
I've created example with [User Roles](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html) for you:
```js
import { ClientFunction, Role, Selector } from 'testcafe';

const patchAuth = ClientFunction(() => {
    window['op' + 'en'] = function (url) {
        var iframe = document.createElement('iframe');

        iframe.style.position = 'fixed';
        iframe.style.left = '200px';
        iframe.style.top = '150px';
        iframe.style.width = '400px';
        iframe.style.height = '300px';
        iframe.style['z-index'] = '99999999';;		
        iframe.src = url;
        iframe.id = 'auth-iframe';

        document.body.appendChild(iframe);
    };
});

const facebookAccUser = Role('<your site url>/login', async t => {
    await patchAuth();

    await t
        .click('.btn.btn-big.btn-fb')
        .switchToIframe('#auth-iframe')
        .typeText('#email', 'email')
        .typeText('#pass', 'pass')
        .click('#u_0_0')
        .switchToMainWindow();

    await Selector('#page-header-top-menu')();
});

fixture `fixture`
    .page `<your site url>`
    .beforeEach(async t => await t.useRole(facebookAccUser));
	
test('first test', async t => {
    await t.click(Selector('.dashboard-tab').nth(1));
});

test('second test', async t => {
    await t.click(Selector('.dashboard-tab').nth(2));
});
```

**Comment by neilmatillano** [comment]
@LavrovArtem , I'm sorry but I am getting an error with the example.

1) - Error in Role initializer -
      Error on page "http://localhost:8080/login":

      Uncaught TypeError: Cannot read property 'call' of undefined

      Browser: Chrome 63.0.3239 / Mac OS X 10.13.2

         23 |const loginSelector = Selector(elementWithIdOrClassName("btn
      btn-big btn-fb"))
         24 |const facebookAccUser = Role('http://localhost:8080/login',
      async t => {
         25 |    await patchAuth();
         26 |
         27 |    await t
       > 28 |        .click('.btn.btn-big.btn-fb')
         29 |        .switchToIframe('#auth-iframe')
         30 |        .typeText('#email', 'email')
         31 |        .typeText('#pass', 'pass')
         32 |        .click('#u_0_0')
         33 |        .switchToMainWindow();

**Comment by LavrovArtem** [comment]
@neilmatillano,
This error occurs on your site and TestCafe detects it. Please try to run TestCafe with the `--skip-js-errors` flag. ([more information](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-e---skip-js-errors)):

**Comment by viking2917** [comment]
@LavrovArtem Thanks for this example. I am also trying to use Test Cafe to test my app with Facebook login (I am using Ionic and the Facebook login plugin as well) 

When I follow your steps above, I get the following errors:

`
O {code: "auth/popup-blocked", message: "Unable to establish a connection with the popup. It may have been blocked by the browser."} "email: " undefined "code " "auth/popup-blocked" (from hammerhead.js line 2)
`

and

`Refused to display 'http://192.168.1.82:54306/2Bt1Drjkn!i/https://m.facebook.com/login.php?skip_api_login=1&api_key=518797921496187&signed_next=1&next=https%3A%2F%2Fm.facebook.com%2Fv2.8%2Fdialog%2Foauth%3Fredirect_uri%3D.......' in a frame because it set 'X-Frame-Options' to 'deny'.`

I think this is because the url of the frame opening the FB login is 'http://192.168.1.82:54306/ ...' and my Facebook Login settings do not include that particular URL/port combination in the 'Valid OAuth redirect URIs' settings. But because test cafe generates a new port number every time, I don't see any way to add it...not sure if that's clear but wondering if you have any suggestions?

Thanks!

**Comment by LavrovArtem** [comment]
Hi @viking2917,
The `Refused to display` error maybe related with x-frame-options replacement.
>* skipped the `x-frame-options` header because it disallowed a login page loading in an iframe.
 https://github.com/DevExpress/testcafe-hammerhead/blob/bf87b68374d88c6f9e409268c31c3422aba8295c/src/request-pipeline/header-transforms.js#L143-L143

https://github.com/DevExpress/testcafe-hammerhead/issues/1428#issuecomment-353625362
https://github.com/DevExpress/testcafe-hammerhead/issues/1428#issuecomment-353852603

I will add PR which rid you from a `node_modules` code modification, as soon as possible.

**Comment by viking2917** [comment]
Thanks @LavrovArtem I did modify the header-transforms.js to make the change to 'x-frame-options': skip, but it's possible I messed up somewhere along the way...

**Comment by joshpitzalis** [comment]
I am getting the same popup-blocked error

```
M {code: "auth/popup-blocked", message: "Unable to establish a connection with the popup. It may have been blocked by the browser."}
```

I have made sure that I skipped the x-frame-options in header-transfor.js:

<img width="1130" alt="screen shot 2018-06-14 at 11 57 42 am" src="https://user-images.githubusercontent.com/10258114/41395157-4c3968e8-6fca-11e8-95c6-9397252d6402.png">

tried jumping into chrome setting and allowing popups before the login button get clicked but no difference. Has anyone found a way around this yet?

**Comment by LavrovArtem** [comment]
Hi @joshpitzalis,
I need some time to investigate it.

**Comment by MohamedRasool786** [comment]
@LavrovArtem

I have faced issue while clicking on a #googleSignInn button. It doesn't redirect to the google POPUP page.Below I attached my code

Expected Behaviour is to give my credentials in google popup page and then it should redirect to my homesite.

Thanks in advance

`import { ClientFunction, Role, Selector } from 'testcafe';

const patchAuth = ClientFunction(() => {
window['op' + 'en'] = function (url) {
var iframe = document.createElement('iframe');

    iframe.style.position = 'fixed';
    iframe.style.left = '100px';
    iframe.style.top = '150px';
    iframe.style.width = '600px';
    iframe.style.height = '600px';
    iframe.style['z-index'] = '99999999';;		
    iframe.src = url;
    iframe.id = 'auth-iframe';

    document.body.appendChild(iframe);
};
});

const googleAccUser = Role('https://merida-web.herokuapp.com/', async t => {
await patchAuth();

await t
    .click("#LoggIn")
    .click("#googleSignInn")  
    .switchToIframe('#auth-iframe')
    .typeText('#identifierId', 'mohamed@cogzidel.com')
     .click("#identifierNext")
     .typeText('#password', 'maduraiboys007')
     .click("#passwordNext")
    .switchToMainWindow();

await Selector('#page-header-top-menu')();
});

fixture Merida E2E Testing
.page https://merida-web.herokuapp.com/
.beforeEach(async t => await t.useRole(googleAccUser));

test('first test', async t => {
await t.click(Selector('.dashboard-tab').nth(2));
});`

**Comment by LavrovArtem** [comment]
Hi @joshpitzalis,
There are two `header-transforms.js` files which should be modified.
![image](https://user-images.githubusercontent.com/5373460/41720776-c25f632c-756c-11e8-8980-34e95d26f0ac.png)

**Comment by LavrovArtem** [comment]
Hi @MohamedRasool786,
I will investigate it.

**Comment by MohamedRasool786** [comment]
Hi @LavrovArtem 

Thanks for your cool reply!
I have tried that too, It's not working to me, Am using firebase google authentication for log in.

Is it possible to do for firebase google authentication in Testcafe.

**Comment by LavrovArtem** [comment]
@MohamedRasool786 
Unfortunately, I cannot find a workaround for google authentication.

**Comment by MohamedRasool786** [comment]
@LavrovArtem 
Thanks.
Is it possible to do using iFrames as like Facebook you did before in #1385

**Comment by LavrovArtem** [comment]
@MohamedRasool786 
I just try to use the same `iframe workaraund` as for Facebook but Google authentification is more difficult.

**Comment by miherlosev** [comment]
We are developing a public API for operating with multiple windows simultaneously. Track https://github.com/devexpress/testcafe/issues/912 to be informed about our progress.
