### ISSUE TITLE
Can't submit a form

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#1434]
https://rosreestr.ru/wps/portal/p/cc_ib_portal_services/online_request/

click #submit-button to try to submit

**Comment by LavrovArtem** [comment]
The form has invalid markup.
```html
<table>
    <form>
    // rows and cells with inputs
    </form>
</table>
```
Correct case:
```html
<form>
    <table>
    // rows and cells with inputs
    </table>
</form>
```
We can set the `form` attribute to the `input` elements which turn out of the `form` element after html processing.

**Comment by LavrovArtem** [comment]
[Workaround](https://github.com/DevExpress/testcafe-hammerhead/commit/542e452c97c7ca359886fd35dc3a59e466447c2f) for [Github form issue](https://github.com/DevExpress/testcafe/issues/2317).
