### ISSUE TITLE
Illegal invocation error on call 'FileListWrapper.item' method

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1446]
Markup to reproduce:
```js
<html>
	<body>
		<input type="file" id="test" multiple>
		<script>
			var testFile = document.getElementById('test');
			
			testFile.addEventListener('change', function (event) {
		
				 var files = event.target.files;
				
				for (var i = 0; i < files.length; i++) {
					console.log('retrieving file', i);
					
					var f = files.item(i); // Illegal invocation
					var formData = new FormData();
					console.log('about to append form data');
					formData.append(event.target.name, f, f.name);
					console.log('form data appended');
				}
			});
		</script>
	</body>
</html>
```

**Comment by javiercbk** [comment]
I've created a [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/1458) that solves this issue.

I've tested it using hammerhead's playground and it is working. It seems that the **item** method on the **FileListWrapper** was being overwritten by some native method that was causing this error.

**Comment by miherlosev** [comment]
Hi, @javiercbk .
Thanks for your work. It helps us to fix the issue.
I've created the separate [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/1459) containing your fix and the test for it.
