### ISSUE TITLE
Uncaught RangeError: "Maximum call stack size exceeded" on https://www.linkedin.com/m/login/

### ISSUE THREAD

**Issue by angryglassbee** [DevExpress/testcafe-hammerhead#1452]
As result, page is infinitely loading.

![screen shot 2018-01-17 at 11 25 44](https://user-images.githubusercontent.com/4927558/35038131-0ea52c5c-fb7a-11e7-9f8d-7b36a47a4a00.png)

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
The fix is published in `testcafe@0.18.7-dev20180124`.
