### ISSUE TITLE
Have Selectors implement iterable protocol

### ISSUE THREAD

**Issue by djwashburn** [DevExpress/testcafe-hammerhead#1478]
Selectors can be iterated over using a standard for loop and the .nth(int) method. However, they cannot be iterated over using for..of syntax because they do not implement the iterable protocol (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols), which is inconvenient and unexpected, since testCafe otherwise is compatible with and expects modern (ES6+) javascript features like async/await.

**Comment by miherlosev** [comment]
Hi @djwashburn. 
Thanks for you proposal.
It related to the `TestCafe` API and I moved your proposal to the [main repository](https://github.com/DevExpress/testcafe/issues/2101).
