### ISSUE TITLE
Add support for multiple ShadowUI stylesheets

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#155]
see https://github.com/superroma/testcafe-hammerhead/pull/154

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Need rewrite for multiple files - https://github.com/superroma/testcafe-hammerhead/blob/master/src/client/sandbox/shadow-ui.js#l161

**Comment by churkin** [comment]
@miherlosev  Good remark
