### ISSUE TITLE
Cannot set the '//' src to an image

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1568]
related with https://github.com/DevExpress/testcafe/issues/2312

**Comment by s-mendez-criteo** [comment]
Hi @LavrovArtem, thank you for quickly looking into the issue. Just so I can communicate this to my team, is there an eta for the [Sprint #11](https://github.com/DevExpress/testcafe-hammerhead/milestone/17)?

**Comment by LavrovArtem** [comment]
Hi @s-mendez-criteo,
I think we will fix this issue next week. We will let you know when we release a version with the fix.
