### ISSUE TITLE
Refactor resource processing mechanism (js, css, page, manifest ...)

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#16]
\cc @LavrovArtem @miherlosev 

Based on https://github.com/superroma/testcafe-hammerhead/issues/5
1. Separeate all to a different independent processors: dom, js, page, manifest, style...
2. Each of the processors should be self-sufficient entity

**Comment by inikulin** [comment]
Related: #15, #12

**Comment by miherlosev** [comment]
Done
