### ISSUE TITLE
Function called twice when location keyword used

### ISSUE THREAD

**Issue by wham** [DevExpress/testcafe-hammerhead#1612]
Consider test ``page.html`` with following content:

```
<script>
var getMyLocation = function() {
    document.write("getMyLocation();");
    return "1355 Market Street";
};

var updateLocation = function(location) {
    location = getMyLocation();
    return location;
};

updateLocation("399 Fremont Street");
</script>
```

When this page is opened directly in a browser, it outputs:

``getMyLocation();``.

When this page is opened via TestCafe, it outputs:

``getMyLocation();getMyLocation();``.

Function ``getMyLocation()`` is called twice. Depending on it's nature it can turn the application under test into a completely unpredictable state.

**Comment by wham** [comment]
This is caused by [location-get.js](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/script/transformers/location-get.js). Function ``updateLocation()`` is transformed into:

```
var updateLocation = function(location) {
     0,function(){return __set$Loc(location,getMyLocation())||(location=getMyLocation());}.call(this);
    return  __get$Loc(location);
};
```

Resulting into double invocation of ``getMyLocation()``.

**Comment by LavrovArtem** [comment]
I'm working on this
