### ISSUE TITLE
Update the nodejs minimal supported version up to 6.0

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1615]
see https://github.com/DevExpress/testcafe/commit/249739ebb2b98ce3bbbd39d04bf151523917f621

1)replace  `Array.indexOf` to `Array.includes`
2)update babel setting

**Comment by LavrovArtem** [comment]
3) https://github.com/DevExpress/testcafe-hammerhead/issues/190

**Comment by miherlosev** [comment]
I'm working on this
