### ISSUE TITLE
Regression of the outerHTML property refactoring

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1639]
In the line below the `this` keyword equals to element which `outerHTML` property is setting instead of the WindowSandbox instance.
https://github.com/DevExpress/testcafe-hammerhead/blob/44639ebbc4eda08a750581aa4419ebdabb18b5a4/src/client/sandbox/node/window.js#L1081

**Comment by vzaidman** [comment]
home this get fixed. im stuck on older testcafe. thanks
