### ISSUE TITLE
Wrong proxing gif image in iframe

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1643]
http://www.littlewebhut.com/articles/html_iframe_example/

![image](https://user-images.githubusercontent.com/4133518/41143509-3bff3b96-6b02-11e8-9963-3ca10d6a07f0.png)

**Comment by bkossb** [comment]
Hi, when you fix this issue?

**Comment by miherlosev** [comment]
The current development sprint is already planned. We will consider this issue during planning the next development sprint.
