### ISSUE TITLE
Need to rethink iframe processing

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1649]

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/1799
https://github.com/DevExpress/testcafe/issues/2787

**Comment by miherlosev** [comment]
Stages

1)Fix all iframe-related bugs (if it's possible at this stage)
2)Remove iframe-related outdated code (ie9, ie10)
3)Simplify iframe processing code (IframeSandbox.processIframe, and etc.)
4)Rewrite parent-child window relationship to remove hard understable hammerhead parts (iframe native methdos backup, iframe reattach, parting iframe overriding before iframe loading and etc.)

**Comment by Farfurix** [comment]
**After implementation:** https://gist.github.com/Farfurix/f92ddb721422dd69c865c2a96a373bb7#gistcomment-2867414

**Comment by miherlosev** [comment]
We've fixed the most common cases. The edge cases will be considered separately.
