### ISSUE TITLE
is:issue is:open fetch.toString() prints full function code instead of function fetch() { [native code] }

### ISSUE THREAD

**Issue by dahannes** [DevExpress/testcafe-hammerhead#1662]
I am testing an app that stores data to indexedDB via [localForage](https://github.com/localForage/localForage)

When testing on iOS (11.4) localForage fails to recognize indexedDB and falls back to other storage drivers. Besides other conditions it checks for the availability of fetch like so: `fetch.toString().indexOf('[native code') !== -1`

This condition returns `true` when running the app on iOS directly but fails when remote testing the app on iOS via testcafe, because `fetch.toString()` prints the whole function code instead of `function fetch() { [native code] }` as expected from any browser.

**Comment by miherlosev** [comment]
Hi @dahannes 

Thank you for your report. W will fix this problem in the [current development sprint](https://github.com/DevExpress/testcafe-hammerhead/milestone/19).

**Comment by AndreyBelym** [comment]
Hi @dahannes, I've just published `testcafe@0.20.5` with the fix! Please, update your TestCafe installation, and feel free to reopen the issue if the problem isn't fixed in your environment.
