### ISSUE TITLE
Support 'beforeUnload' event added via 'addEventListener'

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#168]
Event listener can have 'object' type.
see issue - https://github.com/superroma/testcafe-hammerhead/issues/133

1)UnloadSandbox._onBeforeUnloadHandler
Reproduce in IE11, Safari. Need to check in all browsers.
Code for reproduce:

``` html
<html>
    <body>
        <h1 id="msg"></h1>
        <br/>
        <script>
            var eventHandler = {
                property: "1",
                handleEvent: function(e) {
                    return "Are you ready";
                }
            };
            window.addEventListener('beforeunload', eventHandler);
        </script>
        <a href="http://example.com">Go to EXAMPLE.COM</a>
    </body>
</html>
```

**Comment by inikulin** [comment]
@miherlosev Why it's proposal state? If it's a possible bug-maker we should mark it as a bug.

**Comment by miherlosev** [comment]
I am working on this

**Comment by miherlosev** [comment]
In UnloadSandbox we are proxing the following instruction:
```javascript
window.onbeforeunload = function () {
    return "<some text>";
}
```
The `window.onbeforeunload` is a cross-browser way to show confirm dialog with 'Leave this page' and 'Stay on this page' buttons.
There is a non cross-browser way - `window.addEventListener('beforeunload', handler)`.
It supports only in IE(11), Safari (8.0.7).
I think we should not to support this way now. 
I have two reason:
a)it does not support in most popular browsers (Chrome, FF).
b)problem does not found on real web sites.

We will support this way if it present on real web sites
What do you think? @inikulin @churkin
