### ISSUE TITLE
Hammerhead tries to add "event" property to null contentWindow in IE11 (possibly related to Custom Elements)

### ISSUE THREAD

**Issue by highspotjeremy** [DevExpress/testcafe-hammerhead#1684]
We are writing tests for a large product that implements Custom Elements. We are currently using the WebReflection Custom Elements implementation (https://github.com/WebReflection/document-register-element). TestCafe works beautifully in every tested browser except IE11. There, it chokes when trying to create an `event` property on a null `contentWindow` object.

The "contentWindow" object appears to be coming from an empty IFRAME. I'm unsure what was inserting the IFRAME, but it was happening for each custom element on the page, so maybe it's part of the shadow DOM implementation (which we aren't using, anyway).

I modified the local versions of hammerhead.js and hammerhead.min.js to add a function wrapper to the `objectDefineProperty` call (line 8062 of hammerhead.js v0.20.5-alpha.1). I also had to add null checks to the two `delete curWindow.event` calls, as `curWindow` will not have an `event` property when null, nor can one be deleted from it.

With these changes, I was able to achieve a successful test pass in IE11 with Custom Elements. I'm unsure how much of the issue is directly related to Custom Elements, but it never hurts to have null checks. :-)

Side note: Using the webcomponents.org Custom Elements polyfill, we ran into class inheritance issues when running TestCafe (possibly because we have a set of base elements that we inherit from rather than using HTMLElement for all of them).

**Comment by LavrovArtem** [comment]
Hi @highspotjeremy,
Thanks for the good described issue. I will investigate and fix it.

**Comment by LavrovArtem** [comment]
Hi @highspotjeremy,
I've investigated this issue. I can locate the problem and fix it by adding a check for the null value, but it looks like a workaround. I cannot reproduce this issue on a page that uses the `WebReflection Custom Elements` implementation. And because of this, I cannot find out the reason for this issue. Could you please provide me a small example that uses the `WebReflection Custom Elements` implementation, with which I could reproduce the issue?

**Comment by highspotjeremy** [comment]
I apologize for the delay in getting back to you.

As yet, I have been unable to create a simple repro for this issue. There appears to be an additional component in the mix that TestCafe is not interacting well with, but I haven't been able to determine what.

I am unable to use IE's debugger with TestCafe running. The developer tools freeze up and refuse to do anything. This makes it difficult to track down the culprit, as there is no IFRAME on the page when TestCafe isn't running (I have manually performed the same steps as in my test). Visual Studio, unfortunately, has not really been of any help in tracking this down, either.

Do you have any ideas on what might be causing the IFRAME to be injected or how I can trace the issue more easily?

**Comment by MarinaRukavitsyna** [comment]
@highspotjeremy 
Would you please try to debug your app using alert()?

**Comment by highspotjeremy** [comment]
The problem with trying to debug this issue was that I had no idea what was actually causing it, since it only happens with TestCafe in the mix, and the debugger was completely useless due to the footprint of our application combined with TestCafe.

I was finally able to get Visual Studio to debug the application and have made some progress. Based on what I can gather, the issue happens when an event is fired on an element that hasn't been appended to the document. In my specific case, a `focus` event is being fired on an orphaned `SVGTextElement`. I'm unsure why it thinks its a SVG element, as exploring the DOM in the offending location has not revealed the existence of one. However, this does appear to be a document with a `<video>` tag, and the document is contained by an IFRAME. We use Video.js for our videos. I'm unsure if that helps.

The Hammerhead code that is responsible for the problem is located in the `_raiseDispatchEvent()` method in client/sandbox/event/simulator.js. The offending code is:
```javascript
nativeMethods.objectDefineProperty.call(window.Object, iframe.contentWindow, 'event', {
    get:          () => window.event,
    configurable: true
});
```

In this instance, `iframe.contentWindow` is null, because the IFRAME has not been appended to the document. `iframe.ownerDocument.defaultView` does map to a valid `window` instance (but is not the same as the top-level window).

Additionally, the following line of code will result in complications:
```javascript
const curWindow         = iframe ? iframe.contentWindow : window;`
```

Since `iframe` does not have a `contentWindow` object, `curWindow` will be null. Later in the method, this code is called:
```javascript
if (browserUtils.isIE11)
    delete curWindow.event;
```

I'm not sure if the event should just failed to be raised in this scenario, or if it should fall back to the `window` object from `iframe.ownerDocument.defaultView`. In the latter case, I imagine you wouldn't want to try defining the `event` property at all (let alone delete it).

I'm not entirely sure how to effectively repro this issue. In theory, creating a detached IFRAME and then trying to fire an event on some element added to the document inside it *should* produce this behavior, but I haven't tried to write a test to validate that. Regardless, though, some null checks should be added to ensure there is actually an object to set a property on before trying to do so.

**Comment by MarinaRukavitsyna** [comment]
@highspotjeremy 
Thank you for your detailed feedback. We are researching the issue now and are going to fix it soon.
