### ISSUE TITLE
The non-native arrayFilter function is used in our code

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#1710]
site: https://www.goodreads.com/

![image](https://user-images.githubusercontent.com/5373460/43759657-968d3d38-9a28-11e8-83e3-f6eda1fb3338.png)

**Comment by Farfurix** [comment]
"https://github.com/LavrovArtem/testcafe-hammerhead/blob/032ccbd73cf41ba3deff74c18ff5b9d4429b0fe4/src/client/sandbox/node/live-node-list/wrapper-state.js#L18" file is no longer in this repository, and there is no `Array.filter` references in the `src/client/sandbox/node/live-node-list` folder, so i close this issue.
