### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by sorin-davidoi** [DevExpress/testcafe-hammerhead#1716]
I'm getting the following with the latest TestCafe (`20.1.1`) and Firefox 61:
![screen shot 2018-08-09 at 11 32 50](https://user-images.githubusercontent.com/2109702/43890868-310f448c-9bc8-11e8-8563-35907468a2d1.png)

I think it was introduced by https://github.com/DevExpress/testcafe-hammerhead/pull/1698, since this particular test wasn't reaching this step because of https://github.com/DevExpress/testcafe-hammerhead/issues/1673.

Don't have self-contained reproduction test that I can share right now unfortunately.

**Comment by miherlosev** [comment]
Hi @sorin-davidoi 

Thank you for the report. We will try to reproduce the problem itself.
But it will be very helpful if you can provide a simple example to reproduce.

**Comment by LavrovArtem** [comment]
I think it related to https://github.com/DevExpress/testcafe-hammerhead/issues/1722

**Comment by sorin-davidoi** [comment]
`0.22.0-alpha.1` seems to have fixed the issue.
