### ISSUE TITLE
Instruct testcafe to not prefix iframe src

### ISSUE THREAD

**Issue by prototype23** [DevExpress/testcafe-hammerhead#1730]
Testcafe prefixes iframe `src` with computer's local ip. Then it stores the original value on the attribute `src-hammerhead-stored-value` like this:
```html
<iframe src-hammerhead-stored-value="http://my.site/content/service/getfile/type/html/name/PDFjs?file=http%3A%2F%2Fmy.site%2Fdownload%2Fasset.php%3Fpath%3D%252Fcrm_uploads%252Feproposal%252Fpdf_1534510813_5b76c6ddbfd8f.pdf%26customasset%3D1%26id%3D9999%26assetpassword%3D202cb962ac59075b964b07152d234b70" src="http://10.10.23.53:57574/PmEeV0e94!i/http://my.site/content/service/getfile/type/html/name/PDFjs?file=http%3A%2F%2Fmy.site%2Fdownload%2Fasset.php%3Fpath%3D%252Fcrm_uploads%252Feproposal%252Fpdf_1534510813_5b76c6ddbfd8f.pdf%26customasset%3D1%26id%3D9999%26assetpassword%3D202cb962ac59075b964b07152d234b70"></iframe>
```
This causes our pdfjs (customized pdfjs) to encounter a crossdomain issue on tests.

**Question**
Can i instruct testcafe to not change that iframe src or is it necessary for it's functionality?

**Comment by MarinaRukavitsyna** [comment]
Hello @prototype23 
TestCafe uses  [URL-rewriting proxy](https://github.com/DevExpress/testcafe-hammerhead). With the proxy we inject scripts that emulate user actions via DOM API. So, it is impossible to accomplish your task with TestCafe. 
You can learn more about how TestCafe works internally in [this](https://testcafe-discuss.devexpress.com/t/why-not-use-selenium-how-to-use-testcafe/47/2) thread.
