### ISSUE TITLE
[WebSocket]: Error: write ECONNABORTED

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1744]
Reproduced on farm with http://www.upworthy.com site.

http://ccnet.devexpress.devx/ccnet/server/farm/project/TESTCafe+Health+Monitor+(hammerhead_git)/build/log20180831220003.xml/ViewBuildReport.aspx

**Comment by cor3000** [comment]
maybe this helps:
I encountered the same error message when running on nodejs 8.5.0 (on windows 10 64bit), the error disappeared when switching to version 10.0.0
