### ISSUE TITLE
Can't override global properties when their native descriptors are data descriptors

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1758]
The [createOverriddenDescriptor](https://github.com/DevExpress/testcafe-hammerhead/blob/4825d79b9c17a1a6c7c0345347488ea93cb97d3d/src/client/utils/property-overriding.js#L13) function expects that the native property descriptor is an accessor descriptor (has  `get` and `set`  properties). However, in older Chrome browsers (55 and below) it is a data descriptor (has `writable` and `value` properties). [Details about different descriptor types at MDN.](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Description). You can't mix properties from different descriptors types, so the current `createOverriddenDescriptor` implementation completely breaks pages under TestCafe.

Despite the issue is currently reproducible only on older Chrome browsers, I think we shouldn't expect that native property descriptors will always be accessor desciptors in all browsers, so we should properly handle data descriptors for native properties.

**Comment by miherlosev** [comment]
Will be viewed before https://github.com/DevExpress/testcafe/issues/2908
