### ISSUE TITLE
Support '/s' flag for reqular expressions

### ISSUE THREAD

**Issue by smsadvert** [DevExpress/testcafe-hammerhead#1759]
This line of code causes the problem:

```const regex = /[\d+\-. ()]{7,1000}.{0,10000}[\d+\-. ()]{7,1000}/gs;```

Changing to regex object will fix the problem:

```const regex = new RegExp('[\\d+\\-. ()]{7,1000}.{0,10000}[\\d+\\-. ()]{7,1000}', 'gs')```

**Comment by LavrovArtem** [comment]
The code above is used a new feature from the ES9 standard.

Description: https://medium.freecodecamp.org/es9-javascripts-state-of-art-in-2018-9a350643f29c
> #### s (dotAll) flag for regular expressions

Our js parser throws the `SyntaxError: Invalid regular expression flag` error.

**Comment by LavrovArtem** [comment]
This issue has already been fixed in this [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/1956).
The fix will be published in the next release.
