### ISSUE TITLE
The document.body.children.length has wrong value in IE and Edge.

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1763]
Reproducible on `https://localvoid.github.io/uibench/`.

Without hammerhead the `document.body.children.length` property is `5`.

In Chrome with hammerhead playground it's still `5`.

In IE and Edge, it's `6`. The last element of the `document.body.children` collection is hammerhead's shadow root, and it turns into `undefined` when trying to get it from an instrumented code. It causes infinite recursion in `testcafe-react-selectors` here: https://github.com/DevExpress/testcafe-react-selectors/blob/master/src/react-16/get-root-els.js#L19

**Comment by link89** [comment]
Hope this fix could be included in next release

**Comment by Farfurix** [comment]
I'm working on it.
