### ISSUE TITLE
shadowUI.isShadowUIMutaion don't filter Hammerhead attributes

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1769]
There are a lot of exceptions when trying to load `https://adidas.co.uk` in `testcafe-hammerhead`'s playground:
![image](https://user-images.githubusercontent.com/4479386/46082959-0017e580-c1a9-11e8-938c-9d14e3eb9d0b.png)

Exceptions aren't raised without `testcafe-hammerhead`.

**Comment by miherlosev** [comment]
`shadowUI.isShadowUIMutation` returns a wrong result for hammerhead-related attribute mutation.

Need to rewrite checking algorithm as follows:
1)if mutation has `attributes`  type then check that changed attribute is not a hammerhead attribute.
2)if mutation has `characterData` type then check that `changedNode.parentNode` is not a shadow ui element
3)if mutaion has `childList` type then check that changed node is not a shadow ui element.

For more detail see links:
* https://dom.spec.whatwg.org/#mutationrecord
* https://dom.spec.whatwg.org/#characterdata
* https://dom.spec.whatwg.org/#mutationobserver
