### ISSUE TITLE
TypeError (NPE) in Mac Safari

### ISSUE THREAD

**Issue by simonpai** [DevExpress/testcafe-hammerhead#1780]
<img width="1015" alt="screen shot 2018-10-08 at 9 01 17 pm" src="https://user-images.githubusercontent.com/785058/46610488-77506080-cb3d-11e8-871c-159b72c13a25.png">

Safari version: `Version 9.1 (11601.5.17.1)`

I believe the root cause is that 
```
Object.getOwnPropertyDescriptor(Document.prototype, "cookie").get
```
gives you `undefined` in Safari, which leads to a TypeError in the following section:

https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/native-methods.js#L62-L66

<img width="906" alt="screen shot 2018-10-08 at 8 56 28 pm" src="https://user-images.githubusercontent.com/785058/46610535-9ea72d80-cb3d-11e8-92ce-671e1e280866.png">

I'm using the hammerhead standalone, and I haven't tested it with the whole TestCafe.

**Comment by miherlosev** [comment]
Hi @simonpai 

We supports only two latest major Safari versions: [`10`](https://github.com/DevExpress/testcafe-hammerhead/blob/master/Gulpfile.js#L71) and [`11`](https://github.com/DevExpress/testcafe-hammerhead/blob/master/Gulpfile.js#L66). Soon, we will change them to `11` and `12`. Safari 9.1 is not supported version.
