### ISSUE TITLE
Steps in README not correct

### ISSUE THREAD

**Issue by jaiminpanchal27** [DevExpress/testcafe-hammerhead#1786]
#### Description:
Steps given here https://github.com/DevExpress/testcafe-hammerhead#first-look resulted in following errors.

On running `gulp run build`, i got following error
```
[11:25:15] Using gulpfile ~/code/temp/testcafe-hammerhead/gulpfile.js
[11:25:15] Task never defined: run
[11:25:15] To list available tasks, try running: gulp --tasks
```

So i just ran `gulp build` and it worked fine.

On running, `npm run http-playground` I am getting following error.
```
npm ERR! missing script: http-playground
```

Can you suggest what wrong i am doing here. Also update README if there are some steps missing.

I am using node v9.

**Comment by LavrovArtem** [comment]
We've corrected the [First Look](https://github.com/DevExpress/testcafe-hammerhead#first-look) description.
