### ISSUE TITLE
Use the Public Suffix List for domain validation

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#1787]
* cookie validation
* same-origin check

https://publicsuffix.org/
https://publicsuffix.org/list/public_suffix_list.dat
https://github.com/wrangr/psl

**Comment by miherlosev** [comment]
https://github.com/DevExpress/testcafe-hammerhead/issues/47
https://github.com/DevExpress/testcafe/issues/2406

**Comment by pci** [comment]
@miherlosev We've run into this in using TestCafe, and would like to help out if we can?

Has any headway been made? If not I'm happy to put some time into putting together a PR, however I'd probably need someone willing to mentor to help me get around the codebase / ask questions of?

**Comment by miherlosev** [comment]
Hi @pci 
 
Thank you for your interest in TestCafe.
 
The `sameOriginCheck` function performs the cross-domain validation. 
https://github.com/DevExpress/testcafe-hammerhead/blob/18f8fd4a3253749989879d0423b49cef91815812/src/utils/url.ts#L83
At present, it uses a simplified algorithm. So, it's necessary to remove the old algorithm and write the new one that uses the `Public Suffix List` data.
 
A few thoughts about implementation details:
* it is necessary to create a very simple parser for https://publicsuffix.org/list/public_suffix_list.dat. The existing solutions do not fit, because it will be used in client and server code parts.
* need to use such data structure that allows implementing the fastest way to perform `isSubdomain` check (for example, prefix tree)
 
If you need additional information, feel free to ask us.

**Comment by pci** [comment]
@miherlosev Thanks for the reply.

Our problem is specifically on the cookie domain side, which I believe is this function?
https://github.com/DevExpress/testcafe-hammerhead/blob/bfcdb5a5411cd40aa001b278e894fe1379f67e81/src/client/utils/cookie.ts#L118
I know cookie validation better than I know the details of same-origin checks, so I'll look to do something there first then move onto the same-origin checks, if that's ok? But of course, keeping the Public Suffix List checker generic between the two.

I've had a look at the existing solutions and both the libraries [psl](https://github.com/wrangr/psl) (that you link to above) and [tld.js](https://github.com/oncletom/tld.js) have browserified artifacts that seem to work in testing for both node - through directly `require`ing the browserified artifact, and through inclusion in the browser. As much as I'd like to build a custom parser and fast implementation (really - it genuinely sounds like a very fun project!), would it be better to try to see if I can get one of these libraries working in both the client and server first, to increase maintainability? Note: both libraries are MIT licensed.

There may well be something I'm missing though, as I'm still getting to grips with how hammerhead does its importing on the client side - I've found [hammerhead.get](https://github.com/DevExpress/testcafe-hammerhead/blob/cc26d8d2dd1f789ff4ab1c8d7a860826a89c9864/src/client/index.ts#L100-L103), but haven't followed the build process through yet.

**Comment by miherlosev** [comment]
The `testcafe-hammerhead` module should work with any web sites. 
Some web sites can override built-in JavaScript functions (`Array.filter`, `Object.defineProperty`, etc). 
We are forced to store [native JavaScript methods](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/native-methods.ts) and use them in our code. 
This allows us to avoid the infinite recursion in the case when a customer's web site overrides the function used by us.
The [psl](https://github.com/wrangr/psl/blob/master/index.js#L14) module uses the `Array.map` function and the [tld](https://github.com/oncletom/tld.js) module uses `String.trim`. 
So, we cannot use these libraries because they used native JavaScript methods, which can be overridden by the web site's client code.
Unfortunately, we need our own implementation of the parser and the domain checker.

**Comment by pci** [comment]
@miherlosev Ouch! I see the problem, thanks for the explanation. I'll have a look what I can do then, but it might take a bit longer to put something together.

It's not a blocker on getting starts, but I guess punycode support would be a requirement? As domains containing punycode are still valid but the Public Suffix List only have the UTF8 versions.

**Comment by miherlosev** [comment]
> I guess punycode support would be a requirement? As domains containing punycode are still valid but the Public Suffix List only has the UTF8 versions.
 

Yes, it's true. We should simulate the native browser behavior. As I see, the [psl](https://github.com/wrangr/psl) parser performs conversion of the Unicode domain parts to the ASCII representation before domain processing. 
 
See these links:
* https://github.com/wrangr/psl/blob/master/index.js#L40
* https://github.com/wrangr/psl/blob/master/index.js#L99
 

However, you can postpone the support domains with punycodes.
