### ISSUE TITLE
Need to refactror FocusBlurSandbox

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#179]
Problem places:
1)Nested calls for __raiseEvent
2)Large methods
3)'Callback' parameter of focus, blur methods uses only for tests

**Comment by inikulin** [comment]
The most important: `_raiseEvent` is inconsistent: for IE it should be sync, while for other browsers it should be async. We should split it into two version: the sync one and the async one.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Done
