### ISSUE TITLE
Upload folder creation is expected in TestCafe Studio

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#1797]
In TestCafe Studio we set `session.uploadStorage.uploadsRoot`. After file uploading (during recording) we get error "we can't copy files to uploads folder".

**Comment by miherlosev** [comment]
Implemented in https://github.com/LavrovArtem/testcafe-hammerhead/commit/8a53435d26d3a63920e19ecd73154dd3c144bc80
