### ISSUE TITLE
Significantly increased error rate according to health monitor

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#182]

**Comment by miherlosev** [comment]
Need to fix the following issues:
https://github.com/superroma/testcafe-hammerhead/issues/184
https://github.com/superroma/testcafe-hammerhead/issues/125

**Comment by inikulin** [comment]
The error rate is still above status quo, so let's keep it open

**Comment by inikulin** [comment]
We are somehow near threshold now. So, closing. Next aim - zero errors
