### ISSUE TITLE
Fetch Calls Removes Authorization Header

### ISSUE THREAD

**Issue by mparker11** [DevExpress/testcafe-hammerhead#1822]
Hi guys. I believe this issue is back, or hasn't been fully resolved. I am using TestCafe and I have an API call that errors with `401 (Unauthorized)` and it's due to the Authorization header is being removed from my Fetch calls. jQuery works fine, leaving all headers in tact.

**Current Behavior**
* TestCafe logs in (jQuery ajax -- works)
* TestCafe get user personal info (jQuery ajax -- works)
* TestCafe gets user projects (Fetch call -- **breaks, 401, no authorization header**)

**Expected Behavior**
* TestCafe logs in (jQuery ajax -- works)
* TestCafe get user personal info (jQuery ajax -- works)
* TestCafe gets user projects (Fetch call -- _**works**_)

TestCafe version: 0.23.1
Node version: 8.11.4
Browser: Chrome and Firefox (haven't tested Edge and IE yet)
OS: WIndows 10

**Comment by kirovboris** [comment]
Moved to https://github.com/DevExpress/testcafe-hammerhead/issues/1822

**Comment by LavrovArtem** [comment]
Could you please provide me information about settings of your fetch request? Headers, mode, credentials, etc.
