### ISSUE TITLE
[Feature]: Support lastModified on File input

### ISSUE THREAD

**Issue by szrharrison** [DevExpress/testcafe-hammerhead#1831]
There is `lastModifiedDate` but not `lastModified` on the `File` object that TestCafé creates when using the `setFilesToUpload` method. [lastModified MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/File/lastModified) show broader browser support than lastModifiedDate.

**Comment by edimistra** [comment]
I am having the same issue, is there any plans on supporting lastModified?

**Comment by AlexKamaev** [comment]
At the moment, we do not plan to implement this feature in the near future.
