### ISSUE TITLE
Removing a cookie results in extra space added to next cookie value

### ISSUE THREAD

**Issue by JRiggenbach** [DevExpress/testcafe-hammerhead#1843]
Has anyone come across an issue where clearing a cookie value
`document.cookie = key=''` 
results in an empty space being added to the next cookie value?

When executing this same code outside of the testcafe, so in the actual web page, this situation does not happen.  Only when running in the context of testcafe.

Here a screen capture of the before and after state of the cookie while running within testcafe.
![testcafe_jquerycookie](https://user-images.githubusercontent.com/1473610/48866623-73049d80-eda1-11e8-82d9-bce302b06a50.jpg)

**Comment by LavrovArtem** [comment]
I've reproduced this issue.
