### ISSUE TITLE
Uncaught TypeErrors in hammerhead.js file

### ISSUE THREAD

**Issue by mabellan** [DevExpress/testcafe-hammerhead#1849]
I'm trying to do a remote test with TestCafe Studio in a Portable Google Chromium (v. 49) browser and when I tried to do it I have the following errors:

![untitled](https://user-images.githubusercontent.com/23740467/48901567-20d18400-ee56-11e8-9b84-8fc51c6762a0.png)

I have tried the same .js test in a local Google Chrome (version 70) and it works.

I have to use the Portable Google Chrome in the 49 version. 

Thanks :)

**Comment by LavrovArtem** [comment]
Hi @mabellan, we officially support only the latest versions of Google Chrome: [Browser Support](https://devexpress.github.io/testcafe/documentation/using-testcafe/common-concepts/browsers/browser-support.html#officially-supported-browsers). We can't guarantee backward compatibility with outdated browsers in next TestCafe releases.
