### ISSUE TITLE
Testcafe breaks certain syntactic pattern

### ISSUE THREAD

**Issue by mixtur** [DevExpress/testcafe-hammerhead#1862]
### Are you requesting a feature or reporting a bug?
bug

### What is the current behavior?
Testcafe seems to break code with certain syntactic patterns in it.

### How would you reproduce the current behavior (if this is a bug)?
test this code with any (even empty) test
```js
const x = 'a';
const y = {
    async [x]() {
        await 0;
    },
}[x];
```

### Specify your

* operating system: Ubuntu 16.04
* testcafe version: 0.22.0
* node.js version: 10.9.0

**Comment by LavrovArtem** [comment]
@rrrainbows At the moment, no. We are going to fix this issue in the near future.
