### ISSUE TITLE
Salesforce Lightning Experience does not render some component properly

### ISSUE THREAD

**Issue by fadliabdulrahman** [DevExpress/testcafe-hammerhead#1874]
As shown below is the screenshot of actual Salesforce Lightning Experience and the same page with the testcafe proxy.

Some component does not render properly such as the logo in the header at top right of the page.
- Actual salesforce homepage:
  <img width="1679" alt="lightning-homepage" src="https://user-images.githubusercontent.com/8084553/50259056-6ecdad80-043d-11e9-9729-9c8f47951f1d.png">

- Proxy salesforce homepage:
  <img width="1680" alt="lightning-homepage-proxy" src="https://user-images.githubusercontent.com/8084553/50259057-6f664400-043d-11e9-9d75-6a28accdf943.png">

"Jira Issues" and "Jira Comments" are the custom salesforce apex component which have the same issue as well.
- Actual salesforce custom apex component:
  <img width="1680" alt="custom-lightning-component" src="https://user-images.githubusercontent.com/8084553/50259054-6ecdad80-043d-11e9-95ad-7dd9a4e57a9a.png">

- Proxy salesforce custom apex component:
  <img width="1679" alt="custom-lightning-component-proxy" src="https://user-images.githubusercontent.com/8084553/50259055-6ecdad80-043d-11e9-9bdd-1215e4bdb087.png">

And there is no error in the browser console. I checked the network tab, there is no error for all network request.

**Comment by Farfurix** [comment]
@fadliabdulrahman, @miherlosev, I've reproduced it on Chrome 71/Windows 10.

**Comment by fadliabdulrahman** [comment]
Thanks @Farfurix @miherlosev

**Comment by Farfurix** [comment]
@fadliabdulrahman, we will close this issue when we fix it.

**Comment by Gedochao** [comment]
Also having this issue. Do we know what's causing it?

**Comment by fadliabdulrahman** [comment]
Hi @Farfurix @miherlosev, is there any update regarding this issue?

**Comment by Farfurix** [comment]
@Gedochao, @fadliabdulrahman, we are working on it. We added this issue to the current sprint.

**Comment by fadliabdulrahman** [comment]
Hi @Farfurix I saw there is open PR for this issue [here](https://github.com/DevExpress/testcafe-hammerhead/pull/1904) . May I know when is the estimated date of the PR is going to merge and release?
