### ISSUE TITLE
Mouse event should not be triggered on the disabled button

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe-hammerhead#1880]
based on https://github.com/DevExpress/testcafe/issues/2902

**Comment by pshendry** [comment]
@AlexKamaev Thank you for this fix! I installed TestCafe two days ago and ran into this issue with a click event on a disabled button in Firefox/Edge; it's great that all I had to do was upgrade to 1.0 and it was fixed. 👍
