### ISSUE TITLE
All event handlers are cleaned after the document.open function call

### ISSUE THREAD

**Issue by fnlctrl** [DevExpress/testcafe-hammerhead#1881]
### What is your Test Scenario?
Testing Google Apps Script web app, which adds two levels of iframe to your content.
 
### What is the Current behavior?
Test hangs on `await Selector(..)()`
 
### What is the Expected behavior?
Test runs normally
 
### What is your web application and your TestCafe test code?

 
Your website URL (or attach your complete example):
https://script.google.com/macros/s/AKfycbznLgTmhAx4iz4tdfY__7I_326s3ZLqWQaR3HKoJi37R0U4OcM/exec

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
fixture`Testcafe nested iframe freezing issue repro`
  .page('https://script.google.com/macros/s/AKfycbznLgTmhAx4iz4tdfY__7I_326s3ZLqWQaR3HKoJi37R0U4OcM/exec');

import { Selector } from 'testcafe';

test('It stucks on nested iframe selector', async t => {
  await t
    .switchToIframe('#sandboxFrame')
    .switchToIframe('#userHtmlFrame');

  await Selector('#helloworld')();
  console.log("This is never logged as it's stuck");
});
```
</details>

<details>
<summary>Your complete test report:</summary>
None.
</details>

### Steps to Reproduce:

1. Run the test
2. See the test hangs
 
### Your Environment details:
 
* testcafe version:                   0.23.2
* node.js version:                    v11.2.0
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 70.0.3538
* platform and version:          Mac OS X 10.14.1

**Comment by fnlctrl** [comment]
Anything I can do to help?

**Comment by fnlctrl** [comment]
Any updates?

**Comment by LavrovArtem** [comment]
@fnlctrl,
I apologize for the delayed response. I'm researching this issue and will fix it. Thank you for your patience.

**Comment by LavrovArtem** [comment]
I've figured out the cause of this issue. All event handlers are cleaned after the `document.open` function call. Therefore, the nested iframe does not handle messages from the top window. I've simplified the provided example:

<details>
<summary>Server for reproducing</summary>

```js
const http = require('http');

http
    .createServer((req, res) => {
        switch (req.url) {
            case '/':
                res.writeHead(200, { 'content-type': 'text/html' });
                res.end(`<iframe src="http://localhost:2201/"></iframe>`);
                break;
            default:
                res.end();
        }
    })
    .listen(2200);

http
    .createServer((req, res) => {
        switch (req.url) {
            case '/':
                res.writeHead(200, { 'content-type': 'text/html' });
                res.end(`
                    <iframe src="/iframe"></iframe>
                    <script>
                        var iframe = document.querySelector('iframe');

                        iframe.contentDocument.open();
                        iframe.contentDocument.write('<div id="helloworld">Hello world</div>');
                        iframe.contentDocument.close();
                    </script>
                `);
                break;
            case '/iframe':
                res.writeHead(200, { 'content-type': 'text/html' });
                res.end(``);
                break;
            default:
                res.end();
        }
    })
    .listen(2201);
```
</details>

<details>
<summary>Test</summary>

```js
fixture`fixture`
    .page('http://localhost:2200/');

import { Selector } from 'testcafe';

test('test', async t => {
    await t
        .switchToIframe('iframe')
        .switchToIframe('iframe');

    const selector = Selector('div');
    
    await s();
    
    console.log("This is never logged as it's stuck");
});
```
</details>

**Comment by istvandesign** [comment]
Could you please give us an estimate on when this can be fixed ? It's a blocker for all of our test cases and I have to revert to wdio if not fixable. Thank you for your work, testcafe is amazing so far.

**Comment by AndreyBelym** [comment]
Unfortunately I can't give an estimate for a fix yet because the issue is rather complex. However I will try to provide a workaround in the next couple of days.

**Comment by fnlctrl** [comment]
The current workaround I'm using is to avoid using selector api and to use client functions like ```t.eval(() => document.querySelector(....))``` This is ugly, but is ok for my use case.

**Comment by fnlctrl** [comment]
🎉 🎉 🎉 🎉 🎉
