### ISSUE TITLE
HTTP Strict Transport Security support

### ISSUE THREAD

**Issue by ctmay4** [DevExpress/testcafe-hammerhead#1894]
### What is your Test Scenario?

Attempting to do a simple test of an authenticated user using `useRole`.  Works locally but fails under Gitlab CI.

### What is the Current behavior?
I've written tests which incorporate `useRole` and all work perfectly when run on my local machine.  I followed the instructions at https://devexpress.github.io/testcafe/documentation/continuous-integration/ to run the same tests in Gitlab CI and they fail.  The only failures occur when I try to use roles.  The first time the role is encountered it works passes but all the other tests after that try to use the role fail.

If I manually log for each test they pass.  In other words if I replace all `useRole` instances with the code from the role (i.e. enter user/password and click login) then all the tests pass on Gitlab CI.

If I reorder the tests it is always the first one that passed and after that all fail.  I assume that TestCafe is using cookies to save the authentication and that seems to not work under Gitlab CI.

I've searched through other issues and didn't see anything that looks like it was related to roles and continuous integration.  
 
### What is the Expected behavior?
The tests that work locally should also work under Gitlab CI.
 
### What is your web application and your TestCafe test code?

<details>
<summary>Your complete test code (or attach your test files):</summary>

Here is a simple example:

```js
import {Selector} from 'testcafe';
import roles from '../helpers/roles';
import config from '../helpers/config';

fixture`Home page`
    .page`${config.baseUrl}`;

test('News', async t => {
    await t
        .useRole(roles.userMin)

        .expect(Selector('#news-section > div.section_top > div > div').innerText).contains('Latest News')
});

test('System information popup', async t => {
    await t
        .useRole(roles.userMin)

        // check some of the values of the version popup
        .click("#logo > span.version.dms-link > a")
        .expect(Selector('#info-build-date_label').innerText).contains('Build Date')
        .expect(Selector('#info-build-date').value).match(/\d{2}-\d{2}-\d{4} \d{2}:\d{2}:\d{2}(AM|PM)/)
}); 
```

Here is the role definition I am using:

```js
import {Role, Selector} from 'testcafe';
import config from './config';

const userMin = Role(`${config.baseUrl}`, async t => {
    await t
        .typeText('#username', 'username_for_testing')
        .typeText('#password', 'password_for_testing')
        .click(Selector('button').withExactText('Login'));
});

export default {
    userMin
}
```

Here is my `.gitlab.ci.yml` which is copied directly from the documentation and simplified to only run against Chromuim.  I also tested against firefox:headless and it failed the same way.

```yml
e2e_tests:
  image:
    name: testcafe/testcafe
    entrypoint: ["/bin/sh", "-c"]
  script:
    - /opt/testcafe/docker/testcafe-docker.sh chromium tests/**/*
```

</details>

<details>
<summary>Your complete test report:</summary>

When I run locally this results look like this:

```
> testcafe chrome:headless tests/

 Running tests in:
 - HeadlessChrome 71.0.3578 / Windows 10.0.0

 Home page
 √ News
 √ System information popup


 2 passed (4s)
```

Here is what it looks like when running through Gitlab CI:

```
Checking out 156cd2cc as master...
Skipping Git submodules setup
$ /opt/testcafe/docker/testcafe-docker.sh chromium tests/**/*
 Running tests in:
 - Chrome 68.0.3440 / Linux 0.0.0

 Home page
 ✓ News
 ✖ System information popup

   1) The specified selector does not match any element in the DOM tree.

       > | Selector('#logo > span.version.dms-link > a')

      Browser: Chrome 68.0.3440 / Linux 0.0.0

         15 |test('System information popup', async t => {
         16 |    await t
         17 |        .useRole(roles.userMin)
         18 |
         19 |        // check some of the values of the version popup
       > 20 |        .click("#logo > span.version.dms-link > a")
         21 |
      .expect(Selector('#info-build-date_label').innerText).contains('Build
      Date')
         22 |
      .expect(Selector('#info-build-date').value).match(/\d{2}-\d{2}-\d{4}
      \d{2}:\d{2}:\d{2}(AM|PM)/)
         23 |});
         24 |
         25 |

         at click (/builds/seer/seerdms-testcafe/tests/home.js:20:10)
         at test (/builds/seer/seerdms-testcafe/tests/home.js:15:1)
         at markeredfn
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous>
      (/usr/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:239:19)
         at TestRun._executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:235:38)
         at _executeTestFn
      (/usr/lib/node_modules/testcafe/src/test-run/index.js:284:24)



 1/2 failed (48s)
ERROR: Job failed: exit code 1
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   0.23.3
* node.js version:                    v10.14.1
* command-line arguments:  testcafe chrome:headless tests/
* browser name and version: Chrome 71; Chromium 68
* platform and version:          Windows 10 locally and a remote Gitlab CI

**Comment by ctmay4** [comment]
Thanks for looking into this.  Any idea why my scripts work locally (on Windows) and not when run through Gitlab CI?  If the HTTP Strict Transport is the issue why do my scripts work at all?

**Comment by LavrovArtem** [comment]
Our proxy server hangs out on an attempt to get an `http` resource because your site is not available through `http`. I think that the `http` server with your site is run on your local machine and thus this test is passed locally.

**Comment by ctmay4** [comment]
I am connecting to the same remote site in both cases, not a locally running server.  The local script works correctly connecting to "https://demo.seerdms.com/" but doesn't work in Gitlab CI.  From your explanation I would have expected neither to work.

**Comment by lucidtech** [comment]
I have the same issue as @ctmay4 .  My useRole is in a beforeEach hook.  Everything works perfectly on my local machine - and then fail in TeamCity.  The set up is the same - the only difference I can see is that testcafe is being run in a docker container on TC but locally on my dev box.  In both cases I am testing with ReactSelectors so in both cases I am serving up an unminified page served by react-scripts with HTTPS=true that proxies to my backend.

**Comment by LavrovArtem** [comment]
Could you please open the http://demo.seerdms.com/ URL (HTTP protocol) on your local machine in Chrome **incognito mode**_(it's important)_? Do you see your site? If yes, that's why the test works as expected on your machine.
