### ISSUE TITLE
Css source map regex is commenting code

### ISSUE THREAD

**Issue by jdcl32** [DevExpress/testcafe-hammerhead#1907]
This [regular expression](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/style.js#L11) will match all characters of the source map comment even the `*/`, leaving `/*` which can lead to the rest of the style being commented if someone has imported a stylesheet that also contains a source map comment.

Changing it to `/#\s*sourceMappingURL\s*=\s*[^\s]+?(\s|\*\/)/i` fix the issue. I tested the behavior of this Regex with: https://regexr.com/.

**Comment by Farfurix** [comment]
Hello, @jdcl32.
I've reproduced this issue. Our team will research it and check for a suitable solution.

**Comment by jdcl32** [comment]
Great, do you have an estimate of when this will be solved?

**Comment by Farfurix** [comment]
@jdcl32,

Any personal estimate may be misleading, so I cannot currently tell you the precise date. Once we get any results, I assure you that we will notify you.
