### ISSUE TITLE
Tag inside a Table with on-click function is not working properly in IE Browser

### ISSUE THREAD

**Issue by Testingfun** [DevExpress/testcafe-hammerhead#1908]
### What is your Test Scenario?

Like to click a table tag of class button with onclick functionality which have multiple tds. 

### What is the Current behavior?

The button is getting clicked, test is getting passed but the page is  not navigating as expected
 
### What is the Expected behavior?

The button should be getting clicked and it should be navigated to the expected page
 
### What is your web application and your TestCafe test code?

 
Refer to the attachment below. 
[Testcode.txt](https://github.com/DevExpress/testcafe/files/2787143/Testcode.txt)

Your website URL (or attach your complete example):

Please use the file as HTML
[Samplecode.txt](https://github.com/DevExpress/testcafe/files/2787147/Samplecode.txt)

![sampleimage](https://user-images.githubusercontent.com/46961087/51607092-b57d5e80-1f39-11e9-8ef9-9061b337d141.jpg)

<summary>Screenshots:</summary>

![sampleoutput](https://user-images.githubusercontent.com/46961087/51607050-9d0d4400-1f39-11e9-84e6-0f0d1ea88c0a.jpg)

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...  Refer to the attachment samplecode.txt (HTML Page) 
3. Execute this command...    testcafe ie testcode.js -e
4. See the error... Refer to the screenshot "sampleoutput.jpeg"
 

This is not the complete application we use, have sent you the sample script to reproduce the error, when running the script in the original webpage, we get the below error as mentioned in the attachment.
![console1](https://user-images.githubusercontent.com/46961087/51607530-e9a54f00-1f3a-11e9-9f5b-447bb5a36f0c.jpg)

Also tried with client function for the browser IE, error occured as mentioned in below screenshot

![console2](https://user-images.githubusercontent.com/46961087/51607657-4bfe4f80-1f3b-11e9-80f9-7225a0929c0b.jpg)

### Your Environment details:
 
Testcafe version: 0.21.1
NodeJS version: 8.11.2
command-line arguments:  testcafe ie testcode.js -e
browser name and version: IE and 11.0
platform and version: Windows and 10.0.0

**Comment by AlexKamaev** [comment]
I cannot give you accurate estimate, but I think we'll fix it in one of nearest releases of the `testcafe-hammerhead` module, since this issue is related to it.
Track the status of this issue to be notified when we fix it.

**Comment by Testingfun** [comment]
> I've researched your page and found that the second argument of this function:
> 
> ```js
> popwin = window.open('../control?navigate=login', IDNumber, config='left=0,top=0,width=' + (screen.availWidth-20) + ' height = ' + (screen.availHeight-50) + ' toolbar=no, menubar=no, scrollbars=no, resizable=yes,location=no, directories=no, status=yes').focus();
> ```
> 
> `IDNumber` has the Number type. However, according to the [article ](https://developer.mozilla.org/en-US/docs/Web/API/Window/open), the `window.open` function should accept a string value as a second argument.
> 
>  I rewrote the argument to `IDNumber.toString()` and it worked. Please try this approach.
> 
> In addition, I wish to mention that currently TestCafe does not support testing in multiple browser windows. Please refer to the following issue to track the progress with this feature [DevExpress/testcafe#912](https://github.com/DevExpress/testcafe/issues/912)

Hi Alex,
I  tried changing the type of IdNumber by injecting this argument `IDNumber.toString()` using client function as it is not possible to change the source code, even if it is changed using client function it is showing the same error as before. Can you please help with this?

**Comment by AlexKamaev** [comment]
I think there is no appropriate workaround for the issue, however we are planning to fix it in the current sprint.

**Comment by hiruthre** [comment]
@AlexKamaev Currently there is a folder name 'testcafe-hammerhead' in node_modules when we downloaded testcafe. So above fixed 'testcafe-hammerhead' and folder in node_modules are same... if not then, how to use this updated 'testcafe-hammerhead'...

Thanks in advance...

**Comment by AlexKamaev** [comment]
@hiruthre 
The `testcafe-hammerhead` module is core module of TestCafe. The current [testcafe-hammerhead](https://www.npmjs.com/package/testcafe-hammerhead) version in `npm` is 14.4.13. The fix will be available only in the next version, which is not published yet. After the new version of `testcafe-hammerhead` is published, you can manually update the [ `package.json` ](https://github.com/DevExpress/testcafe/blob/0999206dbf224fc401b52ec874f22081aa3555ff/package.json#L118)file in your TestCafe repository and run `npm install` command.
Or, you can just wait for new TestCafe version, which will probably contain the updated `testcafe-hammerhead` version with the fix.

**Comment by hiruthre** [comment]
@Alex Thanks for the update.. can you let me know when the new release (testcafe-hammerhead or testcafe) will be available..

**Comment by AlexKamaev** [comment]
@hiruthre
We've published the new `testcafe-hammerhead` 14.4.14 version. Please update your `package.json`. We're are also going to update the `testcafe` version soon.

**Comment by Testingfun** [comment]
Hi Alex, Thanks for your support and help, For updating the latest testcafe-hammerhead 14.4.14 version, I need to update my package.json and rum npm i testcafe-hammerhead. Is this correct?

Also can you please notify here, once the testcafe version has been upgraded. Thanks in advance

**Comment by AlexKamaev** [comment]
@hiruthre 
After your `package.json` is modified, it's sufficient to run the `npm i` command. It will update `testcafe-hammerhead` automatically.
The new TestCafe version has already been published. You can use it right now. So there is no need to update `testcafe-hammerhead` separately.

**Comment by hiruthre** [comment]
Thanks for the update Alex...
