### ISSUE TITLE
WorkerGlobalScope is unaware of HTTP proxy

### ISSUE THREAD

**Issue by IanConnolly** [DevExpress/testcafe-hammerhead#1914]
We send `fetch`es from a Worker to the same origin which served the original page. This works fine in the browser, but under testcafe the `origin` of the request is the proxy's origin (eg. `Origin: http://10.1.10.236:36039` ). Similarly, `WorkerGlobalScope.location` leaks the proxy's details in its various attributes. This turns our normally same-origin requests into a CORS/CSRF issue for our app/framework, which we're attempting to hack around. 

Is this intended behaviour that we should workaround or a missing feature/bug?

**Comment by LavrovArtem** [comment]
Duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/1221
