### ISSUE TITLE
TestCafe fails to load page styles / CSS

### ISSUE THREAD

**Issue by sijosyn** [DevExpress/testcafe-hammerhead#1920]
### What is your Test Scenario?

Download the provided test repo and execute the tests with **node v10.14.2** (LTS)
 
### What is the Current behavior?

After TestCafe executes the test **"Clicking a News, Entertainment and Sports link opens the correct page"** in desktop/404.js (line 49), all subsequent tests fail because TestCafe fails to load the page style/CSS. (see attached screenshot)
 
### What is the Expected behavior?

TestCafe should always load the page styles/CSS
 
### What is your web application and your TestCafe test code?

Download this repo - https://github.com/sijosyn/testcafe-syntests and run the test suite.
 
Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 Above provided repo contains all the test code.
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

![bug](https://user-images.githubusercontent.com/29459281/50021908-8245c800-ffa8-11e8-921a-cc984b31172f.png)
-----
<img width="1186" alt="screen shot 2018-12-14 at 1 31 40 pm" src="https://user-images.githubusercontent.com/29459281/50021240-70fbbc00-ffa6-11e8-8168-e1c3b8d1eaca.png">

</details>

### Steps to Reproduce:

Please read the README provided in the repo - https://github.com/sijosyn/testcafe-syntests . 
Run the full test suite. After TestCafe executes line 56 in 404.js file, TestCafe fails to load the page styles in all subsequent tests.
 
### Your Environment details:
 
* testcafe version:                    0.23.2
* node.js version:                     v10.14.2
* command-line arguments:   npm run aperture   or   testcafe chrome desktop -e
* browser name and version:  Chrome 70
* platform and version:           macOS 10.13
* other:

**Comment by Farfurix** [comment]
@sijosyn,

I didn't reproduce this issue on Chrome 71.0.3578 / Firefox 64.0.0  / Mac OS X 10.14.1 (TestCafe 0.23.3 / 1.0.0).
 
Please note that you can pass `retryTestPages` as the sixth (undocumented) parameter to the [createTestCafe function](https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/createtestcafe.html) when you create a TestCafe server from JavaScript API:

```js
const createTestCafe = require('testcafe');
 
createTestCafe('localhost', 1337, 1338, null, false, true)
    .then(testcafe => {
        const runner = testcafe.createRunner();
        /* ... */
    });
```

This flag was designed to make TestCafe work stable in harsh network conditions. 
 
Can you please try to run your tests using TestCafe@1.0.0 and the `retryTestPages` parameter and tell us the results?

**Comment by sijosyn** [comment]
@Farfurix,

 It's fairly easy to reproduce this issue and can be consistently reproduced if you are using the **Node LTS v10.15.1** (or 10.14.2). Can you please test it with latest Node LTS and you should be able see this issue?. I can still reproduce this on Chrome 72.0.3626 / Mac OS X 10.14.2 and Node v10.15.1  (TestCafe v1.0.0 & v0.23.3)
Note: There is another issue that I logged where TestCafe hangs when running with Node LTS - https://github.com/DevExpress/testcafe/issues/3436 . If TestCafe hangs during execution, please quit & restart again to reproduce the page styles/CSS loading issue. 

Attached video links showing the page styles/CSS loading issue:- 
https://gyazo.com/c48d8add74299c7e48d6057c5518fbb3
https://gyazo.com/d234fd765e06bf78082ab939442e9d48

BTW, I'm not using programming API to run the tests. Is there a way I can pass `retryTestPages` via TestCafe CLI?

**Comment by Farfurix** [comment]
@sijosyn,

I've reproduced this issue for the `desktop` tests run (`testcafe firefox desktop -e`):
 - Win 10 / macOS / Firefox / testcafe@0.23.3
 - Win 10 / Firefox / testcafe@1.0.0
![testcafe1 0 0-firefox-1](https://user-images.githubusercontent.com/30019338/52703284-11626280-2f8f-11e9-888d-3f3ca7232818.PNG)
 - Win 10 / Chrome / testcafe@1.0.0: 
`ERROR The Chrome 72.0.3626 / Windows 10.0.0 browser disconnected. This problem may appear when a browser hangs or is closed, or due to network issues.`

Our team will research it and check for a suitable solution.

**Comment by green-arrow** [comment]
@Farfurix - I'm curious if the root cause of this issue is the same that would cause the `Cannot read property 'callsite' of undefined` error that is filed in DevExpress/testcafe#3441? After upgrading from `0.19.2` to `1.1.0`, we are getting these errors when running in our CI environment.

What's odd is that I can run all tests locally and they all pass. But running in our Jenkins CI in Browserstack, we get the callsite error. Both local and CI run node v8.12.0.

**Comment by AndreyBelym** [comment]
@green-arrow issue #3441 is a different issue. Since it is closed, please create a [new bug report](https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md) and provide a page and a test that can be used to reproduce the problem.

**Comment by vijaydandu** [comment]
Hi @LavrovArtem @Farfurix Do you suggest any workaround for this until this bug is fixed ? I am running into the same issue as @sijosyn

**Comment by LavrovArtem** [comment]
Hi @vijaydandu
Unfortunately we can't provide a workaround at the moment. We are working on this issue. Thank you for your patience.

**Comment by Farfurix** [comment]
Hello @sijosyn,

Could you please share your repository with us? I wasn't able to reach out to it by using [your URL](https://github.com/sijosyn/testcafe-syntests).

Hello @vijaydandu,

Could you create a separate issue with a complete example? We will examine it and check for a suitable solution.

**Comment by sijosyn** [comment]
@Farfurix - Sorry that I deleted the repository. After updating the node version to v12.13.1, I'm not seeing this issue happen very often but it does happen sometimes. I can't consistently reproduce this issue now. Our pages are quite heavy with lots of ads. I think that's when this issue occurs. I'll share the URL's here for now and then try to provide reproducible test script later.

https://start.toshiba.com/
https://wowway.net/
https://centurylink.net/

**Comment by AlexSkorkin** [comment]
Thank you for the update, @sijosyn
