### ISSUE TITLE
'X-Frame-Options: sameorigin' causes iframe loading to be refused

### ISSUE THREAD

**Issue by AdamPike** [DevExpress/testcafe-hammerhead#1945]
An example of this would sainsburys.co.uk, if you login and add a card to your account the card submission is in an iframe. 

When submitting the form through the test server, you get the error:

<test-server-host> refused to connect

if you check the dev toolkit in Chrome, the console tab shows the error as:

Refused to display <test-server-host/url> in a frame because it set 'x-frame-origins' to 'sameorigin'.

**Comment by LavrovArtem** [comment]
I cannot debug the site you provided without credentials and card information. Could you please clarify the following questions?
+ specify the iframe's parent and iframe proxy ports
+ specify the value of the `content-security-policy` header of the iframe
