### ISSUE TITLE
OSS AST, location use case

### ISSUE THREAD

**Issue by DevSide** [DevExpress/testcafe-hammerhead#1950]
I found weird the way hammerhead transpiles location or other global statements causing different kind of bugs.

This code:
```js
function test(){
  var location = { href: 'test', assign: 'test'};
  return { get location() { return location; } }; 
}
```

Become:
```js
function test(){
  var location = { href: 'test', assign: 'test'};
  return { get location() { return __get$Loc(location); } }; 
}
```

We can't trust `isLocation` which checks if the shape looks like window.location in this situation to fix a wrong transpilation.

With acorn parser and acorn-globals plugin, it is possible to know if the location variable is global or local. So we can have the right transpilation.
Exemple: https://runkit.com/devside/5c77f24c9e234500133e73a9

I was wondering if there any plan for hammerhead to use **esprima** or **acorn** instead of his own parser ?
acorn is able to make the difference between a **getter** function and **private** function. It can handle ES20XX Javascript too.

**Comment by LavrovArtem** [comment]
Thank you for your investigation.
We've already fixed the `isLocation` function.
https://github.com/DevExpress/testcafe-hammerhead/commit/ca9b8e0c7e22bcdb56fe4046c12915842e7ad651#diff-274406cb9dc0bf2d8888997d8ff59ba0R546
The fix is published in `testcafe@1.1.0`.
