### ISSUE TITLE
Slow computations in mathematical AWS cognito token generation

### ISSUE THREAD

**Issue by kossmoboleat** [DevExpress/testcafe-hammerhead#1958]
### What is your Test Scenario?
I'm using AWS JS Cognito API to login
 
### What is the Current behavior?
The computation of the authentication token is taking extremely long 8 seconds when it's over in < 1 second without testcafe. I've tracked down the offending function in AWS BigInteger modPow method: https://github.com/aws-amplify/amplify-js/blob/master/packages/amazon-cognito-identity-js/src/BigInteger.js#L685
 
### What is the Expected behavior?
Testcafe execution doesn't take a lot more time than execution without testcafe.
 
### What is your web application and your TestCafe test code?
 
I'm sorry I cannot give you access to my web app currently and I haven't reduced the problem to an example yet. It requires an AWS account or I would have to mock it for a test.

### Steps to Reproduce:

Again, sorry there are no steps to reproduce yet. I'll provide them if it turns out that this is surprising behavior that computations are much slower...
 
### Your Environment details:
 
* testcafe version:                  1.1.0
* node.js version:                    10.15.2
* command-line arguments:  testcafe -e 'chrome' src/testcafe -S -s screenshots -f 'SignedIn Client Route Tests'
* browser name and version: Chrome 72.0.3626 / 
* platform and version:          macOs 10.14.3
* other:                                    tests are written in Typescript (while amazon's Cognito/BigInteger code isn't)

Here's a Chrome profile from a testcafe run that shows that a lot of time is spent in `bnModPow`: [testcafe_slow_sign-in.json.zip](https://github.com/DevExpress/testcafe/files/2937439/testcafe_slow_sign-in.json.zip)

And here's a Chrome profile from a run without testcafe that is spending significantly less time overall and especially in the token generation and `bnModPow` method:
[without_testcafe_fast_sign-in.json.zip](https://github.com/DevExpress/testcafe/files/2937447/without_testcafe_fast_sign-in.json.zip)

Both profiles were created manually during the sign-in.

**Comment by vsorrokin** [comment]
I have reduced the problem to minimum example - https://github.com/vsorrokin/testcafe-bugs
Clone, install deps via yarn, run server - yarn start. Then open 127.0.0.1:8001 in the hammerhead and compare result with non-proxied page. Difference is huge. Here is the code:

```
var t0 = performance.now();

let arr = [];

for (let i = 0; i < 5000000; i++) {
  arr[i] += 64;
}

var t1 = performance.now();

console.log(t1 - t0);
```

**Comment by tsabolov** [comment]
I also have huge execution times in my project. It's obvious that the rewriting of all assignments/readings of object properties takes more time. There could be some way to fix that. Anybody researched?

**Comment by Farfurix** [comment]
@vsorrokin

Hello,

Thank you for the example. We'll take it into account.

>We use key encrypting/decrypting in my project at most of operations which makes testing flow really slow because of this hammerhead problem.
>
> Also can you please tell how to develop testcafe-hammerhead and help you?

Our team need to examine the issue locally.

> I mean you have instruction how to run playground but how to develop with changes watching, live reloading or HMR? For now I can't even modify built hammerhead.js and see changes in browser after manual reloading.

You need to restart the `http-playground` Gulp command after you make any changes in `testcafe-hammerhead`. If you are monitoring the changes in your TestCafe test file, I suggest you follow these steps:
**Note: both repositories may have cross changes; that is why, you need to downgrade to the latest released version.**
1. Clone the `testcafe` repository and create a branch based on the **latest non-rc/alpha** version, for example: `v1.8.4`.
2. Clone the `testcafe-hammerhead` repository. You can find a **suitable version** in `./package.json` of your `testcafe` branch, for example, `"testcafe-hammerhead": "16.2.3"`. Create a branch based on the `v16.2.3` tag.
3. [Link](https://docs.npmjs.com/cli/link.html) your `testcafe-hammerhead` local branch to your `testcafe` local branch.
4. Make necessary changes in the `testcafe-hammerhead` local branch and run the `gulp build` command.
5. Run the `testcafe` local branch with your `testcafe-hammerhead` changes: `node bin/testcafe chrome ./some-test.js`.

**Comment by Farfurix** [comment]
@tsabolov 

Hello,

We'll update this thread once we have any results.
