### ISSUE TITLE
A proxied request hangs if a request to the original site emits an error

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#1961]
I don't know if this can be reproduced in production, but likely it can.

Take a looks at the error handlers of the DestinationRequest's `req` object:

[_onError at src/request-pipeline/destination-request/index.ts](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/src/request-pipeline/destination-request/index.ts#L171)
```ts
    _onError (err: Error): void {
        if (this._isSocketHangUpErr(err))
            this.emit('socketHangUp');

        else if (requestAgent.shouldRegressHttps(err, this.opts)) {
            requestAgent.regressHttps(this.opts);
            this._send();
        }

        else if (this._isTunnelingErr(err)) {
            //...
        }

        else if (this._isDNSErr(err)) {
            //...  
        }

        else
            this.emit('error', err);
    }
```

[error at src/request-pipeline/utils.ts](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/src/request-pipeline/utils.ts#L95)
```ts
    req.on('error', () => {
        ctx.hasDestReqErr = true;
        resolve();
    });
```

If an error can't be handled by any brach in the `_onError` handler, it will be handled by the generic `error` handler, that just sets the `ctx.hasDestReqErr` and doesn't set the `ctx.goToNextStage` flag. After that the first flag is not handled by any code because without the second request pipeline silently terminates [here](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/src/request-pipeline/index.ts#L210) just after the request is resolved.

How to reproduce:
1. (optional) Add logging statements or breakpoints:
[test/playground/server.js:24](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/test/playground/server.js#L24)
[src/request-pipeline/index.ts:210](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/src/request-pipeline/index.ts#L210)
[src/request-pipeline/utils.ts:95](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/src/request-pipeline/utils.ts#L95)
[src/request-pipeline/destination-request/index.ts:171](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/src/request-pipeline/destination-request/index.ts#L171)

1. `npm i nock`
2. Create `test.js`:
```js
const nock = require('nock');
const playground = require('./test/playground/server');

nock('http://example.com')
    .get('/')
    .replyWithError('this fails')
    .persist();

playground.start();
```
3. `node test.js`
4. When a browser opens, open DevTools.
5. Proxy `example.com`.
6. Request to the proxied page started and never finishes, no error is logged in [handlePageError at test/playground/server.js](https://github.com/DevExpress/testcafe-hammerhead/blob/v14.5.1/test/playground/server.js#L24)

**Comment by gal432** [comment]
I think that is what I am dealing with in this [ticket](https://github.com/DevExpress/testcafe/issues/3576)

**Comment by gal432** [comment]
any updates about the problem?

**Comment by AlexSkorkin** [comment]
No updates yet. You will be automatically notified once we make progress.
