### ISSUE TITLE
src/utils/url.ts parseUrl does not recognize Authentication

### ISSUE THREAD

**Issue by trendfischer** [DevExpress/testcafe-hammerhead#1990]
The method parseUrl does not recognize the authentication part in an URL like https://test:secret@domain.tld/test/

As result, a `parsed.host = "test:secret@domain.tld"` is returned resulting in a DNS failure using testcafe.

Expected would be a type ParsedUrl
```
{
    protocol: 'https',
    host: 'domain.tld',
    hostname: 'domain.tld',
    port: '',
    username: 'test',
    password: 'secret'
}
```
I found this error when I used testcafes user roles with http authentication in combination. The role initializer gets an URL with the authentication part. This outputs the `cantResolveUrl` message:

```
      Error details:
      Failed to find a DNS-record for the resource at
```

Hopefully this testcafe-hammerhead repo is the right place to fix this issue. If not, I would open an issue in the testcafe repo with a more generalized error report.

**Comment by Farfurix** [comment]
@trendfischer 

Hello.

If you use [HTTP Basic](https://en.wikipedia.org/wiki/Basic_access_authentication) or [Windows (NTLM)](https://en.wikipedia.org/wiki/NT_LAN_Manager) authentication in your project, you need to use the approach described in [HTTP Authentication](https://devexpress.github.io/testcafe/documentation/test-api/authentication/http-authentication.html).

I tried to run the following test [using the HTTP Authentication](https://devexpress.github.io/testcafe/documentation/test-api/authentication/http-authentication.html), and it was successful:
```js
import { Selector } from 'testcafe';

fixture `My Fixture`
    .page `http://www.httpwatch.com/httpgallery/authentication/`;

test
    .httpAuth({
        username: 'httpwatch',
        password: 'httpwatch123',
    })
    ('test', async (t) => {
    await t
        .click(Selector('#displayImage'))
        .debug();
});
```

**Comment by trendfischer** [comment]
@Farfurix 

Sorry, I fear "question" is the wrong tag for this ticket. My setup is like the following, in contrast to our internal servers, it works fine with httpbin:

```js
/* global fixture, test */
import { Role } from 'testcafe';

const userRegular = Role(
    'https://httpbin.org/redirect-to?url=https%3A%2F%2Fhttpbin.org%2Fbasic-auth%2Ftest%2Fsecret',
    async t => {
        await t
        // Do some login procedure
    }
);

fixture `My Fixture`
    .page `https://httpbin.org/status/200`
    .httpAuth({
        username: 'user',
        password: 'secret',
    })

test ('test', async (t) => {
    await t
        .useRole(userRegular)
        .navigateTo(`https://httpbin.org/status/200`)
        ;
});
```
The role "userRegular" is processing a cookie based authentication and returns a redirect. This works fine on a development machine. On our integration server called "preview", there is an HTTP authentication. If I login into the app with the cookie authentication combined with HTTP authentication, I get a response with a location header looking like this: `http://172.29.64.146:33109/N97MeeYNL/https://user:secret@preview/admin`

I do not know, if hammerhead, a used application library or our load balancer is responsible for the URL with the credentials, but the test fails with the described DNS failure message.

Since authentication in an URL is a common pattern, it would be nice if hammerhead would support it. And the source code looks like it would be no big change, since the returned type has already a username/password property. As a side effect, configuration between different test servers with and without http authentication would be easier to configure. So I would be grateful, if this ticket receives at least a "feature request".

**Comment by Farfurix** [comment]
@thegreyt 

Thank you for the additional details.
We have reproduced this issue. Our team will research it and check for a suitable solution.
