### ISSUE TITLE
Missing localStorage property after redirect

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe-hammerhead#1999]
### What is your Test Scenario?

I am trying to test login integration. We are using OAuth2 for authentication. After a succesfull login on backend, client get redirected to the http://localhost:3000/oauth_callback.html

The code there looks something like:

`oauth_callback.html`

```html
<html>
  <head>
    <script type="text/javascript">
       const accessToken = getAccessTokenFromUrl(window.location.hash)
       localStorage.setItem("app", accessToken)
       const redirectUrl = window.location.href.split('oauthCallback')[0];
       location.assign(redirectUrl); # http://localhost:3000/
    </script>
  </head>
  <body></body>
</html>

```

At this point I can confirm that the accessToken gets stored into the localStorage. However, after the `location.assign(redirectUrl)` happens, React app starts, and in the code we check if there is a token in localStorage and else redirect back to the login (backend). At this point, `localStorage` that was previously set is missing the property thus there is a infinite loop between backend and client.

### What is the Current behavior?

localStorage that I set inside my callback is empty on app start
 
### What is the Expected behavior?

localStorage should be preserved
 
### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example):

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 import { Selector } from 'testcafe';

const baseUrl = 'http://localhost:3000/';

fixture('<Login />').page(baseUrl);

const emailInput = Selector('input[name=username]');
const passwordInput = Selector('input[name=password]');

const loginButton = Selector('button[type=submit]');

const reactRootElement = Selector('#root');

test('Logs in with correct credentials', async t => {
  await t
    .typeText(emailInput, 'mail@gmail.com')
    .typeText(passwordInput, 'password')
    .click(loginButton)
    .wait(10000)
    .expect(reactRootElement.exists)
    .ok();
});
```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   v1.1.0
* node.js version:                    v10.8.0
* command-line arguments:  testcafe chrome src/test/e2e --hostname 127.0.0.1
* browser name and version: Chrome 73.0.3683
* platform and version:          Mac OS X 10.14.3

**Comment by AlexKamaev** [comment]
While we are researching this issue, I found a possible workaround.
I wrapped the call to the `location.replace` method in `oauthCallback.html` in the `setTimeout` method and now the test works as expected. 
```JS
localStorage.setItem("app", JSON.stringify(auth));

var redirectUrl = window.location.href.split("oauthCallback")[0];

setTimeout(function () {
    location.replace(redirectUrl);
}, 0);
```

**Comment by Meemaw** [comment]
Thanks for the workaround, it works indeed - we can start writing tests. However, it would still be very nice if this was fixed, as it is not something unusual or rare in my opinion.

**Comment by AlexKamaev** [comment]
Sure, we are planning to fix it.
