### ISSUE TITLE
hammerhead seems to break yet another syntactic pattern

### ISSUE THREAD

**Issue by mixtur** [DevExpress/testcafe-hammerhead#2002]
This code
```html
<script>
  new X(() => {
    (async () => {
      await a;
      b[c] = d;
    })();
  });
</script>
```
is being transformed into something invalid.

Browser says

`Uncaught SyntaxError: await is only valid in async function`

**Comment by miherlosev** [comment]
Thank you for the provided detail. We've reproduced the problem.
