### ISSUE TITLE
Salesforce custom lightning components not visible to testcafe

### ISSUE THREAD

**Issue by blokeefe** [DevExpress/testcafe-hammerhead#2003]
### What is your Test Scenario?
Login to Salesforce and interact with any custom lightning component.
 
### What is the Current behavior?
No custom lightning components appear to be visible to testcafe
 
### What is the Expected behavior?
testcafe should be able to interact with custom lightning components just like a user in browser
 
### What is your web application and your TestCafe test code?
Salesforce
 
Your website URL (or attach your complete example):
![custom_lightning_component_in_testcafe](https://user-images.githubusercontent.com/5287694/56438984-a9900700-62b2-11e9-8144-5e44c15ff7ba.jpg)
![custom_lightning_component_in_browser](https://user-images.githubusercontent.com/5287694/56438985-a9900700-62b2-11e9-813d-f9cb8759b2dd.jpg)

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```
import { Selector } from 'testcafe'; 

fixture`Custom Lightning Component issue`// declare the fixture
    .page`https://brave-bear-e42cd9-dev-ed.my.salesforce.com/`;  // specify the start page

test('Lightning Component', async t => {
    await t
        .typeText('#username','watkinssf@brave-bear-e42cd9.com')
       .typeText('#password','Password1234')
        .click('#Login')
        .click('.slds-icon-waffle')
        .click(Selector('ul li a span .label.slds-truncate.slds-text-link').withText('Accounts'))
        .click(Selector('.slds-truncate.outputLookupLink.slds-truncate.forceOutputLookup').withText('United Oil & Gas Corp.'))
        .expect(Selector('div.slds-card__body div').innerText).contains('Hello I\'m a custom lightning component')
}); 

</details>

<details>
<summary>

```
</summary>

```
✖ Lightning Component

   1) Cannot obtain information about the node because the specified selector does not match any node in the DOM tree.

       > | Selector('div.slds-card__body div')

      Browser: Chrome 73.0.3683 / Mac OS X 10.14.4

          9 |        .typeText('#password','Password1234')
         10 |        .click('#Login')
         11 |        .click('.slds-icon-waffle')
         12 |        .click(Selector('ul li a span .label.slds-truncate.slds-text-link').withText('Accounts'))
         13 |        .click(Selector('.slds-truncate.outputLookupLink.slds-truncate.forceOutputLookup').withText('United Oil & Gas Corp.'))
       > 14 |        .expect(Selector('div.slds-card__body div').innerText).contains('Hello I\'m a custom lightning component')
         15 |        .debug()
         16 |});

         at Object.<anonymous> (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:14:64)
         at <anonymous> (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:7:71)
         at __awaiter (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:3:12)
         at test (/Users/brian.okeefe/Projects/DevExpress-TestCafe/e2e/tests/lightning_comp_test.ts:6:39)
         at markeredfn (/usr/local/lib/node_modules/testcafe/src/api/wrap-test-function.js:17:28)
         at <anonymous> (/usr/local/lib/node_modules/testcafe/src/api/wrap-test-function.js:7:5)
         at fn (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:242:19)
         at TestRun._executeTestFn (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:238:38)
         at _executeTestFn (/usr/local/lib/node_modules/testcafe/src/test-run/index.js:291:24)



 1/1 failed (30s)
```
</details>

<details>
<summary>Screenshots:</summary>

```
attached
```
</details>

### Steps to Reproduce:

1. Go to the salesforce scratch org https://brave-bear-e42cd9-dev-ed.my.salesforce.com
3. log in with credentials in test
4. Navigate to Accounts
5. Assert on custom lightning component with text "Hello I'm a custom lightning component"
 
### Your Environment details:
 
* testcafe version:  1.1.3
* node.js version:  v11.14.0
* command-line arguments:  testcafe chrome e2e/tests/lightning_comp_test.ts
* browser name and version: Chrome 73.0.3683
* platform and version: Mac OS X 10.14.4
* other:  have tried across multiple browsers and multiple versions of testcafe.  bumping up to hammerhead v 14.6.0 resolved another issue for us where the navigation bar was not appearing in testcafe. 
Noticed the issue in our production like QA environment.  
Custom Lightning Component for this example was created through this trailhead https://trailhead.salesforce.com/en/content/learn/projects/quickstart-lightning-components/quickstart-lightning-components3

**Comment by Farfurix** [comment]
There is a "scope" issue on processing in the following code:
**.../aura_prod.js** (https://github.com/forcedotcom/aura/blob/d43015978d728b8545204e046090df13fec09edb/aura-resources/src/main/resources/aura/resources/lockerservice/aura-locker.js#L2080):
```js
function ie (e) {
    const { realmRec: { unsafeFunction: t } } = e;

    return t(`
    with (arguments[0]) { // !!!
      const {${Na.join(',')}, Function, window, document} = arguments[0];
      return function() {
        'use strict';
        return eval(arguments[0]);
      };
    }
  `);
}
```
In this case, it is **not possible** to use our internal instructions inside the `with` block.

The only solution is to remove this "not recommended" with statement from the code on the https://www.salesforce.com/ side.

I suggest you contact the Salesforce support as their customer and describe your case. Feel free to reference this comment.

### Note
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with

> Using `with` is **not recommended**, and is forbidden in ECMAScript 5 strict mode.

**Comment by blokeefe** [comment]
@Farfurix thank you for your help on this issue.
