### ISSUE TITLE
content-type application/json header removed by proxy

### ISSUE THREAD

**Issue by bryanh84** [DevExpress/testcafe-hammerhead#2005]
### What is your Test Scenario?
The client side of my application is sending a request to the server with a Content-Type application/json header but this header seems to be getting removed by the proxy. 
 
### What is the Current behavior?
content-type application/json header is being removed by the proxy when the client side of my application adds it to a POST.
 
### What is the Expected behavior?
The content-type header should not be removed by the proxy.
 
### Your Environment details:
 
* testcafe version:                   1.1.2
* node.js version:                    8.11.1
* command-line arguments:  testcafe chrome test.js
* browser name and version: Chrome 73
* platform and version:          macOS 10.14.4

**Comment by bryanh84** [comment]
@miherlosev Do you have an approximate ETA for when this will be fixed? Thanks in advance for any additional info you're able to provide.

**Comment by AlexSkorkin** [comment]
Any personal estimate may be misleading, so I cannot currently tell you the precise date. Once we get any results, I assure you that we will notify you.

**Comment by LavrovArtem** [comment]
We have already fixed this issue in #2025.
