### ISSUE TITLE
TestCafe Studio in record mode (i.e. human clicking) cannot get past Recaptcha

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe-hammerhead#2011]
Hello, I understand obviously that TC playback or code will not get past Recaptcha, but I need to record steps later in this flow. This is working directly in the browser, only an issue when recording steps through Studio.

Using TestCafe Studio version 1.0.0
Chrome 74 (tested with FF also) / Mac OSX

Steps to reproduce:
* Launch Studio with tested site's URL: https://www.sainsburys.co.uk/
* (Proxy URL in browser = http://10.152.234.81:56347/d3PHngHg7/https://www.sainsburys.co.uk/)
* Click: Log in / Register
* Click: Groceries account
* Enter email address: anything@gmail.com
* Click: Enter

Issue:
Now Recaptcha is displayed using the select pictures version.
Continue click all the correct answers.
But Recaptcha never resolves / completes.

<img width="670" alt="recaptchaTestcafeIssue" src="https://user-images.githubusercontent.com/1033474/56816868-4a933a80-683c-11e9-85df-c4f7f8680f8e.png">

**Comment by AlexKamaev** [comment]
Thank you for your interest in TestCafe Studio.

We do not provide support for commercial products on Github, which is reserved for questions related to the free and open source TestCafe version. I recommend that you submit a new support ticket in the [DevExpress Support Center](https://www.devexpress.com/Support/Center/Question/ChangeFilterSet/1?FavoritesOnly=False&MyItemsOnly=False&MyTeamItemsOnly=False&TechnologyName=Testing+Tools&PlatformName=AllPlatforms&ProductName=TestCafe+Studio&TicketType=All)
