### ISSUE TITLE
iframe content is blocked by 'X-Frame-Options' set to 'sameorigin' directive (Workaround added)

### ISSUE THREAD

**Issue by bennymeade** [DevExpress/testcafe-hammerhead#2012]
Hello, 

**Tool versions:** 
"testcafe": "^0.23.3"
Chrome 74 (tested with FF also)
Mac OSX Mojave 10.14 (tested on Wins 10 also)

**Summary:**
An iframe on our website is coming from a 3rd party supplier, processing card payments. The iframe directive of X-Frame-Options is set to ‘sameorigin’ and this is working fine when tested manually in a normal browser instance.

But when running TestCafe the iframe is 'refused to connect', as TestCafe is serving the test site via a proxy server. The iframe directive is blocking the response content from being displayed, due to its ‘sameorigin’ security level. 

I've asked the 3rd party if they can use 'allow-from' on the iframe directive, but that's not possible. So I need to figure out how to get TestCafe to view the iframe contents as this is a major blocker for us.

**Run command:** 
$ npm run testChromeUi
"testChromeUi": "testcafe chrome tests/ --screenshots ./screenshots --screenshots-on-fails -e --allow-insecure-localhost --allow-running-insecure-content --dev --debug-on-fail",

**Error:**
Refused to display 'http://192.168.15.42:59242/g9fBtWYro!if/https://www.URL/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

<img width="1244" alt="Screenshot 2019-04-26 at 21 29 47" src="https://user-images.githubusercontent.com/1033474/56834840-788f7380-686a-11e9-82f1-970653e9aa05.png">

<img width="802" alt="Screenshot 2019-04-26 at 21 29 59" src="https://user-images.githubusercontent.com/1033474/56834842-788f7380-686a-11e9-92fb-f2d1f5048922.png">

**Comment by Farfurix** [comment]
Hello,

Unfortunately, this information is not sufficient to find the cause of the issue.

You are using an old TestCafe version. Please update your installation to `v1.1.3`. If it doesn't help, could you please provide us with a simple project (or public URL) illustrating this issue?

**Comment by bennymeade** [comment]
@Farfurix I've updated my TestCafe version, but unfortunately the same issue is occurring:
"devDependencies": {
    "testcafe": "^1.1.3"
}

I'm not able to provide access to our test env and anyhow it's inside a private domain. But I will try to reproduce it on the live site with new code. How can I then share this example privately with you?

**Comment by Farfurix** [comment]
@bennymeade 

Hello,

Thank you for the additional information. I've reproduced the issue under Chrome 74 / Windows 10. We need some time to investigate this issue using your credentials.

**Comment by bennymeade** [comment]
Thanks @Farfurix if you need any additional info for your investigation, I'm happy to provide it if possible.

**Comment by miherlosev** [comment]
@bennymeade 
 
Yes, you've created this issue in the `testcafe` repository. I moved it to the `testcafe-hammerhead` repository because the TestCafe problem is related to the module that is located in its repository.
 
> Once a fix arrives is it applied to latest testcafe version, as opposed to testcafe-hammerhead?

No, it's not. I will write to you when the TestCafe version with the fix is available.

**Comment by bennymeade** [comment]
@miherlosev many thanks for the speedy replies.

**Comment by appendixshuffle** [comment]
We are facing same issue in our project and this is blocker for us too because our whole app is displayed in x-frame.

**Comment by Farfurix** [comment]
@appendixshuffle 

Hello,

We need some time to investigate it. It would be great if you could provide us with a sample project to reproduce this issue without any credentials and CAPTCHA tests.

**Comment by bennymeade** [comment]
@Farfurix This is the work around we used for this issue:

Using [TestCafe Mock](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-requests.html) we intercepted the POST request after submitting the payment form details. 

We were able to achieve the intercepting using TC [-d, --debug-mode](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-d---debug-mode), and extracting the HTML code.

We then removed the problem header `res.headers['X-Frame-Options'] = ''`.

This allows us to then simply click on the Continue button and get the payments card confirmation page as normal.

```
import { RequestMock } from 'testcafe';

// const tlgUrl = '/MyCardsAdd?langId=44&storeId=10151';
const providerUrl = '/wcs/stores/servlet/MyCardsAddReturnView';

const isProvider = ({ url, method }) => url.includes(providerUrl) && method === 'post'

// Dev tools with TC debugger paused on request - Response from file 'MyCardsAddReturnView' - Method 'POST'
// Request URL:http://192.168.0.22:58532/J0PruHvww!if/https://www.testenv.co.uk/MyCardsAddReturnView

const mockedPageHtml = `
<!doctype html>
<html>
   <body>
      <form action="MyCards" method="post" id="myCards" name="myCards" target="_parent"/>
         <input type="hidden" name="haveReturnedFromPaymentGateway" value="true">                  
         <p class="paymentGatewayIframeReturnEndPoint">Please select continue to add your card</p>
         <div class="formButton">
            <input class="buttonPrimary" type="submit" id="paymentGatewayIframeReturnSubmit" name="paymentGatewayIframeReturnSubmit" value="Continue" />
         </div>
         <script type="text/javascript" ></script>
      </form>
   </body>
</html>
`

export const unlockIframe = RequestMock()
  .onRequestTo(isProvider)
  .respond(async (req, res) => {
    res.headers['X-Frame-Options'] = ''
    res.statusCode = '200';
    res.setBody(mockedPageHtml);
})
```

**Comment by aleks-pro** [comment]
Hi @bennymeade ,

I'm happy to hear that you have found a workaround. It's a great idea to mock a response. But why do you mock the page's HTML? It looks like removing the `'X-Frame-Options'` header should be sufficient to overcome the issue.
 
Also, I suggest discussing all the issues concerning this workaround in the [StackOverflow thread you've created](https://stackoverflow.com/questions/57327950/testcafe-clientfunction-typeerror-error-as-document-is-undefined). It will help us process your questions more efficiently.

**Comment by bennymeade** [comment]
Only removing the `'X-Frame-Options' `header was not enough in my scenario, because a blank page was returned in place of a payments confirmation page. The solution for this was intercepting the POST request after submitting the payment form details, and using the HTML to display the Continue button, the button which once clicked did display the payments confirmation page.

**Comment by osmtechnologies** [comment]
i am checking your website and add test card named Er Malkeet Khang, Its working fine. Now close your issue.
Thanks if you want to develop any website contact with us, search on google ->Er Malkeet Khang or tech.osmdude@gmail.com

**Comment by kacy-weakley** [comment]
Is there any update on this? My team is running into this same issue.
