### ISSUE TITLE
JavaScript error is thrown on page in Electron app

### ISSUE THREAD

**Issue by aleks-pro** [DevExpress/testcafe-hammerhead#2040]
Without testcafe everything works fine.
See the [ticket](https://isc.devexpress.com/Thread/WorkplaceDetails/T739753).
Also we need to fix [this]( https://github.com/DevExpress/testcafe-hammerhead/issues/2033), [this](https://github.com/DevExpress/testcafe-browser-provider-electron/pull/44) and [this](https://github.com/DevExpress/testcafe-hammerhead/issues/2105), cause Electron app is packed into asar archive.

**Comment by kirovboris** [comment]
Duplicate of #2105
