### ISSUE TITLE
Try to disable the node.js warning

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#2051]
![image](https://user-images.githubusercontent.com/4133518/59663466-c44e0180-91b7-11e9-99a6-68413f159f97.png)

**Comment by aleekhang** [comment]
I've been seeing this warning as well when running testcafe tests - @miherlosev any updates on this?

**Comment by miherlosev** [comment]
Hi @aleekhang 
We are going to fix this issue in the [current](https://github.com/DevExpress/testcafe-hammerhead/milestone/41) development sprint.

**Comment by miherlosev** [comment]
Done in https://github.com/DevExpress/testcafe-hammerhead/commit/737ea46477a359a18d529396ee04c79d3af3b7f3
