### ISSUE TITLE
Testcafe version of browser.waitUntil and browser.execute

### ISSUE THREAD

**Issue by blanche-pinto** [DevExpress/testcafe-hammerhead#2083]
### What is your Test Scenario?
Replicate the following code written in Selenium to TestCafe framework.

```
browser.waitUntil(
      () => {
        return browser.execute(() => {
          return (
            navigator &&
            navigator.serviceWorker &&
            navigator.serviceWorker.controller &&
            navigator.serviceWorker.controller.state &&
            // We want to ensure the Service Worker is fully activated,
            // other states don't mean success.
            navigator.serviceWorker.controller.state === 'activated'
          );
        }).value;
      },
      10000,
      'Service Worker registration failed!'
    );
```
 
### What is the Current behavior?
Can't figure out how to write the above code using ClientFunctions
 
### What is the Expected behavior?
Use ClientFunctions to test for Service Workers

### Your Environment details:

* testcafe version: 1.2.1
* node.js version: v10.15.3
* command-line arguments: testcafe chrome -d --skip-js-errors
* browser name and version: Chrome
* platform and version: macOS 10.14

**Comment by blanche-pinto** [comment]
@Farfurix 

The code is giving me an error where it can't detect getRegistration. It says that it is undefined.

**Comment by Farfurix** [comment]
@blanche-pinto 

[The example test](https://github.com/DevExpress/testcafe-hammerhead/issues/2083#issuecomment-512270901) passed successfully under Mac OS X 10.14 / Chrome 75 / Safari 12. It should be noted that I use the **`--hostname localhost`** command line option.
Result:
```
testcafe chrome,safari test.js --hostname localhost
 Running tests in:
 - Chrome 75.0.3770 / Mac OS X 10.14.5
 - Safari 12.1.1 / Mac OS X 10.14.5

 Fixture
 ✓ navigator.serviceWorker


 1 passed (3s)
```
