### ISSUE TITLE
Script error on a page with <frameset>

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe-hammerhead#2085]
### What is the Current behavior?
I get `SyntaxError: Unexpected token )` error in the browser console running page under playground and `TypeError: Cannot read property 'origin' of undefined`, `TypeError: Cannot read property 'body' of null` running page from Studio.
 
### What is your public web site URL?

The page from https://isc.devexpress.com/Thread/WorkplaceDetails?id=T757411.

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                    v10.16.0
* browser name and version: Chrome 75
* platform and version:          Windows 10 x64

**Comment by Farfurix** [comment]
### An example page:
```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">


<head>
    <title>Dealertrack</title>
</head>

<base target="main">
<body>
<iframe id="iFrm" frameborder="0"></iframe>

<script language='javascript' type="text/javascript">
    var strDetect = navigator.userAgent.toLowerCase();
    var bIE = (strDetect.indexOf('msie') + 1) || navigator.userAgent.match('Trident') ? true : false;

    var str = '' +
        '<frameset framespacing="0" border="0" frameborder="0" rows="119,*,25">' +
        '' +
        '' +
        '<frame name="nav" scrolling="no" noresize target="main" src="topFrameCanada.aspx">' +
        '' +
        '' +
        '<frame name="main" target="main" scrolling="auto" src="welcome_prtl.aspx">' +
        '' +
        '' +
        '<frame name="bottom" src="bottomframe.aspx" scrolling="no">' +
        '</frameset>' +
        ''


    //			document.frames['iFrm'].document.write(str);
    var iframe = document.getElementById('iFrm');
    debugger;
    var doc = iframe.contentDocument ? iframe.contentDocument : (iframe.contentWindow.document || iframe.document);
    doc.write(str); // !!!
    if (!bIE)
        doc.close();
</script>

</body>
</html>
```
### The main issue:
write `<frameset>` to `iframe.contentDocument`.

### Playground behavior:
there is an empty `iframe.contentDocument` body after `doc.write(str)`. 

### Note:
the [`<frameset>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frameset) feature is no longer recommended.

**Comment by helen-dikareva** [comment]
We already have a request to add support for frameset elements. We discussed it with the team and decided not to add this functionality. Read more about out decidion here.
