### ISSUE TITLE
`Authorization` header prefixed with `hammerhead|prefix|by-client`

### ISSUE THREAD

**Issue by jshor** [DevExpress/testcafe-hammerhead#2104]
### What is your Scenario?

Send an XHR request from an application by passing `Authorization` header with the value of `Bearer <some-jwt>`
 
### What is the Current behavior?

The XHR request contains `hammerhead|prefix|by-client` prefixed in the value
 
### What is the Expected behavior?

The `Authorization` header (nor any other header!) should be mutated
 
### What is your public web site URL?

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 import axios from 'axios'

axios({
  method: 'post',
  url: '/foo',
  headers: {
    Authorization: 'Bearer some-value'
  }
})
```
</details>

### Steps to Reproduce:

1. Observe any request passing `Authorization` header containing the offensive `hammerhead|prefix|by-client` prefix

### Your Environment details:

* node.js version:                    8.9.1
* browser name and version: 75.0.3770.100 (Official Build) (64-bit)
* platform and version: OS | Mac OS X 10.12.6 Sierra

**Comment by Farfurix** [comment]
This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/4474#issuecomment-553401933.
