### ISSUE TITLE
upload file multiple time failed on (chrome) x (linux, win10) via selenium grid

### ISSUE THREAD

**Issue by link89** [DevExpress/testcafe-hammerhead#2106]
### What is your Test Scenario?

Call upload file multiple time.
 
### What is the Current behavior?

It's OK  using testcafe 1.1.0, but after we upgrade testcafe to 1.3.2, it's success to upload first file, but nothing is triggered when uploading second file.

It only happen on (chrome) x (linux, win10), but it works well on mac. 
 
### What is the Expected behavior?

Second file should also upload successfully.

### What is your web application and your TestCafe test code?

Your website URL (or attach your complete example):
Internal app

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
await t.setFilesToUpload(uploadFileInput, filesPath);
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version: 1.3.2                  
* node.js version: 10.9.0                   
* command-line arguments:  testcafe selenium:chrome *.js  
* browser name and version: Chrome 74, 75 
* platform and version:  win10, linux(docker)        
* other:

**Comment by link89** [comment]
Hi, do you have plan to fix this on recent release? This bug blocks us from upgrading to latest testcafe release.

**Comment by miherlosev** [comment]
Our developers will look into this issue in one of the next springs. Your patience is greatly appreciated.

**Comment by link89** [comment]
@miherlosev  Or maybe you can provide a solution so that we can try to create a PR to fix it? 
For me I think a feasible and simplest solution is to provide an option named `forceChange` for `setFilesToUpload` method. When this option is set, the onchange event will always been sent.

**Comment by miherlosev** [comment]
An additional option is unnecessary and can make it more complicated. `testcafe-hammerhead` should just emulate a native browser's behavior. I cannot provide your with any recomendation to create a PR because we need an additional time to investigate this problem and find the best solution for it.

**Comment by link89** [comment]
Hi team, do you have a plan to fix this? We are waiting for this fix to upgrade the testcafe to latest version.

**Comment by miherlosev** [comment]
Hi @link89 

We prioritize bugs according to their frequency. Your bug has frequency '1'.
First, we will fix the bugs marked with the 'frequency 2' label. Then, the bugs with the 'frequency 1' label.

If this bug is critical for you, the PR is greatly appreciated.

**Comment by link89** [comment]
@miherlosev 
May I just let `_shouldRaiseChangeEvent ` always return true.
As you can see this condition
```typescript
     if (filesToUpload.length !== currentFiles.length || 
         isFirefox || (isMacPlatform && isChrome || isSafari)) 
         return true; 
```
, if a web app want to work properly on all os x browser, it should always handle onChange event no matter if there is a real change or not. 
So from my point of view, it is less harm to always raise changeEvent than fail to raise change event when it should be raised, until you have a better solution to fix this problem.

**Comment by AlexKamaev** [comment]
@link89
We cannot return `true` in all cases, because the behavior of a real browser can vary and we need to check all of them. Moreover, there can be some limitations because of the same file names even if the full path is different.
Thus it's quite a difficult issue and cannot be solved quickly.

**Comment by link89** [comment]
Hi @AlexKamaev , my point is that
1. this bug is introduced by `_shouldRaiseChangeEvent`, we didn't bother by this bug before testafe@1.1.3 
2. I know that before `_shouldRaiseChangeEvent` being added, there was bug too. But compare with the current one, the original bug is less harm because for web app designed to run on all browsers will handle this scenario properly. Our case is a good example.

I know that it won't be easy to fix this bug, so my suggestion is, before we find a perfect solution for this issue, can we simple revert  `_shouldRaiseChangeEvent` and just return `true`? And bring back `_shouldRaiseChangeEvent` once you have solutions.

**Comment by AndreyBelym** [comment]
As @AlexKamaev said, browsers are very complex, and even browser developers can't achieve predictable and consistent results for different pages and different platforms. The current TestCafe version works consistently on all platforms and fails only in one specific case. Always returning `true` from `_shouldRaiseChangeEvent` will break upload functionality completely on some platforms, so it is definitely a step back in progress with this issue.

I apologize that this issue still affects your experience, but have you tried clearing your file upload input manually with [t.clearUpload](https://devexpress.github.io/testcafe/documentation/test-api/actions/upload.html#clear-file-upload-input)? Setting any value to an empty input will raise the `change` event.
