### ISSUE TITLE
JSZip Returns an empty blob when ZipObject.async used

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe-hammerhead#2115]
### What is your Scenario?

 Our app uses jszip to uncompress files from a zip. We get this file through a request and later try to unzip it using jszip.
At a certain point this command is run :

**def.async('blob').then(content => new ContentData(path, content)**

where def is a ZipObject. 

### What is the Current behavior?

 When using our app without testcafe everything works properly, it returns a blob with correct filesize. 
When using our app through testcafe the blob returned is size 20 and it turns out to be an empty string. It returns 20 whether the file is empty or it contains content. Each file provided from the zip file returns 20 and finally an empty file.

This makes decompressing these files impossible through testcafe's hammerhead.

### What is the Expected behavior?

 Decompressing with JSZip on testcafe should first get the correct size when using async on a jszip ZipObject of type binary
### What is your public web site URL?

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 **def.async('blob').then(content => new ContentData(path, content)**

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Get a zip file over a request
2. Use jszip to filter through the files inside
3. Finally use async function on zipobjects to get the size and type of each.

### Your Environment details:

* node.js version:  10.15.1                    
* browser name and version: Chrome 76 
* platform and version: Mac Os          
* other:

**Comment by franciscolosardo** [comment]
More info on method used at :
[https://stuk.github.io/jszip/documentation/api_zipobject/async.html](url)

**Comment by AndreyBelym** [comment]
Thank you for your report. Could you please share a page and a test that can be used to reproduce the problem? Otherwise, I will need to create my own example. It will take some time and it's not guaranteed that the problem will be reproduced with it.

**Comment by franciscolosardo** [comment]
Hey! I'll check with my superiors if the page can be shared and gladly will do so.
I'll keep you informed, thanks for the feedback!

**Comment by franciscolosardo** [comment]
Hey, great news! 
Not only was i able to provide you a fiddle but also im providing the zip which causes the problem.

[https://jsfiddle.net/L6adh8g1/98/](https://jsfiddle.net/L6adh8g1/98/)

**You can use the button to make the request to the zip and try to decompress it with jszip.
Check the console to see the result of the jsZipObject.async function on each one of the files inside.**

You'll notice it returns 20 filesize for each file using testcafe and without using testcafe it returns different file size for each.

Hope this helps bring out a solution!

**Comment by AndreyBelym** [comment]
Thank you for sharing your example. Unfortunately, I get the following error when I try to run it without TestCafe:
![image](https://user-images.githubusercontent.com/4479386/63706097-4b15ff00-c837-11e9-9f18-9d7069df8c2a.png)

I also tried to view it without the editor (https://jsfiddle.net/L6adh8g1/98/show) but still get the same error. Could you please check if it works correctly on your side?

**Comment by Farfurix** [comment]
@franciscolosardo 

Hello,

Thank you for the sample "JSFiddle" project.
I've reproduced the issue. Our team will research it and check for a suitable solution.
