### ISSUE TITLE
An `import` context is lost when it is used in the evaluated code

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#2122]
An imported url will be resolved relative a page url instead of a script url.

```js
var f = new Function('w', 'return import(w);');
f('./123.js')
```

**Comment by Davor111** [comment]
Hi, we are using testcafe together with stencil and are affected by this bug. We don't want to migrate away from it and cannot migrate away from stencil. Any news would be appreciated!

**Comment by npesa92** [comment]
+1 here. Stencil build outputs files with dynamic imports.

**Comment by smyls1** [comment]
Hello, we are in limbo as well, may we please get an update, thank you for the help.

**Comment by miherlosev** [comment]
Our developers will look into this issue in one of the next sprints. You will be automatically notified once we make progress. Your patience is greatly appreciated.

**Comment by smyls1** [comment]
Thanks @miherlosev , appreciate it.

**Comment by smyls1** [comment]
Thanks for picking this up in sprint 44.

**Comment by smyls1** [comment]
Thanks @LavrovArtem @miherlosev

**Comment by vogloblinsky** [comment]
@miherlosev Problem still appear in my repro repository with last version 1.6.1 : https://github.com/vogloblinsky/testcafe-stencil
It just a simple html page loading a Stencil Web Component.
The page runs perfectly alone, but none inside testcafe/hammerhead.

![](https://user-images.githubusercontent.com/2841805/62812080-91175700-bb04-11e9-968c-6387465bef53.png)
![](https://user-images.githubusercontent.com/2841805/62812084-95437480-bb04-11e9-8681-5abbadad4908.png)

**Comment by LavrovArtem** [comment]
@vogloblinsky, the last version 1.6.1 doesn't contain this fix.

**Comment by smyls1** [comment]
@LavrovArtem Thanks for fixing this issue, when are we planning to bump the version to include this fix, looking forward to, thank you

**Comment by LavrovArtem** [comment]
I think that we will bump the version next week.
