### ISSUE TITLE
testcafe +КриптоПро ЭЦП Browser plug-in

### ISSUE THREAD

**Issue by ShukinDmitriy** [DevExpress/testcafe-hammerhead#2151]
Hi! I try to use testcafe together with CryptoPro EDS Browser plug-in. I launch the browser with the following command "chrome: userProfile". When I open the site in the console, I get the following errors:
```
hammerhead.js:17 Uncaught SyntaxError: JSON.parse
    at exports.parse (hammerhead.js:17)
    at Function.t._getMessageData (hammerhead.js:7)
    at t.r._onMessage (hammerhead.js:7)
    at n (hammerhead.js:14)
    at n (hammerhead.js:7)
    at hammerhead.js:7
```

### Your Environment details:
 
* testcafe version:                  1.5.0
* node.js version:                    v10.15.0
* command-line arguments:  testcafe chrome:userProfile --allow-insecure-localhost
* browser name and version: Chrome  77.0.3865.90
* platform and version:           Windows 10 64
* other:                                   you can get КриптоПро ЭЦП Browser plug-in here https://www.cryptopro.ru/sites/default/files/products/cades/demopage/main.html

**Comment by Farfurix** [comment]
@ShukinDmitriy 

I have examined this issue in greater detail, but it looks like we cannot help much in this situation. The current TestCafe version is not capable of interacting with a browser plug-in/extension and thus it cannot be used in tests that rely on a certain browser plug-in behavior.
