### ISSUE TITLE
Failed to execute 'postMessage' on 'Window': Invalid target origin 'about://:50335/' in a call to 'postMessage'.

### ISSUE THREAD

**Issue by DavidSampson** [DevExpress/testcafe-hammerhead#2165]
### What is the Current behavior?
During test runs we are seeing an error in the console related to `postMessage` in hammerhead, always on the same URL:

![postmessage](https://user-images.githubusercontent.com/11844890/67310242-f99a9100-f4c2-11e9-9e61-7012c310a257.PNG)

With javascript errors disabled it does not affect our test (that we know of), but we are having some other problems with Testcafe and we want to see if this is perhaps related, or generally something that needs to be fixed.
 
### What is the Expected behavior?

 This error would not occur.

### Steps to Reproduce:

```js
fixture('postMessage test');
test('postMessage test', async t =>{
  await t.navigateTo('https://indsol1.sws.siemens.com/');
  await t.wait(30000);
});
```
1. Run the above code, ex: `testcafe chrome ./postMessageTest.js`
2. Notice the JS error that appears.

The error occurs on every page, not just the landing page.
 
### Your Environment details:

* node.js version:                    12.10.0, various 10.x.x 
* browser name and version: Chrome 77, 78 beta, older.
* platform and version:          Windows 10

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I've reproduced this issue on my side. We'll research it and update this thread as soon as we have any result.

**Comment by willsteinmetz** [comment]
👍 Seeing this exact same issue firing right after a call to t.navigateTo() as well.

**Comment by willsteinmetz** [comment]
@DavidSampson are you by chance using Adobe Audience Manager (formerly Demdex) on your site anywhere or through any other 3rd party tools you might be pulling in? I have a hunch but I'm not sure if it's right and the code is a bit of a mess.

**Comment by DavidSampson** [comment]
@willsteinmetz I know we use Adobe Analytics, but I am not specifically aware of any of our dependencies using Audience Manager. Tomorrow I'll will try pulling Analytics out and seeing if the error recurrs.

**Comment by willsteinmetz** [comment]
@DavidSampson sounds like a plan. I know we're also using that. I found a bit of code that look suspicious but I can't for sure narrow that down or figure out why it would be mucking with hammerhead.

My reasoning for thinking that could be the culprit is that there is an iframe on the page that opens **about:blank**. In the adobe code, there is a piece that - despite being somewhat obfuscated - is splitting what looks like the URL and putting parts 0 and 2 back together. It's a long shot but I thought was worth trying to investigate further and worth asking if you also used some of that code.

**Comment by willsteinmetz** [comment]
Just wondering if anyone has had any chance to look into this more or found any work arounds that are working well.

**Comment by LavrovArtem** [comment]
Server for the reproducing for team:

```js
const http = require('http');

http
    .createServer((req, res) => {
        if (req.url === '/') {
            res.writeHead(200, { 'content-type': 'text/html' });
            res.end('<iframe src="//localhost:2019/"></iframe>');
        } else
            res.end();
    })
    .listen(2018, () => console.log('http://localhost:2018'));

http
    .createServer((req, res) => {
        if (req.url === '/') {
            res.writeHead(200, { 'content-type': 'text/html' });
            res.end(`
            <body>
            <script>
                var iframe = document.createElement('iframe');

                iframe.src = 'about:blank';
                iframe.addEventListener('load', function () {
                    var script = document.createElement('script');
                
                    script.textContent = 'top.postMessage("message", "*");';
                    iframe.contentDocument.body.appendChild(script);
                });
                document.body.appendChild(iframe);
            </script>
            `);
        } else
            res.end();
    })
    .listen(2019);
```
