### ISSUE TITLE
Firefox 70 crashes at start of tests

### ISSUE THREAD

**Issue by feedmypixel** [DevExpress/testcafe-hammerhead#2167]
### What is your Scenario?
Running tests in Firefox `70.0` cause the browser to crash. Running tests in Firefox ~`40` cause the browser to hang with `JavaScript` errors (details below)
 
#### Of Note
I had Firefox `~40` on my machine and have upgraded as I thought this may of been the cause. I don't know the exact version of `40`.

### What is the Current behavior?
Firefox `70` crashes. Firefox `~40` hangs with `JavaScript` errors
 
### What is the Expected behavior?
Firefox runs the tests successfully in the same way `Chrome Version 77.0.3865.120 (Official Build) (64-bit)` does

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
### testcafe version
```json
"testcafe": "1.6.0"
```
### npm scripts
```json
"test-e2e:ci": "npm run test-e2e:chrome -- --color --reporter spec,xunit:reports/testcafe/results-chrome.xml && npm run test-e2e:firefox -- --color --reporter spec,xunit:reports/testcafe/results-firefox.xml",
"test-e2e:local": "E2E_BASE_URL='' npm run test-e2e:chrome -- --debug-on-fail",
"test-e2e:chrome": "testcafe chrome test/e2e/*.test.js",
"test-e2e:firefox": "testcafe firefox test/e2e/*.test.js",
```
</details>

<details>
<summary>Screenshots:</summary>

### Firefox 70 
Firefox 70 just crashes with no information in the console
![Screenshot 2019-10-25 at 11 32 08](https://user-images.githubusercontent.com/2305016/67564650-54c6c080-f71b-11e9-8869-df79e0b06422.png)

### Firefox ~40 
Firefox ~40 hung on `about:blank` and gave the following errors

<img width="1005" alt="Screenshot 2019-10-25 at 10 51 44" src="https://user-images.githubusercontent.com/2305016/67564690-6f993500-f71b-11e9-8cf4-7f158e43a74a.png">

</details>

### Steps to Reproduce:
1) Run tests via:
```
"test-e2e:local": "E2E_BASE_URL='' npm run test-e2e:firefox -- --debug-on-fail",
...
"test-e2e:firefox": "testcafe firefox test/e2e/*.test.js",
```
2) Firefox 70 opens
3) Browser crashes
 
### Your Environment details:

* node.js version:                    `v12.12.0`
* browser name and version: `Firefox 70.0.`
* platform and version:           `Mac OS X 10.14.0`
* testcafe version:                   `"testcafe": "1.6.0"`
* other:                                     The same test on the same platform run fine on `chrome Version 77.0.3865.120 (Official Build) (64-bit)`

**Comment by Farfurix** [comment]
@feedmypixel 

Hello,

I guess I was supposed to reproduce the problem in your [repository](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend). If so, unfortunately I wasn't able to pass a ["test"](https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/blob/master/package.json#L25) command under my Windows 10 / macOS 10.15 environments (I passed a "build" command). Could you please provide us with complete steps?

If you can reproduce the issue in some simple project (or a public URL) it will be great if you provide it to us.

**Comment by feedmypixel** [comment]
It turns out I'm not able to make an environment available for you publicly. Closing this issue and I will debug myself 🙏
