### ISSUE TITLE
Numerous enhancements for the Health Monitor UI

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#217]
- [x] Add commit list and commit hyperlinks in the HealthMonitor history view

- [x] Show clickable page URL somethere on the page. Currently I can't find the way to open URL without typing it. Moreover, some URL are so long what I can't see them whole in the combobox.

- [x] Duplicate combobox colored status somether on the page with the colored text. Red - "Has errors", white - "All fine", gray - ... what the hell the gray mean, BTW? JFYI colors in combobox doesn't work for me on MacOS Chrome. So, it's impossible to figure out which sites in the list are actually failing. Maybe we should have 2 (3 with gray) lists for each category of sites instead of 1?

- [x] Show labels on timing bars with the actual numbers in milliseconds, currenlty sometimets it's hard to determine magnitude from just the axis

- [x] Remove "Resources not load on proxy" list. Does anybody find it useful (\cc @churkin @LavrovArtem )? Have we spotted at least one bug with it? Nearly in 99% it just shows resources with unique URLs, which differs for different requests.

- [x] Long error messages in the error list are cut even if I press 'more' button. (e.g. second error [here](https://testcafe-hhhm.devexpress.com/history?timestamp=1445799791886&url=http://www.etsy.com/))

- [x] Please, make distinct colors for resources on the main page. It's extremely hard to distinct e.g. script from stylesheet. For first runs don't use another shade of the same color, use the same color instead but with another line style (if it's possible). Or shade + different line style

- [x] Dots and bars in charts on the main page should have cursor "pointer", to indicate what they are actually clickable (see https://github.com/DevExpress/testcafe-hammerhead/issues/217#issuecomment-154421265)

- [x] We have different time for the same runs on the main page and the history pages. For some reason they differ for one our. Extremely confusing, please fix that.

- [x] Provide the new badge text - with 'status quo' phrase. Use "status quo" in charts as well.

**Comment by miherlosev** [comment]
@inikulin Provide the new badge text - with 'status quo' phrase

**Comment by inikulin** [comment]
More enhancement requests for the history page (e.g. https://testcafe-hhhm.devexpress.com/history?timestamp=1445799791886&url=http://www.etsy.com/):

- [ ] Show clickable page URL somethere on the page. Currently I can't find the way to open URL without typing it. Moreover, some URL are so long what I can't see them whole in the combobox.

- [ ] Duplicate combobox colored status somether on the page with the colored text. Red - "Has errors", white - "All fine", gray - ... what the hell the gray mean, BTW? JFYI colors in combobox doesn't work for me on MacOS Chrome. So, it's impossible to figure out which sites in the list are actually failing. Maybe we should have 2 (3 with gray) lists for each category of sites instead of 1?

- [ ] Show labels on timing bars with the actual numbers in milliseconds, currenlty sometimets it's hard to determine magnitude from just the axis

- [ ] Remove "Resources not load on proxy" list. Does anybody find it useful (\cc @churkin @LavrovArtem )? Have we spotted at least one bug with it? Nearly in 99% it just shows resources with unique URLs, which differs for different requests.

- [ ] Long error messages in the error list are cut even if I press 'more' button. (e.g. second error [here](https://testcafe-hhhm.devexpress.com/history?timestamp=1445799791886&url=http://www.etsy.com/))

- [ ] Please, make distinct colors for resources on the main page. It's extremely hard to distinct e.g. script from stylesheet. For first runs don't use another shade of the same color, use the same color instead but with another line style (if it's possible). Or shade + different line style

- [ ] Dots and bars in charts on the main page should have cursor "pointer", to indicate what they are actually clickable

- [ ] We have different time for the same runs on the main page and the history pages. For some reason they differ for one our. Extremely confusing, please fix that.

**Comment by inikulin** [comment]
\cc @miherlosev

**Comment by miherlosev** [comment]
I am working on 'Commit list between HHM runs'.

**Comment by miherlosev** [comment]
# Sketch


![1](https://cloud.githubusercontent.com/assets/4133518/10907525/d264bcc6-823b-11e5-9486-14ddc44dc12a.png)

**Comment by miherlosev** [comment]
@VasilyStrelyaev 
Please provide more redable text for 'Commits after previous run' phrase

**Comment by LavrovArtem** [comment]
I am working on 
>Long error messages in the error list are cut even if I press 'more' button. (e.g. second error here)

**Comment by VasilyStrelyaev** [comment]
> Please, provide more redable text for 'Commits after previous run' phrase
`Changes`
`Commits since last run`
`Changes since last run`

**Comment by VasilyStrelyaev** [comment]
Let's look at the rest of the page:
*Build history for* - not OK
The whole module is *History*, yeah, but the controls at the top allow you to choose the site and date to view the *report* for.
Can we have two labels: *Test page* and *Build*

**Comment by VasilyStrelyaev** [comment]
*Resources not load on proxy*
Do you mean *Resources not loaded to proxy* ?

**Comment by VasilyStrelyaev** [comment]
The *info* column in the grid has *more* or *less* links.
I'd expect them to show/hide some additional info but they just expand rows with trimmed text.
Can we rename them to *expand* or *collapse*.

**Comment by VasilyStrelyaev** [comment]
\r-

**Comment by inikulin** [comment]
BTW, on charts latest builds exceeds time limits, however badge shows what everything is fine. Also, I have no idea load event can happen before ready event (which happens constantly according to our charts). \cc @churkin @miherlosev @LavrovArtem

**Comment by miherlosev** [comment]
> Show clickable page URL somethere on the page. Currently I can't find the way to open URL without typing it. Moreover, some URL are so long what I can't see them whole in the combobox.
I am working on this

**Comment by LavrovArtem** [comment]
@inikulin
1) Badge shows what everything is fine because use coefficient 0,4 but on the charts coefficient 0,2
2) On the statistics chart shown ratio between proxy time and origin time, for example:
load ratio 2583 / 2317 = 1,113
ready ratio 1801 / 1517 = 1.187
ready ratio > load ratio
![image](https://cloud.githubusercontent.com/assets/5373460/10991684/6c567a96-8470-11e5-98e2-8e8acfaa9253.png)

**Comment by inikulin** [comment]
@LavrovArtem I'm talking about homepage

**Comment by LavrovArtem** [comment]
@inikulin me too
![image](https://cloud.githubusercontent.com/assets/5373460/10992902/9acfad24-847b-11e5-8536-53d574c802c2.png)

**Comment by VasilyStrelyaev** [comment]
I'd go for *Proxy latency factor*
Though *proxy/origin ratio* may also fit but it lacks the *time* component in its meaning

**Comment by VasilyStrelyaev** [comment]
*Proxy latency* turns out to be already reserved.
And I'm not sure about *Proxy lag factor*. Do you like it?
Otherwise, we'll stick to *Proxy/origin ratio*

**Comment by VasilyStrelyaev** [comment]
Or *Proxied/direct ratio* - if we use a more common terminology

**Comment by miherlosev** [comment]
> Duplicate combobox colored status somether on the page with the colored text. Red - "Has errors", white - "All fine", gray - ... what the hell the gray mean, BTW? JFYI colors in combobox doesn't work for me on MacOS Chrome. So, it's impossible to figure out which sites in the list are actually failing. Maybe we should have 2 (3 with gray) lists for each category of sites instead of 1?

I am working on this

**Comment by miherlosev** [comment]
Gray color means 'page load time more than 40 sec'.
I think we need to remove gray color and mark items as error (use red color).
If it is own problem we need to fix the perfomance problem.
If it is site problem we need to remove site from test list
@inikulin @churkin

**Comment by inikulin** [comment]
@miherlosev I agree

**Comment by miherlosev** [comment]
> Provide the new badge text - with 'status quo' phrase. Use "status quo" in charts as well.

I am working on this

**Comment by miherlosev** [comment]
> Please, make distinct colors for resources on the main page. It's extremely hard to distinct e.g. script from stylesheet. For first runs don't use another shade of the same color, use the same color instead but with another line style (if it's possible). Or shade + different line style

I am working on this

**Comment by miherlosev** [comment]
> Dots and bars in charts on the main page should have cursor "pointer", to indicate what they are actually clickable

I am working on this

**Comment by inikulin** [comment]
@miherlosev :disappointed: 
BTW, I don't like this "copy to clipboard" button. Can we just show the link, which will open page in the new window?

**Comment by inikulin** [comment]
@LavrovArtem BTW, can we remove X axis ticks in Events and Resource. I have no idea what do they mean and why we need them.

**Comment by miherlosev** [comment]
> @miherlosev :disappointed:
BTW, I don't like this "copy to clipboard" button. Can we just show the link, which will open page in the new window? You can add one more title under "Changes since previous run" named "Page" under which link will be provided

Sketch
![1](https://cloud.githubusercontent.com/assets/4133518/11028838/2f0fc6f0-86d3-11e5-92c0-680ef03ae2ca.png)

@inikulin

**Comment by inikulin** [comment]
@miherlosev Why not provide the link as I suggested: 1)It will server as the title 2)You will be able to copy it 3)You will be able to open it. I don't like this small buttons and other things, then we can use just a link.

**Comment by LavrovArtem** [comment]
>@LavrovArtem BTW, can we remove X axis ticks in Events and Resource. I have no idea what do they mean and why we need them. BTW, why we have side margins on this charts (e.g. Events starts from -5). And let's color error bars with some light smooth red color.

done

**Comment by VasilyStrelyaev** [comment]
> Provide the new badge text - with 'status quo' phrase. Use "status quo" in charts as well.

@inikulin OMG! *Status quo* has a completely different meaning!

**Comment by VasilyStrelyaev** [comment]
LOL

**Comment by VasilyStrelyaev** [comment]
Like, if we have a history of a function that does not exceed a particular limit, then *f(x) < lim* can be called status quo - but not *lim*.

**Comment by inikulin** [comment]
@VasilyStrelyaev how about `threshold`?

**Comment by VasilyStrelyaev** [comment]
*Threshold* is what I was thinking about.
I'm trying to come up with a definitive word for *threshold* , cause probably *Ready (Load) threshold* is not quite clear.
*Ready (Load) warning threshold* maybe... 

Another solution is to avoid *threshold* in the chart. Just write *Warning (Ready)* and *Warning (Load)*. It's obvious that it's a threshold after all - the chart speaks for itself.

**Comment by inikulin** [comment]
I like this idea

**Comment by inikulin** [comment]
@VasilyStrelyaev *waterline*?

**Comment by VasilyStrelyaev** [comment]
heh, sounds cool

**Comment by miherlosev** [comment]
> @miherlosev Why not provide the link as I suggested: 1)It will server as the title 2)You will be able to copy it 3)You will be able to open it. I don't like this small buttons and other things, then we can use just a link.

Done

**Comment by inikulin** [comment]
@VasilyStrelyaev yet another option: *regression line*

**Comment by miherlosev** [comment]
> Remove "Resources not load on proxy" list. Does anybody find it useful (\cc @churkin @LavrovArtem )? Have we spotted at least one bug with it? Nearly in 99% it just shows resources with unique URLs, which differs for different requests.

I think we should do this:
1)rename to 'Resource errors'
2)show only resources with status code greater than 400 (errors)

**Comment by VasilyStrelyaev** [comment]
> yet another option: regression line

even further than *status quo*

**Comment by miherlosev** [comment]
> We have different time for the same runs on the main page and the history pages. For some reason they differ for one our. Extremely confusing, please fix that.

I am working on this

**Comment by miherlosev** [comment]
> We have different time for the same runs on the main page and the history pages. For some reason they differ for one our. Extremely confusing, please fix that.

Done
