### ISSUE TITLE
Improve the build performance

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#2175]
Now, it is near 25-30 sec.
Maybe we need to migrate to `webpack` and use caching.

**Comment by miherlosev** [comment]
http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-6.html#apis-to-support---build-and---incremental

**Comment by LavrovArtem** [comment]
related issue https://github.com/DevExpress/testcafe-hammerhead/issues/1646

**Comment by miherlosev** [comment]
Pphases:

1) linting
On first build lint all files, the next build lint only changed files

2)building
On first build need to compile all files, the next build compile only server or client sides.
