### ISSUE TITLE
TestCafe cannot load website with incorrect headers

### ISSUE THREAD

**Issue by KingM1** [DevExpress/testcafe-hammerhead#2188]
### What is your Test Scenario?
I'm trying to load https://www.freepeople.com and verify that the page loaded. 
 
### What is the Current behavior?
When I'm using node version 12 and above, the page never loads and is stuck at the "about:blank" page. If I use node 10.13.0, the page loads successfully. I am able to load other pages on node version 12, so I'm not sure why this website specifically won't load.
 
### What is the Expected behavior?
I am expecting the page to load.
 
### What is your web application and your TestCafe test code?
Using node version 12.13.0, and testcafe v1.6.1
 
```js
 import { Selector, ClientFunction } from 'testcafe';

function getUrl() {
    const clientfunction = ClientFunction(() => document.location.href);
    return clientfunction();
}

fixture('Core Application Tests')

test('Should load the page', async (t) => {
    await t.navigateTo('https://www.freepeople.com');
    await t.wait(3000);
    await t.expect(getUrl()).eql('https://www.freepeople.com');
});
```
</details>

### Steps to Reproduce:

1. Run the above code using node version 10.13.0, and testcafe v1.6.1
2. Notice that the website loads correctly
3. Run the above code using node version 12.13, and testcafe v1.6.1
4. Notice that the website never loads, and is stuck on the about:blank page
 
### Your Environment details:
 
* testcafe version: 1.6.1
* node.js version: 12.13.0
* command-line arguments:  
* browser name and version: Chrome, Firefox
* platform and version:  macOS 10.14. Also able to reproduce using docker

**Comment by andrzej-kodify** [comment]
I've bumped into similar issue. Symptoms on client side where that when running test in chrome the network requests tab shown pending request that never completed. In hammerhead it actually entered the error handler here https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/utils.ts#L37 

```
Error: Parse Error: Invalid header value char
    at TLSSocket.socketOnData (_http_client.js:456:22)
    at TLSSocket.emit (events.js:210:5)
    at TLSSocket.EventEmitter.emit (domain.js:498:23)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:182:23) {
  bytesParsed: 1056,
  code: 'HPE_INVALID_HEADER_TOKEN',
  reason: 'Invalid header value char',
  rawPacket: <...>
}
```

Turned out it's this node issue https://github.com/nodejs/node/issues/27711
Try setting this `NODE_OPTIONS='--http-parser=legacy'` env variable when you launch and see if that helps (or some other workaround suggested in this thread). 

As for hammerhead side - when this error handler is reached wouldn't it be better to at least close socket after some timeout or return an error. Currently testcafe waits forever on my end.

**Comment by Dmitry-Ostashev** [comment]
@andrzej-kodify Thank you for your research and information. We'll take it into account.

**Comment by LavrovArtem** [comment]
This issue relates to [node.js](https://github.com/nodejs/node/issues/27711) that works according to [http specification](https://tools.ietf.org/html/rfc7230#section-3.2.4). On the TestCafe side we will fix it in the following way: 

* TestCafe will not hang up.
* TestCafe will raise a clear message about this problem: `Parse Error: Invalid header value char`.

As a workaround, you can revert to the parsing header behavior on Node.js side by passing the `NODE_OPTIONS='--http-parser=legacy'` environment variable.

**Comment by andrzej-kodify** [comment]
Yes, I can pass the `http-parser` option (and I'm doing that) but note that it's removed in node 13 https://nodejs.org/api/deprecations.html#deprecations_dep0131_legacy_http_parser

Also note that (as far as I can tell) Testcafe is modifying headers especially cookie header making them effectively different (potentially longer) than the original headers on the app.

**Comment by LavrovArtem** [comment]
You can fix that on your side according to specifications.

> Also note that (as far as I can tell) Testcafe is modifying headers especially cookie header making them effectively different (potentially longer) than the original headers on the app.

Cookies are stored on our proxy server side, and what you see is a service cookie used to synchronize a client side with the proxy server side. These cookies are removed after synchronization.

**Comment by AndreyBelym** [comment]
There is the `--insecure-http-parser` flag for both Node 13.x and 12.x (>=12.15.0): https://nodejs.org/dist/latest-v13.x/docs/api/cli.html#cli_insecure_http_parser

**Comment by miherlosev** [comment]
After discussing this with the team, we decided to do the following. We need to catch the 'Invalid header value char' error and provide a clear message for a customer explaining how to fix this problem. The message should contain the cause of the problem and steps to fix it.

Here is a message draft:

```js
The request to '<url>' contains the '<name>' header that doesn't comply with the specification <link>. It causes an internal Node.js error on parsing this header. To fix the problem, you need to specify the legacy http header parser via the 'NODE_OPTIONS' environment variable or change the header name according to the specification.
<code_piece>
```
