### ISSUE TITLE
Object.assign does not merge Symbols correctly

### ISSUE THREAD

**Issue by mike247** [DevExpress/testcafe-hammerhead#2189]
### What is your Test Scenario?
After starting the test runner with chrome, and putting a t.debug() at the very start before doing anything, going into the console and running the following does not work as expected

<img width="474" alt="Screen Shot 2019-11-19 at 11 45 09 PM" src="https://user-images.githubusercontent.com/676071/69193357-d2b59600-0b26-11ea-9140-8e7068fdc233.png">
 
### What is the Current behavior?
The Object.assign is failing to merge the symbol key into the object
 
### What is the Expected behavior?
The Symbol should be merged into the object
<img width="399" alt="Screen Shot 2019-11-19 at 11 49 46 PM" src="https://user-images.githubusercontent.com/676071/69193559-49529380-0b27-11ea-8857-21e5a518dc96.png">
 
### What is your web application and your TestCafe test code?
This is application independant

<details>
<summary>Your complete test code (or attach your test files):</summary>

No tests are being run
</details>

### Steps to reproduce
1) Have a simple test
2) Place a t.debug() as the first thing to do after opening a url
3) Unlock the page
4) Right click and open the dev tools
5) Go to the console
6) Repeat the code in the screenshots 

### Your Environment details:
 
* testcafe version:                   1.6.0
* node.js version:                    11.12.0
* command-line arguments:  testcafe --skip-js-errors chrome ./tests
* browser name and version:  chrome, 78.0.3904.97
* platform and version:           Mac OS X 10.13.6

**Comment by mike247** [comment]
Hey

We use the merging of Symbols to track our form inputs, and to validate objects that can be modified by several forms over seperate pages

Here is an example
```
 Object.assign(person, {
      [Symbol('touched')]: {
        firstName: !!person.firstName,
        lastName: !!person.lastName,
        day: !!person.day || !!person.age,
        month: !!person.month || !!person.age,
        year: !!person.year || !!person.age
      },
      [Symbol('valid')]: {
        firstName: !!person.firstName,
        lastName: !!person.lastName,
        day: !!person.day || !!person.age,
        month: !!person.month || !!person.age,
        year: !!person.year || !!person.age
      }
    })
```

We are extending our Person object with the 'Valid' and 'touched' symbols, these are used to track if the form field representing those Keys was touched or is valid

One of the key benefits of this approach is we are able to track form validation inside the objects that are modified directly while still being able to call Object.keys(person) to filter out all this metadata.

Because the Object.assign is not merging in symbols, while running automated tests all our forms are always invalid and the automated software cannot continue onto the next step

I hope this answers your question!

**Comment by Farfurix** [comment]
@mike247 

Thank you for the clarification. I will add this issue to the current development sprint. Stay tuned for our updates in this thread.
