### ISSUE TITLE
`Authorization` header prefixed with `hammerhead|prefix|by-client` #2104

### ISSUE THREAD

**Issue by rssfrncsrenishaw** [DevExpress/testcafe-hammerhead#2192]
Certain requests have a prefixed Authroization header value. The prefix is "hammerhead|prefix|by-client" and is causing requests to fail with 403s.

Related to resolved #2104  which does not state how/why it was resolved.

**Comment by Farfurix** [comment]
@rssfrncsrenishaw 

Hello,

This issue is a duplicate of https://github.com/DevExpress/testcafe/issues/4474#issuecomment-553401933.
