### ISSUE TITLE
Loads an empty page

### ISSUE THREAD

**Issue by rzhang606** [DevExpress/testcafe-hammerhead#2193]
### What is your Scenario?

I followed the hammerhead set up instructions to run the proxy, and set https://www.easygym.co.uk/set-to-sweat as the url to proxy. Afterwards, I clicked the top right, "easyGym" text and it redirected and loaded an empty page. On the site when accessing normally, it redirects to the proper web page.
 
### What is the Current behavior?

Loads/redirects into a blank page
 
### What is the Expected behavior?

Load the correct page
 
### What is your public web site URL?

https://www.easygym.co.uk/set-to-sweat

### Steps to Reproduce:

1. Go to:  https://www.easygym.co.uk/set-to-sweat
2. Execute this command: Click the top right logo,(Selector:  #main > header > div.header-top > a)
3. See the error: Redirects into blank page
 
### Your Environment details:

* browser name and version: Chrome 78.0.3904.108 (Official Build)
* platform and version:          Windows 10
* other notes: this behavior seems to happen on other SPA sites as well

**Comment by rzhang606** [comment]
Comparing https://stackblitz.com/angular/qrqmegvrdye through regular chrome vs the proxy creates similiar behavior as well!

**Comment by miherlosev** [comment]
Hi @rzhang606 

> I followed the hammerhead set up instructions to run the proxy,
Could you please send us the code that runs the proxy?

**Comment by rzhang606** [comment]
@miherlosev 
I'm confused to what you mean. I cloned master and followed the "First Look" section of the readme to run the proxy.

**Comment by Farfurix** [comment]
@rzhang606 

Hello,

I wasn't able to reproduce the issue in the case of https://www.easygym.co.uk/set-to-sweat.
My steps:
1. Run `gulp testcafe-hammerhead`.
2. Go to https://www.easygym.co.uk/set-to-sweat.
3. Click on "easyGym".
4. See no blank page.

Please clarify your steps to reproduce the first case (https://www.easygym.co.uk/set-to-sweat) and let me know if I missed something.

My environment details:
- `testcafe-hammerhead` master
- Node.js v12.13.1
- Windows 10

I reproduced [the second case](https://github.com/DevExpress/testcafe-hammerhead/issues/2193#issuecomment-561349778):
![Capture](https://user-images.githubusercontent.com/30019338/70325122-515a4500-1842-11ea-8477-329efd4fde32.PNG)

Our team will research it and check for a suitable solution
