### ISSUE TITLE
Error occurs when opening Salesforce Lightning Web Components preview

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe-hammerhead#2199]
### What is your Scenario?
A customer is using TestCafe Studio for E2E testing of LWC Application.
 
### What is the Current behavior?
The error message "Unable to resolve http://localhost:1402/McMzGrFOI!s!utf-8/https://d3nm9grey5nsoo.cloudfront.net/api/runtime/lwc-components/1.3.0-alpha/src/lightning/utilsPrivate/assert from api/runtime/lwc-components/1.3.0-alpha/src/lightning/utilsPrivate/utilsPrivate.js" is shown on the Preview pane.
 
### What is the Expected behavior?
Content should be rendered as it works without the Hammerhead proxy.
 
### What is your public web site URL?

Your website URL (or attach your complete example): 
https://developer.salesforce.com/docs/component-library/tools/playground

<details>
<summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/24777868/71009235-f30f4b00-20fa-11ea-9013-bd7b9aaf3f12.png)

</details>

### Steps to Reproduce:

1. Launch gulp http-playground
2. Proxy https://developer.salesforce.com/docs/component-library/tools/playground
3. See the problem
 
### Your Environment details:

* node.js version:                    v10.16.0, 12.13.1
* browser name and version: Chrome 79
* platform and version:          Windows 10, Lubuntu

**Comment by Dmitry-Ostashev** [comment]
For the team:
A Support Center ticket - https://supportcenter.devexpress.com/internal/ticket/details/T822312
The previous issue - https://github.com/DevExpress/testcafe-hammerhead/issues/2152

**Comment by LavrovArtem** [comment]
I cannot reproduce it.
