### ISSUE TITLE
Cursor position cannot be get for the specific input

### ISSUE THREAD

**Issue by alexey-lin** [DevExpress/testcafe-hammerhead#2205]
Hammerhead cannot get selection for inputs with type `number` or `e-mail` directly and uses `INTERNAL_PROPS.selection` for it (see [selection.ts:150](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/selection.ts#L150)). This property should be set when selection is changed (see [selection.ts:64](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/selection.ts#L64)), but for some reason it never happens for one specific input. I tried to set breakpoint into this function and it wasn't hit.

### What is your Scenario?
Typing in the e-mail type input during test recording.
 
### What is the Current behavior?
The cursor jumps to the position 0 ocassionally, so text is typed backwards.
 
### What is the Expected behavior?
The cursor stays at the end of line, the text is typed fine.
 
### What is your public web site URL?

https://accounts.geneu.net/

<details>
<summary>Your complete app code (or attach your test files):</summary>

N/A. The issue is reproduced in TestCafe Studio.
</details>

<details>
<summary>Screenshots:</summary>

Please, see the [original ticket](https://supportcenter.devexpress.com/internal/ticket/details/T848243).

</details>

### Steps to Reproduce:

1. Launch TestCafe Studio
2. Create a fixture with https://accounts.geneu.net/ URL
3. Start recording a test
4. Start typing into the E-mail input
5. Finish the queued action (by clicking 'Complete typing' popup or pressing Backspace or other non-character key)
6. Continue typing
7. See that the text you are typing appears at the start of the line
 
### Your Environment details:

* node.js version:                    v10.15.3
* browser name and version: Chrome 79.0.3945.88
* platform and version:          Windows
* other:                                  &mdash;

**Comment by alexey-lin** [comment]
SC ticket - https://supportcenter.devexpress.com/internal/ticket/details/T848243
Studio issue - https://github.com/DevExpress/testcafe-studio/issues/2909

**Comment by Farfurix** [comment]
Wait for https://github.com/DevExpress/testcafe-studio/issues/2736
