### ISSUE TITLE
Running inside Chrome with the flag `--disable-local-storage` breaks TestCafé

### ISSUE THREAD

**Issue by macarie** [DevExpress/testcafe-hammerhead#2214]
### What is your Scenario?
When trying to run Chrome with the flag `--disable-local-storage` from TestCafé. This sets `localStorage` to `null`.
 
### What is the Current behavior?
The browser just hangs, waits some time, then it restarts and does the same all over again until you stop the tests.

Hammerhead tries to use `localStorage.removeItem()`, but `localStorage` is `null`, so an error is thrown.
 
### What is the Expected behavior?
Hammerhead should try to look if `localStorage` exists and only then use it.

### Steps to Reproduce:
I tried to make an example in [this repository](https://github.com/macarie/testcafe-disabled-storage), inside you can also find the terminal output and the console output.

```console
$ git clone https://github.com/macarie/testcafe-disabled-storage

$ yarn

$ yarn serve &

$ yarn with-storage

$ yarn no-storage
```
 
### Your Environment details:

* node.js version: `v13.5.0`
* browser name and version: `Chrome 79.0.3945.130`
* platform and version: `macOS 10.15.2`

---

I was not sure where to open the issue because it's related to TestCafé too, but I think the problem is in this repository.

I've tried to look a bit around and found out that [`_cleanLocalStorageServiceData`](https://github.com/DevExpress/testcafe-hammerhead/blob/c3747da3b81ddfbc87012ac8459bd3081ff7560d/src/client/index.ts#L189-L191) is called at the beginning of a test, it calls `nativeMethods.winLocalStorageGetter` that comes from [here](https://github.com/DevExpress/testcafe-hammerhead/blob/c3747da3b81ddfbc87012ac8459bd3081ff7560d/src/client/sandbox/native-methods.ts#L925) without checking if the method does exist or not.

After a quick search with GitHub, I see that `winLocalStorageGetter` is used in more places. An easy fix, if you want to support this scenario, would be to create a `localStorage`-compatible API that stores data in memory.

**Comment by LavrovArtem** [comment]
Hi, TestCafe uses the localStorage object to store internal data. Unfortunately, TestCafe will not work without it.

**Comment by macarie** [comment]
Yeah, after digging a bit more into the codebase I kinda imagined that.

Thank you anyway 😊
