### ISSUE TITLE
Promise rejection: Cannot read property 'P' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'P' of undefined

### ISSUE THREAD

**Issue by renita1509** [DevExpress/testcafe-hammerhead#2215]
When trying to execute a suite of test, getting the hammerhead typescript error below and the test fails.

![2020-01-20 14_06_53-a7c326db-5597-4615-a288-e39cd882d945 (2538×621)](https://user-images.githubusercontent.com/57610411/72698479-7f001100-3b98-11ea-830a-8db0d68aecf4.png)

Promise rejection: Cannot read property 'P' of undefined ; Zone: <root> ; Task: Promise.then ; Value: TypeError: Cannot read property 'P' of undefined

These are the versions of testcafe and hammerhead installed

testcafe-hammerhead": "16.0.2"

"testcafe": "version": "1.8.0"

Is there a workaround for this or is there a solution to overcome this issue.Thanks

**Comment by LavrovArtem** [comment]
Could you please provide a page or a small example so that we can reproduce the issue?

We look forward to your response.

**Comment by renita1509** [comment]
Hi , 
Our Dev team will try and emulate the issue further with a sample app that is closest with ours. We will update the ticket with our findings as soon as we can. 

Our initial findings though are that our app (StencilJS) has has Differential Loading which is when the app is split up into many small scripts and loaded as needed. This outputs individual modules. The reference script to the our app in index.html dynamically loads these individual modules as needed.

TestCafe uses a proxy to fetch external resources, including script files, as it needs to transform them for its implementation.

For an unknown reason, there is a difference when a test is run as the first test vs. not the first test. Dynamically loaded script resources are not fetched properly when a test is not the first test run. The test then fails with a 404 Not Found error when fetching this file, as TestCafe has not fetched and transformed the resource. This can be verified by debugging the test and using Developer tools to inspect the Sources of the page. The dynamic resource does not exist.

**Comment by LavrovArtem** [comment]
Thank you for understanding, we will wait for your updates.
