### ISSUE TITLE
e2e tests fails if the static server/playground does not set cache-control header

### ISSUE THREAD

**Issue by onemindatime** [DevExpress/testcafe-hammerhead#2226]
### What is your Scenario?
e2e tests fails if the static server/playground does not set cache-control header. This only happens if a JS file dynamically imports another JS file. I've replicated the test failures in a sample repo and documented all the details there.

I spent quite some time to debug the actual issue and found out it was due to the cache-control header not set in my static demo server. I've documented the issue and my findings here - https://github.com/onemindatime/hammerheadbug

### What is the Current behavior?
Other than the first test all the other tests in an e2e suite fails.
Test1:
![image](https://user-images.githubusercontent.com/37280030/73891322-e371d000-4828-11ea-85d6-211d4262bb1b.png)

Test2:
![image](https://user-images.githubusercontent.com/37280030/73891329-e79ded80-4828-11ea-9f4b-7c19a2c19010.png)

Test2 (cached js file)
![image](https://user-images.githubusercontent.com/37280030/73891388-fdabae00-4828-11ea-82cb-e74a5f6dd809.png)
 
### What is the Expected behavior?
* It should rewrite the URL for the import statement inside the cached js file for each test with its session id.
* At least document the cache-control requirement for the server that testcafe hits to run the tests
 
### What is your public web site URL?
n/a

Your website URL (or attach your complete example):
https://github.com/onemindatime/hammerheadbug

### Steps to Reproduce:
Please check the shared repo
 
### Your Environment details:

* node.js version:                    v12.13.0
* browser name and version: Chrome 79.0.3945.130
* platform and version:          macOS 10.14

**Comment by AlexKamaev** [comment]
I followed your steps, but I got the `page can’t be found` error on the `yarn test` step. Did I miss anything or is there an error on your site? I also tried to run your site using your `serve` command, however, I was not successful.

**Comment by ganeshsomasundaram-okta** [comment]
@AlexKamaev I just tried cloning the repo and I can reproduce the error that I described. 

After the dependencies are installed `npm i` if you run `npm run serve`, it should start the static server that you can hit on the localhost
![image](https://user-images.githubusercontent.com/40774045/74363458-748ffc00-4d7f-11ea-8492-25444382a321.png)

When you run `npm run test` you should be able to see the static serve command and testcafe command run in parallel and the second test fail.
![image](https://user-images.githubusercontent.com/40774045/74363556-a30dd700-4d7f-11ea-8443-bb6996d3ad55.png)

Running the `npm run testdebug` will open the browser (hard-coded to chrome) in debug mode where you can run the test by each step and when the second test runs the network requests in DevTools will show the 404 for the "js" file that I posed in the screenshot.

**Comment by onemindatime** [comment]
@AlexKamaev I just tried cloning the repo again and I can reproduce the error that I described. 

After the dependencies are installed `npm i` if you run `npm run serve`, it should start the static server that you can hit on the localhost
![image](https://user-images.githubusercontent.com/40774045/74363458-748ffc00-4d7f-11ea-8492-25444382a321.png)

When you run `npm run test` you should be able to see the static serve command and testcafe command run in parallel and the second test fail.
![image](https://user-images.githubusercontent.com/40774045/74363556-a30dd700-4d7f-11ea-8443-bb6996d3ad55.png)

Running the `npm run testdebug` will open the browser (hard-coded to chrome) in debug mode where you can run the test by each step and when the second test runs the network requests in DevTools will show the 404 for the "js" file that I posed in the screenshot.

------------

The demo repo is built using a very basic stencil component. It is probably possible to replicate it by loading a JS file that import another file using relative path like this - `import "./some.js" and serving this file using a simple `http-server` with cache header set to 0 like above command in the screenshot - `http-server www -c0`

**Comment by bertschneider** [comment]
I think I am currently tracking the same problem but it looks like a session error. But I will also have a look at the cache header as @onemindatime suggested.

I added some log statements at https://github.com/DevExpress/testcafe-hammerhead/blob/f17ba0974f16daefeebbb2b6470444dac8b79191/src/request-pipeline/context.ts#L192-L195 and it seems that the passed in `openSessions` doesn't contain the needed one. I don't know if it is the old one or the one contained in the cached files as @onemindatime mentioned.
```
No open session found for "D6Fmai0v3" in Map {
  'uAbIecsfl' => SessionController {
    _events: [Object: null prototype] {},
    ...
  }
```

**Comment by bertschneider** [comment]
I extended the logs and it really looks like an old/cached version of a page is used and so refers to an old session.

**Comment by onemindatime** [comment]
Yup, that's exactly the same issue @bertschneider 
The cached script has the replaced url for the imported script path which had the old session id. We need to be able to update the session id inside the cached file in jsCache or disable caching for some runs.

Thanks
