### ISSUE TITLE
Page content doesn't load : Invalid template

### ISSUE THREAD

**Issue by Sabou44** [DevExpress/testcafe-hammerhead#2228]
### What is your Test Scenario?

TestCafe fails to load page content

### What is the Current behavior?

 
![current-behavior](https://user-images.githubusercontent.com/59806062/73670172-0b3a2a00-46a9-11ea-9ca0-a0bcd3e71a80.PNG)

![testcafe-invalid-template](https://user-images.githubusercontent.com/59806062/73670347-5a805a80-46a9-11ea-8c3c-756615f5d253.PNG)

### What is the Expected behavior?

![expected-behavior](https://user-images.githubusercontent.com/59806062/73670201-17be8280-46a9-11ea-9570-5abf798deae2.PNG)

### What is your web application and your TestCafe test code?

 
<details>
<summary>Your website URL (or attach your complete example):</summary>

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my https://jazz.net/
2. Log-in or register
3. Got to https://jazz.net/preview01-qm/web/console/Adaptive%20Cruise%20Control%20Testing/_dukf0GrUEeenhapigYqJzw#action=com.ibm.rqm.planning.home.actionDispatcher&subAction=viewResult&resultItemId=_HPmREH2bEeeXk_LU3pdwfQ
 
### Your Environment details:
 
* testcafe version: v1.8.1
* node.js version: v10.16.3
* browser name and version: Chrome 79.0.3945.130, Firefox 72.0.2
* platform and version: Windows 10 Pro

**Comment by LavrovArtem** [comment]
Hi @Sabou44,

I've researched this issue and figured out that you are using a wrong markup on your side. Please check out this file:
` /preview01-qm/web/com/ibm/rqm/execution/web/ui/internal/view/templates/execution/ExecutionLogBody.html`

A simplified example of the wrong markup:
```html
<div id="parent">
    <div id="first-child">
        <table>
            <tr>
                </div> <!-- the extra closed div tag -->
            </tr>
        </table>
    </div>
    <div id="second-child">
    <div>
</div>
```

This issue is reproducing only with TestCafe, a browser swallows this markup, but TestCafe cannot process **wrong markup**.

**Comment by frejfrej** [comment]
Hi guys!
I'm working with @Sabou44 :)
Is there any way for us to observe the response and fix it before it's loaded by TestCafé? Some sort of a listener we could register upon page load? Or anything?
We really need to navigate this page, so any hint you can think of is more than very welcome 👍 
Thanks

**Comment by AlexSkorkin** [comment]
Hi,
See if the [Mocking HTTP Requests](https://devexpress.github.io/testcafe/documentation/test-api/intercepting-http-requests/mocking-http-requests.html) topic can be useful in your scenario.
