### ISSUE TITLE
Slow page load: https://accounts.google.com

### ISSUE THREAD

**Issue by adriancable** [DevExpress/testcafe-hammerhead#2237]
I am using a low-power embedded system (960MHz ARM). testcafe-hammerhead is always very slow, for example, loading https://accounts.google.com through hammerhead takes typically 17-18 seconds (compared with under 2 seconds without proxy). Presumably hammerhead is doing a lot of work rewriting JS code, but I still wonder why it is so slow.

What is the root cause of the general slow performance, and is it ever possible to address? Thank you!

**Comment by Farfurix** [comment]
@adriancable 

Hello,

Yes, the `testcafe-hammerhead` proxy needs to use client resources to process web application code as you mentioned above: DOM, resources, script and style processing, overriding native interfaces methods, adding some specific business logic, etc. We consider performance issues, for example: https://github.com/DevExpress/testcafe-hammerhead/issues/2149, https://github.com/DevExpress/testcafe-hammerhead/issues/2198. These cases are related to page code, not the specific environment. Also, we track our [health monitor results](http://66.55.147.18:13500/) based on loading real web pages.

We cannot consider this performance issue in the context of any low performance custom hardware environment. If the performance issue can be reproduced on Windows/Linux/macOS desktops (or CI systems), feel free to share a simple project or a public URL. We will examine it.

**Comment by adriancable** [comment]
Hi @Farfurix - I'm very sorry that my original post was unclear. The performance issue isn't specific to my low performance custom hardware environment. It can also be reproduced on Mac OS and Linux (at least). The test URL is: https://accounts.google.com

You will notice that the load of this URL takes several seconds, even on fast hardware. In the mean time, because testcafe-hammerhead does not use worker threads, the NodeJS process locks up.

Hope this is more clear.

**Comment by adriancable** [comment]
Added some more detail and changed the title to be more descriptive.

**Summary of issue**

testcafe-hammerhead is extremely slow to load accounts.google.com, despite the small page size.

**How to reproduce**

Use test/playground (or any other instantiation of the testcafe-hammer-headproxy) and navigate to: https://accounts.google.com

**Expected result**

Page loads quickly. Chrome 80, Mac OS X without proxy: 0.9s

**Actual result**

Page very slow to load - long blank screen before render. Chrome 80, Mac OS X with proxy: 4.2s

**Comment by Dmitry-Ostashev** [comment]
Thank you for the detailed information. We'll research this case and notify you as soon as we have any result.

**Comment by sswales** [comment]
Any update on this issue?
