### ISSUE TITLE
Re: TestCafe should apply the last executed RequestMock's response for a matched request

### ISSUE THREAD

**Issue by macarie** [DevExpress/testcafe-hammerhead#2239]
I'm opening this issue because @AndreyBelym said that https://github.com/DevExpress/testcafe/issues/4680 should be _fixed_ here.

I looked a bit around and found that if this `if`:

https://github.com/DevExpress/testcafe-hammerhead/blob/46f5fb8fd985caeab5b76f17913918ca69e07cfd/src/request-pipeline/context.ts#L389

is changed to be only `if (mock)` only the last matching `RequestMock` is run, but I understand that this might not be an ideal solution.

What would you prefer? To run every matching `RequestMock` and overwrite the request's response every time or just to run the last one?

**Comment by Dmitry-Ostashev** [comment]
This enhancement requires some changes in several repositories (including the original repository: https://github.com/DevExpress/testcafe). We'll discuss it with the team and provide all the information in the original thread: https://github.com/DevExpress/testcafe/issues/4680. So, let's continue conversation there and close the current issue.
