### ISSUE TITLE
Testcafe promise bug

### ISSUE THREAD

**Issue by Meemaw** [DevExpress/testcafe-hammerhead#2255]
### What is your Test Scenario?

Test an application doing HTTP requests using [ky-universal](https://github.com/sindresorhus/ky-universal).
 
### What is the Current behavior?

Testcafe crashes on what seems to be cloning of a promise.
 
### What is the Expected behavior?

Testcafe should not crash.
 

<img width="637" alt="Screenshot 2020-02-23 at 18 26 55" src="https://user-images.githubusercontent.com/8524109/75116596-558c4680-566a-11ea-8907-967d518d386d.png">

### Steps to Reproduce:

```sh
➜ git clone https://github.com/Meemaw/testcafe-ky-bug.git
➜ cd testcafe-ky-bug
➜ yarn install
➜ yarn start # If you go to http://localhost:3000 you should see list of "comments" being rendered
```

In a new terminal:

```sh
➜ yarn testcafe chrome e2e/specs -f '<TestcafeBug />'
```

I'm fairly sure you can reproduce this in any setup.

### Your Environment details:
 
* testcafe version:                   1.8.2
* node.js version:                    v10.16.0
* platform and version:         macOS 10.14.6

**Comment by Meemaw** [comment]
Any estimates on time it will take to fix this? This seems like a quite problematic bug preventing one from using Testcafe at all.

**Comment by Dmitry-Ostashev** [comment]
Currently, we cannot provide any estimates, however, we would appreciate your PR.
