### ISSUE TITLE
Suggestion for easy performance improvement: acorn+esotope -> meriyah+astring

### ISSUE THREAD

**Issue by adriancable** [DevExpress/testcafe-hammerhead#2257]
Hi,
As you know hammerhead can significantly slow down websites due to processing overhead, which can make testing very slow on websites that use a lot of JS.

On the hammerhead server side, 95% of CPU cycles are spent on the analyse (parse), transform, generate loop. (Remaining 5% are spent on pre-processing and post-processing.) Of that, 60% is analyse (acorn) + generate (esotope), and 40% is transform.

If we replace acorn+esotope with meriyah+astring, we can get a significant improvement. In general, meriyah is > 2X the performance of acorn. See here for example: https://meriyah.github.io/meriyah/performance/

I tried replacing acorn+esotope with meriyah+astring on the server side on hammerhead (changing under 5 lines of code), and 95%+ of the unit tests pass, and I see a real world page load time improvement of > 30% on complex sites. I did not look in detail into the failing tests, but meriyah claims to be 100% ECMAScript compliant so it may be the issues are due to assumptions on the hammerhead side. Regardless, while I do not know for sure, changing out acorn+esotope with meriyah+astring may be a very quick way to get a significant boost in performance.

Also in general I think it would be good to use standard packages for JS parse and generate, rather than forks of acorn and esotope. I understand the reason, but then you have to maintain the forks and make sure they stay current with the base package (which they are not ... acorn is already a major version ahead of acorn-hammerhead).

What do you think?

-Adrian

**Comment by miherlosev** [comment]
Hi @adriancable
 
Thank you for this information. We use the forks of these libraries to optimize performance and avoid certain bugs.
Theoretically, libraries used for parsing, transformation and code generation can be changed, but this does not seem to be an easy thing. 
For example, you would need to do the following for that:
* rewrite syntax tree transformers (https://github.com/DevExpress/testcafe-hammerhead/tree/master/src/processing/script/transformers)
* make sure that changed transformations work correctly for all edge cases (see them in the https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/server/script-processor-test.js file)
* run our internal performance tool that checks changed code with a lot of real web sites.
	 
If you are ready to do this, we will be happy to help you.

**Comment by adriancable** [comment]
@miherlosev - thank you so much for your response. I will see if in the first instance I can get the built-in unit tests passing with the new parser/generator. Then I will reach out to you regarding tests on a lot of real web sites.
