### ISSUE TITLE
Dom Processor after proxy

### ISSUE THREAD

**Issue by NizarBsb** [DevExpress/testcafe-hammerhead#2268]
Hello,

Can you please tell me how to activate the DOM inspector after proxying a website? I would like to be able to scan a website DOM to highlight the HTML tag element on mouse-hover, similar to TestCafe Studio using testcafe-hammerhead.

**Comment by AlexKamaev** [comment]
You do not need to do anything special to activate the DOM inspector with TestCafe. In Chrome it is enough to press the `F12` button (if you are using Windows);
If you want to run the inspector during the test execution, you can pause the test using the `t.debug()` command.
In addition, you want to start Chrome with the opened Inspector using the `--auto-open-devtools-for-tabs` flags, i.e `testacafe "chrome ----auto-open-devtools-for-tabs" test.js`.

**Comment by NizarBsb** [comment]
@AlexKamaev Thanks for your straightforward answer. This ticket can be closed.
