### ISSUE TITLE
Incompatible with react-scripts 3.4.0 and greater

### ISSUE THREAD

**Issue by kerly** [DevExpress/testcafe-hammerhead#2278]
# What is your Scenario?
After upgrading our app's frontend to react-scripts 3.4.0, TestCafe is unable to load webpages built from react-scripts.
 
### What is the Current behavior?
Webpages don't load when running TestCafe tests against app built from react-scripts
Webpages load fine manually browsing in the browser against app built from react-scripts
Webpages load fine when running TestCafe when app is built in other manner (production build)
 
### What is the Expected behavior?
Webpages load when running TestCafe tests against app built from react-scripts

### Steps to Reproduce:
Execute testcafe against a webapp built from react-scripts using a version pre 3.40 and a version post 3.4.0

1. TODO: Reproduce on a small create-react-app project and link it here
 
### Your Environment details:
* node.js version:                    10.15.2
* testcafe version:                   1.8.3
* browser name and version: Tested against Chrome, Chromium and Firefox
* platform and version:           macOS 10.14.6

### Notes:
My research has led me to believe this could be due to the proxying of testcafe and the proxy changes made in react-scripts.   
https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md#nail_care-enhancement-1
"do not redirect served path if request may proxy"

**Comment by AlexKamaev** [comment]
Thank you for your input.
>TODO: Reproduce on a small create-react-app project and link it here

We will check your example after it is linked. Thank you in advance.

**Comment by kerly** [comment]
This error might not be related to hammerhead. I'm going to close for now.
