### ISSUE TITLE
Investigate the possible crash with Google Recaptcha V2

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#2301]
https://supportcenter.devexpress.com/internal/ticket/details/T882600

It can be connected with https://github.com/DevExpress/testcafe-hammerhead/issues/2223.

**Comment by Farfurix** [comment]
I close this issue due to https://github.com/DevExpress/testcafe-hammerhead/issues/2223#issuecomment-628031482.
