### ISSUE TITLE
Something wrong with load page after login

### ISSUE THREAD

**Issue by biujmm** [DevExpress/testcafe-hammerhead#2304]
Step to Reproduce:
1. Go to page https://portal.azure.com/ through a proxy
2. Login in 
3. Page carsh after few second

Testcafe-hammerhead 16.2.6
Node 12.16.2

**Comment by Farfurix** [comment]
Hello,

I was able to reproduce the "authentication loop" issue. You can resolve it using the [`options.preserveUrl`](https://devexpress.github.io/testcafe/documentation/test-api/authentication/user-roles.html#optionspreserveurl) `Role` option:
```js
import { Role } from 'testcafe';

const role = Role('https://portal.azure.com/signin', async t => {
    await t
        .typeText('#i0116', '*****')
        .click('#idSIButton9')
        .typeText('#i0118', '*****')
        .click('#idSIButton9')
        .debug() // I use it to unlock the tested page and enter the security code
        .click('#idBtn_Back');
}, { preserveUrl: true });

fixture `My Fixture`;

test('My test', async t => {
    await t
        .useRole(role);

    await t
        .navigateTo('https://portal.azure.com/#home');

    await t.wait(100000);
});
```

My environment:
Windows 10
Node v12.16.2
TestCafe v1.8.4

**Comment by biujmm** [comment]
I try your sollution but it does`t work. Sometimes page is load correctly after login but sometimes is go in loop.

**Comment by AlexKamaev** [comment]
I was able to reproduce the issue using @Farfurix's example even with the `preserveUrl` option enabled.
@biujmm
This issue is a duplicate of [https://github.com/DevExpress/testcafe/issues/4024](https://github.com/DevExpress/testcafe/issues/4024), so please track the original issue.
