### ISSUE TITLE
Values retrieved from localStorage are returned in their original type rather than as a string

### ISSUE THREAD

**Issue by welkup** [DevExpress/testcafe-hammerhead#2313]
### What is your Test Scenario?
Local storage is returning entries as their type at time of storage rather than as a string. For example,

```
window.localStorage['foo'] = true
window.localStorage.getItem('foo') // got true, want 'true'
```

### What is the Current behavior?
Currently returns the raw boolean value, true

### What is the Expected behavior?
Expected to return string value 'true'

<details>
<summary>Screenshots:</summary>
Behavior in TestCafe browser window:

![image](https://user-images.githubusercontent.com/6898824/80916365-cfe9de80-8d1d-11ea-9874-023c353bbb85.png)

Behavior in regular Chrome browser window:

![image](https://user-images.githubusercontent.com/6898824/80916405-0de70280-8d1e-11ea-8fed-6b3e07171312.png)

</details>

### Steps to Reproduce:

1. Call `.debug()`
3. Unlock the page
4. Open dev tools
5. In console, enter `window.localStorage['foo'] = true`
6. then enter `window.localStorage.getItem('foo')`
 
### Your Environment details:
 
* testcafe version: 1.8.4      
* node.js version: v12.16.1                 
* command-line arguments:  testcafe chrome ./test-file.js
* browser name and version: Chrome 80
* platform and version: Linux Ubuntu 18.04.4

**Comment by miherlosev** [comment]
Hi @welkup 

Thank you for the provided information. I've reproduced the problem.

**Comment by iwt-hhesselbarth** [comment]
Any progress in this bug? We currently have a problem in production, which is blocking our pipelines. The usercentric cookie consent is accessing the localStorage and mapping the length of its values. Now its the case that there are null values in the localStorage and calling length on a raw null value rather then the string representation (like defined in the localStorage interface) causing the script to crash.

**Comment by wentwrong** [comment]
We haven't started working on that particular bug yet and cannot give you any estimates as to when it will be fixed.

As a workaround, we can suggest you use proxy for your `localStorage` object in a custom way. [Injecting Client Scripts](https://devexpress.github.io/testcafe/documentation/guides/advanced-guides/inject-client-scripts.html) can help you override values already initialized by TestCafe Hammerhead. With the help of the [ES6 Proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) you can wrap the `localStorage` object and make it return the results you want:

```js
// /home/eax/test/test.js
import { ClientFunction } from 'testcafe';

const overrideLocalStorage = () => {
    Object.defineProperty(window, 'localStorage', {
        value: new Proxy(localStorage, {
            set: (target, propKey, value) => {
                target[propKey] = value;
                
                return true;
            },
            get: (target, propKey) => {
                if (typeof target[propKey] !== 'function') {
                    return String(target[propKey]);
                }

                return function (...args) {
                    const result = target[propKey].apply(target, args);
                    
                    return String(result);
                };
            }
        })
    });
};

fixture `Local Storage Overriding`
    .page('file:///home/eax/test/test.html')
    .clientScripts({
        content: `(${overrideLocalStorage.toString()})()`
    });

test(`Check that a localStorage.foo value should be equal to the "null" string`, async t => {
    const getLocalStorageFoo = ClientFunction(() => window.localStorage.foo);
    const fooValue           = await getLocalStorageFoo();

    await t.expect(typeof fooValue).eql('string');
    await t.expect(fooValue).eql('null');
})
```

```html
<!-- It's content of the "/home/eax/test/test.html" file -->
<script>
    window.localStorage.foo = null;
</script>
```

**Comment by iwt-hhesselbarth** [comment]
Hi Pavel, 
Thank you for your quick response! Your answer helps me alot. I stumbled across the client functions aswell but my workaround still wasn't working correctly. I will give it another try with the ES6 Proxy :-).

I although figured out that the version 1.5 of usercentric cookie consent management (which was released on 15th july 20) triggering the bug. They introduced a function which squashes the localStorage and therefore calculation the size of it. So Version 1.44.2 is still working. Maybe this helps you (and others) if there are other tickets, i guess usercentric CMP is used quite often.

**Comment by miherlosev** [comment]
Hi @iwt-hhesselbarth

Thank you for sharing additional information about this problem.

**Comment by iwt-hhesselbarth** [comment]
Just FYI:

Thank to your help i implemented a workaround. I used your script and changed it slightly and then injected it as client script via .testcaferc.json

fixHammerheadLocalStorageAcccess.js
```
Object.defineProperty(window, 'localStorage', {
  value: new Proxy(localStorage, {
    set: (target, propKey, value) => {
      if (value) {
        target[propKey] = value;
      }
      return true;
    },
    get: (target, propKey) => {
      if (typeof target[propKey] !== 'function') {
        return String(target[propKey]);
      }

      return function (...args) {
        return target[propKey].apply(target, args);
      };
    }
  })
});
```

.testcaferc.json
```
{
  "skipJsErrors": true,
  "clientScripts": [
    {
      "path": "src/workaround/fixHammerheadLocalStorageAcccess.js"
    }
  ]
}
```

Thanks again for the fast feedback!
