### ISSUE TITLE
MutationObserver - MutationRecord nextSibling and previousSibling return invalid sibling

### ISSUE THREAD

**Issue by tomashanacek** [DevExpress/testcafe-hammerhead#2321]
### What is your Scenario?
MutationObserver - MutationRecord nextSibling and previousSibling properties should correctly return previous and next sibling node
 
### What is the Current behavior?
Current behavior is that mentioned properties return `null` instead
 
### What is the Expected behavior?
Expected behavior is to return correct nextSibling and previousSibling node
 
### What is your public web site URL?

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                     
* browser name and version: 
* platform and version:          
* other:

**Comment by tomashanacek** [comment]
I already have fix for this issues, PR is coming in next couple of minutes

**Comment by tomashanacek** [comment]
PR: https://github.com/DevExpress/testcafe-hammerhead/pull/2322

**Comment by alexey-lin** [comment]
Hi @tomashanacek,

Thank you for your contribution! We'll look into the PR in the near future.
