### ISSUE TITLE
LocationWrapper can be initialized without `messageSandbox`, but `messageSandbox` optional isn't properly handled

### ISSUE THREAD

**Issue by tomashanacek** [DevExpress/testcafe-hammerhead#2326]
### What is your Scenario?
`LocationWrapper` can be initialized without `messageSandbox`, but `messageSandbox` optional isn't properly handled
 
### What is the Current behavior?
Test is failing on 
```
Cannot read property 'on' of undefined
```

when `LocationWrapper` is initialized without `messageSandbox`

https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/properties/index.ts#L87

https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/location/wrapper.ts#L159
 
### What is the Expected behavior?
Call `messageSandbox.on` only if `messageSandbox` is provided

https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/location/wrapper.ts#L159
 
### What is your public web site URL?

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                     
* browser name and version: 
* platform and version:          
* other:

**Comment by LavrovArtem** [comment]
Thank you for the bug reporting!
