### ISSUE TITLE
 Cannot read property 'frames' of undefined

### ISSUE THREAD

**Issue by ankush29** [DevExpress/testcafe-hammerhead#2339]
url: https://www.bedbathandbeyond.com/

try it in hammerhead playground and open console
and run below code:  
```js
var frames = window.frames;
console.log('Length', frames.length); // or // var frames = window.parent.frames;
for (var i = 0; i < frames.length; i++) {
  // do something with each subframe as frames[i]
   console.log(i);
   console.log(frames[i]);
  frames[i].document.body.style.background = "red";
}
```
And press enter, you will find the error: VM917:6 Uncaught DOMException: Blocked a frame with origin "https://www.bedbathandbeyond.com" from accessing a cross-origin frame.

it's a blocker for me but we can handle this by adding one condition in a file named window-sync.ts:

open file: window-sync.ts and line number : 68
```ts
 private _getWindowsForSync (initiator: Window, currentWindow: Window, windows: Window[] = []): Window[] {
        if (currentWindow !== initiator && currentWindow !== this._win.top)
            windows.push(currentWindow);

        // @ts-ignore
        for (const frameWindow of currentWindow.frames)
            this._getWindowsForSync(initiator, frameWindow, windows);

        return windows;
    }
```
change this into 
```ts
 private _getWindowsForSync (initiator: Window, currentWindow: Window, windows: Window[] = []): Window[] {
        if (currentWindow !== initiator && currentWindow !== this._win.top)
            windows.push(currentWindow);

        // @ts-ignore
       if(currentWindow) {
            // @ts-ignore
            for (const frameWindow of currentWindow.frames)
                this._getWindowsForSync(initiator, frameWindow, windows);
       }
        return windows;
    }
```

just by adding if condition before for loop which will handle undefined frames.

Thanks

**Comment by LavrovArtem** [comment]
I don't understand how the code from the first block is related to the issue. Could you please create a simple sample that demonstrates the problem?

**Comment by ankush29** [comment]
actually, it's an ongoing confidential project. can't share site details but I got this error. please go through it 
![testcafe hammer head](https://user-images.githubusercontent.com/11795347/83874701-88f36c80-a753-11ea-9e8b-ffe56f575000.PNG)

**Comment by ankush29** [comment]
any update on it?

**Comment by Farfurix** [comment]
@ankush29 

Hello,

> try it in hammerhead playground and open console
and run below code:

Is it a part of the internal logic on this website? If so, could you describe steps to reproduce this issue in a real scenario and share your test code?

**Comment by ankush29** [comment]
I have just navigated to the website and got this error in the console. Due to error, a website is not behaving properly.

**Comment by AlexKamaev** [comment]
@ankush29
I executed the code from your original message on your site without TestCafe or Hammerhead Playground and I got the same error.
Could you try running your script without playground? It looks like this is not a testcafe related issue.

**Comment by Saturate** [comment]
Seems like this issue can arise when you close a cookie notification from https://cookieinformation.com/ as they use a iframe in a way that seems to mess with hammerhead.js

**Comment by PavelMor25** [comment]
Hello @Saturate,

This information is not sufficient to reproduce the issue you described. Please create a separate ticket in the official GitHub repository using the following [bug template](https://github.com/DevExpress/testcafe/issues/new?assignees=&labels=TYPE%3A+bug&template=bug_report.yaml) so that the TestCafe team can research the problem. Please also refer to the following help topic: [how to create a minimal working example](https://testcafe.io/documentation/402636/faq/general-info#how-to-create-a-minimal-working-example-when-you-submit-an-issue).
