### ISSUE TITLE
data-hammerhead-hovered is being inserted on wrong DOM element in Firefox 77

### ISSUE THREAD

**Issue by deeptigetfeedback** [DevExpress/testcafe-hammerhead#2348]
### What is your Scenario?
Hovering over an element in the iframed page should bring it into focus.
 
### What is the Current behavior?
Hover does not trigger mouseover event. 

### What is the Expected behavior?
Hover should trigger mouseover event.

### Your Environment details:

* node.js version:  v13.11.0
* browser name and version: Firefox 77
* platform and version:  Mac OS 10.15.5
* other: I have attached screenshots of the data-hammerhead-hovered attribute insertions from my two runs one on Chrome and other on Firefox as comparison. Unfortunately this app functionality is not public facing for me to point you to any specific code. I tried the whole CSS path, specific css selector, but nothing seems to be putting the hovered state on the right element in Firefox. This works fine in Chrome 83.0.4103.97 and I can see the data-hammerhead-hovered being inserted into the right element.

![chrome-working](https://user-images.githubusercontent.com/42978526/84442257-1faba780-abf2-11ea-8057-266410450cfa.png)
<img width="1418" alt="firefox-not-working" src="https://user-images.githubusercontent.com/42978526/84442267-22a69800-abf2-11ea-8619-075aab794833.png">

**Comment by Farfurix** [comment]
@deeptigetfeedback

Hello,

> Unfortunately this app functionality is not public facing for me to point you to any specific code.

It is difficult to find the cause of this issue without reproducing it on our side. Could you please create a simple example based on your application logic and share it together with your test code with us? [For example](https://testcafe-discuss.devexpress.com/t/svg-object-selection/1007/4):
```js
import { Selector } from 'testcafe';

fixture `SVG test`
    .page `http://jsfiddle.net/asgallant/QjQNX/`;

test('get values', async t => {
    await t.switchToIframe('iframe');

    const rect      = Selector('[fill="#3366cc"]');
    const rectCount = await rect.count;
    const valueText = Selector('text').filter(el => el.textContent === 'Value:').nextSibling();
    const values    = [];

    for (let i = 1; i < rectCount; i++) {
        await t.hover(rect.nth(i));

        values.push(await valueText.textContent)
    }

    await t.expect(values).eql(['53', '71', '36', '42', '87', '64']);
});
```

**Comment by deeptigetfeedback** [comment]
@Farfurix here you go: The fiddle page is in the code itself. I was able to recreate the issue with this on Firefox 77.0.1. It passed on Chrome Version 83.0.4103.97
`fixture("Test hover donut chart element")
.page(
  `http://jsfiddle.net/bk6cg1wu/22/`
); // fiddle page with the iFramed donut chart

test("Hover over donut segment", async t => {
  await t.debug(); // need to wait for fiddle to load
  await t.switchToIframe('[name="result"]');
  await t
    .hover(Selector("g.c3-chart-arc g path"))
    .expect(Selector(".c3-chart-arc.c3-focused text").exists)
    .ok();
});`

**Comment by deeptigetfeedback** [comment]
@Farfurix Any update on this?

**Comment by SergeyShurygin** [comment]
Hi @deeptigetfeedback  

I apologize for the delayed response. I've reproduced the issue using TestCafe 1.8.7 and FireFox 77. We'll look into it.
