### ISSUE TITLE
Remove `integrity` attributes from resources

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#235]
See: http://www.w3.org/TR/SRI/

This attribute is used to avoid MITM attacks. Attribute contains SHA of the desired resource. Which doesn't work for us. This is widely used currently. And it brokes e.g. GitHub proxying. I suggest to remove this attribute entirely. It applies only to `<script>` and `<link>` elements.

**Comment by LavrovArtem** [comment]
Unprocessed cases:
```js
script.setAttribute('integrity', '...');
script.integrity = '...';
```

**Comment by Farfurix** [comment]
I'm working on it.
