### ISSUE TITLE
Extend the limit of http header size

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#2356]
* Increase size to 16Kb (check for command-line and programmatic interfaces).
* Add a warning if there is header that size is more than limit.

`--max-http-header-size`

https://stackoverflow.com/questions/1097651/is-there-a-practical-http-header-length-limit/6160643#6160643

**Comment by AndreyBelym** [comment]
The default max HTTP header size is 16kB by default starting with Node v14.0.0: 
https://nodejs.org/api/cli.html#cli_max_http_header_size_size

#2398 increased the max header size for all requests to the previous default, 80kB.

It also added an error message that describes the problem and suggests some ways to increase the max header size above the limit.
