### ISSUE TITLE
Wrong processing of 'for...of' with destructuring

### ISSUE THREAD

**Issue by uriacuesta** [DevExpress/testcafe-hammerhead#2363]
Original Script
```js
function test(t) {
    for(let[o,i]of t) {
        console.log(o,i);
    }
}

test([[1,2],[3,4]]);
```
 
Processed Output
```js
function test(t) {
    for(let _hh$temp0of t) {
         let o=_hh$temp0[0],i=_hh$temp0[1];console.log(o,i);
    }
}
```

Expected
```js
function test(t) {
    for(let _hh$temp0 of t) {
         let o=_hh$temp0[0],i=_hh$temp0[1];console.log(o,i);
    }
}
```

The script is valid in chrome, however the processed output will cause a syntax error "Uncaught SyntaxError: Unexpected identifier". `for(let[o,i]of t)` should be processed to `for(let _hh$temp0 of t)` instead of `for(let _hh$temp0of t)`

### Environment Details
* node.js version: v12.16.0
* browser name and version: Version 83.0.4103.106 (Official Build) (64-bit)

**Comment by Farfurix** [comment]
@uriacuesta

Hello,

Thank you for the detailed information. I reproduced the issue and added this issue to the current development sprint.
