### ISSUE TITLE
Support service workers

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe-hammerhead#2387]
### What is your Test Scenario?

 I have an app using msw, a mock service worker which provides seamless mocking between node & browser using a service worker.  In the browser, it does this by mocking the fetch calls in a service worker.

When I run my unit tests (in jest) or when I run my app in the browser, they both can share the same mock endpoints.  I am now trying to run the tests in testcafe but running into what i believe could be a conflict between `transport-worker` and `mockServiceWorker` which is causing this problem. The details of the bug can be found here https://github.com/mswjs/msw/issues/259 (I posted it in both projects just in case) 

### What is the Current behavior?

 mockServiceWorker is not able to intercept fetches.

### What is the Expected behavior?

 mockServiceWorker is able to intercept fetches.
 
### What is your web application and your TestCafe test code?

 https://github.com/benmonro/msw-server/tree/feature/testcafe
<details>
<summary>Your website URL (or attach your complete example):</summary>
just running locally in above repo.

</details>

<details>
<summary>Your complete test code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```

```
</details>

<details>
<summary>Your complete test report:</summary>

```

```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to my website ...
3. Execute this command...
4. See the error...
 
### Your Environment details:
 
* testcafe version:                   
* node.js version:                    
* command-line arguments:  
* browser name and version: 
* platform and version:          
* other:

**Comment by benmonro** [comment]
@AndreyBelym this is going to be a major blocker for us at Walmart.com.  If I purchase a PRO license of testcafe and file a ticket, would that help expedite the implementation of this issue?  The issue you referenced above is 3 years old and has no estimate on when it will be implemented.

**Comment by AlexKamaev** [comment]
@benmonro

We understand that you are interested in this feature a lot. We are working on it. We accept your vote for this feature. However, we take a lot of other factors into account when we set priorities. We appreciate your patience.

**Comment by benmonro** [comment]
@AlexKamaev  @AndreyBelym @miherlosev 

I believe I found a way to make this work quite nicely.  if we can add a configuration option to add the ability ignore a service worker file at this line: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/window.ts#L618 then MSW (and other specified service workers) will behave as expected.

for example, suppose in the testcafe config we had a list of serviceWorker files like this:

```json
{
   "unmodifiedServiceWorkerPaths":["/mockServiceWorker.js", "path/to/other.js"]
}
```

then just add an additional condition like this on that line:

```js
if(typeof url === 'string' && !config.unmodifiedServiceWorkerPaths.includes(url)) 
```

The heart of my issue is that [`getProxyUrl`](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/window.ts#L627) changes the behavior of the service worker such that fetch calls are not intercepted.  

I have verified that this works locally in hammerhead, but I'm not clear on how to pass the hammerhead config down to this class.  any guidance you can provide for me on this?  

then i can open a PR for this issue.

**Comment by Farfurix** [comment]
@benmonro 

Hello,

We described the reasons why we can't accept your PR in the comments to it: https://github.com/DevExpress/testcafe-hammerhead/pull/2388.

Here's another workaround you can use. Take note of the `mockServiceWorkerRegister` function and `clientScripts`:
```js
function mockServiceWorkerRegister () {
    const hammerhead            = window["%hammerhead%"];
    const registerServiceWorker = hammerhead.nativeMethods.registerServiceWorker;
    const getProxyUrl           = hammerhead.utils.url.getProxyUrl;
    const stringifyResourceType = hammerhead.utils.url.stringifyResourceType;
    window.navigator.serviceWorker.register = registerServiceWorker;
}
fixture('Fixture')
  .clientScripts({ content: `(${mockServiceWorkerRegister.toString()})()` })
  .page(`localhost:3000`);
test('test', async t => { 
    await t.debug();
})
```

**Comment by benmonro** [comment]
@Farfurix I have tried using this solution, it seems to work, but I have seen intermittent failures with it. I'm registering my clientScript in config so that it will be on every page/test.  Here's the script I have:

```js
  const getProxyUrl = window["%hammerhead%"].utils.url.getProxyUrl;

  window["%hammerhead%"].utils.url.getProxyUrl = function mswGetProxyUrl() {
    const url = arguments[0];
    if (!url.startsWith("/mockServiceWorker")) {
      return getProxyUrl.apply(this, arguments);
    }
    console.log("HERE",{url})
    return url;
  };

```

We really need a stable and reliable way to interact with service workers.  Is there any way to prioritize this issue?  I have a paid PRO license for support.

**Comment by miherlosev** [comment]
Hi @benmonro

Thank you for acquiring the PRO license for TestCafe Studio. This will give us resources for improving the open-source TestCafe version.The solution created by @Farfurix is a workaround. We cannot grantee that it will work fine in all complex scenarios. 
Right now we are working hard on the 'Web Workers' feature. The [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/2397) is already available. We will publish a new TestCafe version as soon as we complete this feature. Please stay tuned.
