### ISSUE TITLE
Tests for nested iframes

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#239]
There are the following iframe types:
1)without a src attribute
2)src is set to a same-domain url
3)src is set to a cross-domain url
4)src has the 'about:blank' value
5)src has a javascript protocol value (`src = "javascript:'<html><body><h1>test</h1></body></html>'"`)

Need to add tests for nested iframes for all combinations

**Comment by inikulin** [comment]
I suppose it's covered by web platform tests

**Comment by miherlosev** [comment]
Our tests cover the described cases.
