### ISSUE TITLE
Can't get <title> textContent

### ISSUE THREAD

**Issue by viktorss89** [DevExpress/testcafe-hammerhead#2390]
### Are you requesting a feature or reporting a bug?
This used to work in my previous version of testcafe (1.8.0). I updated to 1.8.8 and I noticed these tests failing because of not getting the text from the title tag, nothing changed in my code so I'm supposing it's an issue at your end.

### What is your Test Scenario?
I'm going into my project's website and try to get title.textContent, and assert it against a given string.

### What is the Current behavior?
title.textContent returns "".
If I go to the dev tools in a browser window and inspect the elements I can successfully do $('title').text and retrieve the text from the title.
**However, if I debug from testcafe window and inspect the element and I do $('title').text it retrieves ''.
I can only retrieve the text properly with $('title').outerText, but this property is not available in the Selector objector.**

### What is the Expected behavior?
title.textContent returns the text from the title tag.

### How would you reproduce the current behavior (if this is a bug)?
I can't share my project so I have no idea how to help you out in reproducing this issue :/

### Your Environment details:
 
* testcafe version:                   1.8.8
* node.js version:                   12.16.3
* command-line arguments:  testcafe chrome (or chrome:headless)
* browser name and version: Chrome 81.0.4044.138 / macOS 10.14.6

**Comment by miherlosev** [comment]
Hi @viktorss89 

> The problem was occuring because we have an esincludes that messes up the DOM and the title is in the body instead of the header.

The <title> element is always used within a page's <head> block (according to the [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title) help topic ). The browsers extends the standard and handle a `<title>` element from a `<body>` element. We will not support this scenario until there is a large number of people who are affected by this scenario.
