### ISSUE TITLE
connection-reset-guard throws error and brokes tests

### ISSUE THREAD

**Issue by artur-michalak** [DevExpress/testcafe-hammerhead#2396]
I'm using node latest LTS v12.0 with TestCafe v1.8.8 running regular test (with user Role) i'm getting this error
```
 My account page displays correct info about user

   1) - Error in Role initializer -
      Uncaught exception:
      
      Error:

      Browser: Chrome 84.0.4147.105 / macOS 10.15.5
```
It's thrown here https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/connection-reset-guard.ts#L15
![image](https://user-images.githubusercontent.com/2443904/88907120-95c6a500-d258-11ea-8080-949b99efa6ac.png)

Unfortunately there is no message or any detail. I'm not sure what is purpose exact purpose of this module but after commentin these lines out i got correct results.
Moreove domain api has been deprecated https://nodejs.org/docs/latest-v12.x/api/domain.html so i'd be good to reactor this file.

**Comment by Ogurecher** [comment]
Hello @artur-michalak,

Thank you for your report. Please provide a simple page and test code that demonstrates this issue.

**Comment by artur-michalak** [comment]
I'll try, however it maybe hard to recreate on different machine as this looks like connection issue which relates probably to network configuration.

BTW. i found workaround by adding **-u switch** to testcafe command https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-u---skip-uncaught-errors
