### ISSUE TITLE
Client scripts intermittently not loaded

### ISSUE THREAD

**Issue by benmonro** [DevExpress/testcafe-hammerhead#2400]
### What is your Scenario?

 I have a scenario where I have 4 client scripts. Testcafe testing library, axe, tiny-cookie and a local script I need to inject into the page during tests.

### What is the Current behavior?

 
Most of the time everything works fine, but occasionally I am seeing a situation where 1 or 2 of the client scripts do not get injected.  I'm using the debug on fail flag to inspect the dom where I can see some but not all of the custom client script tags in the head of the document.

### What is the Expected behavior?

 All the client scripts are always injected.

### What is your public web site URL?

I have had trouble reliably reproducing this issue but when I do I will update it here.
Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                     
* browser name and version: 
* platform and version:          
* other:

**Comment by miherlosev** [comment]
Hi @benmonro 

Thank you for sharing this information. To reproduce and examine the issue, we need an example to work with even if the issue can be reproduced unstably. So, we will wait until you can share such an example.
