### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ';' error occurs when using Angular website

### ISSUE THREAD

**Issue by AlexSkorkin** [DevExpress/testcafe-hammerhead#2401]
See the following private bug report for details:

[T920714 - Record test with TestCafe Studio: Uncaught SyntaxError: Unexpected token ';' is thrown](https://supportcenter.devexpress.com/internal/ticket/details/T920714)

This issue is similar to this one:

[Cant open Login page when opend with testcafe](https://github.com/DevExpress/testcafe-hammerhead/issues/2391)

**Comment by Farfurix** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/2389
