### ISSUE TITLE
Test freezes with "Maximum call stack size exceeded" error - Testcafe version 1.8.3 and up

### ISSUE THREAD

**Issue by KingM1** [DevExpress/testcafe-hammerhead#2405]
### What is your Scenario?
My test does the following: goes to a product page, opens a Write Review modal, and writes a review. But, when it goes to do anything on the modal (select a star, type the review, etc), it freezes and throws a "Maximum call stack size exceeded" error in the console over and over until I manually quit the test.
I'm unable to upgrade testcafe past 1.8.2 because of this bug. 
 
### What is the Current behavior?
Write Review modal opens, and app freezes when trying to click a rating
 
### What is the Expected behavior?
Modal should not freeze, and should select a rating correctly
 
### What is your public web site URL?

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
fixture('Reviews');
test('Add Review', async (t) => {

    await t.navigateTo('https://www.anthropologie.com/shop/liv-duster-kimono');
    await t
        .click('.c-pwa-reviews-snippet__reviews-link')
        .click('.c-pwa-reviews-snippet__reviews-link'); // might not need this depending on network speed

    await t
        .click('[for="review-rating-1"]')
        .typeText('#review-title', 'test')
        .typeText('[data-qa-review-message]', 'test test test test test test');
});


```
</details>

<details>
<summary>Screenshots:</summary>
<img width="1073" alt="Screen Shot 2020-08-13 at 11 36 58 AM" src="https://user-images.githubusercontent.com/18680414/90155671-96cbfc00-dd59-11ea-9336-1b680f27309f.png">

</details>

### Steps to Reproduce:
* Run the above test script
* When the modal opens, you'll see it get frozen when it tries to click on a star, and the console consistently throws the error attached to this ticket
 
### Your Environment details:

* node.js version:                    10.13.0
* browser name and version: Chrome 83
* platform and version:          macOS 10.14
* other:                                   Happens with testcafe v1.8.3 and above (testcafe v1.8.2 does not have this issue)

**Comment by miherlosev** [comment]
Hi @KingM1 

Thank you for the provided information. I've reproduced the problem.
