### ISSUE TITLE
Support for Blob 

### ISSUE THREAD

**Issue by xorxero** [DevExpress/testcafe-hammerhead#2422]
Repeat test actions in the browser and check the console for errors.
      If you see this error, it means that the tested website caused it. You can fix it or disable tracking JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
      If this error does not occur, please write a new issue at:
      "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

      JavaScript error details:
      TypeError: Blob is not a constructor

I'm using a library called React-PDF using it to generate a pdf and I use the .toBlob() function which probably calls the constructor.

You can take a look at their .toBlob function here
https://github.com/diegomura/react-pdf/blob/fdbda8bb951832d6748696123447afedfedc9bb5/src/index.js

**Comment by russsauce** [comment]
Our team ran into a similar issue with this as well. We have the following sanitization code that uses Blob `size` to filter out characters of a string:

```
chars.filter((char) => new Blob([char]).size <= 3).join('');
```

When running our e2e tests in Chrome, it actually prevents characters other than special characters from being entered into a certain field, and playing around in the console shows the following:

<img width="640" alt="Screen Shot 2021-02-19 at 17 20 07" src="https://user-images.githubusercontent.com/56034040/108531786-61d7cd80-72d7-11eb-85d9-1db4a9768684.png">

I also verified that the definition of `Blob` is coming from `hammerhead.js`

**Comment by Farfurix** [comment]
@russsauce 

Hello,

You are right, this is a part of [our proxy](https://github.com/DevExpress/testcafe-hammerhead).

Thank you for the additional scenario. We will take it into account in the context of this issue. At the moment, I cannot give you any estimate on when this issue will be fixed.
