### ISSUE TITLE
window.location constructor properties shadowed incorrectly

### ISSUE THREAD

**Issue by adriancable** [DevExpress/testcafe-hammerhead#2423]
Sample code:

```
console.log('-1->', window.location.constructor.name);
console.log('-2->', window.location.constructor.toString());
console.log('-3->', Function.prototype.toString.apply(window.location.constructor));
console.log('-4->', window.location instanceof Location);
```

When run in a real browser:

-1-> Location
-2-> function Location() { [native code] }
-3-> function Location() { [native code] }
-4-> true

When run under Testcafe:

-1-> g
-2-> function(e,t,r){var n=this ...
-3-> function(e,t,r){var n=this ...
-4-> false

Issue is that many websites (e.g. Google login) use a check like this as part of botguard and change their behaviour as a result.

Can testcafe-hammerhead be improved to "stealth" these changes?

**Comment by Farfurix** [comment]
@adriancable 

> When run under Testcafe:
>
> -1-> g
> -2-> function(e,t,r){var n=this ...
> -3-> function(e,t,r){var n=this ...
> -4-> false

I checked several websites and got the correct result:
```
-1-> Location
-2-> function Location() { [native code] }
-3-> function Location() { [native code] }
-4-> true
```

Could you please share your project and your environment (see our [Bug report template](https://github.com/DevExpress/testcafe-hammerhead/issues/new?assignees=&labels=&template=bug_report.md&title=))? We will examine it and check for a suitable solution.

**Comment by adriancable** [comment]
@Farfurix - to reproduce please do the following.

1. Clone new copy of testcafe-hammerhead from github, and run the playground:

git clone https://github.com/DevExpress/testcafe-hammerhead.git
cd testcafe-hammerhead
npm install
node node_modules/gulp/bin/gulp http-playground

2. Navigate to http://localhost:1400 in Chrome (I am on 85.0.4183.83) or Safari (13.1.2), and direct the playground to this URL:

https://sidewinder.starlinghome.io/beta_old/ifcheck.html

3. Look in the console.

**Comment by Farfurix** [comment]
@adriancable

Thank you for the information. I reproduced the issue using your markup:
```html
<html>
<head></head>
<body></body>
<script>
  console.log('-1->', window.location.constructor.name);
  console.log('-2->', window.location.constructor.toString());
  console.log('-3->', Function.prototype.toString.apply(window.location.constructor));
  console.log('-4->', window.location instanceof Location);
</script>
</html>
```

Our team will examine it and check for a suitable solution.

For the team: partially related to https://github.com/DevExpress/testcafe-hammerhead/issues/2394.
