### ISSUE TITLE
Script fails to load when accessing an website with TestCafe: error: (failed net::ERR_CONTENT_DECODING_FAILED)

### ISSUE THREAD

**Issue by mariuspahontu** [DevExpress/testcafe-hammerhead#2427]
### What is your Test Scenario?
A javaScript file fails to load when accessing the website with TestCafe.
The same javaScript file is loading correctly when accessing the website manually

Steps to reproduce it:
- For TestCafe - Run the attached code
- Manually: it cannot be reproduced.

### What is the Current behavior?
When accessing the test website with TestCafe one script from OneTrust is not loaded, instead is thrown an error: **failed net::ERR_CONTENT_DECODING_FAILED**
![image](https://user-images.githubusercontent.com/5627543/91850723-ace92000-ec66-11ea-9918-44588e5cd557.png)
OneTrust cookie banner is not displayed:
![image](https://user-images.githubusercontent.com/5627543/91850769-c2f6e080-ec66-11ea-8646-ab1302cc6a85.png)

### What is the Expected behavior?
When accessing the test website with TestCafe all scripts are loaded correctly.
OneTrust Cookie banner is displayed: 
![image](https://user-images.githubusercontent.com/5627543/91850887-f3d71580-ec66-11ea-8f29-a611de65cc94.png)

 
### What is your web application and your TestCafe test code?

<summary>https://www.westrock.com/</summary>

<summary>Your complete test code (or attach your test files):</summary>

``
test('Visit the page', async t => {
    await t.navigateTo('https://www.westrock.com/');
})``
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "screenshotPath": "screenshots",
  "browsers": "chrome",
  "screenshots": {
    "takeOnFails": true,
    "fullPage": true
  },
  "debugOnFail": false,
  "skipJsErrors": true,
  "disablePageCaching": false,
  "color": true,
  "speed": 0.90,
  "pageLoadTimeout": 30000,
  "assertionTimeout": 30000,
  "selectorTimeout": 30000,
  "concurrency": 1
}

```
</details>

<details>
<summary>Screenshots:</summary>

The Request headers for that Javascript file 
- using TestCafe: 
![image](https://user-images.githubusercontent.com/5627543/91933519-c2eff280-ecf1-11ea-9c7d-d768c2d9c899.png)

- with manual testing; 
![image](https://user-images.githubusercontent.com/5627543/91933537-d00ce180-ecf1-11ea-815a-0d3f33612b4c.png)

```

```
</details>

### Steps to Reproduce:
1. Run the attached code

 
### Your Environment details:
 
* testcafe version:                   1.9.1
* node.js version:                    v11.2.0
* command-line arguments:  no additional parameters
* browser name and version: Chrome - Version 84.0.4147.135 (Official Build) (64-bit)
* platform and version:          win 10

**Comment by miherlosev** [comment]
Thank you for the provided information. I've reproduced the problem.

For team:
It can be connected with a wrong encoding calculation.
![image](https://user-images.githubusercontent.com/4133518/91941130-5f6dc100-ed01-11ea-9494-4353d46c7741.png)
