### ISSUE TITLE
Add support sites with 'Content-Security-Policy'

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#243]
'Content-Security-Policy' header allows to restrict resouce loading (scripts, styles).
After proxing a same sites we can have a 'Refused to load the script ' errors.

Example - https://www.dropbox.com/

Details:
http://www.w3.org/TR/CSP1/
https://en.wikipedia.org/wiki/Content_Security_Policy
http://content-security-policy.com/
http://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by inikulin** [comment]
@miherlosev we already remove those headers: https://github.com/superroma/testcafe-hammerhead/blob/master/src/request-pipeline/header-transforms.js#L49 So, AFAIK it should work already

**Comment by miherlosev** [comment]
On client side it will be added via meta tag:
`<meta http-equiv="Content-Security-Policy" content="script-src https: 'unsafe-eval';">`

**Comment by inikulin** [comment]
Oh, I see. So we just need to remove this metas.

**Comment by inikulin** [comment]
We can do it for now, to prevent errors. And create separate issue for the full-featured CSP emualtion

**Comment by inikulin** [comment]
So at least we will behave as original browser. But this is quite complex feature. Since we will need feature detection and other stuff

**Comment by miherlosev** [comment]
I am working on this
