### ISSUE TITLE
Unable to fetch data, getting 222 response

### ISSUE THREAD

**Issue by taras-dubyk** [DevExpress/testcafe-hammerhead#2437]
### Description:

I’m trying to make a request to an external API, but getting response code 222.
Without testcafe request works as expected.

If I understand correctly, 222 means request doesn't pass testcafe internal cors validation, but I couldn't figure out what's wrong.
In devtools I see a few headers are missed when request is called from testcafe: "Sec-Fetch-Dest", "Sec-Fetch-Mode" and "Sec-Fetch-Site". Can be a cause of the issue?

##### Correct request without testcafe:
![1](https://user-images.githubusercontent.com/25536318/92499285-5e0e2e00-f204-11ea-87b9-567c9b2e8286.png)

##### Request from testcafe with 222 response:
![2](https://user-images.githubusercontent.com/25536318/92499473-94e44400-f204-11ea-8ea0-fcf4de50ffe5.png)

### Your Environment details:

* node.js version: 12.14.0
* browser name and version: Chrome (Electron) 80
* electron: 8.3.0
* testcafe: 1.9.2
* testcafe-hammerhead: 17.1.15
* testcafe-browser-provider-electron: 0.0.15

**Comment by miherlosev** [comment]
Hi @taras-dubyk
 
Yes, you are right. The `222` HTTP status code means that the request failed the CORS validation.
TestCafe uses the [Access_control_CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS) algorithm to validate requests.
The validation of requests in Electron applications can be different from the validation of web pages.

I'm afraid the information you shared is insufficient. So, I suggest you debug TestCafe's CORS validation mechanism. To do this, find the `node_modules/testcafe-hammerhead/lib/request-pipeline/xhr/same-origin-policy.ts` file and output the debug information for the corresponding code lines.
