### ISSUE TITLE
A class that extends `Function` is not getting the correct prototype when running under Hammerhead

### ISSUE THREAD

**Issue by praxxis** [DevExpress/testcafe-hammerhead#2439]
### What is the Current behavior?
A class that extends `Function` is not getting the correct prototype.

To reproduce, create a minimal app that executes the following:
 
```js
class Test extends Function {
	extend() {}
}
console.log(new Test().__proto__);
 
```

Running it in Chrome shows the following in dev tools:

![image](https://user-images.githubusercontent.com/15754/92962676-4a9ad700-f43f-11ea-8ceb-90d526fd01a0.png)

When running under Testcafe, the following is shown:
![image](https://user-images.githubusercontent.com/15754/92962632-38b93400-f43f-11ea-8b2a-7d317c534128.png)

In Testcafe, instantiated classes that extend `Function` no longer have access to their methods. Presumably this is due to the native `Function` [being overwritten](https://github.com/DevExpress/testcafe-hammerhead/blob/f7c0cc4cc53fa4fbc0c05fe7ae9801d4c330576c/src/client/sandbox/node/window.ts#L726-L728) but I didn't do much other digging once I could create a test case.

### Your Environment details:

* node.js version:                    v14.4.0
* browser name and version: Chrome Version 85.0.4183.102 (Official Build) (64-bit)
* platform and version:          Observed on OSX and Windows

**Comment by Farfurix** [comment]
@praxxis 

Hello,

Thank you for your research. I reproduced the issue. Our team will examine this behavior and check for a suitable solution.

> but I didn't do much other digging once I could create a test case

Could you please share a real-world example with us? It will help us research the issue in a real scenario.

**Comment by praxxis** [comment]
The code is in the [rest-hooks](https://github.com/coinbase/rest-hooks/blob/master/packages/endpoint/src/endpoint.js#L16) library. https://codesandbox.io/s/vigorous-taussig-cpt73?file=/src/App.js has a small rest-hooks app that should exhibit the behavior.
