### ISSUE TITLE
IE11: Web worker fails with NetworkError

### ISSUE THREAD

**Issue by danielroe** [DevExpress/testcafe-hammerhead#2440]
### What is your Test Scenario?
I'm testing a site using a web worker in IE11.
 
### What is the Current behavior?
<details>
<summary>The test fails with this error:</summary>

```
 1) A JavaScript error occurred on

 "https://mysite".
    Repeat test actions in the browser and check the console for errors.
    If you see this error, it means that the tested website caused it. You can fix it or disable tracking
    JavaScript errors in TestCafe. To do the latter, enable the "--skip-js-errors" option.
    If this error does not occur, please write a new issue at:
    "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".

    JavaScript error details:
    NetworkError
        No stack trace available
```

</details>

The issue is the following code which has been injected into a web worker script that is being fetched in the site:

https://github.com/DevExpress/testcafe-hammerhead/blob/2a3f7ada747b9416242afd917ea6c52fdb4bc312/src/processing/script/header.ts#L53

This was introduced in https://github.com/DevExpress/testcafe-hammerhead/pull/2397. However, in IE11 `location.origin` appears to be undefined within a web worker so this leads to a NetworkError and a failing test.
 
### What is the Expected behavior?
I expect no error at this point.

**Comment by danielroe** [comment]
**Update**: It seems this issue is caused when the test runner is on the same network as the IE browser - it enables [the Intranet Zone](https://docs.microsoft.com/en-gb/archive/blogs/ieinternals/the-intranet-zone), which disables `location.origin`.

**Comment by SergeyShurygin** [comment]
I tried to reproduce the issue using the following code:
[test.zip](https://github.com/DevExpress/testcafe-hammerhead/files/5217057/test.zip) and v1.9.2 of testcafe. My test site was deployed to the localhost server. The test fails in Internet Explorer with a JS error (" Expected ')'") and passes successfully in Chrome. I was unable to reproduce the "Network Error" error message. Could you modify the sample and/or share more information on how to reproduce the original error?

**Comment by danielroe** [comment]
@Sergey.Shurygin Happy to prepare a reproduction - but can I first clarify what you mean by your message? It sounds like you're saying the test fails in IE (that is, there is a bug) - but the error you're getting isn't the one that I have reported, and you are wondering why there is a difference. Is that right?

**Comment by SergeyShurygin** [comment]
Yes, that's right. I'm getting another error, not NetworkError as reported in the issue.
