### ISSUE TITLE
Patching minified bundle.js incorrectly

### ISSUE THREAD

**Issue by bolatbekb** [DevExpress/testcafe-hammerhead#2442]
### What is your Scenario?
Test a web application that uses minified bundle.js
 
### What is the Current behavior?
An uncaught error is thrown:
`Uncaught SyntaxError: unexpected token ","`

Problem code fragment from bundle.js:
`{[(i = t, i.replace(new RegExp("Valid$"), ""))]: !1}`

TestCafe convert it to:
`{[i = t, __call$(i, "replace", [new RegExp("Valid$"), ""])]: !1}`
 
### What is the Expected behavior?
There should be no error.
 
### Your Environment details:

* node.js version:                    12.x.x 
* browser name and version: chrome/firefox current any versions
* platform and version:          Windows 10

**Comment by Farfurix** [comment]
@bolatbekb 

Hello,

I wasn't able to reproduce the "missing parentheses" issue with your source. My result:

```
Source:    {[(i = t, i.replace(new RegExp("Valid$"), ""))]: !1}
Processed: {[(i=t,__call$(i,"replace",[newRegExp("Valid$"),""]))]:!1}
```

Could you please try to run your website using the latest v17.1.18 TestCafe hammerhead version and share your result with us?

**Comment by bolatbekb** [comment]
@Farfurix 
Hello,
please try with this code:
`
const t = 'xValid';
Object.assign({}, {[(i = t, i.replace(new RegExp("Valid$"), ""))]: !1})
`

> @bolatbekb
> 
> Hello,
> 
> I wasn't able to reproduce the "missing parentheses" issue with your source. My result:
> 
> ```
> Source:    {[(i = t, i.replace(new RegExp("Valid$"), ""))]: !1}
> Processed: {[(i=t,__call$(i,"replace",[newRegExp("Valid$"),""]))]:!1}
> ```
> 
> Could you please try to run your website using the latest v17.1.18 TestCafe hammerhead version and share your result with us?

**Comment by Farfurix** [comment]
@bolatbekb 

Hello,

Thank you for the clarification. I reproduced the "missing parentheses" issue. We'll research it and check for a suitable solution.

**For the team**. A working example:

```js
var i = ''; var tst = Object.assign({}, {[(i = '', i.replace('', ''))]: !1}) // tst - {"": false}
//                                        ^                         ^
```

Processed:

```js
var i = ""; var tst =  __call$(Object,"assign",[ {},{[i="",__call$(i,"replace",["",""]) ]:!1}])
//                                              ^                                      ^
```

**Comment by bolatbekb** [comment]
@Farfurix could you clarify the status pls?

**Comment by Farfurix** [comment]
@bolatbekb

No updates yet. Now we are working on [the current development sprint](https://github.com/DevExpress/testcafe-hammerhead/milestone/72). This week we are going to plan our next sprint.
