### ISSUE TITLE
Adobe Launch Analytics requests are not fired when accessing a page with TestCafe

### ISSUE THREAD

**Issue by mariuspahontu** [DevExpress/testcafe-hammerhead#2453]
### What is your Scenario?
If accessing the test website with the TestCafe the Adobe Launch Analytics requests are not displayed.
If accessing the page manually in browser, Adobe Launch Analytics requests are displayed.
 

### Steps to Reproduce:
- For TestCafe - Run the attached code
  - While the page is loading open the Developer Tools and filter the requests by **b/ss** and observe that there are no requests
- Manually: it cannot be reproduced.

### What is the Current behavior?
- When accessing the website the TestCafe no Adobe Launch Analytics requests are fired.
- Also one or more JavaScript errors are displayed in Console: ***Cannot read property 'indexOf' of undefined*** 
  - Note that these JavaScript errors are not displayed when visiting the page manually.
![image](https://user-images.githubusercontent.com/5627543/95088328-76059e80-072b-11eb-9839-052ae7c27d26.png)

 
### What is the Expected behavior?
- When visiting the page with TestCafe Adobe Launch Analytics can be fired:
- No JavaScript errors are displayed after accepting the cookies
 
### What is your public web site URL?
https://www.newegg.com/

<summary>Your complete test code (or attach your test files):</summary>

```

import {Selector} from "testcafe";

fixture`Analytics`
    .beforeEach(async t => {
        await t.maximizeWindow();
    })

test('Adobe Launch Analytics', async t => {
    await t.navigateTo("https://www.newegg.com/");
    await t.click(Selector("#onetrust-pc-btn-handler"));
    await t.click(Selector('div:nth-child(3) label span.ot-switch-nob').filterVisible());
    await t.click(Selector('div:nth-child(4) label span.ot-switch-nob').filterVisible());
    await t.click(Selector('div:nth-child(5) label span.ot-switch-nob').filterVisible());
    await t.click('.save-preference-btn-handler.onetrust-close-btn-handler');
    await t.debug();
})


```
</details>

<details>
<summary>Your complete configuration file (if any):</summary>

```
{
  "screenshotPath": "screenshots",
  "browsers": "chrome",
  "screenshots": {
    "takeOnFails": true,
    "fullPage": true
  },
  "debugOnFail": false,
  "skipJsErrors": true,
  "disablePageCaching": false,
  "color": true,
  "speed": 0.90,
  "pageLoadTimeout": 30000,
  "assertionTimeout": 30000,
  "selectorTimeout": 30000,
  "concurrency": 1
}

```
</details>

 
### Your Environment details:

* testcafe version: 1.9.4
* node.js version:                    v11.2.0
command-line arguments: no additional parameters
* platform and version:        Chrome - Version 85.0.4183.121 (Official Build) (64-bit) 
* other:                                 win 10

**Comment by Farfurix** [comment]
@mariuspahontu 

Hello,

I wasn't able to reproduce the issue due to the following error:
![Capture](https://user-images.githubusercontent.com/30019338/95174366-a2202e80-07c2-11eb-8717-d6cf4a04d7b5.PNG)
I inspected the main page and couldn't find the elements you used in the test. Could you please fix your test code and share it with us?

**Comment by mariuspahontu** [comment]
Hi @Farfurix,

Thanks for your response. I've update the test. Can you please give another try?

Thanks,
Marius

**Comment by Farfurix** [comment]
@mariuspahontu 

Thank you for the update. I reproduced the issue. Our team will examine it and check for a suitable solution.

For the team.
test.js:
```js
fixture `Fixture`
    .beforeEach(async t => {
        await t.maximizeWindow();
    });

test('test', async t => {
    await t.navigateTo('https://www.newegg.com/');
    await t.debug(); // See the "Cannot read property 'indexOf' of undefined" error in Chrome DevTools
});
```

**Comment by dalebaldwin** [comment]
I possibly have a similar issue, I have an app that makes analytics events to a server. All our events are currently working with the exception of onclick events that trigger the window to navigate to a new page. It seems like the moment you click a link all in flight requests are closed and nothing is returned in the network request logger.

**Comment by arubtsov** [comment]
@dalebaldwin Thank you for reaching out to us. For now, we will process your request in the context of the [issue](https://github.com/DevExpress/testcafe-hammerhead/issues/2467) you created.
