### ISSUE TITLE
Network requests aren't recieved by server after clicking on a link

### ISSUE THREAD

**Issue by dalebaldwin** [DevExpress/testcafe-hammerhead#2467]
### What is your Scenario?
I'm testing a custom analytics service we have written that captures a number of events including on click events that are fired when a user clicks on a link to an external site.
 
### What is the Current behavior?
We have found inside the hammerhead reverse proxy that any network call fired on or after clicking on an `a href` link are never sent by the browser and received by the server. It appears the browser cancels all in flight network requests or fails to fire any new network requests and all unload events as well.

I've tested this back to back with multiple browsers and the events work normally as expected when interacting with the browser but they fail inside of testcafe tests and when manually using the site inside the hammerhead reverse proxy.
 
### What is the Expected behavior?
Any network event triggered as part of a link click and all unload behaviour is finalised when navigating to a new page.
 
### What is your public web site URL?
https://linktr.ee/dalebaldwin

### Steps to Reproduce:
Given a user is at https://linktr.ee/dalebaldwin
When a user clicks on the `Github` link
Then all network events are fired and completed during transition to github.com
 
### Your Environment details:

node.js
Chrome, Chromium, Firefox, Safari, UI Kit webview, IE, Edge

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I've reproduced the issue. We'll research it and update this thread once we have any news.
