### ISSUE TITLE
HH opens new window if the form target attribute points to a nonexistent window name

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#247]

**Comment by churkin** [comment]
I'm working on this

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Waiting for https://github.com/DevExpress/testcafe-hammerhead/issues/623

**Comment by miherlosev** [comment]
We should not waiting for #623 because on saucelab's machine is installed the non-latest Google Chrome version - 51.0.2704.63
![untitled](https://cloud.githubusercontent.com/assets/4133518/15855371/d1453718-2cb7-11e6-811f-78a7ca3f9b64.png)

For now, the latest Google Chrome version - 51.0.2704.84.
