### ISSUE TITLE
invalid property lookup, invalid error instance assumption

### ISSUE THREAD

**Issue by cdaringe** [DevExpress/testcafe-hammerhead#2480]
### What is your Scenario?

- running tests in CI
 
### What is the Current behavior?

On test, we _periodically receive_:

```
13:06:13 TypeError: Cannot read property 'toString' of undefined
13:06:13     at Proxy._onServiceMessage (/opt/app/node_modules/testcafe-hammerhead/lib/proxy/index.js:149:41)
13:06:13     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The below line assumes that the thrown entity is an `Error` instance, but as demonstrated above, clearly is not 100% of the time guaranteed to be the case:
https://github.com/DevExpress/testcafe-hammerhead/blob/352d2a71a672266f63fa5348fef097ce2db295c9/src/proxy/index.ts#L156
 
### What is the Expected behavior?

Either `toString` exists 100% of the time, or defensive programming practiced in exception handlers

 
### What is your public web site URL?

- internal. bummer. i would love to share it.

### Steps to Reproduce:

TBD. We have a job that runs our testcafe tests continuously to uncover flakiness. This error creeps up somewhat randomly in otherwise healthy tests. non-determinisitic.
 
### Your Environment details:

* node.js version:     12.17.0
* browser name and version: chome @ latest
* platform and version:  `testcafe/testcafe:1.8.6`, so alpine of sorts :)

**Comment by benmonro** [comment]
my team has run into this issue as well.

**Comment by miherlosev** [comment]
Hi @cdaringe

The `testcafe/testcafe:1.8.6` version is outdated. Try to run you tests with the latest testcafe version - `1.9.4`.
If the problem persists, try to find the type of the raised error. To do that, set the `DEBUG` environment variable and collect the request information into a file as described in this example:

```
set DEBUG=hammerhead:*
testcafe chrome index.js 2> hammerhead.log
```

Please share the file with the logged information.
