### ISSUE TITLE
Health Monitor - recalculate status quo value for 'Sites with errors' on each run

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#250]
status quo value = 1.1 * count errors for best run

**Comment by inikulin** [comment]
I was thinking about it recently and I think we should not have any threshold for the site errors. So, if we have 9 errors, we should set limit to the 9, without 1.1 amplification

**Comment by miherlosev** [comment]
Ok.
status quo value = count errors for best run

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Complete.
