### ISSUE TITLE
Uncaught TypeError: 'deleteProperty' on proxy: trap returned falsish for property 'token'

### ISSUE THREAD

**Issue by Timebutt** [DevExpress/testcafe-hammerhead#2504]
### What is your Scenario?
A recent change breaks some E2E tests we are running using Testcafe with the following error message:

`Uncaught TypeError: 'deleteProperty' on proxy: trap returned falsish for property 'token'`
 
### What is the Current behavior?
Above error message is thrown, tests fail at runtime.
 
### What is the Expected behavior?
The exact code snippet provided here used to run in Testcafe versions pre `1.10.x`. Right now it's breaking at runtime, blocking us from upgrading. When running the HTML page in a normal browser without the Hammerhead proxy, no error is thrown.
 
### What is your public web site URL?
I don't have this hosted publicly, but this minimal HTML snippet will throw the error when run in the Hammerhead playground.

```
<!DOCTYPE html>
<html>
    <body>
        <script>
            class LocalStorageService {
                constructor() {
                    this.delete = function (key) {
                        delete window.localStorage[key];
                    };
                }
            }

            const localStorageService = new LocalStorageService();
            localStorageService.delete("token");
        </script>
    </body>
</html>
```
### Steps to Reproduce:
1. Create an `html` file with above contents.
2. Serve somewhere (locally using `http-server` for instance)
3. Open the file in the Hammerhead playground
 
### Your Environment details:

* node.js version: 14.8.0
* browser name and version: Chrome
* platform and version: Windows 10 64 bit

**Comment by aleks-pro** [comment]
Hello @Timebutt ,

Thank you for reporting a bug. I have managed to reproduce the issue. We will research it and update this thread once we have any results.

NOTE: at the moment, the `1.10.x` TestCafe version is a release candidate, so we do not recommend using it in production.

For the team:
- link to sandbox https://codesandbox.io/s/loving-wave-t9bjr
- test:
```js
fixture `New Fixture`
    .page `https://t9bjr.csb.app/`;

test('New Test', async t => {
});```
