### ISSUE TITLE
Use of md5 for etag fails on FIPS enabled Kernels

### ISSUE THREAD

**Issue by beatrichartz** [DevExpress/testcafe-hammerhead#2516]
### What is your Scenario?

Running test on a linux image with FIPS enabled
 
### What is the Current behavior?

Tests error with error `ERROR Error: error:060800C8:digital envelope routines:EVP_DigestInit_ex:disabled for FIPS`
 
### What is the Expected behavior?

Tests should run

### Steps to Reproduce:

1. Run testcafe on a FIPS enabled Kernel (check `cat /proc/sys/crypto/fips_enabled` returns 1)
2. See it fail because of use of `md5` in https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/proxy/router.ts#L50

 
### Suggestion
Use sha256 for etags

### Your Environment details:

* node.js version:                    14.15.1
* browser name and version: Any (chromium, firefox)
* platform and version:          RHEL 8

**Comment by Farfurix** [comment]
@beatrichartz 

Hello,

Thank you for the information. Our team will research this case.

**Comment by miherlosev** [comment]
Closed in favor https://github.com/DevExpress/testcafe/issues/5864
