### ISSUE TITLE
We broke the css selector that is invalid

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#2517]
Example:
```js
document.querySelector('button:not([class="sm"]')
                                               ^
                                       no closing parenthesis
```

**Comment by Farfurix** [comment]
Modern browsers (Google Chrome eg.) can correct this before element querying. To support [Built-in Wait mechanisms](https://devexpress.github.io/testcafe/documentation/guides/concepts/built-in-wait-mechanisms.html), TestCafe pre-processes selectors passed to the `document.querySelector` function. So, TestCafe failed to process incorrect selectors. It's very difficult to imitate the browser's selector correction mechanism on the TestCafe side in such cases, so we advise customers to fix the problematic selector in their projects.
