### ISSUE TITLE
The onDocumentCleaned event is raised wrongly after document.write is called for a document that is still being loaded

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#253]
Multiple calls to  `document.write`  leads to the page hanging. Because each time`onDocumentCleaned` is raised Hammerhead gets initialized.

**Comment by miherlosev** [comment]
Please, provide a simple example

**Comment by LavrovArtem** [comment]
I found site with sorce code:
```html
<ul>
    <li>
        <a href="href">href</a>
        <script>document.write('<noindex>Text</noindex>');</script>
    </li>
    .....
    over 50th items
<ul>
```

**Comment by inikulin** [comment]
We have a numerous regressions caused by the fix in hhm: https://testcafe-hhhm.devexpress.com/history?timestamp=1447700581777&siteUrl=https://www.yahoo.com/&onlyWithErrors=true
Please, take a look. Reopening for now.
