### ISSUE TITLE
A CORS error doesn't occur when a request contains a disallowed header

### ISSUE THREAD

**Issue by Dmitry-Ostashev** [DevExpress/testcafe-hammerhead#2535]
### What is the Current behavior?
A CORS error doesn't occur when a request contains a disallowed header
https://stackoverflow.com/questions/65500857/how-to-get-testcafe-to-fail-on-the-not-allowed-cors-headers 

### What is the Expected behavior?
The browser should display a CORS error.
 
### Steps to Reproduce:
1. Start the following web server script:
```
const express = require('express');
const cors    = require('cors');
const app     = express();

app.use(cors({ allowedHeaders: ['Content-Length', 'X-Foo', 'X-Bar'] }));

app.options('/', cors());
app.get('/', (req, res) => {
    res.send(new Date().toTimeString());
});

app.listen(3001, () => {});
```
2. Launch `gulp http-playground`
3. Navigate `http://localhost:3001/` using the textbox on the Hammerhead page.
4. Open DevTools console, execute the following script:
`fetch('http://127.0.0.1:3001', { headers: { 'My-Header': '123' } })`
5. This request will be passed.
6. Repeat these steps without Hammerhead. The request will be failed with the CORS error.

**Comment by balazser** [comment]
Is this something easy to fix? I would be happy to contribute to this issue because my team also depends on this ticket.. :)

**Comment by Farfurix** [comment]
@balazser 

Hello,

I cannot reproduce the issue using `testcafe@1.10.2-alpha.1`. Please check your scenario with this alpha version.

**Comment by arubtsov** [comment]
Hi @balazser, I tried to reproduce this in the example shared by @Dmitry-Ostashev, but with no luck. The fetch request fails in the following test:

```
import { ClientFunction } from 'testcafe';

fixture('Cors')
    .page('http://localhost:3001/');

const performRequest = ClientFunction(() => {
    return fetch('http://127.0.0.1:3001', { headers: { 'My-Header': '123' } });
});

test('Cors error', async t => {
    await performRequest();
});
```

Could you please share an example where TestCafe behaves differently or modify this example so that we could reproduce this issue?
