### ISSUE TITLE
Service Worker overwriting window object causes crash

### ISSUE THREAD

**Issue by timostark** [DevExpress/testcafe-hammerhead#2538]
Hi All,

First i am very sorry, for the bad bug report. The scenario is happening specifically with SAP Analytics Cloud (Major Analytics solution by SAP). Everything here is of course properitary. I hope the technical details and possible solution are good enough to understand the issue.

Generally: Cloud Analytics is heavily relying on service workers. This seems to cause issues.
 
### Summary
Crash during startup, in case a service worker is (partly) filling the window object.

### Technical Reason for crash
Native Methods nodeFirstChildGetter is undefined when using XHR requests in service-worker.
![grafik](https://user-images.githubusercontent.com/19237828/103466581-96eb8900-4d46-11eb-876b-d0664177d73b.png)

As a service worker does not have a window.Node/HTMLElement object, the resolve method shouldn't be called after all. The code for this logic is already available - The problem seems to be that the caller (resolve) is not detecting that it is inside a worker thread (see following screenshot).
![grafik](https://user-images.githubusercontent.com/19237828/103466685-5b04f380-4d47-11eb-90a9-8b7f42708bf3.png)

The reason for this, is that the window object was partly overwritten (with DedicatedWorkerGlobalScope - so the actual "self" object). If I open the application directly, it shows the same behavior inside the worker thread. Therefore the window object is overwritten / defined by the service worker.
![grafik](https://user-images.githubusercontent.com/19237828/103466838-0d898600-4d49-11eb-9980-238400b9cb8f.png)

Now I am really not sure about the service worker specification. Is a service worker allowed to overwrite any window method? Adjusting the code to:
![grafik](https://user-images.githubusercontent.com/19237828/103466878-9a344400-4d49-11eb-9575-69794ea3f056.png)
solves the issue and the application simply starts up..
Alternative (yes the ts-ignore is ofc bullshit):
![grafik](https://user-images.githubusercontent.com/19237828/103467233-4c213f80-4d4d-11eb-9cb0-2524981accf6.png)

What do you think? Is that a valid solution (maybe including Node and other window objects you are accessing..)

Thanks for any feedback,
Timo

**Comment by timostark** [comment]
Remark: I just found the causing code inside the Cloud Analytics application:
![grafik](https://user-images.githubusercontent.com/19237828/103467140-4ecf6500-4d4c-11eb-8d93-14e86805026f.png)

So yes - SAP is setting the window object inside the service worker on itself. Again I don't know if that is not allowed. Anyhow of course the local browser is accepting that (without warning), and the crash is only occuring with testcafe (cause is clear), so I would say yes..

**Comment by timostark** [comment]
Additional issue (wont raise as new bug, as almost 100% identical). If the service-worker is overwriting "document",  it causes a crash for the same reason due to "incorrect/not sufficient" service worker detection in: src\client\utils\destination-location.ts.
![grafik](https://user-images.githubusercontent.com/19237828/103488776-f1045100-4e0f-11eb-823b-b7f242433fd1.png)

Error:
![grafik](https://user-images.githubusercontent.com/19237828/103488804-1729f100-4e10-11eb-81e3-92602bbf31c8.png)

**Comment by Farfurix** [comment]
@timostark 

Hello,

> What do you think? Is that a valid solution (maybe including Node and other window objects you are accessing..)

I'm afraid we cannot say anything regarding this solution until we reproduce the issue ourselves. Could you please share a simple project (or a public URL)? We'll examine it and check for a suitable solution.

If your project is private, you can use our mailbox ([support@devexpress.com](mailto:support@devexpress.com)). However, since your website sits behind a proxy and requires authentication, we will not be able to access it. Our policy prevents us from accessing a customer’s internal resources without a prior written approval from the entity that owns the server/web resource. If you want us to research the problem further, we’ll need access to the server/web resource. Please ask the website owner to send us ([support@devexpress.com](mailto:support@devexpress.com)) a written confirmation. It must permit DevExpress personnel to remotely access the website and its internal resources for research/testing/and debugging purposes.

**Comment by timostark** [comment]
@Farfurix : Uploaded a reproducible to https://lemokla.de/service_worker_hammerhead/index.html 
Please note that those are two different issues..

1. Failure in Dedicated Worker for XMLHTTPRequest, in case document is overwritten 
2. Failure in Service Worker for fetch, in case window is overwritten.

Possible Code solution is maintained in the first post (using instanceof, instead of just checking the window object),

![grafik](https://user-images.githubusercontent.com/19237828/103537568-ec35b080-4e94-11eb-814a-f4a1931939ca.png)


Code:
index.html
`
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Service worker scope</title>
  </head>

  <body>
    <h1>Service worker</h1>

    <section></section>

    <script src="app.js?v=13"></script>
  </body>
</html>`

app.js
`if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('./sw.js', { scope: ' /service_worker_hammerhead/ ' }).then(function (reg) {
        if (reg.installing) {
            console.log('Service worker installing');
        } else if (reg.waiting) {
            console.log('Service worker installed');
        } else if (reg.active) {
            console.log('Service worker active');
        }

    }).catch(function (error) {
        // registration failed
        console.log('Registration failed with ' + error);
    });
}
if (window.Worker) {
    const myWorker = new Worker("./worker.js?v=2");
}`

sw.js
`self.window = self;
self.document = self;

fetch('./index.html?fromSW=1').then(function (response) {
});`

worker.js
`self.window = self;
self.document = self;

var oReq = new XMLHttpRequest();
oReq.open("GET", "./index.html?fromWorker=2");
oReq.send();`

**Comment by timostark** [comment]
For me the issue is solved with the two following adjustments:

Dedicated Worker, for XMLHTTPRequest.open ( src\client\utils\destination-location.ts )
![grafik](https://user-images.githubusercontent.com/19237828/103538032-c361eb00-4e95-11eb-9494-bad0f861bdd7.png)

Service Worker with Fetch ( src\client\utils\global-context-info.ts )
![grafik](https://user-images.githubusercontent.com/19237828/103538060-d1177080-4e95-11eb-8954-ff41d8cb2816.png)

**Comment by AlexKamaev** [comment]
@timostark 
Thank you for sharing your example. I was able to reproduce the issue. I confirm that everything works without TestCafe. The error occurs if I run the project with TestCafe or with the `testcafe-hammerhead ` playground. 
Thank you for your detailed research. It looks like you found the cause of the issue. However, we still need to discuss the issue with the team, so it can take some time. Please follow the updated in this thread.

**Comment by LavrovArtem** [comment]
It fixed partially in https://github.com/DevExpress/testcafe-hammerhead/pull/2533
