### ISSUE TITLE
Service Worker initialized with parameterized scope

### ISSUE THREAD

**Issue by timostark** [DevExpress/testcafe-hammerhead#2539]
Hi All,

Same Application as used within Issue #2538 . Again I can hardly provide any reproducible example, but just show the exact technical error, as the source code is propertiary. In case you need any more information let me know again please.

### Summary
Crash during startup, in case navigator.serviceWorker.register is called with a URL with a query parameter.
![grafik](https://user-images.githubusercontent.com/19237828/103487338-e0021280-4e04-11eb-964d-cb90a5ed272d.png)

### Technical Reason/Details for crash
- Application is calling navigator.serviceWorker.register with a parametrizied URL
![grafik](https://user-images.githubusercontent.com/19237828/103487297-8d285b00-4e04-11eb-9495-efe62ff6953c.png)
- In hammerhead a postMessage takes place to communicate with the worker thread (apperantly)
- Both Scope and current scope is sent inside the postMessage
- In my example application by SAP, the URL has a URL parameter. See following screenshot:
![grafik](https://user-images.githubusercontent.com/19237828/103487211-0a9f9b80-4e04-11eb-973d-3251f75586ea.png)
- The result of getURLScope is incorrect (should be identical, as of course the query parameter should be ignored)
![grafik](https://user-images.githubusercontent.com/19237828/103487235-29059700-4e04-11eb-9fd3-a77f3b2e7ce4.png)
- Registration fails due to incorrect Scope
![grafik](https://user-images.githubusercontent.com/19237828/103487333-db3d5e80-4e04-11eb-8d19-8d1762f0dff1.png)

### Possible Solution
Of course again I have no real clue of your source-code (I guess the function order is incorrect), but for me the simple following code adjustment is working fine..
![grafik](https://user-images.githubusercontent.com/19237828/103487395-569f1000-4e05-11eb-9c8c-44b95c0da6b3.png)

Regards,
Timo

**Comment by Farfurix** [comment]
@timostark 

Hello,

I created a simple example to reproduce this issue. Our team will examine it and check for a suitable solution.

**./sw-test/index.html**:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">

    <title>Service worker scope</title>
  </head>

  <body>
    <h1>Service worker</h1>

    <section></section>

    <script src="app.js"></script>
  </body>
</html>
```

**./sw-test/app.js**:
```js
if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('/sw-test/sw.js?https://some.url', { scope: '/sw-test/' }).then(function(reg) {

        if(reg.installing) {
            console.log('Service worker installing');
        } else if(reg.waiting) {
            console.log('Service worker installed');
        } else if(reg.active) {
            console.log('Service worker active');
        }

    }).catch(function(error) {
        // registration failed
        console.log('Registration failed with ' + error);
    });
}
```

**./sw-test/sw.js**:
```js
// blank file
```
**Steps to reproduce**:
1. Run `http-server`.
2. Open `localhost:8080/sw-test/`.

Expected result:
```
app.js:7 Service worker installing
```

Result with `testcafe-hammerhead`:
```
Registration failed with Error: The path of the provided scope ('/sw-test/') is not under the max scope allowed ('/sw-test/sw.js?https://'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope.
```

**Comment by Farfurix** [comment]
It is a duplicate of https://github.com/DevExpress/testcafe-hammerhead/issues/2524.

**Comment by timostark** [comment]
Thanks for your feedback and your work on a reproducible example.the issue mentioned perfectly describes my issue report, so thanks for closing this one. I will use your example to create a reproducible example for the other issue too.
