### ISSUE TITLE
Google Slides do not load in testcafe-hammerhead

### ISSUE THREAD

**Issue by adriancable** [DevExpress/testcafe-hammerhead#2569]
To reproduce:

1. Start testcafe-hammerhead playground. Desktop Safari, Chrome, etc. - any browser is the same.
2. Proxy this URL: https://docs.google.com/presentation/d/1XrSz1-5B_gEUQS9YXQclm-vzTBlizHqwDmFVIJDu0sY/edit
3. Note error: 'Unable to load file.'

What I expect instead: file loads OK. (Try that URL without testcafe-hammerhead.)

Issue is not specific to this single document.

**Comment by miherlosev** [comment]
Hi @adriancable 

Thank you for the provided information. I've reproduced the problem.
