### ISSUE TITLE
Processing error for the https://qa.xreach.app/ page

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#2573]
Steps to reproduce:
* open the https://qa.xreach.app/ page in the playground
* white page will be displayed instead of origin page
* open Chrome  DevTools and see the script error
![image](https://user-images.githubusercontent.com/4133518/106244524-11aba500-621c-11eb-8c0e-642ccb5cbd31.png)

**Comment by LavrovArtem** [comment]
Parentheses are lost by our js formatter, example:
```js
var a = new Function('i[j] = () => {for (var x of (a, b)) c();}'); // Uncaught SyntaxError: Unexpected token ','
                                                  ^    ^
```
