### ISSUE TITLE
Error starting https://demo.e-thermo.fr

### ISSUE THREAD

**Issue by felis2803** [DevExpress/testcafe-hammerhead#2577]
From support center: [T970056](https://supportcenter.devexpress.com/internal/ticket/details/T970056)

### What is your Scenario?
Launch https://demo.e-thermo.fr in any way: by `gulp http-playground`, by TestCafe and TestCafe Studio.
 
### What is the Current behavior?
The page does not load, and you see an error in the console:
![изображение](https://user-images.githubusercontent.com/34184692/106733763-54f28300-6623-11eb-8c5e-b4224a99bcdf.png)

### What is your public web site URL?
https://demo.e-thermo.fr
 
### Your Environment details:

* node.js version:                    v13.14.0
* browser name and version:  Chrome, Firefox
* platform and version:           Win7

**Comment by LavrovArtem** [comment]
Example:
```js
for (const [n, r] of new Set([1, 2]).entries()) {
    const e = r,
        n = 5;
}
```
The error occurs after our destructuring.

**Comment by felis2803** [comment]
The reason is destructuring assignment in user code:
```js
for (const [n, r] of e.entries()) {
    const e = r.physicalProperty,
          n = Kz.getInstance().user.myUnits.find(t => t.physicalClass.code === e.physicalClass.code);

    t = t && !n.isWTin100Unit();

    const i = r.dataValues;

    for (const r of i) {
        const e = r.uncertaintyPhysicalUnit;

        t = t && !e.isWTin100Unit()
    }
}
```
After processing this code by Hammerhead:
```js
for (const _hh$temp111 of e.entries()) {
    const n = _hh$temp111[0],
          r = _hh$temp111[1];

    const e = r.physicalProperty,
          n = Kz.getInstance().user.myUnits.find(t => t.physicalClass.code === e.physicalClass.code);

    t = t && !n.isWTin100Unit();

    const i = r.dataValues;

    for (const r of i) {
        const e = r.uncertaintyPhysicalUnit;

        t = t && !e.isWTin100Unit();
    }
}
```
The user is advised to fix this in their code.
