### ISSUE TITLE
Style is not processed if it was created via style.appendChild(document.createText(<text>))

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#259]
Web page contains the following script:
```javascript
var style = document.createElement('style');
var styleText = 'div { background-image: url("/image.png"); }';
var styleTextNode = document.createTextNode(String(styleText));

style.appendChild(styleTextNode);
document.head.appendChild(style);
```

After proxying the page, the url from the code `url("/image.png")` must be replaced.

**Comment by inikulin** [comment]
Do we need such processing for scripts as well?

**Comment by miherlosev** [comment]
Already proceed - 
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L215.
But we need to checking all variants (insertBefore, innerHtml) for style and scripts.

**Comment by churkin** [comment]
@miherlosev should not innerHtml

**Comment by inikulin** [comment]
Seems like this caused a lot invalid invocation errors. @miherlosev please, take a look. Reopening for now

**Comment by miherlosev** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/297
I will checking after merge it.

**Comment by miherlosev** [comment]
The problem fixed (see https://testcafe-hhhm.devexpress.com/history?timestamp=1448622003671)
