### ISSUE TITLE
HTTP POST Requests with total length > 1260 chars fail (empty response)

### ISSUE THREAD

**Issue by enriccarrion** [DevExpress/testcafe-hammerhead#2597]
### What is your Scenario?
I'm using TestCafe 1.12.0 (but I can also reproduce with 1.9.4) which uses Hammerhead 19.4.2 to perform automatic tests against a local environment. It's a Web application that connects to an API in a web server (Microsoft IIS) to perform HTTP (no SSL) GET and POST calls.
 
### What is the Current behavior?
I've noticed that all POST requests whose length exceeds 1260 chars (approx.):
- Do not reach the web server (I have double-checked with server logs and network traffic, the request does not go out of hammerhead)
- Return 0 bytes ("Empty response" error in the browser)
I've analyzed and tested with the HTTP requests with Fiddler. For example taking a request that works and adding whitespace characters to the request body it keeps working until I reach the amount of 1260 approx. Then the request fails (Fiddler shows a 504 error: "server returned 0 bytes"). 
What counts as a limit is not the request body in particular, but the whole HTTP raw request. Attaching examples below.
 
### What is the Expected behavior?
It seems a strange behavior to me, so I'm not sure if I need a configuration tweak at some level, I am missing any known limitation or it is just an issue in hammerhead. 
 
Can't really provide a piece of code since it is something that doesn't need particular TestCafe code to get reproduced.

![browser_error](https://user-images.githubusercontent.com/17001216/111439422-a5bac880-8705-11eb-8897-6506827ed3d7.PNG)
![failing_request_504](https://user-images.githubusercontent.com/17001216/111438856-0c8bb200-8705-11eb-9d20-bc9e197722fc.PNG)
![successful_request](https://user-images.githubusercontent.com/17001216/111438859-0d244880-8705-11eb-925b-a8ae1efa67f4.PNG)
[failing_request_504.txt](https://github.com/DevExpress/testcafe-hammerhead/files/6154843/failing_request_504.txt)
[successful_request_200.txt](https://github.com/DevExpress/testcafe-hammerhead/files/6154844/successful_request_200.txt)

### Your Environment details:

* node.js version:                    10.23.1 
* browser name and version: Chrome 89.0.4389.82 (launched by TestCafe)
* platform and version:          Windows Server 2012 R2

Please can you provide some guidance? Thank you!

**Comment by LavrovArtem** [comment]
I cannot reproduce this issue. Please, try to change my simple server for reproducing it below:
```js
require('http')
    .createServer((req, res) => {
        if (req.url === '/') {
            res.writeHead(200, { 'content-type': 'text/html' });
            res.end(`
                <script>
                    const xhr = new XMLHttpRequest();

                    xhr.open('post', '/xhr');
                    xhr.send('12345'.repeat(300));

                    xhr.addEventListener('load', () => alert('status => ' + xhr.status + ' ' + xhr.responseText));
                </script>
            `);
        } else if (req.url === '/xhr') {
            const chunks = [];

            req.on('data', chunk => chunks.push(chunk));
            req.on('end', () => {
                res.writeHead(200, { 'content-type': 'text/plain' });
                res.end('ok, body length is ' + Buffer.concat(chunks).length);
            });
        }
    })
    .listen(2021, () => console.log('http://localhost:2021'));
```

**Comment by enriccarrion** [comment]
Hi @LavrovArtem thanks a lot for replying. After performing some more network troubleshooting we have found our firewall to be the guilty of the blocked requests. These requests we not even appearing in the firewall log, that is why we we suspecting they didn't go out of hammerhead. After tweaking the firewall rules now the requests reach the server successfully. Still no idea why the firewall was only blocking the requests coming from hammerhead but not the same exact ones without using it.
Anyway, I'm closing the issue. Thanks again for the support!
