### ISSUE TITLE
Not all types of 'eval' function calls wrapped

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#260]
We have to wrap:

```javascript
var temp = eval;

temp('some code');
```

to 

```javascript
var temp = eval === window.eval ? script => eval(__proc$Script(script)) : eval;

temp('some code');
```

**Comment by inikulin** [comment]
We need to parenthesize it to preserve precedence:
```js
var temp = (eval === window.eval ? script => eval(__proc$Script(script)) : eval);
```

**Comment by inikulin** [comment]
There are numerous regressions in HHM caused by fix. So, reopening \cc @churkin

**Comment by LavrovArtem** [comment]
Uncaught ReferenceError: Invalid left-hand side in assignment
google.loader.eval={}       =>         __get$Eval(google.loader.eval)={}
