### ISSUE TITLE
How does Hammerhead rewrite JS so effectively? (Question)

### ISSUE THREAD

**Issue by shawtylikeamelody** [DevExpress/testcafe-hammerhead#2604]
Hello,

This isn't a issue or a bug but I am curious how Hammerhead rewrites JS so effectively. I am a creator of my own web proxy that is meant to serve as a other gateway for the web instead of just testing like Hammerhead. I've tried every method I could think of to rewrite JS but none were that effective. If I could be given a few tips that would be amazing!

**Comment by miherlosev** [comment]
Hi @shawtylikeamelody

To get the best performance, we are using custom forks of the JavaScript parser (`acorn-hammerhead`) and serializer (`esotope-hammerhead`). The rest of the process is standard: determine the resource type, parse JavaScript to AST (an abstract syntax tree), apply transformations, serialize modified AST to a JavaScript string. To get more details, try to debug the resource processing. A good start point for it is the [process](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/processing/resources/index.ts) function.
