### ISSUE TITLE
Referer request header is incorrectly set when called in t.navigateTo 

### ISSUE THREAD

**Issue by raj-balaebail** [DevExpress/testcafe-hammerhead#2607]
### What is your Scenario?

Navigate to a URL and only set the referer if appropriate

### What is the Current behavior?

When I navigate to a page using fixture.page it doesn't set the request.headers.referer. However, if I navigate to the same page using t.navigateTo, request.headers.referer is being set to `about:blank`

### What is the Expected behavior?

 t.navigateTo should behave the same as fixture.page

### What is your public web site URL?

Your website URL (or attach your complete example): 
`https://personalloanapply.us.hsbc.com/apply`
<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
import { Selector, t, RequestLogger } from 'testcafe';

const logger = RequestLogger('', {
  logRequestHeaders: true
});

fixture('tests')
  .requestHooks(logger)
//.page('https://www.hsbc.staging.amount.com/apply')

test('testing', async t => {
  await t.navigateTo('https://www.hsbc.staging.amount.com/apply')
  console.log(logger.requests[0].request.headers)
})
```
</details>
Comment out the navigateTo and uncomment the .page to reproduce the issue
<details>
<summary>Screenshots:</summary>

```
navigateTo gives:
{
  host: 'www.hsbc.staging.amount.com',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'en-US,en;q=0.5',
  connection: 'keep-alive',
  referer: 'about:blank',
  'upgrade-insecure-requests': '1'
}

fixture.page gives:
{
  host: 'www.hsbc.staging.amount.com',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:87.0) Gecko/20100101 Firefox/87.0',
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
  'accept-encoding': 'gzip, deflate',
  'accept-language': 'en-US,en;q=0.5',
  connection: 'keep-alive',
  'upgrade-insecure-requests': '1'
}
```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                     
* browser name and version: 
* platform and version:          
* other:

**Comment by AlexanderMoiseev** [comment]
Hello, 

Thank you for your input. We have reproduced the problem and need some time to investigate it, please stay tuned.
