### ISSUE TITLE
TypeError Cannot read property 'prototype' of undefined - page failing to load

### ISSUE THREAD

**Issue by juststeveee** [DevExpress/testcafe-hammerhead#2611]
Hello team! 

I am seeing an issue where the frontend page is failing to load due to a typeerror, hammerhead seems to have an issue rewriting window.location. 

Browser console error;
```
hammerhead.js:14136 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at new Location (hammerhead.js:14136)
    at Object.get (hammerhead.js:19834)
    at value (hammerhead.js:19873)
    at Object.location (2.594d2bf1.chunk.js:2)
    at Object.o.getHostnameNoWww (2.594d2bf1.chunk.js:2)
    at new h (2.594d2bf1.chunk.js:2)
    at Module.<anonymous> (2.594d2bf1.chunk.js:2)
    at i (2.594d2bf1.chunk.js:2)
    at 2.594d2bf1.chunk.js:2
    at Object.<anonymous> (2.594d2bf1.chunk.js:2)
```

Here is the test code; 
```
import {Selector} from 'testcafe';

const okButton = Selector('[data-test="ok"]');

fixture("My xFixture")
    .page("https://savings.secure.investec.com/login");
    

test("First test", async (t) => {
        await t
            .debug()
            .click(okButton);
});

```
Testcafe config;
{
    "browsers": ["chrome"],
     "src": ["tests/firstTest.js"],
     "quarantineMode": true,
     "debugMode": true,
     "debugOnFail": true,
     "stopOnFirstFail": true,
     "skipJsErrors": true,
     "skipUncaughtErrors": true,
     "appInitDelay": 3000,
     "concurrency":1,
     "selectorTimeout": 60000,
     "assertionTimeout": 60000,
     "pageLoadTimeout": 60000,
     "speed": 1,
     "disablePageCaching": false,
     "developmentMode": true,
     "qrCode": true,
     "hostname": "127.0.0.1"
 }

### Your Environment details:
* node.js version:                    v14.15.
* browser name and version:  IE11, Chrome 69, Firefox 100
* platform and version:          Windows

Any advice would be much appreciated, do let me know if you require further information. 

Thank you. 

Stephen

**Comment by Farfurix** [comment]
@juststeveee 

Hello,

I reproduced the issue with `testcafe-hammerhead`, Chrome 89, and Window 10.

For the team:
We are trying to get `Location` from a non-window client object (the second execution of this line).
![Untitled-2](https://user-images.githubusercontent.com/30019338/113829310-05991200-978e-11eb-9c1c-41ebf71f01ee.jpg)

**Comment by juststeveee** [comment]
Hi, 

Do you know if there is a workaround I can apply locally to bypass this issue?
