### ISSUE TITLE
Error when requesting blob object urls through XHR

### ISSUE THREAD

**Issue by acostajohn** [DevExpress/testcafe-hammerhead#2634]
### What is your Scenario?
Using XHR to request object urls of type  `blob:` will make hammerhead error out and thus, the request is not made.

I tracked down the exception to this line which expects `reqOpts` to have a value in the `send` wrapper, but no values where defined in the `open` method wrapper because it is a local object url.

Here is where the request options are supposed to be set (`xhr.open`). This only happens for `http` and `file` domains, not for `blob` which I think makes sense.

https://github.com/DevExpress/testcafe-hammerhead/blob/a878aefb01e45c3dc58d9d92da6e618cbc494c4c/src/client/sandbox/xhr.ts#L149

And here in `xhr.send` it tries to retrieve the request options which never fails for regular requests to `http` urls, but since those never are set for `blob:` urls, it fails badly.
https://github.com/DevExpress/testcafe-hammerhead/blob/a878aefb01e45c3dc58d9d92da6e618cbc494c4c/src/client/sandbox/xhr.ts#L162
 
### What is the Current behavior?

Considering the following snippet:

```js
const blob = new Blob(['this is a text'], { type: 'plain/text' });
const url = URL.createObjectURL(blob);

const xhr = new XMLHttpRequest();

xhr.open('get', url, false);
xhr.addEventListener('load', () => {
    console.log(xhr.responseText);
});

xhr.send(); // <-- this throws an exception: "a is undefined"
```
 
Because of the exception, the request is not made.

### What is the Expected behavior?
`xhr.send();` correctly sends the request and the event listener prints `this is a text`.
 
### What is your public web site URL?

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 
```
</details>

<details>
<summary>Screenshots:</summary>

```

```
</details>

### Steps to Reproduce:

1. Go to: ...
2. Execute this command: ...
3. See the error: ...
 
### Your Environment details:

* node.js version:                     
* browser name and version: 
* platform and version:          
* other:

**Comment by acostajohn** [comment]
Hey, sorry! just added more details. Please let me know if y'all need anything else from my side.

**Comment by miherlosev** [comment]
Hi @acostajohn 

Thank you for the shared information. I've reproduced the issue.

For team
Steps to reproduce:
* Open the page with the following content:
```js
<html>
	<body>
		<button id="send">Send blob via xhr</button>
		<script>
			var sendBtn = document.getElementById('send');
			
			sendBtn.addEventListener('click', function () {
				const blob = new Blob(['this is a text'], { type: 'plain/text' });
				const url  = URL.createObjectURL(blob);
				const xhr  = new XMLHttpRequest();

				xhr.open('get', url, false);
				
				xhr.addEventListener('load', () => {
					console.log(xhr.responseText);
				});

				xhr.send();
			});
		</script>
	</body>
</html>
```

in `health-monitor` and press 'Send blob via xhr' button.
* the script error will be displayed in the DevTools console tab
![image](https://user-images.githubusercontent.com/4133518/119101607-d4b12b80-ba21-11eb-9fa5-506a53715e42.png)

**Comment by trzopekm** [comment]
Hi, any updates here?

**Comment by kirillsalikhov** [comment]
Hello

I want to try to fix this issue, by adding check for reqOpts variable existence in send method override:
```
// src/client/sandbox/xhr.ts

        overrideFunction(xmlHttpRequestProto, 'send', function (this: XMLHttpRequest, ...args: Parameters<XMLHttpRequest['send']>) {
            //...
            const reqOpts = XhrSandbox.REQUESTS_OPTIONS.get(this);
            
            if (reqOpts && reqOpts.withCredentials !== this.withCredentials)
                XhrSandbox._reopenXhr(this, reqOpts);
            //...
        });
```

and test 
```
// test/client/fixtures/sandbox/xhr-test.js

test('should handle blob object urls (GH-1397)', function () {
    return new Promise(function (resolve) {
        var xhr = new XMLHttpRequest();
        var blob = new Blob(['this is a text'], { type: 'plain/text' });
        var url = URL.createObjectURL(blob);

        xhr.open('get', url, false);
        xhr.addEventListener('load', function () {
            resolve(xhr);
        });

        xhr.send();
    }).then(function (xhr) {
        strictEqual(xhr.responseText, 'this is a text');
    });
});
```
