### ISSUE TITLE
is hammerhead-worker supposed to handle mock service worker?

### ISSUE THREAD

**Issue by Geddard** [DevExpress/testcafe-hammerhead#2658]
### What is your Scenario?
I'm using testcafe for a very simple app, but I need to use Mock Service Worker for local testing.

MSW works like a charm on unit tests and normal navigation.

### What are you suggesting?
Support MSW?

### What alternatives have you considered?
Using the real endpoint locally? i would prefer not to have to do this.

### Additional context
I've done some reading around and found some guys with a clientScript that should help with this, but i still see failiures for the endpoint with the PREFLIGHT call getting "EMPTY_RESPONSE" and a hammerhead-worker just (failed).

Any suggestions on how to get MSW working with testCafe?

Thanks and kind regards

**Comment by miherlosev** [comment]
Hi @Geddard

> I'm using testcafe for a very simple app, but I need to use Mock Service Worker for local testing.

You can use the [RequestMock](https://testcafe.io/documentation/402667/reference/test-api/requestmock) to mock requests sent by Service Worker or stub the Service Worker functionality with the [ClientScript](https://testcafe.io/documentation/402843/guides/advanced-guides/inject-client-scripts). It is not entirely clear what you want to mock. Could you please share an example that illustrates your use case?
