### ISSUE TITLE
Error in hammerhead.js when creating a contact in SalesForce lightning experience

### ISSUE THREAD

**Issue by Asuza** [DevExpress/testcafe-hammerhead#2662]
### What is your Scenario?
Use TestCafe for testing SalesForce.
 
### What is the Current behavior?
Attempting to click various buttons in SalesForce results in an error that results in a technical error reported as follows:
```
[Cannot read property 'hammerhead|event|internal-blur' of null]
_cancelInternalEvents()@http://10.1.156.24:54555/hammerhead.js:7:20424
{anonymous}()@http://10.1.156.24:54555/hammerhead.js:7:25695
HTMLElement.dispatchEvent()@http://10.1.156.24:54555/hammerhead.js:7:19465
eval()@https://<omitted>.lightning.force.com/components/lightning/inputName.js:1:4173
eval()@https://<omitted>.lightning.force.com/components/lightning/utilsPrivate.js:1:9214
e.EventEmitter.emit()@https://<omitted>.lightning.force.com/components/lightning/utilsPrivate.js:1:9195
eval()@https://<omitted>.lightning.force.com/components/lightning/inputUtils.js:1:6087
```
 
### What is the Expected behavior?
No errors from hammerhead.
 
### What is your public web site URL?
There is no public way to access this to my knowledge.

### Steps to Reproduce:
Attempt to create a contact in the lightning component version of SalesForce.
 
### Your Environment details:

* node.js version:                    v12.19.0, v16.5.0
* browser name and version: Chrome 91
* platform and version:          Windows 10
* other:                                   I don't mind trying to debug this with a little bit of direction on how to set up hammerhead in such a way that it can be debugged via TestCafe, or demoing the issue to someone more familiar with debugging TestCafe/hammerhead.

**Comment by Asuza** [comment]
How can I get TestCafe to use the unminified version of the _hammerhead.js_ script for easier debugging?

**Comment by Asuza** [comment]
While I still mostly don't know what I'm doing, the error seems to be happening here:
```javascript
    function isShadowUIElement(element) {
        // @ts-ignore
        return !!element[INTERNAL_PROPS.shadowUIElement];
    }
```
It appears that `element` is not getting passed into this function... though I'm not sure how to apply changes to this file to whatever TestCafe is running in order to do further debugging. I assume I need to somehow turn this _hammerhead.js_ file into it's corresponding _hammerhead.min.js_ file, but I don't know how to do that at this time.

**Comment by Dmitry-Ostashev** [comment]
Thank you for your report. I tried to reproduce the issue with [SalesForce Lightning Components Playground](https://localhost:1401/H2AtLb33x/https://developer.salesforce.com/docs/component-library/bundle/lightning:button/example). Could you please try to reproduce it on this page or in some public demo?

Also, you can launch the testcafe-hammerhead proxy without TestCafe and debug it by following this instruction:
https://github.com/DevExpress/testcafe-hammerhead#first-look. Run the proxy with the `--dev` parameter to debug the unminified `hammerhead.js` file.

**Comment by Asuza** [comment]
To my knowledge, there is no public demo site to attempt this with. I wish there were! However, with your guidance I was able to get the dev version of the proxy running and can reproduce the issue there.

It seems that the issue is coming from a script called aura_prod.js, where it is calling `dispatchEvent`, which also happens to be a method in hammerhead. I don't know if there's some kind of conflict there, or if that's normal.

![image](https://user-images.githubusercontent.com/658248/126205715-bf697792-fded-4cb2-adf6-dfaf29aa280a.png)

The whole thing kicks off in SalesForce's _button.js_, here:
```javascript
        handleButtonFocus() {
          this.dispatchEvent(new CustomEvent('focus'))
        }
```
Perhaps this `CustomEvent` is throwing off the hammerhead event detection? I'm going to keep investigating and hope you have an idea to try, @Dmitry-Ostashev.

**Comment by Asuza** [comment]
@Dmitry-Ostashev, this is the closest I've found to a "public" demo site, but I hope this works for what you need. Let me know if I can provide any additional details.

**Steps to reproduce:**
1. Set up your hammerhead-testcafe proxy for the steps below
2. Navigate to https://trailblazer.me/trailblazerlogin
3. Log in with e-mail or whatever works for you (might need to create a free account?)
4. Navigate to: https://trailhead.salesforce.com/en/content/learn/modules/accounts_contacts_lightning_experience/accounts-and-contacts-lightning (might need to click "Log In" in the top right corner)
5. Once logged in, at the very bottom of the lesson should be a blue "Launch" button.
![image](https://user-images.githubusercontent.com/658248/126213698-b2939227-2122-479e-b7d1-2e5e73e1a7af.png)
6. Once that page has launched, open your debugger and Pause on exceptions, Pause on caught exceptions.
7. Click the "All" drop-down right next to the search bar at the very top of the page.
![image](https://user-images.githubusercontent.com/658248/126213918-760bf608-46bf-4835-9217-76c6c52f7bdb.png)
8. At this point, the error should be triggered.

**Comment by Dmitry-Ostashev** [comment]
@Asuza thank you for the detailed steps. I've reproduced the issue on this demo website. We will research the problem and update this thread once we have any news.

**Comment by Asuza** [comment]
Is there anything that I can do to contribute to resolving this issue? I'm not sure how long it would take for me to really understand hammerhead enough to be helpful, but if it would save time in the long run, I'm willing to try.

**Comment by LavrovArtem** [comment]
@Asuza thank you for your willingness to help. I am planning to start working on this issue in the current sprint. So, I believe I can handle it myself soon.
