### ISSUE TITLE
Testcafe Environment with ImmutableJS does not allow Collection Destructuring

### ISSUE THREAD

**Issue by Michael-cube19** [DevExpress/testcafe-hammerhead#2669]
### What is your Scenario?
My react app uses ImmutableJS and uses standard ES6 destructuring on Immutable Lists, i.e const [a, b, c] = Immutable.List([1, 2, 3]). When running testcafe tests these variables come back as 'undefined' and cause tests to fail etc. Destructuring works on regular JS arrays all the time and on immutable lists only when not in the testcafe environment.
### What is the Current behavior?
Variables that have been made on Immutable Lists using ES6 destructuring return 'undefined' during testcafe testing.
### What is the Expected behavior?
Destructuring should work on ImmutableJS collections in the testcafe environment and behave just like a normal environment
### Your website URL (or attach your complete example):
See Attached Zip - 
[Archive.zip](https://github.com/DevExpress/testcafe-hammerhead/files/6900405/Archive.zip)

### Steps to Reproduce:
1. unzip file
2. run `npm install` in terminal
3. run `"npx testcafe chrome tests/tests.js -d"`
4. while the test is paused in debugging mode open the console
5. reference the index.html file and look at the console logs
6. you will see that the destructured Immutable variables return `undefined`

**Comment by Farfurix** [comment]
@Michael-cube19 

Hello,

I reproduced the problem. Check the following issue to learn why our destructuring scheme is not working with Immutable: [Immutable doesn't use JS getters in their Lists](https://github.com/immutable-js/immutable-js/issues/21). As a workaround, you can use [`.toJS()`](https://github.com/immutable-js/immutable-js#converts-back-to-raw-javascript-objects) (`const [immFirst, immSecond, ...ImmReast] = immutableArr.toJS();`) in your "dev" environment.

For the team:
We can check the `isArray` condition for these cases and convert the target to an `Array` object.
