### ISSUE TITLE
Question? How did this proxy get Google's Recaptcha to work?

### ISSUE THREAD

**Issue by caracal-js** [DevExpress/testcafe-hammerhead#2674]
I wasn't really sure where to ask this but how does Google Recaptcha work on this proxy. I've been trying to get it work to on my own [proxy](https://github.com/titaniumnetwork-dev/Corrosion) for a while but to no success.

**Comment by Farfurix** [comment]
@caracal-js 

Hello,

Please refer to our documentation: [Test Websites That Use reCAPTCHA](https://testcafe.io/documentation/402794/recipes/integrations/test-websites-that-use-recaptcha).
