### ISSUE TITLE
The element picker works incorrectly due to the cookie synchronization mechanism (w3cschools case)

### ISSUE THREAD

**Issue by AlexKamaev** [DevExpress/testcafe-hammerhead#2677]
https://supportcenter.devexpress.com/internal/ticket/details/T991816

_Originally posted by @Dmitry-Ostashev in https://github.com/DevExpress/testcafe-hammerhead/issues/1921#issuecomment-842962261_

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe

**Comment by Farfurix** [comment]
According to the Chrome performance log, most of the resources are spent on synchronizing cookies (`CookieSandbox.setCookie -> _canSetCookie` is called by `syncWindowCookie`, `CookieSandbox.syncCookie` most of the time):
![Performance-log](https://user-images.githubusercontent.com/30019338/130763451-35563836-a705-4233-a32a-96a2c1c8b4e9.jpg)
Disabling this synchronization (as an experiment) improves the situation, but does not completely fix it.
**As a workaround for TestCafe Studio, we can use the advertisement mocking as a Custom script**:
```js
const mock = RequestMock()
    .onRequestTo(/prebid/).respond('', 200)
    .onRequestTo(/showad\.js/).respond('', 200)
    .onRequestTo(/html\/container\.html/).respond('', 200);

await t.addRequestHooks(mock);
```
Even in this case, there are sometimes slight freezes, but a test can be recorded.
