### ISSUE TITLE
Testcafe adding Prefix to Authorization header for no specific reason

### ISSUE THREAD

**Issue by franciscolosardo** [DevExpress/testcafe-hammerhead#2690]
### What is your Scenario?
We're using a token sent as uri parameter to our website. But when the website makes an xhr request, testcafe is adding the prefix :
`~~~TestCafe added this prefix to control the authorization flow~~~TOKEN_XXXXX
` 
### What is the Current behavior?
Testcafe is adding an unnecessary prefix.  This used to work properly a month ago.
I located the lines where the prefix is added in testcafe-hammercode's src :

https://github.dev/DevExpress/testcafe-hammerhead/blob/a9fbf7746ff347f7bdafe1f80cf7135eeac21e34/src/client/sandbox/fetch.ts#L61-L61

 
### What is the Expected behavior?
I believe this prefix shouldn't be added to this request.
 
### What is your public web site URL?
Not shareable

Your website URL (or attach your complete example): 

<details>
<summary>Your complete app code (or attach your test files):</summary>

 
```js
 We're using a simple fetch with the header Authorization.
```
</details>

 
### Your Environment details:

* node.js version:                   12.0.4
* browser name and version: Chrome 90.
* platform and version:          MacOs 10.14
* other: Testcafe Ver 1.14.2

**Comment by ImanMh** [comment]
This should not happen when using  ` --experimental-proxyless` right? But I'm running proxyless and still get this header which causes my tests to fail.

**Comment by AlexKamaev** [comment]
Hi @ImanMh,

The issue is specific to the `proxyless` mode. We fixed the issue in the latest `rc` version. Please try to run your test using the [https://github.com/DevExpress/testcafe/releases/tag/v2.5.0-rc.1](https://github.com/DevExpress/testcafe/releases/tag/v2.5.0-rc.1) TestCafe version.
