### ISSUE TITLE
Injected CSS

### ISSUE THREAD

**Issue by csutorasr** [DevExpress/testcafe-hammerhead#2710]
### What is your Scenario?

I test an Angular application. It adds style tags to the html to have view encapsulated elements. Hammerhead processes them.

### What is the Current behavior?

Without testcafe the style shows up on the page fine.

Currently the processing runs by hammerhead and the style is injected. However it does not show up.

If I inspect the style tag in the DevTools of Chrome or Safari (I tested on these browsers) I see it is there and after copying the selector I can find the element with window.querySelector. The styles are not applied.

If I edit the text after a double click and press enter (so I don't edit text in it), the styles are applied.

This happens for this component on a specific page. If I open one another page first with this component the styles are working fine.

### What is the Expected behavior?

Being able to see the view encapsulated css without having to navigate to another page first, or editing the element with debugger.

### What is your public website URL? (or attach your complete example)

I can share to the support address if needed.

### What is your TestCafe test code?

It is not relevant, but if a must I can share to the support address.

### Steps to Reproduce

I can share it to the support address.

### TestCafe version

1.16.1

### Node.js version

16.1.0

### Command-line arguments

testcafe safari,chrome -e test.js

### Browser name(s) and version(s)

Chrome 95.0

### Platform(s) and version(s)

MacOS

**Comment by miherlosev** [comment]
Hi @csutorasr,

Try to create a [minimal example](https://testcafe.io/402636/faq#how-to-create-a-minimal-working-example-when-you-submit-an-issue) using your web application (remove private data and extra pages, mock the database connection, etc.) and share it in this thread.
