### ISSUE TITLE
Forced Content-Disposition headers causes unwanted downloading

### ISSUE THREAD

**Issue by mastermatt** [DevExpress/testcafe-hammerhead#2740]
### What is your Scenario?

I would like to have the browser navigate to a JSON route and not download the response.

### What is the Current behavior?

Navigating to any route that responds with a Content-Type not listed below adds a `Content-Disposition: attachment` header.

    'text/cache-manifest',
    'text/html',
    'text/plain'
    'text/xml',
    'application/xhtml+xml',
    'application/xml',
    'application/x-ms-application'

### What is the Expected behavior?

It seems this behavior was added to avoid an issue with PDFs causing TC to stall. 
https://github.com/DevExpress/testcafe-hammerhead/pull/2637
https://github.com/DevExpress/testcafe/issues/1471

I'd like to see the list of Content-Types that aren't affected grow, or preferably, flip the logic so only known offenders (e.g. `application/pdf`) get this treatment. 
Also, the fact that this behavior can't be overridden by the downstream response is a problem. Manually providing a `Content-Disposition: inline` doesn't stop Hammerhead from forcing it back to 'attachment'. 

### What is your public website URL? (or attach your complete example)

```js
fixture`Force Download`

test('test', async t => {
  await t.navigateTo('https://postman-echo.com/get')
})

```

### What is your TestCafe test code?

```js
t.navigateToUrl('https://some.host.com/foo.json')
```

### Your complete configuration file

```json
{
  "disablePageCaching": true,
  "color": true,
  "browsers": "chromium:headless",
  "selectorTimeout": 120000,
  "assertionTimeout": 120000,
  "browserInitTimeout": 240000,
  "videoOptions": {
    "singleFile": false,
    "failedOnly": false,
    "pathPattern": "${DATE}_${TIME}_${TEST}.mp4"
  }
}
```

### Your complete test report

NA

### Screenshots

NA

### Steps to Reproduce

1. Call `navigateToUrl` for any path that returns a Content-Type other then the ones listed above.
2. See the browser download the response body instead of inlining the text.

### TestCafe version

1.17.0

### Node.js version

14.17.3

### Command-line arguments

chrome foo.test.js

### Browser name(s) and version(s)

Chrome 98

### Platform(s) and version(s)

macOS 11.6.3

### Other

https://github.com/DevExpress/testcafe-hammerhead/blob/52c7769365b580a65c0cf3a7bbc22f92bbe0ebc0/src/request-pipeline/header-transforms/transforms.ts#L88-L90

https://github.com/DevExpress/testcafe-hammerhead/blob/e4b63a650dfad77b033475de2125fbfad7143f1d/src/request-pipeline/context.ts#L300-L301

https://github.com/DevExpress/testcafe-hammerhead/blob/27f4f570505689d36d42a2b37880f14cf70823af/src/utils/content-type.ts#L6-L12

**Comment by mastermatt** [comment]
An easy solution to my particular pain would be to add `application/json` to the `PAGE_MIMES` array. However, the general behavior of forcing a download by default seems undesirable.

**Comment by mastermatt** [comment]
fyi @mrsmithgavin

**Comment by VasilyStrelyaev** [comment]
Thank you for your suggestion, @mastermatt!

We implemented the behavior when non-HTML content is downloaded as an attachment in order to facilitate HTML page testing, which is what TestCafe is designed for. We agree that support for JSON route and API testing will be a good addition to the TestCafe framework. This is why we planned the [HTTP API Testing](https://github.com/DevExpress/testcafe/issues/4288) feature as a part of [our current roadmap](https://testcafe.io/402949/roadmap). Please subscribe to [this issue](https://github.com/DevExpress/testcafe/issues/4288) to keep track of our progress.
