### ISSUE TITLE
Heroku hosting results in an error

### ISSUE THREAD

**Issue by NotQuiteZook** [DevExpress/testcafe-hammerhead#2747]
### What is your Scenario?

I forked the code for this project and attempted to host this on heroku.

### What is the Current behavior?

After hosting it and Heroku declaring it as "published," I went to the site and saw the heroku error screen.

### What is the Expected behavior?

From what I saw in heroku dashboard, everything should of gone smoothly.

### What is your public website URL? (or attach your complete example)

https://java-lessons.herokuapp.com/

### What is your TestCafe test code?

The default from the github

### Screenshots

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/59753693/155618550-07b1a449-32bb-41d5-a11f-aaaaf88ec7e4.png">
<img width="661" alt="image" src="https://user-images.githubusercontent.com/59753693/155618571-30abddb7-b46a-46a1-8481-0be4d5d9607e.png">
<img width="2544" alt="image" src="https://user-images.githubusercontent.com/59753693/155618757-061ad419-5e6a-428b-8262-0c808f01bd18.png">
<img width="1942" alt="image" src="https://user-images.githubusercontent.com/59753693/155618783-a298bd93-d5fc-4592-94c5-6f399467421b.png">

### Steps to Reproduce

1. Fork the github to a presonal repo
2. Host it on heroku
3. Go to the site

### TestCafe version

Using Heroku, cannot do this

### Command-line arguments

Using Heroku, cannot do this

**Comment by gamerboy80** [comment]
make a start script in package.json

**Comment by NotQuiteZook** [comment]
But what file should i designate as the start file? index.js? or some other file?

**Comment by NotQuiteZook** [comment]
I wrote the command 
<img width="618" alt="image" src="https://user-images.githubusercontent.com/59753693/155750446-4cfccf2d-606f-4794-b514-1c82ec3a1616.png">
but it still results in an error in heroku

**Comment by miherlosev** [comment]
Hi @NotQuiteZook 

I am not familiar with Heroku. Could you please write step-by-step instructions on how to reproduce the issue?

**Comment by NotQuiteZook** [comment]
@miherlosev 
1. Fork the Repo to your personal account
2. Log on to heroku
3. Click the "New button and then the "Create new app" button.
4. Name the app
5. Create the app
6. Go to the "Deploy" section
7. Search the repo, in this case it would be miherlosev/testcafe-hammerhead
8. Click deploy main
9. Then visit the site
The issue should be apparent.

**Comment by NotQuiteZook** [comment]
@alexphilin 
https://github.com/DevExpress/testcafe-hammerhead

**Comment by alexphilin** [comment]
Hi @NotQuiteZook

I've repeated the steps to reproduce and got the same result - the 'Application error' on deploying the `miherlosev/testcafe-hammerhead` repository.

However, it's not a bug. The `testcafe-hammerhead` repository is not a repository with Heroku app sources. So, correct running is not guaranteed after a deploy.

Try to find the cause of the issue or ask StackOverflow about it.
