### ISSUE TITLE
teestcafe blank page

### ISSUE THREAD

**Issue by hoqueal** [DevExpress/testcafe-hammerhead#2753]
### What is your Scenario?

I get a blank screen when I try to navigate to  https://www.clinicalkey.com/student/.  when I try a different domain it works fine.

### What is the Current behavior?

I get a white blank page

### What is the Expected behavior?

I should see the login page.

### What is your public website URL? (or attach your complete example)

https://www.clinicalkey.com/student

### What is your TestCafe test code?

fixture`My Fixture`
  .page('https://www.clinicalkey.com/student/login');

test('open browser', async (t) => {
  await t.click(Selector('#c-ckm-field__input-1'));
});

### Steps to Reproduce

1. try to open the URL with https://www.clinicalkey.com/student/
2. you should see the issue
3.

### TestCafe version

1.18.5

### Command-line arguments

testcafe chrome testid

**Comment by Aleksey28** [comment]
Thank you for the report. I reproduced the described case. We will update this thread once we have any news.

**Comment by hoqueal** [comment]
Thank you @Aleksey28 for looking into this. Please let me know if you need any additional information. This is a major blocker for me.

**Comment by Aleksey28** [comment]
I appreciate this, @hoqueal. We will contact you if we need additional information.

**Comment by vietrovo** [comment]
Hi @Aleksey28 Do you have any news when we can expect the issue being resolved? We are unable to run our auto suit because of this bug. 
Thank you.

**Comment by Aleksey28** [comment]
Folks,

I tried to reproduce the issue again, but everything works fine. It looks like the tested web page was changed and the original issue doesn't occur anymore. Try to run your tests again. If the issue persists, please share a new example that reproduces it.

**Comment by vietrovo** [comment]
Hi @Aleksey28. Yes, after our recent release the issue got fixed. It appears to be our code issue.
Thank you for help.
