### ISSUE TITLE
Max event listeners exceeded when using cache

### ISSUE THREAD

**Issue by ben-gooding-sky** [DevExpress/testcafe-hammerhead#2767]
### What is your Scenario?

Running suite of tests for around 200 tests and near the end it prints out 6 warnings to the console:

```
(node:73798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:73798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:73798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:73798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 data listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:73798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
(node:73798) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [IncomingMessageLike]. Use emitter.setMaxListeners() to increase limit
```

### What is the Current behavior?

It emits warnings when it shouldn't be

### What is the Expected behavior?

It should not emit these warnings

### What is your public website URL? (or attach your complete example)

I can't submit an example because it would require sending 200+ tests

### What is your TestCafe test code?

There is no specific code relating to the issue other than the config file

### Your complete configuration file

```
{
  "browsers": ["chrome:headless"],
  "hostname": "localhost",
  "screenshots": {
    "path": "reports/screenshots/",
    "takeOnFails": true,
    "fullPage": true
  },
  "reporter": [
    {
      "name": "spec"
    },
    {
      "name": "html",
      "output": "reports/report.html"
    }
  ],
  "debugMode": false,
  "debugOnFail": false,
  "concurrency": 4,
  "speed": 1,
  "cache": true,
}
```

### Steps to Reproduce

1. turn on cache
2. run a lot of tests in one command (happens with and without concurrency)
3. Look through console output for the memory leak warning

### TestCafe version

1.18.3

### Node.js version

12.16.0

### Command-line arguments

testcafe path/to/test

### Browser name(s) and version(s)

chrome:headless

### Platform(s) and version(s)

macOS 12.3.1

**Comment by AlexKamaev** [comment]
I did not manage to reproduce the issue on my side using your configuration file and my set of tests. I think the cause can be specific to your usage scenario. Please simplify your tests and share them with us so that we will reproduce the issue on our side.

I would also like to note that you are using the 1.18.3 TestCafe version. I would recommend you run your tests with the latest 1.18.6 version. Please also update your nodejs, since the 12.* version is not maintained yet.
