### ISSUE TITLE
navigator.serviceWorker may throw an exception due to the sandbox settings of the iframe

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#277]
```javascript
test('', function() {
    var iframe = document.createElement('iframe');

    iframe.setAttribute('sandbox', '');
    iframe.src = window.getCrossDomainPageUrl('../../../data/cross-domain/service-worker-not-available.html');

    document.body.appendChild(iframe);
});
```
```Uncaught SecurityError: Failed to read the 'serviceWorker' property from 'Navigator': Service worker is disabled because the context is sandboxed and lacks the 'allow-same-origin' flag.```
[Source code](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/native-methods.js#L96) where the error occurs.

**Comment by miherlosev** [comment]
Behaviour changed in FF 44.
I am working on this.

**Comment by miherlosev** [comment]
fixed in PR https://github.com/DevExpress/testcafe-hammerhead/pull/406
