### ISSUE TITLE
XHR errors

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#284]
HHM recently showed new errors on http://www.samsung.com/uk/home/. Doesn't seems what they are caused by regression, but more likely they are a result of the site change. In Chrome and IE there is a runtime error, which is caused by an empty response from the XHR (in DevTools it's showed with status "Finished" instead of status code). Meanwhile in Firefox console throws CORS-error and seems like XHR url doesn't proxied at all.
Guys, please take a look. 
\cc @churkin @LavrovArtem @miherlosev

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
Client code sends the xhr without the referer header, because of this proxy does not transform origin header.
```Origin: http://localhost:1401``` // does not transform
