### ISSUE TITLE
Update the deprecated asar package to @electron/asar

### ISSUE THREAD

**Issue by 28two** [DevExpress/testcafe-hammerhead#2852]
### What is your Scenario?

The asar package is deprecated in favour of @electron/asar.

We are having NPM commands thrown with our testcafe due to this package being outdated and we cannot update it due to it being a dependency of hammerhead

### What are you suggesting?

Replace the outdated package with the one as suggested by the author

### What alternatives have you considered?

None, as we are using testcafe, but need the dependency corrected to stop these NPM warnings/errors

**Comment by miherlosev** [comment]
Hi @28two,

Thank you for pointing this out. I've created a PR with a fix.
