### ISSUE TITLE
Adobe Analytics error in FE when running automated tests

### ISSUE THREAD

**Issue by Foxman8472** [DevExpress/testcafe-hammerhead#2861]
### What is your Scenario?

Only reproduces during automated test run.

Error was introduced after an update in which Adobe Analytics were added.

hammerhead.js:42871 TypeError: Cannot read properties of undefined (reading 'name')
    at n.listener [as f] (<anonymous>:17:31)
    at r (<anonymous>:12:456)
    at a.push (<anonymous>:11:195)
    at main.06675433.chunk.js:2:35862
    at Ll (2.57102da7.chunk.js:3:5885056)
    at t.unstable_runWithPriority (2.57102da7.chunk.js:3:5903033)
    at Hi (2.57102da7.chunk.js:3:5824909)
    at Rl (2.57102da7.chunk.js:3:5884481)
    at vl (2.57102da7.chunk.js:3:5875935)
    at 2.57102da7.chunk.js:3:5825141
error @ hammerhead.js:42871
fc @ 2.57102da7.chunk.js:3
a.payload @ 2.57102da7.chunk.js:3
uo @ 2.57102da7.chunk.js:3
Kr @ 2.57102da7.chunk.js:3
qc @ 2.57102da7.chunk.js:3
Sl @ 2.57102da7.chunk.js:3
Cl @ 2.57102da7.chunk.js:3
wl @ 2.57102da7.chunk.js:3
vl @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
t.unstable_runWithPriority @ 2.57102da7.chunk.js:3
Hi @ 2.57102da7.chunk.js:3
qi @ 2.57102da7.chunk.js:3
Gi @ 2.57102da7.chunk.js:3
yl @ 2.57102da7.chunk.js:3
notify @ 2.57102da7.chunk.js:3
notifyNestedSubs @ 2.57102da7.chunk.js:3
i @ 2.57102da7.chunk.js:3
g @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
dispatch @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
o @ 2.57102da7.chunk.js:3
hammerhead.js:42871 React Router caught the following error during render TypeError: Cannot read properties of undefined (reading 'name')
    at n.listener [as f] (<anonymous>:17:31)
    at r (<anonymous>:12:456)
    at a.push (<anonymous>:11:195)
    at main.06675433.chunk.js:2:35862
    at Ll (2.57102da7.chunk.js:3:5885056)
    at t.unstable_runWithPriority (2.57102da7.chunk.js:3:5903033)
    at Hi (2.57102da7.chunk.js:3:5824909)
    at Rl (2.57102da7.chunk.js:3:5884481)
    at vl (2.57102da7.chunk.js:3:5875935)
    at 2.57102da7.chunk.js:3:5825141 Object
error @ hammerhead.js:42871
value @ 2.57102da7.chunk.js:3
o.componentDidCatch.a.callback @ 2.57102da7.chunk.js:3
po @ 2.57102da7.chunk.js:3
gc @ 2.57102da7.chunk.js:3
Tl @ 2.57102da7.chunk.js:3
t.unstable_runWithPriority @ 2.57102da7.chunk.js:3
Hi @ 2.57102da7.chunk.js:3
jl @ 2.57102da7.chunk.js:3
vl @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
t.unstable_runWithPriority @ 2.57102da7.chunk.js:3
Hi @ 2.57102da7.chunk.js:3
qi @ 2.57102da7.chunk.js:3
Gi @ 2.57102da7.chunk.js:3
yl @ 2.57102da7.chunk.js:3
notify @ 2.57102da7.chunk.js:3
notifyNestedSubs @ 2.57102da7.chunk.js:3
i @ 2.57102da7.chunk.js:3
g @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
dispatch @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
(anonymous) @ 2.57102da7.chunk.js:3
o @ 2.57102da7.chunk.js:3
hammerhead.js:42871 Adobe Analytics Error: Cannot read properties of undefined (reading 'indexOf')
hammerhead.js:42871 deny-all

### What is the Current behavior?

Error displayed in front-end and in console when application's landing page finishes loading.

### What is the Expected behavior?

No errors displayed.

### What is your public website URL? (or attach your complete example)

Client Cloudflare configuration prevents access from proxies without whitelist to test environment, so use --experimental-proxyless
https://eucms-cloud-dev.bca.com/

### What is your TestCafe test code?

Not relevant, since the same code was working before the Adobe Analytics update.

                await t.navigateTo(https://eucms-cloud-dev.bca.com/)
                await t.hover([data-cy="country-select"])
                await t.wait(2000) //wait for React refresh
                await t.click([data-cy="country-select"])

### Screenshots

![error](https://user-images.githubusercontent.com/15379598/224954192-8c033c86-ca0e-4300-a5ff-09fe21e5f3b6.jpg)
![error2](https://user-images.githubusercontent.com/15379598/224954423-95b4507a-f978-4313-99fc-eedd45cf6f91.jpg)

### Steps to Reproduce

Run testcafe tests
Error displayed after page load

### TestCafe version

2.4.0

### Node.js version

16.17.0

### Command-line arguments

testcafe chrome e2e.test.js

also tried using experimental proxyless, got same issue

tescafe chrome e2e.test.js --experimental-proxyless

### Browser name(s) and version(s)

Chrome 110.0.5481.180

### Platform(s) and version(s)

Windows

**Comment by AlexKamaev** [comment]
I managed to reproduce the issue. Thank you for sharing your test with us.
