### ISSUE TITLE
TestCafe not rendering header of the page, printing 'App not found.' message in console instead.

### ISSUE THREAD

**Issue by aarti315** [DevExpress/testcafe-hammerhead#2871]
### What is your Scenario?

TestCafe Azure DevOps pipeline which is running approx 120 cases daily since more than 6 months started failing more than 35+ TestCases since last few days.

### What is the Current behavior?

35+ Testcases are failing as page header is not getting loaded. and in console we see message '**App not found**'.

### What is the Expected behavior?

Page should load fine with header and TestCase should run fine without failing

### What is your public website URL? (or attach your complete example)

NA right now as can not share private details.

We need to understand in what scenario hammerhead would print 'App not found' message.

### What is your TestCafe test code?

Not available

### Your complete configuration file

NA

### Steps to Reproduce

1. NA
2.
3.

### TestCafe version

2.4.0

### Node.js version

19.7.0

### Command-line arguments

testcafe chrome:headless SmokeTest/**/* -q  -e --concurrency 2 --disable-http2

**Comment by AlexKamaev** [comment]
It is unlikely that the "App not found" message comes from `testcafe` or `testcafe-hammerhead`. Unfortunately, we cannot say more without a working example that demonstrates the issue.
I can only recommend you to try to run your tests in `proxyless` mode, which was developed especially to replace some `testcafe-hammerhead` features to make tests more stable.

See this article for details: [https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode](https://testcafe.io/documentation/404237/guides/experimental-capabilities/proxyless-mode)
