### ISSUE TITLE
Unable to launch URL 

### ISSUE THREAD

**Issue by sabareesh-r23** [DevExpress/testcafe-hammerhead#2879]
### What is your Scenario?

Tried opening a URL by manually launching the testcafe-hammerhead . Below is the error : 
<img width="701" alt="image" src="https://user-images.githubusercontent.com/69809951/231433580-56c74b26-3e84-4c87-96f4-3060da8bb187.png">

### What is the Current behavior?

<img width="701" alt="image" src="https://user-images.githubusercontent.com/69809951/231433633-94b92c85-8327-4737-b5d7-3ab93d29371f.png">

### What is the Expected behavior?

Should launch the URL without any error message

### What is your public website URL? (or attach your complete example)

https://www.google.com

### What is your TestCafe test code?

Didn't use script . Just followed the steps in the readme.md

### Steps to Reproduce

1.clone the repo
2.npm install
3.node node_modules/gulp/bin/gulp http-playground

### TestCafe version

hammerhead - 31.0.0

### Node.js version

14.15.2

### Command-line arguments

node node_modules/gulp/bin/gulp http-playground

**Comment by Aleksey28** [comment]
Hi @sabareesh-r23,

Thank you for your notice. I created a [PR](https://github.com/DevExpress/testcafe-hammerhead/pull/2880) with the fix.
