### ISSUE TITLE
document.location for the top window is proxied incorrectly

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#290]
If we set document.location for the top window from iframe: 

```javascript
document.location = 'http://some.domain.com/';
```

it is proxied as for the iframe:

`http://hammerhead:1400/sessionId!`**iframe**`/http://some.domain.com/`

**Comment by inikulin** [comment]
@churkin Can you provide more details, please?

**Comment by inikulin** [comment]
Thank you
