### ISSUE TITLE
maximum callstack size exceeded on some webpages

### ISSUE THREAD

**Issue by Ghxst** [DevExpress/testcafe-hammerhead#2938]
### What is your Scenario?

We're running into an issue with some webpages crashing due to a `maximum callstack size exceeded` error.

### What is the Current behavior?

Hammerhead.js attempts to parse resources that cause an error that makes the page crash.

### What is the Expected behavior?

No page crash is expected.

### What is your public website URL? (or attach your complete example)

https://www.marriott.com/sign-in.mi

### What is your TestCafe test code?

`node node_modules/gulp/bin/gulp multi-window-http-playground`

### Steps to Reproduce

1. `node node_modules/gulp/bin/gulp multi-window-http-playground`
2. navigate to `https://www.marriott.com/sign-in.mi`
3. check console

### TestCafe version

n/a

### Node.js version

v18.16.0

### Command-line arguments

n/a

### Browser name(s) and version(s)

Chrome 114

### Platform(s) and version(s)

Windows, Linux Ubuntu

**Comment by miherlosev** [comment]
Hi @Ghxst,

Thank you for the shared information. I've reproduced the issue.

For team:
![image](https://github.com/DevExpress/testcafe-hammerhead/assets/4133518/16819ba7-620e-4971-83c6-02ffe50625df)

**Comment by Ghxst** [comment]
Thanks for picking this up so quickly. I would love to know how your team goed about fixing these issues and what the root cause is. If you have any info that would be awesome.

**Comment by Aleksey28** [comment]
Hi @Ghxst,

We don't have any information yet. We will research this matter promptly and update this thread once we have news.
