### ISSUE TITLE
Tap doesn't set hoverPseudoClass on an element in Android 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#294]
Despite `onmouseover`  doesn't emitted with touchscreens, an element has `:hover` state after tapping on it.

Hammerhead uses `mouseover` to detect current hovered element and set `hoverPseudoClass` on it, so it cannot set `hoverPseudoClass` with touchscreen. It breaks functionality of `:hover` in playback mode.

So we need set  `hoverPseudoClass` on tap/click, or maybe use `focusPseudoClass` instead of `hoverPseudoClass` on Android.

**Comment by helen-dikareva** [comment]
In iOS/Safari the same problem. We're waiting for this for https://github.com/DevExpress/testcafe/issues/113

**Comment by churkin** [comment]
I am working on this
