### ISSUE TITLE
Hammerhead tries to make a request to `https://javascript:;` type urls.

### ISSUE THREAD

**Issue by Ghxst** [DevExpress/testcafe-hammerhead#2965]
### What is your Scenario?

Hammerhead will try to make fetch requests to URLs that contain the `javascript` protocol. 

### What is the Current behavior?

Instead of parsing and handling the JS properly a fetch will be made.

### What is the Expected behavior?

These type of protocols should be handled properly, I am assuming?

### What is your public website URL? (or attach your complete example)

`https://www.delta.com/login/loginPage`

### What is your TestCafe test code?

`node node_modules/gulp/bin/gulp multi-window-https-playground`

### Steps to Reproduce

1. clone `testcafe-hammerhead`
2. run `node node_modules/gulp/bin/gulp multi-window-https-playground`
3. proxy `https://www.delta.com/login/loginPage`
4. check network log and you will see a fetch to `https://javascript:;`

### TestCafe version

n/a

### Command-line arguments

node node_modules/gulp/bin/gulp multi-window-https-playground

**Comment by AlexKamaev** [comment]
Thank you for sharing the example. I managed to reproduce the issue. We'll update the thread once we have any results.
