### ISSUE TITLE
Hammerhead produces invalid code when dealing with destructuring and class syntax in the same line

### ISSUE THREAD

**Issue by tobiaswaltl** [DevExpress/testcafe-hammerhead#2983]
### What is your Scenario?

I would like to use testcafe to test my application that contains ES6 syntax.
As we need multi window support, using native automation is not an option for us.

### What is the Current behavior?

Hammerhead removes the brackets after `extends` in the following code example and thus, creates invalid syntax:
`var {hasOwnProperty: gt} = x , ft = e=>class t extends (e || We) { } ;`

It seems that this does only happen, when the destructuring statement is there.

### What is the Expected behavior?

Hammerhead does not create invalid syntax when processing the code example above.

### What is your public website URL? (or attach your complete example)

I don't have a public example, but in the repro section I have added a link to my fork with an additional unit test that demonstrates the problem.

### What is your TestCafe test code?

n/a

### Steps to Reproduce

1. Run the [test](https://github.com/tobiaswaltl/testcafe-hammerhead/blob/bug/test/server/script-processor-test.js#L891) I have created. It demonstrates how the above code example is transpiled into invalid code.

### TestCafe version

3.4.0

### Node.js version

18.18.2

### Command-line arguments

n/a

**Comment by Bayheck** [comment]
Hello,

>As we need multi window support, using native automation is not an option for us.

Try using [TestCafe v3.5.0](https://testcafe.io/404732/release-notes/framework/2023-12-28-testcafe-v3-5-0-released#experimental-run-multi-window-tests-with-native-automation)'s ‘--experimental-multiple-windows’ mode in Native Automation. Let us know if you need further assistance.
