### ISSUE TITLE
Apple pay failure when using hammerhead as a proxy

### ISSUE THREAD

**Issue by sparsh00** [DevExpress/testcafe-hammerhead#2987]
### What is your Scenario?

I'm using Hammerhead as a stand-alone proxy for running a session on iOS.using

### What is the Current behavior?

The Apple pay sheet is getting auto-closed after throwing an error.

### What is the Expected behavior?

Should be able to complete payment 

### What is your public website URL? (or attach your complete example)

https://applepaydemo.apple.com/

### What is your TestCafe test code?

Running session drictly by using hammerhead as a proxy

### Screenshots
Expected - 
![Screenshot 2023-12-12 at 8 50 24 PM](https://github.com/DevExpress/testcafe-hammerhead/assets/68541575/b54900c0-dc5b-4a3e-ac3a-6cdcfd63d783)

Error -
![Screenshot 2023-12-12 at 8 48 04 PM](https://github.com/DevExpress/testcafe-hammerhead/assets/68541575/b18120aa-9dc6-4089-b8a0-f2c7ccdb0861)
![Screenshot 2023-12-12 at 8 50 51 PM](https://github.com/DevExpress/testcafe-hammerhead/assets/68541575/a5dcf8bf-9bdc-4b22-8b81-f610b3a301ac)

### Steps to Reproduce

1. Setup your device / machine to make Apple Pay Payments . Refer: https://support.apple.com/en-in/HT204506 ( You need to login to iCloud, ( You can use sandbox too ) and Add Card to Wallet ( Personal cards are not required, Sandbox cards also works if you have logged in with Sandbox account )
2. Start testcafe hammer-head proxy ( node node_modules/gulp/bin/gulp https-playground )
3. Open http://localhost:1400/
4. Enter Apple Pay demo website - https://applepaydemo.apple.com/  in the URL
5. Click on Apple Pay button.

### TestCafe version

null

### Node.js version

16.20.2

### Command-line arguments

node node_modules/gulp/bin/gulp https-playground

**Comment by aleks-pro** [comment]
Hello,
 
We do not recommend that you use testcafe-hammerhead as a stand-alone package and do not support such usage scenarios. Could you describe in greater details why you need to use testcafe-hammerhead without testcafe?
