### ISSUE TITLE
Uncaught (in promise) DOMException: Failed to execute 'joinAdInterestGroup' on 'Navigator':May only joinAdInterestGroup from an https origin

### ISSUE THREAD

**Issue by lavender923102** [DevExpress/testcafe-hammerhead#2999]
### What is your Scenario?

I tried the function of testcafe-hammerhead,the first step I did is:
git clone https://github.com/DevExpress/testcafe-hammerhead.git
cd testcafe-hammerhead
npm install
node node_modules/gulp/bin/gulp http-playground
then  I printed the URL https://demo.dynamsoft.com/web-twain/ on the page http://localhost:1401 and then click proxy button

### What is the Current behavior?

On the new page I saw error above and on the console there were many other errors like "Uncaught TypeError: Cannot read properties of undefined (reading 'type')"

### What is the Expected behavior?

No errors

### What is your public website URL? (or attach your complete example)

See above

### What is your TestCafe test code?

No

### Steps to Reproduce

See above steps

### TestCafe version

testcafe-hammerhead@31.7.1

### Node.js version

 v16.17.1

### Command-line arguments

No

### Browser name(s) and version(s)

Chrome122

### Platform(s) and version(s)

windows10 x64

**Comment by PavelMor25** [comment]
Hello @lavender923102,

We do not recommend using testcafe-hammerhead as a standalone package and do not support these usage scenarios. Could you describe in greater detail why you need to use testcafe-hammerhead without testcafe ?
