### ISSUE TITLE
Add the capability to process an iframe whose src attribute is set to an encoded value.

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#3]
iframe.src = "javascript:'%3Chtml%3E%3Cbody%3E%3Ch1%3Etest%3C/h1%3E%3C/body%3E%3C/html%3E'"

Encoded attribute value will be applied for Safari 8, IE 11, Firefox, 
not applied - Chrome 44

**Comment by inikulin** [comment]
Can you provide code examples. Actual/expected? Check title with tech writers. It's not clear currently what's wrong and how it should be fixed.

**Comment by inikulin** [comment]
\ping @miherlosev

**Comment by miherlosev** [comment]
If I set an iframe src attribute to 'javascript:<html><body><h1>test</h1></body></html>', its content
will be '<html><body><h1>test</h1></body></html>'.
Hammerhead patches src attributes for such iframes and adds the additional code.

Some browsers (Safari 8, IE 11, Firefox) allows setting an iframe content by using an encoded value.
For example, if I set 
iframe.src to "javascript:'%3Chtml%3E%3Cbody%3E%3Ch1%3Etest%3C/h1%3E%3C/body%3E%3C/html%3E'", its content will be <html><body><h1>test</h1></body></html>.
Hammerhead cannot patch an src attribute with an encoded value.

**Comment by miherlosev** [comment]
It's a non documented behavior.
