### ISSUE TITLE
React "onChange" event doesn't fire.

### ISSUE THREAD

**Issue by arubtsov** [DevExpress/testcafe-hammerhead#313]
Paragraph element in following sample should reflect user input.

https://gist.github.com/arubtsov/a50fb167c38357de98d4
https://gist.github.com/arubtsov/9580b0e446922bdcb8fc

**Comment by AlexanderMoskovkin** [comment]
It seems it relates to the `testcafe` repo. We'll check it and create an issue for the `testcafe` if necessary.

**Comment by AndreyBelym** [comment]
It's a definitely a `testcafe` issue, I cannot reproduce it in `hammerhead-playground`. So I have created DevExpress/testcafe#214, and close the issue in `hammerhead`.
