### ISSUE TITLE
"input", "change", "submit" simulated events should bubble 

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#318]
Events "input", "change" and "submit" bubble in native browser, "focus", "blur" and "selectionchange" don't. Discovered in context of DevExpress/testcafe#214.

**Comment by AlexanderMoskovkin** [comment]
@churkin Could you please release a new version with this fix and close the https://github.com/DevExpress/testcafe/issues/214 after that?

**Comment by churkin** [comment]
@AlexanderMoskovkin of course
