### ISSUE TITLE
Regression: JSON parse errors in HHM

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#320]
Guys, please take a look @churkin @LavrovArtem @miherlosev 
Seems like it's one of these commits: https://testcafe-hhhm.devexpress.com/history?timestamp=1449082979570&siteUrl=http://www.tripadvisor.com/

**Comment by miherlosev** [comment]
I am working on this

**Comment by LavrovArtem** [comment]
I am working on this

**Comment by churkin** [comment]
#324 duplicate

**Comment by LavrovArtem** [comment]
The Acorn parser can not parse a client script:
```javascript
if(true){a=2}/regexp/.exec()
             ^
```
We need to update the Acorn parser.
