### ISSUE TITLE
After proxing Flash content is not working

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#332]
1)http://demos.devexpress.com/ASPxMultiUseControlsDemos/ObjectContainer/ClientSide.aspx
Open page in playground and without it.
2)Page that opened in playground does not have image that must be drawing with Flash.

Only in Firefox

**Comment by miherlosev** [comment]
I am working on this

**Comment by inikulin** [comment]
@miherlosev it doesn't seem to be a severe issue. Maybe it will be better to focus on the webplatform tests?

**Comment by miherlosev** [comment]
I think at first we need to fix known issues.
Then we will continue to search issues using webplatform tests.

**Comment by inikulin** [comment]
This is endless process

**Comment by miherlosev** [comment]
Firefox 42 sets incorrect HTTP `Accept` header when fetching data for <object> tag with flash content.
Bug report - https://bugzilla.mozilla.org/show_bug.cgi?id=1232583

Flash content fetchs like a page - `accept` header value equals `text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8`.
After duscussion we decide to detect flash by content.

I found three npm module:
1)https://github.com/kevva/is-swf
2)https://github.com/rafaeldias/swf-reader
3)https://github.com/sindresorhus/file-type
All modules check first three byte of the content.

1, 3 modules don't suport the swf 13 and later (see http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/swf/pdf/swf-file-format-spec.pdf (page 27))

I think we need to use the following algorithm:
1)use the https://github.com/rafaeldias/swf-reader
2)try to read content
3)if read is successfully and reading content lenght (from swf header) equal real content length then it is swf

What do you think? @inikulin @churkin

**Comment by inikulin** [comment]
I prefer approach from 1 and 3, since they will not introduce performance overhead. Maybe we will be able to send PR to one of them, so it will support SWF13. Seems like it shouldn't be very hard, since we need to add just new header chars
