### ISSUE TITLE
Implement about:blank page

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#339]
We need to implement page for the `http://proxy-host/session-id/about:blank`. It should be just blank page with our stuff injected. We will need for the new API, there tests could start on blank page. BTW, we can fallback to this blank page URL then we can't create proxy URL instead of throwing an error in `getProxyUrl`

**Comment by inikulin** [comment]
We need 'about:error' as well (it should map to the same empty page)
\cc @miherlosev we need this ASAP

**Comment by miherlosev** [comment]
I'm working on this
