### ISSUE TITLE
Method 'querySelectorAll' should be overrided to use JQuery selectors that returs elements by value of attribute contains URL

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#340]
When test contains selector like this '[href="https://www.google.ru/"]' (or other selector based on attr) jQuery try to get element (by Sizzle) and just call ```document.querySelectorAll(selector)```
Check please may be we have other proxed attr.

**Comment by miherlosev** [comment]
I am working on this

**Comment by miherlosev** [comment]
We need to proxy only two variants of the attribute selectors:
[attribute=value]
[attribute^=value]

Rewrite `document.querySelector, document.querySelectorAll`

Algorithm:
1)check attribute name of the selector. 
2)If we proxy this attribute and we need to proxy this case (see below) and attrubute value is valid url then need to create proxy url for attribute value
3)call the following native method with patched attribute

**Comment by miherlosev** [comment]
waiting for https://github.com/DevExpress/testcafe-hammerhead/issues/342
