### ISSUE TITLE
Avoid calling setAttribute/removeAttribute on HTMLDocument

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#345]
When traversing DOM tree and setting/removing `hoverPseudoClass`, tree eventually may be traversed up to the root - HTMLDocument, that doesn't have `setAttribute`/`removeAttribute` methods.

Check `jointParent.tagName` in `_setHoverMarker` & `_clearHoverMarkerUntilJointParent` in [/src/client/sandbox/event/hover.js#L17](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/hover.js#L17) and [/src/client/sandbox/event/hover.js#L52](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/event/hover.js#L52)

**Comment by AndreyBelym** [comment]
It was encountered once in Firefox 35 ASPTests.RWA.DevAV, but I cannot reproduce it now.

**Comment by AndreyBelym** [comment]
Reopening, reproduced when `newHoveredElement` === `document.body`.

**Comment by AndreyBelym** [comment]
OK, problem is not with the `body`. Looks like a bug in Firefox: when iframe's src has changed, sometimes top level document is recreated. It leads to situation that no one node from previous document is contained in new document.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by AndreyBelym** [comment]
I wrote a test page, but wasn't able to fully separate it from DX ASP Demos. So you need to run DevAV demos at `http://localhost/DevAV` first, and then place the following content in `SITE_ROOT\*.html`.
```html
<!DOCTYPE html>
<html>
<head>
    <title>Test me all!</title>
</head>
<body>

<iframe src="http://localhost/DevAV/Spreadsheet.aspx?ReportArgs=13|ProductOrders1|1">
</iframe>

<script type="text/javascript">
    setTimeout(function () {
        document.querySelector('iframe').setAttribute('src','http://localhost/DevAV/DocumentViewer.aspx?ReportArgs=13|ProductOrders1|1');
    }, 2000);
</script>
</body>
</html>
```
[Check this video](https://goo.gl/PymVqj) to see how to reproduce the bug;
