### ISSUE TITLE
Javascript error on jsfiddle.net

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#359]
See: https://testcafe-hhhm.devexpress.com/history?timestamp=1452867987933&siteUrl=https://jsfiddle.net/ \cc @miherlosev @LavrovArtem

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
Again errors with the mootools framework (#331)

**Comment by LavrovArtem** [comment]
The mootools framework removes the Function.prototype.bind method and replaces it later. I think we need to use the ```apply``` function instead the ```bind```, because it fixes error and [works faster](http://jsperf.com/bind-apply).

**Comment by inikulin** [comment]
@LavrovArtem Yes. We need `eslint-hammerhead` rule as well.

**Comment by inikulin** [comment]
BTW, we have a `fastApply` implemented: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/methods.js#L87. Let's move it to utils, so it can be reused

**Comment by LavrovArtem** [comment]
ok

**Comment by LavrovArtem** [comment]
@inikulin see http://jsperf.com/bind-apply, ```fastApply``` is slower

**Comment by inikulin** [comment]
@LavrovArtem No, if it's used inline: http://jsperf.com/call-apply-optimization

**Comment by inikulin** [comment]
You can even speed it up by passing the actual method instead of method name

**Comment by LavrovArtem** [comment]
But i need closure for replace the bind function
https://github.com/DevExpress/testcafe-hammerhead/pull/360/files#diff-34a0bebdc3e2da8d60cf6769608258aeR31

**Comment by inikulin** [comment]
ok, then
