### ISSUE TITLE
Uncaught TypeError: Cannot read property 'performance' of null 

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#373]
Reproduces permanently: http://66.55.147.18:13500/history?timestamp=1453462167132&siteUrl=http://www.constantcontact.com/next?s_tnt=56324:4:0

**Comment by churkin** [comment]
@LavrovArtem  If a server in the response to a form submission returns a 204 status, then the browser remains in the same page. Our proxy always returns a 200 status, so unnecessary redirect occurs.
