### ISSUE TITLE
Support error generation on wrong method calling

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#375]
For example, we should throw `TypeError` on the following instructions:
`document.getElementById()`
`document.querySelectorAll()`
etc.

We should throw errors as a native methods.
Need to check all overriden methods in all sundboxes.

**Comment by churkin** [comment]
I'm working on this

**Comment by inikulin** [comment]
BTW, how you suppose to do that? I remember we've talked about it. But the best to do that will be passing arguments to the native methods, so it will throw. Because it will be nearly enormous task to perform all checks on our side.

**Comment by churkin** [comment]
@inikulin  I'll check all of the methods that the parameters transferred to the native method as is

**Comment by churkin** [comment]
@inikulin @miherlosev We have replaced all '.apply' using to the '.call' for the optimization. It will not allow to pass parameters in its original form. It is also difficult to write tests. Are we ready to sacrifice performance and a heap of extra code for this issue?

**Comment by inikulin** [comment]
@churkin How it prevent this feature to be implemented? Can you show any example?

**Comment by churkin** [comment]
Now
```javascript
document.createElement = tagName => nativeMethods.createElement.call(document, tagName);
```
After
```javascript
document.createElement = function() { 
   if(arguments.length === 0) 
        nativeMethods.createElement.call(document);
   else if(arguments.length === 1) 
        nativeMethods.createElement.call(document, arguments[0]);
   else if(arguments.length === 2) 
        nativeMethods.createElement.call(document, arguments[0], arguments[1]);
   else if(arguments.length === 3) 
        nativeMethods.createElement.call(document, arguments[0], arguments[1], arguments[2]);

   ........
}
```

**Comment by inikulin** [comment]
Ok, now I get it. Let's try using apply. I'm not sure if we will have any significant performance change.
