### ISSUE TITLE
MethodCallInstrumentation - move code to overriden methods

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#382]
We have a `methodCallInstrumentation` for methods which are already overriden.
For example:
`querySelector`,
`querySelectorAll`,
`write`
`writeln`

We can to move code from `methodCallInstrumentation` to appropriate overriden methods.
After it will be done `methodCallInstrumentation` will contain the code only for `postMessage`.
If we can override `postMessage` then we can to delete `methodCallInstrumentation`.

/cc @churkin @inikulin

**Comment by inikulin** [comment]
> We have a methodCallInstrumentation for methods which are already overriden.

Where? In ShadowUI, I guess?

**Comment by miherlosev** [comment]
In ShadowUI too.

Instrumented methods - https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/methods.js
Overrided methods:
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/document.js#L167
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/document.js#L171
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L393
etc.

**Comment by miherlosev** [comment]
We cannot override `postMessage` in IE11.
So, MethodCallInstrumentation will contain only code for `postMessage`.
Code for another methods will move to appropriate sandboxes.
