### ISSUE TITLE
JavaScript errors when task.js contains special sequences

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#389]
There are sequences starting with `$` sign, that  have a special meaning and can be used in second argument of [String.prototype.replace](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/replace#Specifying_a_string_as_a_parameter), and will transform output of replace. So according to code in [/src/client/sandbox/iframe.js](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/iframe.js#L125) if ```taskScriptTemplate``` has a such sequence, it will be corrupted.

Tip: A function can be used as a second argument to avoid this behavior:
```js
.replace('{{{iframeTaskScriptTemplate}}}', () => JSON.stringify(taskScriptTemplate));
```

**Comment by churkin** [comment]
I'm working on this
