### ISSUE TITLE
Exception on server if an empty file input was inserted with 'appendChild'

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#395]
When a file input is inserted with `appendChild`, it [calls](https://github.com/DevExpress/testcafe-hammerhead/blob/e65bec4bb58a23006d3328a749301531b3f1d90a/src/client/sandbox/node/element.js#L234) `_onElementAdded` and it [calls](https://github.com/DevExpress/testcafe-hammerhead/blob/e65bec4bb58a23006d3328a749301531b3f1d90a/src/client/sandbox/node/element.js#L357) `addFileInputInfo`. Latter [calls](https://github.com/DevExpress/testcafe-hammerhead/blob/e65bec4bb58a23006d3328a749301531b3f1d90a/src/client/sandbox/node/element.js#L386) `infoManager.getFiles` for the input, and `getFiles` [returns](https://github.com/DevExpress/testcafe-hammerhead/blob/a1020bb8c4267a290d8f4564e8f72c9b488269b0/src/client/sandbox/upload/info-manager.js#L165) an empty `FileListWrapper`.

Empty FileListWrapper turns into empty `files` array on server side [here](https://github.com/DevExpress/testcafe-hammerhead/blob/8cdb7417a2a867d15263eb8be1f0a488277a0534/src/upload/form-data-entry.js#L35), that causes an exception `TypeError: Cannot read property 'name' of undefined` on a next statement.

**Comment by LavrovArtem** [comment]
I'm working on this
