### ISSUE TITLE
Node.replaceChild doesn't handle file input elements

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#399]
You can request upload for a file input, and the replace  it with another input with help of [Node.replaceChild](https://developer.mozilla.org/ru/docs/Web/API/Node.replaceChild) before submitting. In that case a value of the second input must be submitted, but hammerhead submits file selected in the first input. So we need to override replaceChild for file inputs just the way we are overriding Node.appendChild and Node.removeChild.

**Comment by miherlosev** [comment]
Already overriden - https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L254

**Comment by AndreyBelym** [comment]
Title and description updated.

**Comment by miherlosev** [comment]
I am working on this
