### ISSUE TITLE
Unstable message sandbox test

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#410]
`sandbox/event/message-test.js`, `timeout` test.

See #404

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Test code:
```javascript
asyncTest('timeout', function () {
    console.log('test message');
    var iframe               = document.createElement('iframe');
    var timeoutExceededError = false;
    var storedDelay          = messageSandbox.PING_IFRAME_TIMEOUT;
    var timeout              = 100;

    messageSandbox.PING_IFRAME_TIMEOUT = 5;

    iframe.src = 'http://cross.domain.com/';

    messageSandbox.pingIframe(iframe, 'pingCmd')
        .then(function (timeoutExceeded) {
            timeoutExceededError = timeoutExceeded;
        });

    window.setTimeout(function () {
        ok(timeoutExceededError, 'timeoutExceededError');
        iframe.parentNode.removeChild(iframe);

        messageSandbox.PING_IFRAME_TIMEOUT = storedDelay;

        start();
    }, timeout);

    document.body.appendChild(iframe);
});
```

Problem in `document.body.appendChild(iframe);`.
Sometimes for iOS emulator this operation have take a long time (150, 200 and even 250 ms).

If `messageSandbox.pingIframe` can be used for non-added to DOM iframe then we will increase timeout.
If not, then I will move `document.body.appendChild(iframe);` before `window.setTimeout`.
@AlexanderMoskovkin

**Comment by churkin** [comment]
@miherlosev make a conditional waiting

**Comment by AlexanderMoskovkin** [comment]
> If messageSandbox.pingIframe can be used for non-added to DOM iframe 

It can be. But I agree with @churkin , maybe we should wait while the iframe is in dom and the try to ping it?

**Comment by AlexanderMoskovkin** [comment]
Let's split the test to two scenarios:
1) Ping an iframe when it is not in the DOM
2) Ping an iframe that is appended to `body`
