### ISSUE TITLE
Call to 'body.appendChild' with 'body' from an another iframe inserts element to wrong 'body'

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#421]
When an iframe is initializing [through IFRAME_DOCUMENT_CREATED_EVENT](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/index.js#L97), a top-level `DocumentSandbox` will be attached to it. So, when you call methods like `iframe.contentDocument.open`, top-level sandboxes will be reattached to the `iframe` on [DOCUMENT_CLEANED_EVENT](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/index.js#L141), including `shadowUI`. So if you try to call  `window.top.document.body.appendChild(child)`,  `child` may be inserted into `iframe.contentDocument.body`, because `child` [will be inserted](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/node/element.js#L229) before parent of `ShadowUI.root` which attached to `iframe`.

**Comment by miherlosev** [comment]
I am working on this

**Comment by miherlosev** [comment]
Open in playground http://demos.devexpress.com/ASPxHtmlEditorDemos/ClientSideAPI/ClientSideCommands.aspx.
Reproduced in FF.
IE11, Chrome - all right.

**Comment by miherlosev** [comment]
Script error is reproduced in IE without hammerhead ([T344908](https://isc.devexpress.com/Thread/WorkplaceDetails/T344908))

**Comment by miherlosev** [comment]
Simple example:
```javascript
test('(GH-421)', function () {
    var iframes                       = [];
    var countIframes                  = 2;
    var createIframes                 = function () {
        for(var i = 0; i < countIframes; i++) {
            var iframe = document.createElement('iframe');

            iframes.push(iframe);
            iframe.id = 'test_GH_i_421_' + i;
            iframe.setAttribute('src', 'javascript:false');
            document.body.appendChild(iframe);
        }
    };
    var performDocumentWriteInIframes = function () {
        for(var i = 0; i < countIframes; i++) {
            var iframe = iframes[i];

            iframe.contentDocument.open();
            iframe.contentDocument.write("<html><head><style></style><title>title</title></head><body></body></html>");
            iframe.contentDocument.close();
        }
    };
    var checkIframes                  = function (){
        for (var i = 0; i < countIframes;i++){
            var iframe = iframes[i];

            ok(!iframe.contentWindow['%hammerhead%'].sandbox.shadowUI.root);
            iframe.parentNode.removeChild(iframe);
        }
    };

    createIframes();
    performDocumentWriteInIframes();

    var container = document.createElement('div');
    document.body.appendChild(container);

    var child = document.createElement('p');

    container.appendChild(child);
    document.body.removeChild(container);

    ok(shadowUI.root);

    checkIframes();
});

```
