### ISSUE TITLE
Hammerhead crashes if client-side code contains document.cookie = null or document.cookie = undefined

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#444]
[T349254](https://isc.devexpress.com/Thread/WorkplaceDetails/T349254)

**Comment by inikulin** [comment]
@churkin we should do `String(val)` before processing, e.g.: https://github.com/tmpvar/jsdom/blob/master/lib/jsdom/living/nodes/Document-impl.js#L694

**Comment by churkin** [comment]
@inikulin  It seems that `null` is exception
