### ISSUE TITLE
DestinationRequest should emit fatal error on ECONNREFUSED

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#446]
Now fatal error is emitted only if requests to a destination emits an ENOTFOUND. But if requested server is down, an another error - ECONNREFUSED - will be emitted. So we should consider ECONNREFUSED a fatal error too.

**Comment by inikulin** [comment]
Is this related to DevExpress/testcafe#367?

**Comment by AndreyBelym** [comment]
Yep, I will add a comment in the `testcafe` issue.
