### ISSUE TITLE
The document.domain property is not processed

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#47]
Consider the following example:

``` html
<!DOCTYPE html>
<!-- url http://subdomain1.domain.com -->
<html>
 <body>
  <iframe src="http://subdomain2.domain.com"></iframe>
  <script>
   document.domain='domain.com';
   document.querySelector('iframe').addEventListener('load', function() {
    this.contentDocument;
   });
  </script>
 </body>
</html>
```

``` html
<!DOCTYPE html>
<!-- url http://subdomain2.domain.com -->
<html>
 <head>
  <script>document.domain='domain.com';</script>
 </head>
</html>
```

If you open the original page at http://subdomain1.domain.com, the browser console remains empty.
If you open the same page through a proxy, the browser console displays the following error:
`Uncaught SecurityError: Failed to read the 'contentDocument' property from 'HTMLIFrameElement': Blocked a frame with origin "http://localhost:1401" from accessing a frame with origin "http://localhost:1402". Protocols, domains, and ports must match.`

[Link to the specification](http://www.w3.org/TR/html5/browsers.html#relaxing-the-same-origin-restriction)

**Comment by inikulin** [comment]
**Important**: It should work for webstorages as well
