### ISSUE TITLE
The client code gets access to the Hammerhead script

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#479]
Client code:

```javascript 
div.innerHTML = '<html></html>';
```

After that `div.childNodes` contains hammerhead service script.

See https://isc.devexpress.com/Thread/WorkplaceDetails/T352264

**Comment by inikulin** [comment]
This is weird and not per spec. Is this browser specific?

**Comment by churkin** [comment]
This expression

```javascript
var div = document.createElement('div'); 
div.innerHTML = '<html><body><div id="test"></div></body></html>'; 
div.childNodes
```

must return `[<div id="test"></div>]`

But the Hammerhead adds our script `[<div id="test"></div>, <script style="hammerhead"></script>]`

**Comment by churkin** [comment]
In all browsers

**Comment by inikulin** [comment]
@churkin I see now, thanks
