### ISSUE TITLE
'uuid' generates the same id for different sessions sometimes 

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#484]
Our TestCafe functional tests sometimes fail with a strange error (rarely but regularly). @georgiy-abbasov have found it happens because `hammerhead` sets identical ids for different sessions [here](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/session/index.js#L32) ([proof](http://screencast.com/t/GlTNsseXCRF))

We should do something with this. We can just add some symbols to session id or use some more specific logic
/cc @inikulin @churkin @georgiy-abbasov

**Comment by AlexanderMoskovkin** [comment]
https://github.com/broofa/node-uuid/issues/117 Looks as the same

**Comment by inikulin** [comment]
Just use https://github.com/dylang/shortid

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov please take this
