### ISSUE TITLE
We need sandbox for the fetch API

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#498]
[Fetch](https://fetch.spec.whatwg.org/) is a modern replacement for the XHR. It's already implemented in Chrome and FF and polyfill exists. So seems like it's start to appear in the wild: https://testcafe-hhhm.devexpress.com/history?timestamp=1458801307399&siteUrl=http://www.flipkart.com/

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
- [ ] proxy fetch requests (cors, basic, opaque)
- [ ] create fetch barrier (testcafe part)

**Comment by miherlosev** [comment]
Waiting for #545 , #546

**Comment by miherlosev** [comment]
then we need to write fetch barrier (testcafe part)

**Comment by miherlosev** [comment]
FetchBarrier was completed - https://github.com/DevExpress/testcafe/pull/570
