### ISSUE TITLE
Use native Promise on server and client sides (if it's possible)

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#502]
On client side: only IE has not `Promise` support.
On server side: only node v 0.10 has not `Promise` support.

**Comment by inikulin** [comment]
Nope. On client it can be overriden, so we need isolated impl

**Comment by miherlosev** [comment]
> Nope. On client it can be overriden, so we need isolated impl

We will use a native browser implementation.

Pseudo code
```javascript
savePromiseToNativeMethods();

if (hasPromiseInNativeMethods())
     usePromiseFromNativeMethods();   
```

**Comment by inikulin** [comment]
Native browser implementation behavior can be adjusted. We can't rely on it. Btw what the point to switch to native impl?

**Comment by miherlosev** [comment]
> Native browser implementation behavior can be adjusted. We can't rely on it
Please, provide examples.

Btw what the point to switch to native impl?
Perfomance optiomization.

**Comment by miherlosev** [comment]
V8 promises implementation is written in JavaScript.
We will not obtain perfomance boost if it will use on server side.
http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird#answer-279003.
