### ISSUE TITLE
Override form.submit and expose 'BEFORE_SUBMIT' event

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#504]
see https://github.com/DevExpress/testcafe/pull/405#discussion-diff-57678009

**Comment by AlexanderMoskovkin** [comment]
Just a reminder for me: use this event in [`testcafe.pageUnloadBarrier`](https://github.com/DevExpress/testcafe/pull/405/files/d4ff8c02e71de1dc376b30ff34ad1241a6eae3f8#diff-6615c0ea3b8b4c303df96bf8852148c5R30) when it's published

**Comment by churkin** [comment]
I'm working on this

**Comment by inikulin** [comment]
Does it fire when `<input type="submit">` clicked?

**Comment by inikulin** [comment]
Same question regarding `formSubmit` in which we put cookies in form.
