### ISSUE TITLE
Shadow UI improvement

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#522]
Since now we will not use any complicated interface and we don't need `<table>`, `<ul>` etc. Maybe we should use custom elements for the shadowUI? Our custom elements will have prefix like `<hammerhead-shadow-div>`. Benefits:
- tag-level CSS rulest on page will not affect our tags (except `*`), this will reduce number of UI bugs
- is shadow element lookup will take linear time (https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/dom.js#L469) since we need to check for the classname of the current element, without necessity to traverse up to the parent.
  \cc @churkin @AlexanderMoskovkin

**Comment by churkin** [comment]
I think we can try, at first glance do not see any problems

**Comment by AlexanderMoskovkin** [comment]
It this works in all supported browsers? As I see at [caniuse](http://caniuse.com/#feat=custom-elements) there are problems with this

**Comment by inikulin** [comment]
@AlexanderMoskovkin There is a little confusion here: caniuse shows information about this feature: http://www.html5rocks.com/en/tutorials/webcomponents/customelements/. I mean we can just use custom tag names - they will be parsed just fine by all browsers

**Comment by AlexanderMoskovkin** [comment]
get it. We can try

**Comment by miherlosev** [comment]
>Benefits:
>- tag-level CSS rulest on page will not affect our tags (except `*`), this will reduce number of UI bugs
>- is shadow element lookup will take linear time

We can add custom tags only for `body`'s shadow ui part. For `head`'s part we need a shadow ui link and script tags. 
We don't have a lot  of UI bugs with `body`'s and it is easy to fix. 
Now, shadow element look take a linear time:
```js
export function isShadowUIElement (element) {
    return !!element[INTERNAL_PROPS.shadowUIElement];
}
```
Using custom tags for `body` will not simplify the shadow ui sandbox. 
On the contrary, it will complicate it - we need a two part of overridden methods for `body` and `head`.
