### ISSUE TITLE
Hammerhead initialization fails in IE after document.write

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#525]
A `cannot execute code from freed script` exception is raised when evaluating task script in iframe, after `document.write` was called. Also bad thing is that the error is silently swallowed, because it is thrown on [RUN_TASK_SCRIPT event](https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/iframe.js#L94), and event emitter just ignores `freed script` errors (https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/event-emitter.js#L23). 

When `document.write` is called, `hammerhead` reattaches existing sandbox, including ShadowUI. When ShadowUI attaches to DOM, it replace some methods in HTMLBodyElement and HeadHTMLElement prototypes. After that iframe is initialized through `_raiseReadyToInitEvent`, and evaluate task script. When it does that, it calls UrlResolver.updateBase, that uses `document.head.getElementsByTagName` method(https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/utils/url-resolver.js#L61), previously overriden by ShadowUI at `document.write`. So it raises a `freed script` error here.

**Comment by churkin** [comment]
I'm working on this

**Comment by AndreyBelym** [comment]
Test page:
```html
<html>
	<head>
		<title>Test iframe</title>
	</head>
	<body>
	    <form action="iframe.html" target="iframe">
                <input type="submit" />
            </form>
            <iframe name="iframe">
            </iframe>
            <script type="text/javascript">
                var button = document.getElementsByTagName('input')[0];
            
                button.addEventListener('click', function () {
                    window.top.test = 1;
                });
            
                var iframe = document.getElementsByTagName('iframe')[0];
            
                iframe.addEventListener('load', function () {
                    if (window.top.test) {
                        window.top.test = false;
                        
                        setTimeout( function () {
                            iframe.contentDocument.write('');
                            iframe.contentDocument.close();
                        }, 0);
                    }
                });
            </script>
	</body>
</html>
```
Content of `iframe.html` doesn't matter, it may be even not HTML, just a plain text. Start `playground` and load the page. Click on submit button, and two 'freed script' errors will be raised.
