### ISSUE TITLE
Try to get rid CodeInstrumentation for properties using Object.defineProperty

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#528]
see example (from browser console):
```javascript
> document.activeElement
<- <body>​…​</body>​
> Object.defineProperty(HTMLDocument.prototype, "activeElement", {
    get: function () {
        return 'overriden';
    }
});
<- Document {}
> document.activeElement
<- "overriden"
```

**Comment by inikulin** [comment]
It will throw security exceptions in Safari. That's why we've switched to instrumentation at some point of the time.

**Comment by miherlosev** [comment]
I tried on Safari 8.0.7 - all works good.

**Comment by inikulin** [comment]
Interesting. It would be nice then

**Comment by miherlosev** [comment]
I'm working on this

**Comment by churkin** [comment]
@miherlosev This is not a primary goal

**Comment by miherlosev** [comment]
Results of investigation:
We cannot override `length` property because we cannot get origin property value after overriding.
If we override prototype properties then we can not using it in hammerhead. 
It is very bad - we cannot use inside hammerhead `firstChild, `lastChild`, `href`, `innerHtml` etc.
Overriding of the `document` and `window` properties (`activeElement`, `documentURI` etc) is not produce perfomance boost.

After discussing with @churkin we decide to close issue
