### ISSUE TITLE
Split browserUtils.isIE to browserUtils.isIE and browserUtils.isMSEdge

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#532]
In `browserUtils` we have the following code:
```javascript
export var isIE = browser.name === 'msie' || isIE11 || isMSEdge;
```
It is wrong - MSEdge is not IE. MSEdge has a different rendering and script engines and a lot of different things.
So we need to split `browserUtils.isIE` to `browserUtils.isIE` and` browserUtils.isMSEdge`.

This condition is used in many places in `hammerhead` and `testcafe`. So we should decide it together.
@DevExpress/testcafe

**Comment by helen-dikareva** [comment]
I agree that Edge is brower with different engines  and we have checks like this in code `isIE && !MSEdge` but checks just `isIE` three times more so that in most cases IE and MSEdge behave the same. I think we can still return true for `isIE` check for MSEdge.

**Comment by inikulin** [comment]
> MSEdge has a different rendering and script engines and a lot of different things.

AFAIK they have different versions of same engines. Is it really bites us somehow at the moment?

**Comment by miherlosev** [comment]
> Is it really bites us somehow at the moment?

It is not big problem now.
It needs for more redable code. There are few places where it was good.
For example:
https://github.com/DevExpress/testcafe-hammerhead/blob/bb022853b2a9ab1008749289d8645ca65239af03/src/client/sandbox/event/focus-blur.js#L75
https://github.com/DevExpress/testcafe-hammerhead/blob/14b6919504b49f9320c0a6f2d6695385826b628a/src/client/sandbox/timers.js#L23
https://github.com/DevExpress/testcafe-hammerhead/blob/bf77d7f886c0ab424806df211928f13bf9259997/src/client/sandbox/event/selection.js#L61

**Comment by churkin** [comment]
@miherlosev Where the condition right now is 
`if(isIE) { .... }`
will you replace by `if (isIE && MSEdge)` or by `if (isIE && !MSEdge)`? :)

I'm afraid we'll get a lot of problems later.

**Comment by miherlosev** [comment]
I agree with you.
