### ISSUE TITLE
Wrong task script injected in iframe HTML

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#534]
A regular `task.js` instead of `iframe-task.js` is injected into iframe page, when using a `form` with `target` attribute that is initially empty, but is later specified through JS.

Example:
Test page:
```html
<html>
	<head>
		<title>Test iframe</title>
	</head>
	<body>
	    <form action="iframe.html">
                <input type="submit" />
            </form>
            <iframe name="iframe">
            </iframe>
            <script type="text/javascript">
                var form    = document.getElementsByTagName('form')[0];
                var button = document.getElementsByTagName('input')[0];
            
                button.addEventListener('click', function () {
                    form.target = 'iframe';
                });            

            </script>
	</body>
</html>
```
Content of `iframe.html` doesn't matter, it may be even not HTML, just a plain text. Start `playground` and load the page. Click on submit button, and check the head of iframe's document. It will contain `<script ... src="task.js">` instead of `<script ... src="iframe_task.js">`.

**Comment by churkin** [comment]
I'm working on this
