### ISSUE TITLE
Cleanup stylesheets from hammerhead comment

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#539]
When you get a stylesheet HTML through `innerHTML`/`outerHTML`, there will be `/* stylesheet processed via hammerhead */` comment.

**Comment by LavrovArtem** [comment]
[This](https://github.com/DevExpress/testcafe-hammerhead/pull/480) PR fix it.
https://github.com/DevExpress/testcafe-hammerhead/pull/480/files#diff-0ed82418a198c24aacd8e3e42d4d5566R42

**Comment by LavrovArtem** [comment]
Fix in #480 PR
