### ISSUE TITLE
We should remove our xhr headers before sending request

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#552]
Before sending xhr request to the destination server we should remove our custom headers (`x-hammerhead|xhr|request-marker-header`, `x-hammerhead|xhr|cors-supported-header`, etc).

**Comment by miherlosev** [comment]
I'm working on this

**Comment by inikulin** [comment]
We already remove request marker: https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/request-pipeline/header-transforms.js#L18

AFAIK CORS flag was part of marker header, since it was set via binary flags. But then we moved to separate header we forgot to add it to the filter
