### ISSUE TITLE
Remove qunit test 'barrier - Skip TestCafeClient requests'

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#577]
from https://github.com/DevExpress/testcafe/blob/master/test/client/fixtures/core/xhr-barrier-test.js

This test is not actual.
Now, service messages are sent using native methods.
And so `xhrBarrier` has not code that filter service messages.

**Comment by inikulin** [comment]
I believe we need to keep it to avoid possible regression when service requests can get into barrier.

**Comment by AlexanderMoskovkin** [comment]
Test is useless now, at least we should decrease the [timeout](https://github.com/DevExpress/testcafe/blob/master/test/client/fixtures/core/xhr-barrier-test.js#L98) in the test because xhr-barrier has his own timeout (3ms). 
I'll investiage this test deeply

**Comment by miherlosev** [comment]
Move issue to testcafe repository - https://github.com/DevExpress/testcafe/issues/533
