### ISSUE TITLE
Publish validation errors

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#588]
![untitled](https://cloud.githubusercontent.com/assets/4133518/15350191/7c5db6a8-1ce0-11e6-9aaa-4c288297af30.png)

**Comment by miherlosev** [comment]
Waiting for https://github.com/inikulin/publish-please/issues/30

**Comment by inikulin** [comment]
It's not related to #30. Also, we need to upgrade to `publish-please` 2.0. It has `ignore` option for sensitive data audit. I suggest to delete `.publishrc` and gulp `publish` task and install v2 as described in README.

**Comment by inikulin** [comment]
Also, setup `git bash` or `cmder` with full runtime and run it from where, to avoid `sed`-related problem
