### ISSUE TITLE
Resource http://w.uptolike.com/widgets/v1/widgetsModule.js?v=a5312ff27600864378d92e743a16cd02 is not processed

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#591]
see https://testcafe-hhhm.devexpress.com/history?timestamp=1463511795638&siteUrl=http://elementy.ru.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
This code is not processed:
```javascript
    function e() {
        console.log('executed');
    }
    /true/i.test('true') ? e() : window.postMessage('data', '*');
```
If I replace reqular expression on `true` string then all works right.

**Comment by churkin** [comment]
`function a(){function b(){}/k/;}`

**Comment by inikulin** [comment]
@churkin Acorn bug?

**Comment by inikulin** [comment]
Works just fine with [Babylon](https://github.com/babel/babylon). Maybe it's make sense to swtich to it? Note that it uses flow types syntax, so it makes sense to add their `.babelrc` and missing plugins to our build.

**Comment by churkin** [comment]
I could not reproduce the problem at the pure acorn v3.1.0. It looks like hammerhead acorn version does not match the real v3.1.0. @LavrovArtem

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
I created issue on acorn https://github.com/ternjs/acorn/issues/416.

**Comment by LavrovArtem** [comment]
I removed the http://elementy.ru site from Health Monitor, after fixing this issue it needs to return it back.

**Comment by inikulin** [comment]
> I removed the http://elementy.ru site from Health Monitor, after fixing this issue it needs to return it back.

Why? We have an issue and it's not fixed. Why hide it?

**Comment by inikulin** [comment]
Also, I still vote for switching to Babylon: e.g. acorn doesn't have support for `async` functions, but both Edge and IE landed support in their dev versions. So we will see them in the wild soon.

**Comment by inikulin** [comment]
\cc @churkin @LavrovArtem

**Comment by LavrovArtem** [comment]
Are there any speed tests acorn and babylon?

**Comment by inikulin** [comment]
Babylon is basically a fork of acorn.

**Comment by churkin** [comment]
@LavrovArtem let's try
