### ISSUE TITLE
Uncaught Error: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-hammerhead#595]
On page:
http://js.devexpress.com/Demos/WidgetsGallery/#demo/data_grid-paging_and_scrolling-record_paging

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Dublicate of https://github.com/DevExpress/testcafe-hammerhead/issues/571
