### ISSUE TITLE
Web Platform Test: Hung on http://w3c-test.org/dom/events/Event-dispatch-redispatch.html

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#604]

**Comment by miherlosev** [comment]
I'm working on this

**Comment by inikulin** [comment]
Is this a regression?

**Comment by miherlosev** [comment]
Yes, it is. On hammerhead 7.0 all works good.

**Comment by inikulin** [comment]
Why HHM doesn't show it then?

**Comment by miherlosev** [comment]
Problem is performed becasue page has `meta` tag with wrong encoding attribute value:
```javascript
<meta charset=urf-8>  //Typo. Should be 'utf-8'
```

**Comment by miherlosev** [comment]
Regression after https://github.com/DevExpress/testcafe-hammerhead/pull/555

**Comment by miherlosev** [comment]
Browser ignore `meta` with wrong encoding name. We wil do same.
