### ISSUE TITLE
Hammerhead doesn't process 'svg' element and it child nodes.

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#614]
It's reproduced in the playground:

1) open next page in the playground.
```html
<!DOCTYPE html>
<html>
<body>
<h1>SVG example</h1>
<svg width="100" height="100">
  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
</body>
</html> 
```
2) evaluate next expressions in the console:
`document.getElementsByTagName('h1')[0].dispatchEvent.toString() //returns overriden function` 
`document.getElementsByTagName('svg')[0].dispatchEvent.toString() //returns original function` 
`document.getElementsByTagName('circle')[0].dispatchEvent.toString() //returns original function`

**Comment by miherlosev** [comment]
I'm working on this
