### ISSUE TITLE
"Uncaught ReferenceError: $ is not defined" on mercadolibre.com.ar

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#617]
This error occurs on every second page load only in Crome.

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
jQuery loads via a cross-domain xhr that fails on every other page load. At the first load, xhr responds with 200 status code and with the `Access-Control-Allow-Origin:*` header. At the second load, xhr responds with 304 status code and without an `Access-Control-Allow-Origin` header. In the second case, we check `sameOriginPolicy` and send the `same origin failed` status code. I think that we shouldn't check `sameOriginPolicy` for xhrs with 304 status code. /cc @churkin @inikulin

**Comment by LavrovArtem** [comment]
1) Without errors 2) I'm searching

**Comment by inikulin** [comment]
@LavrovArtem I'd like to see what spec proposes

**Comment by LavrovArtem** [comment]
[Caching in HTTP](https://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html)
[Cross-Origin Resource Sharing](https://www.w3.org/TR/cors/)
[XMLHttpRequest](https://xhr.spec.whatwg.org/)

**Comment by inikulin** [comment]
@LavrovArtem Can you show what exactly spec suggests?

**Comment by LavrovArtem** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5

> If the client has performed a conditional GET request and **access is allowed**, but the document has not been modified, the server SHOULD respond with this status code.
> Otherwise (i.e., the conditional GET used a weak validator), the response MUST NOT include other entity-headers; this prevents inconsistencies between cached entity-bodies and updated headers.

The `Access-Control-Allow-Origin: *` header is caching at the first load, and if resource is "not modified" its header is restoring from the cach at the second load.
