### ISSUE TITLE
Code instrumentation window properties should be defined as non-enumerable and non-configurable

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#621]
Properties like https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/code-instrumentation/index.js#L38 should be defined this way https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/index.js#L166

I wonder if there will be any negative performance impact.

**Comment by miherlosev** [comment]
I'm working on this.

**Comment by miherlosev** [comment]
Also we should mark all hammerhead specific window properties as non-enumerable, non-configurable and non-writable.
For example:
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/backup.js#L11
https://github.com/DevExpress/testcafe-hammerhead/blob/master/src/client/sandbox/iframe.js#L84
etc.
