### ISSUE TITLE
The col tag is incorrectly wrapped in the processHtml function

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#625]
Before the HTML is processed, the self-closing `col` tag is wrapped as follows:
`<col/> -> <fake_tag_name_col/>`
But `fake_tag_name_col` is not self-closing, so that the markup gets broken in IE.

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by georgiy-abbasov** [comment]
Adding to the previous comment: it's reproduced in the playground on https://demos.devexpress.com/MVCxPivotGridDemos/SampleReports/SampleReports, so it affects ASP tests.
