### ISSUE TITLE
Multiple errors for document.write tests

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#632]
Steps to reproduce:
1)Open https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/fixtures/sandbox/node/document-write-test.js
2)After each `write` or `writeln` statement one setup the comparison the native document write result and our write result. See code snippet below:
```javascript
function getDocumentOuterHtml (iframe) {
    return iframe.contentDocument.documentElement.outerHTML;
}

function checkWriteResults () {
    strictEqual(getDocumentOuterHtml(iframeForWrite), getDocumentOuterHtml(iframeForNativeWrite));
}

test('write script', function () {
      write('<script>');
      checkWriteResults();

      write('var x = 5;');
      checkWriteResults();

//etc. Perform this for all write and writeln calls in all tests
});
```
3)You will get a lot of assertion errors.

**Comment by LavrovArtem** [comment]
I'm working on this
