### ISSUE TITLE
Uncaught RangeError: "Maximum call stack size exceed" on http://www.walmart.com/ (in playground)

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#637]
As result, page is infinitely loading
http://screencast.com/t/6UPSXmAiX

**Comment by miherlosev** [comment]
Script error `cdn-test.min.js:1 Uncaught SyntaxError: Unexpected token <<` presents on `walmart.com` without hammerhead.
But `hammerhead` should not fail with `Uncaugth error: Maximum call stack size exceed`.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by churkin** [comment]
#358 regression

`_ensureIframeNativeMethodsForChrome` twice wraps `document.createElement`

**Comment by miherlosev** [comment]
Don't reproduced
