### ISSUE TITLE
Location assignment doesn't work

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#640]
Run in playground:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input type="button" id="btn">

<script>
    document.querySelector('#btn').addEventListener('click', function () {
        location = 'https://google.com';
    });
</script>
</body>
</html>
```

Clicking `btn` doesn't change location. I'm surprised we didn't encountered it yet. Also, it's worth checking other properties that instrumented the way location does. BTW, replacing `location` with `document.location` or `window.location` works just fine.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
If `location` object passed as a function argument then redirect don't perfom.
