### ISSUE TITLE
The wrong processing of destructuring

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#642]
If `location` declared inside function or passed as function parameter we should not process it.
It needs for fix https://github.com/DevExpress/testcafe-hammerhead/issues/640#issuecomment-228679853

**Update!** The origin issue was transfered to https://github.com/DevExpress/testcafe-hammerhead/issues/2283

**Comment by miherlosev** [comment]
I'm working on this

**Comment by iJigg** [comment]
This is being an issue for me right now.
Unfortunately I am not able to change the code below and this i blocking me from testing altogether.

```
renderThing({ history, location }) { ... }
```

get's transpiled into 

```
renderThing({ history:history,location: __get$Loc(location) }) {  }
```

which throws `Uncaught SyntaxError: Invalid destructuring assignment target`

Any ETA on when this can be solved?

**Comment by Farfurix** [comment]
@iJigg 

Hello,

Thank you for your example. We have plans to fix it. However, I cannot give you any precise time frames.

**Comment by silberjan** [comment]
@Farfurix this bug is making testcafe practically unusable for us right now. Is there any workaround until you fixed it?

**Comment by silberjan** [comment]
Okay i just found out myself.
Renaming the location param to anything else fixes the problem. I guess hammerhead always assumes `location` is `window.location`, which it is not for us.

**Comment by Farfurix** [comment]
@silberjan

Hello,

Yes, `testcafe-hammerhead` has special logic for the `location` object. Thank you for sharing your workaround. It can help other users work around the issue (when they are able to rename such objects in their projects).

We have plans to fix this issue. However, I cannot give you any estimates at the moment. Stay tuned for our updates here.

**Comment by LavrovArtem** [comment]
We need to transform the destructuring to fix this issue. This is a complex task. Here is how babel accomplishes it: [https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-destructuring/src/index.js](https://github.com/babel/babel/blob/master/packages/babel-plugin-transform-destructuring/src/index.js)

**Comment by rcambrj** [comment]
For anything in `node_modules` which causes this problem (for example [react-hook-form](https://github.com/react-hook-form/react-hook-form/issues/1003) ) a temporary solution is to have webpack+babel transpile that particular module:

webpack.config.js
```
{
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: [/node_modules\/(?!(react-hook-form)\/).*/],
        use: [
          {
            loader: require.resolve('babel-loader'),
          },
        ],
      },
    },
  },
};
```

be sure to use `babel.config.js` (not `.babelrc`), because [babel is weird](https://github.com/webpack/webpack/issues/2031#issuecomment-479451346)

**Comment by miherlosev** [comment]
One more case:
`[rand[i], rand[j]] = [rand[j], rand[i]];`
transformed to
`[$__get(rand, i), $__get(rand, j)] = [$__get(rand, j), $__get(rand, j)];`
which results into syntax error.

**Comment by Kryshtopenko** [comment]
There are no any stubs? Still can't navigate to my local web application.

**Comment by AlexKamaev** [comment]
Did you try to use the workaround suggested by @silberjan in the following [comment](https://github.com/DevExpress/testcafe-hammerhead/issues/642#issuecomment-570603800)?

**Comment by Kryshtopenko** [comment]
Workaround.

1. **Install** **next** **dependencies** to your **project**:
`npm i -D @babel/core @babel/plugin-transform-runtime @babel/preset-env`

2. **Add**
`      {
        test: /\.(js)$/,
        exclude: [/node_modules\/(?!(react-hook-form)\/).*/],
        use: [
          {
            loader: "babel-loader"
          }
        ]
      },`
as **rule** to your **webpack.common.ts**.

3. **Create** _babel.config.json_
`{
  "presets": [
    [
      "@babel/preset-env",
      {
        "modules": "commonjs"
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-transform-runtime"
    ]
  ]
}`

Enjoy.

**Comment by ajspott** [comment]
Another example occurs with Angular 9 + ngx-pipes within the ShufflePipe class

This: `[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];`

Becomes this: `  [ __get$(shuffled,i),  __get$(shuffled,j)] = [ __get$(shuffled,j),  __get$(shuffled,i)];`
