### ISSUE TITLE
Sign in to the TravisCI via playground doesn't work

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#651]

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
There is the following code from https://travis-ci.org/ :
```javascript
var img      = document.createElement('img');
  img.src      = "https://third-party-cookies.herokuapp.com/set";
  img.onload   = function() {
    var script = document.createElement('script');
    script.src = "https://third-party-cookies.herokuapp.com/check";
    window.document.body.appendChild(script);
  }
```
Request to "https://third-party-cookies.herokuapp.com/set" is used to set up `cookie`.
![Console](https://cloud.githubusercontent.com/assets/4133518/16651547/516c8bec-444d-11e6-8aaf-c1d3c3cb3dc4.png)

As we don't proxy an `img` src attribute value, the request doesn't go through proxy, so the proxy server doesn't know that `cookie` has been set.
If we will proxy images, this will cause degradation of proxy performance.
The new setting 'proxy images: <true|false>' is a bad variant.
What will we do in this case?

**Comment by inikulin** [comment]
@churkin 
> What will we do in this case?

If `img` has `onload` hander - take it through proxy. I believe we can even do it only for dynamically created images.

**Comment by churkin** [comment]
@inikulin in this case, a src is setted before the load handler assigned

**Comment by miherlosev** [comment]
There is an another idea: if url for `src` has not extention we should create proxy url and direct request through proxy.
What do you think?

**Comment by inikulin** [comment]
> There is an another idea: if url for src has not extention we should create proxy url and direct request through proxy.
What do you think?

I think it's not that reliable. Because this thing could be done with extension. E.g. 1-pixel images often used for tracking.

**Comment by miherlosev** [comment]
Final decision:
If `img` has load handler (img.onload, img.addEventListener, img.attachEvent) then we should create proxy url for `src` attribute value.

**Comment by georgiy-abbasov** [comment]
Looks like the issue is actual now:
http://screencast.com/t/ctm7I5jUtqt

**Comment by inikulin** [comment]
I confirm, it doesn't work. \cc @miherlosev

**Comment by miherlosev** [comment]
I looked it. It is a problem in new place.
I will investigate it more deeply.

**Comment by inikulin** [comment]
@miherlosev I guess it's worth to fill a new issue and close this one, then.

**Comment by miherlosev** [comment]
Ok. I will do this later.

**Comment by inikulin** [comment]
Why later?

**Comment by LavrovArtem** [comment]
Cann't reproduce on the latest commit b4a4447 in hammerhead playground.
