### ISSUE TITLE
Very slow proxing for http://www.answers.com

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#657]
see https://testcafe-hhhm.devexpress.com/history?timestamp=1467659469614&siteUrl=http://www.answers.com/.
It happens because we cyclically send `set-cookie` service message. (see video - http://screencast.com/t/vBYd5NfW3j).
Need to investigate why we do this.

**Comment by miherlosev** [comment]
Same behaviour - `http://www.usatoday.com/`

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Same for https://www.usps.com/.
Sometimes, this site hungs.
See https://testcafe-hhhm.devexpress.com/history?timestamp=1471374341665&siteUrl=https://www.usps.com/

**Comment by miherlosev** [comment]
Same for http://www.wikia.com/Wikia

**Comment by LavrovArtem** [comment]
Fixed in https://github.com/DevExpress/testcafe-hammerhead/pull/1128
