### ISSUE TITLE
Script error for https://www.getresponse.ru/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#659]
see https://testcafe-hhhm.devexpress.com/history?timestamp=1467659469614&siteUrl=http://www.getresponse.ru/

Reproduced in playground.

**Comment by churkin** [comment]
I'm working on it

**Comment by churkin** [comment]
Сookie validation problem:

`"param=value; domain=.ru"` must not be valid for the `www.getresponse.ru`

**Comment by churkin** [comment]
@inikulin  We need to client version of the `tough-cookie` to take into account public suffix list.

**Comment by LavrovArtem** [comment]
This issue is part of #1137

**Comment by miherlosev** [comment]
Close in favor https://github.com/DevExpress/testcafe-hammerhead/issues/1787
