### ISSUE TITLE
'Access-Control-Allow-Origin' header is removed from destination response

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#661]
![untitled](https://cloud.githubusercontent.com/assets/4133518/16613577/6fd6749a-4375-11e6-8498-5ca4505797bf.png)

**Comment by brettveenstra** [comment]
Can confirm this still is a problem... could be root of DevExpress/testcafe#1421 as our authentication strategy relies on CORS

**Comment by miherlosev** [comment]
We perform CORS checks on our side, so we skip this header.
