### ISSUE TITLE
Raise an event when the page is really going to be unloaded

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#667]
Now hammerhead raises the `beforeUnload` event when the document raises it. But sometimes the page is not unloaded after this. For example:

1)

``` js
// we are on the page http://example.com/abc
window.location = 'http://some-other-page.com'; // -> raises the beforeUnload event
window.setTimeout(() => { 
    window.location = 'http://example.com/abc#123'; // -> cancel the page redirect but the beforeUnload event is raised already.
}, 200);
```

2) When we click on the link and it leads to file downloading, `beforeUnload` is raised too, but the page is not unloaded.

**Comment by churkin** [comment]
There are several ways to 'reload'/'load new' page:

- [ ]  Change `location` object:

  - `location.href = ...`
  - `location = ...`
  -  `window.location/document.location = ...`
  - `location.assing(...)`
  - `location.replace(...)`
  - `location.reload(...)`
  - `location.port = ...`
  - `location.host = ...`
  - `location.hostname = ...`
  - `location.pathname = ...`
  - `location.protocol = ...`
  - `location.search = ...`

  It is worth remembering that the `hash` change does not lead to page reloading, `location.reload` method reloads the page without changing the `location` value.

- [ ]  Clicking on the link.
  We must remember that the `target` attribute can point to another window.

- [ ]  Form sabmition.
  We must remember that the `target` attribute can point to another window.

- [ ]  It is necessary to take into account the behavior of the combination of different methods of redirection, sync or async (by the timeout).

**Comment by LavrovArtem** [comment]
Another way to reload the page after a specified number of seconds:
```html
<meta http-equiv="refresh" content="seconds;URL-to-redirect">
```

**Comment by churkin** [comment]
@LavrovArtem Good remark

**Comment by inikulin** [comment]
BTW, we don't need to know that page will really be unloaded, we just need to signal possibility of unloading (we can enable waiting heuristic then and wait for unload). JFYI, maybe it will simplify things for you somehow.

**Comment by churkin** [comment]
is no longer actual
