### ISSUE TITLE
Try to use browser benchmark for hammerhead testing

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#676]
There are many browser benchmarks:
acid3 - http://acid3.acidtests.org/
html5test - http://html5test.com
base mark - http://web.basemark.com
V8 Benchmark Suite - http://www.netchain.com/Tools/v8/

Then I run these benchmarks under playground I getting a lot of different errors (console errors, different scope value, different test result, etc).
Need to do:
1)Fix all errors
2)Add these benchmarks to the health monitor (Benchmarks are single page and very fastly)

**Comment by inikulin** [comment]
> 2)Add these benchmarks to the health monitor (Benchmarks are single page and very fastly)

We should them to CI then, not to health monitor.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Found bugs:
https://github.com/DevExpress/testcafe-hammerhead/issues/679
