### ISSUE TITLE
Wrong processing result for `div.innerHtml=<p><header></header>`

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#688]
Without hammerhead:
`div.innerHTML = "<p><header></header>"`;
`div.innerHTML`
`<p></p><header></header>`

With hammerhead:
`div.innerHTML = "<p><header></header>"`;
`div.innerHTML`
`<p><header></header></p>`

Test code from http://html5test.com
Problem inside `htmlUtils.processHtml`

**Comment by LavrovArtem** [comment]
I'm working on this
