### ISSUE TITLE
Web platform tests integration

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#69]
I think we should run proxied [web platform tests](https://github.com/w3c/web-platform-tests) as an addition to the main test suite. This will definitely will help us reveal problematic areas in the hammerhead.

**Comment by inikulin** [comment]
Docs: http://testthewebforward.org

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
temporary suspended

**Comment by miherlosev** [comment]
Resume

**Comment by miherlosev** [comment]
Implementation

- [ ] continious run
continious run with health monitor
separate web page for results
badge

- [ ] refactoring
init mongo db inside data layer
Promise for async operations
last commitId from environment variable
code simplification, remove unused code
gulp

- [ ] move to github
eslint
config files (editorconfig, gitignore etc)

- [ ] playground for web-platform

- [ ] fix bugs
