### ISSUE TITLE
Add 'generateUniqueId' client function to the test utils

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#696]
see discussion https://github.com/DevExpress/testcafe-hammerhead/pull/694#discussion_r71847685
I think this function should be placed in `qunit-harness`.
@AlexanderMoskovkin

**Comment by AlexanderMoskovkin** [comment]
I don't get how it relates to `qunit-harness`. As I understand - it just some util that generates some unique value. There are a lot of modules for this or create your small custom function (for example in the [before-test.js](https://github.com/DevExpress/testcafe-hammerhead/blob/master/test/client/before-test.js) file.

**Comment by AlexanderMoskovkin** [comment]
in `qunit-harness` we place qunit staff, things that relate to running qunit tests on saucelabs and some complex common utils that is used in `testcafe-hammerhead` and `testcafe` client tests (as the `waitForIframe` function)

**Comment by miherlosev** [comment]
`generateUniqueId` is a common qunit stuff, same as `waitForIframe`.

**Comment by AlexanderMoskovkin** [comment]
you need this only in one `testcafe-hammerhead` test file. Why it's common?
as for me, `'test' + Date.now();` - is quite enough for tests

**Comment by miherlosev** [comment]
Ok
