### ISSUE TITLE
Image slider doesn't load after proxing (http://rutube.ru/)

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#710]
Error from health monitor doesn't reproduce (see https://testcafe-hhhm.devexpress.com/history?timestamp=1470078316293&siteUrl=http://rutube.ru/).

See [video](http://screencast.com/t/PytVgH4K5Ee)

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Site resource `http://rutube.ru/static/js/main.js` doesn't processed on server side.

**Comment by miherlosev** [comment]
Acorn raise exception for the following code:
```javascript
function () {
	var l = function(p1) {
		return p1;
	};
	var o = function (p2) {
		return p2;
	};
	var md5 = function (e) {
		return l(o(e));
	};
}
```

**Comment by inikulin** [comment]
Try to update it to the latest version

**Comment by miherlosev** [comment]
Already in progress

**Comment by miherlosev** [comment]
Reproduced in last `acorn` version - `3.3.0`.
I wrote the https://github.com/ternjs/acorn/issues/445

**Comment by inikulin** [comment]
@miherlosev Can you edit the title for acorn issue and replace it with something more meaningful

**Comment by miherlosev** [comment]
Acorn bug was fixed. Waiting for a new version.
