### ISSUE TITLE
404 errors for xhr request in  https://twitter.com/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#711]
See [video](http://screencast.com/t/2oFUay3HP)

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
For reproduce one need to scroll to the bottom.

**Comment by miherlosev** [comment]
Before proxing site loads contnet from https://video.twimg.com/ext_tw_video/762331094100377602/pu/pl/320x180/Gt65K6I9PG3tShu7.m3u8.
After proxing we loads content from http://localhost:1401/HJndkaHF/https://twitter.com/ext_tw_video/762551750972870656/pu/pl/320x180/HVD56iCVE0WJDAPX.m3u8.

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Twitter client code was changed. 
Now, it does not contains the problem described above.

It has the problem with `XmlHttpRequest.responseURL`.
