### ISSUE TITLE
Script error for https://www.bankofamerica.com/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#767]
see [video](http://screencast.com/t/eWv4cwBXg)

**Comment by miherlosev** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
The error occurs because script sets cookie with length over 76 thousand symbols. This cookie ignoring on the origin site, but we save this cookie in the hh.

If we rewrite the code bellow:
```javascript
(doc, cookie) => this.cookieSandbox.setCookie(doc, String(cookie))
```
with limit:
```javascript
(doc, cookie) => cookie.length > 76e3 ? cookie : this.cookieSandbox.setCookie(doc, String(cookie))
```
then error doesn't occurs.

**Comment by miherlosev** [comment]
https://tools.ietf.org/html/rfc6265#page-27

- At least 4096 bytes per cookie (as measured by the sum of the
      length of the cookie's name, value, and attributes).

-  At least 50 cookies per domain.

 -  At least 3000 cookies total.

**Comment by LavrovArtem** [comment]
@miherlosev But in different browsers this values is different

**Comment by miherlosev** [comment]
Agree with you. 
http://stackoverflow.com/questions/2543851/chrome-cookie-size-limit#answer-12103501
Almost like specification.
I think we can trim cookie value according with specification

**Comment by miherlosev** [comment]
Also you can check it manually using http://browsercookielimits.squawky.net/

**Comment by inikulin** [comment]
@miherlosev According to specification cookie size shouldn't be limited. But for practical reasons we should set limit as well

**Comment by miherlosev** [comment]
Found in https://www.bankofamerica.com/
