### ISSUE TITLE
 'Invalid calling object' error appears in IE11 when active element is changed

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#768]
To reproduce:
1. Open via playground [internal page](http://builder03/Demos-15.2/ASPxGridViewDemos/UserControls/FullScreenViewer.aspx?url=/Demos-15.2/ASPxGridViewDemos/Adaptivity/AdaptiveLayoutWithFormLayoutPage.aspx&width=768&height=576)
2. Take any column header from second line and drop it to first line.

Hammerhead will throw the 'Invalid calling object' error, which leads to `activeElement` isn't dom element here:
![](https://cloud.githubusercontent.com/assets/15088565/18273184/d007857a-7444-11e6-9195-4f27e9bff29f.png)

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Looks like IE bug.
document.activeElement is empty object - see [video](http://screencast.com/t/obN6DOGBHnWi).

**Comment by AlexanderMoskovkin** [comment]
is it possible to reproduce this without hh-playground?

**Comment by miherlosev** [comment]
In progress...

**Comment by miherlosev** [comment]
Today I cann't reproduce on page from issue description.  @georgiy-abbasov  try to create simple example.
