### ISSUE TITLE
Wrong version number for Chrome 

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#777]
For 52 and 53 Chrome it returns `537`

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
In hammerhead.utils.browser we have 2 type of entities: browser engines (WebKit) and browsers (Firefox, IE, etc.).
For browser engines we calculate engine version, for browsers we calculate browser version.
We don't have `isChrome` property in `hammerhead.utils.browser`.
Therefore, we calculate the engine version for Google Chrome and behaviour that was described in issue is valid.

**Comment by miherlosev** [comment]
After discussing with @helen-dikareva we decide to do the following:
- new property `isChrome`
- split `browser.version` to `browser.version` and `browser.engineVersion`.
