### ISSUE TITLE
Script error for https://www.pixnet.net/

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#778]
see [video](http://screencast.com/t/7esy7U7WO)

**Comment by miherlosev** [comment]
In client code there are the following code:
```js
var img = document.createElement('img');
document.body.appendChild(img);
img.src = '//:0';
```
Browser doesn't perform request for this url.
After proxing we perform request to `http://<proxy-url>/sessionId/https://:0` and get 500 status code (Internal server error).

I am searching this case in specification...

**Comment by miherlosev** [comment]
According the https://github.com/whatwg/html/issues/1879#issuecomment-252598388,
I think we should check that url is valid (`window.URL` + fallback for IE9 - on client side, require('url') - on server side).
If url is not valid we shouldn't create a proxy url and leave it as is.
What do you think? @churkin @inikulin

**Comment by inikulin** [comment]
@miherlosev How we'll perform such check?

**Comment by miherlosev** [comment]
There is a new idea - just check 'host' part of URL. If it is empty - don't create proxy and leave URL as is.
