### ISSUE TITLE
Page reloaded after uploading

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#795]
http://builder03/Demos-15.2/ASPxEditorsDemos/ASPxBinaryImage/BinaryImageColumn.aspx
Steps to reproduce in hammerhead-playground:
1) Click on button 'Edit'
2) Upload some image
We need this fix for ASPx Tests for git hub vesion TestCafe. Please fix it ASAP.

**Comment by LavrovArtem** [comment]
this bug has been already debugged https://github.com/DevExpress/testcafe-hammerhead/issues/722

**Comment by helen-dikareva** [comment]
There is no iframe on this page

**Comment by LavrovArtem** [comment]
Try to search an iframe after "1) Click on button 'Edit'"

**Comment by helen-dikareva** [comment]
Ok, so mark this bug like duplicate and fix https://github.com/DevExpress/testcafe-hammerhead/issues/722

**Comment by churkin** [comment]
duplicated to #722
