### ISSUE TITLE
[Testing day 0.9.0-rc1] Script error during log in to http://mail.ru

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#797]
For reproduce you need account on http://mail.ru
see [video](http://screencast.com/t/NSqhfmvSrI)

**Comment by inikulin** [comment]
@miherlosev There is corresponding testcafe issue?

**Comment by inikulin** [comment]
**Update:** Found one more special page related issue: if resource with `about:blank` doesn't require processing - such request hangs forever.

**Comment by miherlosev** [comment]
I'm working on this
