### ISSUE TITLE
"Access denied" on lenta.ru in IE10

### ISSUE THREAD

**Issue by AndreyBelym** [DevExpress/testcafe-hammerhead#801]

**Comment by LavrovArtem** [comment]
```javascript
    var _ajax = new XMLHttpRequest();

    if (typeof XDomainRequest !== 'undefined') {
        _ajax = new XDomainRequest();
    }
```
We aren't override the XDomainRequest. The XDomainRequest is obsolete and non-standard. This class supports only in ie8, ie9 and ie10. https://developer.mozilla.org/en/docs/Web/API/XDomainRequest

Do we need to override this class? @churkin

**Comment by inikulin** [comment]
@LavrovArtem 
>  It was removed in Internet Explorer 10 in favor of using XMLHttpRequest with proper CORS

How it affects us in IE10?

**Comment by inikulin** [comment]
Hmm, for some reason it exists in IE10. @LavrovArtem I guess we can just mock it by using XHR

**Comment by LavrovArtem** [comment]
```javascript
        // NOTE: mock for ie9 and ie10
        if (window.XDomainRequest)
            window.XDomainRequest = window.XMLHttpRequest;
```
Do you mean this? @inikulin

**Comment by inikulin** [comment]
Yes, if it will work
