### ISSUE TITLE
[Migrate ASP Tests to TestCafe OS] Hammerhead doesn't inject scripts in iframe on any page of ASPxSpreadsheet demo

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#815]
e.g. on http://builder03/Demos-15.2/ASPxSpreadsheetDemos/SampleDocuments/ProfitAndLoss.aspx
It reproduced with hammerhead-playground
We need this fix for ASPx Tests for git hub vesion TestCafe. Please fix it ASAP.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Iframe contains `hammerhead`.
![Console](https://cloud.githubusercontent.com/assets/4133518/18785125/0fcba77e-819f-11e6-9c11-b1261c0d47d5.png)

It is not cause of origin bug.

**Comment by helen-dikareva** [comment]
ok, so we need go deeper

**Comment by helen-dikareva** [comment]
I'm sorry that I misled you, but now I've checked page in IE11 and ensure that there isn't hammerhead on page. Also we have problem in Chrome, but there hammerhead is on page and I'll investigate further with it.
![2016-09-23_1633](https://cloud.githubusercontent.com/assets/12034551/18787492/c1e2a140-81ab-11e6-8b12-07662f40eec7.png)

**Comment by miherlosev** [comment]
Ok. I reproduced issue.
