### ISSUE TITLE
PhantomJS: Script error on Object.defineProperty for DOM element and Event objects

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#823]
We setup events and dom elements in source and test code using `Object.defineProperty`.
But PhantomJS doesn't support this - see issue https://github.com/ariya/phantomjs/issues/13895.
Need to investigate way to drop using `Object.defineProperty`.

**Comment by churkin** [comment]
Maybe we should try https://github.com/ianstormtaylor/create-event/pull/9 solution?

**Comment by miherlosev** [comment]
I tried this dark magic and got that it works only for attribute properties.
For event properties it doesn't work.

Step to reproduce:
- download latest PhantomJS from http://phantomjs.org/download.html
- run `phantomjs test.js`

#### Test.js
```js
/*Dom element*/ /*Worked*/
console.log('Dom element');
console.log('document.body.attributes.length before redefine:', document.body.attributes.length);
document.body.attributes.constructor.prototype.__defineGetter__('length', function () {return 1000; }); //work
console.log('document.body.attributes.constructor.prototype.__defineGetter__:', document.body.attributes.length);
document.body.attributes.__defineGetter__('length', function () { return 2000; });// don't work
console.log('document.body.attributes.__defineGetter__:',document.body.attributes.length);



/*Event*/
console.log('Event');
var evt = document.createEvent('StorageEvent');

evt.initStorageEvent('storage',false,false,'key','oldValue','newValue', 'http://fabrikam.com/alleged.html', { test: 1 });
console.log('storageArea before redefine:', evt.storageArea);

evt.constructor.prototype.__defineGetter__('storageArea', function () { return window.sessionStorage; });//don't work
console.log('evt.constructor.prototype.__defineGetter__:', evt.storageArea);

evt.constructor.prototype.__defineGetter__.call(evt, 'storageArea', function () { return window.sessionStorage; });//dont't work
console.log('evt.constructor.prototype.__defineGetter__.call:', evt.storageArea);

evt.__defineGetter__('storageArea', function () { return window.sessionStorage; });//dont't work
console.log('evt.__defineGetter__:', evt.storageArea);

evt.__proto__.__defineGetter__('storageArea', function () { return window.sessionStorage; });//dont't work
console.log('evt.__proto__.__defineGetter__:', evt.storageArea);

window.StorageEvent.__defineGetter__.call(evt, 'storageArea', function () { return window.sessionStorage; });//don't work
console.log('window.StorageEvent.__defineGetter__:', evt.storageArea);
```

**Comment by miherlosev** [comment]
I found way to override properties of event object:
`evt = { get 'storageArea'() { return window.localStorage; } };`

**Comment by churkin** [comment]
@miherlosev how it will help us? :)

**Comment by miherlosev** [comment]
List of properties that we should override using code instrumentation (in progess...)

**Comment by miherlosev** [comment]
Update:
Solution 
`document.body.attributes.constructor.prototype.__defineGetter__('length', function () {return 1000; }); ` is wrong.
It override geter on `document.body.attributes.constructor.prototype level.
After it all `attributes.length` wil return 1000 for all dom nodes.

**Comment by miherlosev** [comment]
In total we cannot override properties of DOM elements and event properties in PhantomJS.

**Comment by miherlosev** [comment]
PhantomJS is died.
https://groups.google.com/forum/#!msg/phantomjs/9aI5d-LDuNE/5Z3SMZrqAQAJ
