### ISSUE TITLE
PhantomJS: Add 'Upload' support

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#829]
PhantomJS hasn't `fileRead.readAsDataURL` method that used in `InfoManager.loadFileListData`.
So we should use another way to support 'Upload' functionality.

**Comment by miherlosev** [comment]
@LavrovArtem I was wrong.
We have two failed tests in `/fixtures/sandbox/event/unload-test.js`.
1. `get uploaded file error: single file`.
2. `get uploaded file error: multi file`.

Aparently, there is a problem with fileReader events ('load').

**Comment by LavrovArtem** [comment]
I was wrong. The `FileReader` works fine. The `dispatchEvent` works fine. Problem with `Object.defineProperty` in tests.
