### ISSUE TITLE
Travis CI: cache node_modules

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#831]
`npm install` took a lot of time.
Travis has build-in support of the caching dependencies.
https://docs.travis-ci.com/user/caching/
https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/

Try to use this feature in our builds.

**Comment by AlexanderMoskovkin** [comment]
I'm not sure we can use it because

> Note that this feature is currently only available for private repositories.

but I'll check it

**Comment by AlexanderMoskovkin** [comment]
After an investigation we've found out it's not very useful for us now (see https://github.com/DevExpress/testcafe-hammerhead/pull/832)
