### ISSUE TITLE
Links in google bar are not proxied on https://calendar.google.com/calendar/

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#845]
Go to https://calendar.google.com/calendar/ and try links in GoogleBar (menu with links to other Google services) - they are not proxied

**Comment by LavrovArtem** [comment]
Our server parser doesn't understand `<plaintext/>` self-closing tag. Therefore he considers as plain text all html after it.

**Comment by inikulin** [comment]
It's 100% not parser issue, unless document is XHTML. Can you confirm it?

**Comment by inikulin** [comment]
Any content after `<plaintext>` tag is considered to be a text. It can't be self-closing. Browsers behaves the same way. It's seems like that content is processed later by script. So you need to dig deeper, issues occurs later in programmatical DOM construction.

**Comment by inikulin** [comment]
I've just researched it a little bit and found out that it handled correctly by hammerhead, open `<xmp>` tag generated by client script before `<plaintext>`, so while on server this content considered to be a text on client side it's escaped and we have a complete markup. It answers the question why it's not processed on server (it shouldn't though). But why it's not processed on client side? Or we don't have any kind of final pass on document ready?

**Comment by inikulin** [comment]
@LavrovArtem ping me tomorrow to discuss this one

**Comment by LavrovArtem** [comment]
Example:
```html
<script>document.write('<xmp>')</script><plaintext></xmp>
<a href="http://some.domain.com/">not processed anchor</a>
```
