### ISSUE TITLE
Link in vk.com profile doesn't work

### ISSUE THREAD

**Issue by inikulin** [DevExpress/testcafe-hammerhead#846]
Open any vk.com profile, e.g. https://vk.com/durov. Click any external link, e.g. `Telegram` - navigation will not occur.

**Comment by churkin** [comment]
```javascript
w._opener.contentWindow.open(href, '_blank');
```
`vk.com` opens external links in the new tab through the internal iframe. We are changing `_blank` to `_self` and actually change iframe window location.

**Comment by churkin** [comment]
we should try to change `_blank` to `_top` instead of '_self'
