### ISSUE TITLE
Investigate how much performance will decrease if load all images through a proxy

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#870]
We have many problems because images don't proxy:
- workaround for [this](https://github.com/DevExpress/testcafe-hammerhead/issues/651) problem with a cookie set through image.
- and [this](https://github.com/DevExpress/testcafe-hammerhead/issues/850) problem. The solution of which is seen only in the [synchronous xhr](http://stackoverflow.com/a/19973880).
- and a lot of potential problems with some one-pixel pictures with cookies and another data.

**Comment by inikulin** [comment]
It will decrease significantly, we've already did it.

**Comment by churkin** [comment]
I have created site with 60 images (~15Kb each).

Page load event:
    - with proxy **76** ms
    - without proxy - **33** ms

We practically do not get anything from this.

**Comment by inikulin** [comment]
> Page load event:
- with proxy 76 ms
- without proxy - 33 ms

> We practically do not get anything from this.


What?

**Comment by churkin** [comment]
speed up load time

**Comment by miherlosev** [comment]
Try to use health monitor for this (large count sites, real pages with real count and size images, etc.)

**Comment by churkin** [comment]
We will not do it
