### ISSUE TITLE
Iframe init script `INIT_SCRIPT_FOR_IFRAME_TEMPLATE` isn't executing in IE11

### ISSUE THREAD

**Issue by georgiy-abbasov** [DevExpress/testcafe-hammerhead#871]
Iframe init script `INIT_SCRIPT_FOR_IFRAME_TEMPLATE` isn't executing (and removing then), but appends to body and head in IE11. As result - we have extra node.
[Internal link](http://172.22.7.46:8080/RegressionTestsSite/ASPxSpreadsheet/Initial/Blank.aspx) to reproduce. 
Hint: the iframe is created [here](http://screencast.com/t/198oxHjzmm) and changed [here](http://screencast.com/t/d41fkxu1LkSP)

**Comment by LavrovArtem** [comment]
IE doesn't run scripts in iframe if `iframe.documentContent.designMode` equals `on`
```html
<iframe></iframe>
<script>
    var iframe = document.querySelector('iframe');
    var idocument = iframe.contentDocument;

    idocument.designMode = 'on';
    idocument.open();
    idocument.write(
        '<body style=\"padding: 0; margin: 0; overflow: hidden;\">',
        '<script>',
        '    alert("run")',
        '<\/script>',
        '</body>');
    idocument.close();
</script>
```
