### ISSUE TITLE
There is no way to set cookie

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#899]
https://testcafe-discuss.devexpress.com/t/set-cookies-on-client-side/65
reproduced with playground:
![cookie](https://cloud.githubusercontent.com/assets/12034551/19882749/ef89b30c-a020-11e6-8106-51f5b8104566.png)

**Comment by helen-dikareva** [comment]
We found an another problem: 
If we trying to set cookie with non-proxing domain hammerhead clearing up cookie. To set cookine in this case we should specify proxied domain.
![cookie new2](https://cloud.githubusercontent.com/assets/12034551/19885599/888fd93c-a030-11e6-88ba-3f81db0d7ca8.png)

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by miherlosev** [comment]
Found two problems:
- wrong work setting cookie without key
- wrong cookie validation for non `http` domain
