### ISSUE TITLE
Override WebSocket class

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#911]
Request for socket opening sends the 'cookie' header with `document.cookie` value, but we don't write cookie in `document.cookie`, we save cookie in hammehread's settings.

https://testcafe-discuss.devexpress.com/t/set-cookies-on-client-side/65/6

**Comment by LavrovArtem** [comment]
Also need for Angular 4

**Comment by johnwebbcole** [comment]
This one is biting me as well... our session id is in in the cookie and we need that to authenticate the web socket request.  Any timeframe on fixing this?  I'm running testcafe 0.17.2.

**Comment by miherlosev** [comment]
I cannot provide an exact timeframe for this task.
But, we've planned to do this in the current development sprint (it ends in 2 weeks).
If we don't have time then the task will be moved to the next sprint.

**Comment by drgnorq** [comment]
Same issue here. We need to be able to extract the cookie header form websocket connection request, so we can authenticate the websocket request. In 0.17.2 (and also the 0.18 alpha version) the request.cookie header is missing. Hopefully the patch will be available soon. Let me know if we can help testing new versions. Hopefully this new version will also take into account the cookie flags (http only and/or secure). It would be very nice if we could modify the flags of cookies maintained by hammerhead from our test script.
