### ISSUE TITLE
Avoid processing documentFragmentNode on the server side

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#912]
http://todomvc.com/examples/polymer/index.html

reproduced in playground. Tested in Chrome but should be check in other browsers

**Comment by georgiy-abbasov** [comment]
Simplified page markup for reproducing
```html
<body>
    <template is="dom-bind">
        <td-model id="model" items="{{todos}}"></td-model>
        <td-todos model-id="model" items="{{todos}}"></td-todos>
    </template>
</body>
```

**Comment by AlexanderMoskovkin** [comment]
@georgiy-abbasov Are you working on it?

**Comment by georgiy-abbasov** [comment]
Yes, it is

**Comment by nickkoss** [comment]
Should this change also be applied to _processElement function? I.e.:

`NodeSandbox.prototype._processElement = function _processElement(el) {`
...
`if (processedContext && el.node !== '#document-fragment') {
  urlAttrName = _domProcessor2.default.getUrlAttr(el);
  urlAttrName = el.hasAttribute(urlAttrName) ? urlAttrName : null}
}
`
Otherwise, it trips up loading a doc fragment with an error that hasAttribute is not a function.

**Comment by LavrovArtem** [comment]
I'll investigate it.

**Comment by LavrovArtem** [comment]
I don't understand how a `document-fragment` is passed to the `_processElement` function. Could you please provide more information about it?

**Comment by nickkoss** [comment]
In our particular app, we do a lot of asynchronous loading into an iframe. One case is loading other pages into a documentFragment via appendChild method. For example:
`iframe.onload = function iframeOnLoad() {`
`var pageFrag = document.createDocumentFragment();`
`...`
`//Load some pages into page variable`
`for(var i=0; i<somecondition;i++){`
`var page = someLogicHere();`
`pageFrag.appendChild(page);`
`...`
`}`
`...`
`iframe.appendChild(pageFrag);`

Hammerhead deals with this fine for most part, but, as I mentioned above it encounters issues if the nodeType is documentFragment. So far, filtering it out in the `_proccessElement` function has been an effective solution.

**Comment by LavrovArtem** [comment]
I've reproduced the bug on the next example page:
```html
<body>
    <script>
        var iframe = document.createElement('iframe');

        iframe.addEventListener('load', function () {
            var pageFrag = document.createDocumentFragment();

            iframe.contentDocument.body.appendChild(pageFrag);
        });

        document.body.appendChild(iframe);
    </script>
</body>
```
@nickkoss Thanks for the clarification.
