### ISSUE TITLE
[todomvc] Js-error appears on the Chaplin demo page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#915]
page: http://todomvc.com/examples/chaplin-brunch/public/
error: `Uncaught TypeError: Cannot read property 'className' of null`

reproduced in playground. Tested in Chrome but should be checked in other browsers

**Comment by AlexanderMoskovkin** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
I've reproduced the problem on the original page if I set 'GPRS (500ms, 50kb/s, 20kb/s)' network throttling in Chrome Dev Tools:
![2016-11-09_1352](https://cloud.githubusercontent.com/assets/12047804/20136008/d1ac73a6-a683-11e6-891d-e858af2df3b0.png)

The problem is in the following. There are some scripts in the page header.
```html
<head>
    <script src="a"></sciprt>
    <script src="b"></sciprt>
    ...
    <script src="z"></sciprt>
</head>
```

Script `a` does the following:
```js
var xhr = new XMLHttpRequest();

xhr.open('GET', someurl, true);
xhr.onload = function (e) {
    document.body.className = document.body.className + 'something else';
};
xhr.send();
```

What happens when the network connection is ok:
- at start when scripts from `<head>` are executing `document.body` is null
- script `a` sends a xhr-request
- scripts `b-z` are executed
- browser appends `<body>` to markup (after scripts from `<head>` are executed)
- script `a` gets response for its xhr-request and successfully execute script with `document.body.className`

What happens when the connection is slow:
- at start when scripts from `<head>` are executing `document.body` is null
- script `a` sends a xhr-request
- scripts `b-z` downloading takes some more time. As a result script `a` gets the response while scripts `b-z` are in downloading.
- as a result script `a` fails with `document.body is null` error.

The same happens when the page is proxied by hammerhead. Script `a` gets a response for its request before hammerhead finished scripts processing `b-z` on the server-side.

Hope the cause of the issue is clear from my description.
I don't see a way how we can fix it on the `testcafe-hammerhead` side. /cc @inikulin @churkin

**Comment by inikulin** [comment]
The question is why we so extremely slow. Maybe we could do prefetch for scripts in head before sending page response in hammerhead?

**Comment by AlexanderMoskovkin** [comment]
FYI: I've reproduced the problem on the original page with the following network settings: Good 3G (40ms, 1.5Mb/s, 750kb/s). So, I can't say the we are extremely slow, but I agree we can figure out how we can be faster there

**Comment by churkin** [comment]
We can make resources preloading, but I think in this case it is a site problem
