### ISSUE TITLE
[todomvc] Js-error appears on the on the VanillaJS demo page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#922]
pages: http://todomvc.com/examples/vanillajs/ http://todomvc.com/examples/vanilla-es6
error: `Uncaught TypeError: Cannot set property 'className' of null`

reproduced in playground. Tested in Chrome but should be checked in other browsers

**Comment by georgiy-abbasov** [comment]
I'm working on this
