### ISSUE TITLE
[todomvc] Js-error appears on the on the Dart demo page

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [DevExpress/testcafe-hammerhead#928]
page: http://todomvc.com/examples/vanilladart/build/web/
error: `app.dart.js:4650 Uncaught TypeError: Cannot read property 'gDD' of null(…)`

reproduced in playground. Tested in Chrome but should be checked in other browsers

**Comment by LavrovArtem** [comment]
I'm working on this

**Comment by LavrovArtem** [comment]
Duplicate on #922
