### ISSUE TITLE
Add mechanism to skip your Shadow-ui root element even if it is not last child of body

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#933]
In some cases this approach may keep operability of page. 
For example it would help with https://github.com/DevExpress/testcafe/issues/958 
Previously root wasn't last body child and nexSibling method return null during bypass of elements, it broke markup.
discussed with @churkin

**Comment by churkin** [comment]
I think it is unnecessary, it is enough that the ShadowUI root element was always the last
