### ISSUE TITLE
[todomvc2] - js error (http://todomvc.com/examples/angular-dart/web)

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#955]
main.dart.js:2473 Uncaught Error: Illegal argument(s)(…)

**Comment by churkin** [comment]
I'm working on this

**Comment by churkin** [comment]
First problem - we adds the `autocomplete="off"` attribute for a input. `main.dart.js` does not expect it.

**Comment by miherlosev** [comment]
We always add `autocomplete` attribute (default value is `on` and we must do this to prevent browser autocompletion).
So, we should hide this attribute from enumerations and existence check: `el.attributes`, `el.hasAttribute`, `el.hasAttributes`.

**Comment by churkin** [comment]
Second problem - code on the page:
```javascript
Object.defineProperty(window.Storage.prototype, 'prop', , {...});

var value = sessionStorage['prop'];
```
We replaces `sessionStorage` to our wrapper, and it doesn't contain `prop` property.
