### ISSUE TITLE
Code instrumentation of the 'lenght' property is very slow

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#979]
See [video](http://screencast.com/t/9cFK4zvr0)

Url for reproduce - http://demos.devexpress.com/bootstrap/GridView/Editing.aspx

On video we see that cascading comboboxes close very slowly.

Profiling result:
![Profing result](https://cloud.githubusercontent.com/assets/4133518/20795736/b92feeea-b7e3-11e6-84fc-e97067f69836.png)

`IsShadowContainerCollection` affects about 38 percent of the time.

Need to speed up instrumentation of this property.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by AlexanderMoskovkin** [comment]
Is there any progress here?

**Comment by miherlosev** [comment]
Need an additional time

**Comment by miherlosev** [comment]
Our stuff (shadow ui scripts and styles) are last child nodes for `body` and `head` tags.
We can improove perfomance if we will redefine `lenght` for these nodes for appropriate case (`appendChild`, `insertBefore`, `removeChild`).
In this case we can remove code instrumentation for `length` property.

**Comment by romanresh** [comment]
Any news?

**Comment by miherlosev** [comment]
The task is in progress
