### ISSUE TITLE
Result of querySelectorAll has wrong type

### ISSUE THREAD

**Issue by miherlosev** [DevExpress/testcafe-hammerhead#980]
Method `document.querySelectorAll` returns `Array`. 
But it should returns `NodeList`.
Same for `getElementsByClassName`, `getElementsByName`, `getElementsByTagName`.

**Comment by miherlosev** [comment]
`document.querySelectorAll` returns non-live NodeList collection.
`getElementsByClassName`, `getElementsByName`, `getElementsByTagName` return live collections

**Comment by LavrovArtem** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/NodeList
>In some cases, the NodeList is a live collection, which means that changes in the DOM are reflected in the collection. For example, Node.childNodes is live.

> In other cases, the NodeList is a static collection, meaning any subsequent change in the DOM does not affect the content of the collection. document.querySelectorAll() returns **a static NodeList**.

**Comment by miherlosev** [comment]
`NodeList` has not public constructor. So, we cann't create instances of `NodeList`.
We will set  appropriate prototype for result collection.
It will be done during fix https://github.com/DevExpress/testcafe-hammerhead/issues/1111
