### ISSUE TITLE
We should process "formaction" attribute

### ISSUE THREAD

**Issue by churkin** [DevExpress/testcafe-hammerhead#988]

**Comment by churkin** [comment]
I think it's time to refactoring our `setAttributeCore` method. We should create common function for the `ElementSandbox` and the DomProcessor. This method should returns list of changed attributes for the element.

**Comment by LavrovArtem** [comment]
@churkin good idea

**Comment by churkin** [comment]
@LavrovArtem Do you want to do it? :)

**Comment by LavrovArtem** [comment]
@churkin I'm working on https://github.com/DevExpress/testcafe-hammerhead/issues/987 issue
