### ISSUE TITLE
Figure out how we may to emulate meta[name="referrer"] tag behavior

### ISSUE THREAD

**Issue by LavrovArtem** [DevExpress/testcafe-hammerhead#997]
We have a problem with it on https://login.yahoo.com

![image](https://cloud.githubusercontent.com/assets/5373460/21259716/b3e30a7e-c393-11e6-9042-4d31fe831e63.png)

This page contains `meta[name="referrer"]` tag because of which we have the referrer with `http://localhost:1401` value
`<meta name="referrer" content="origin-when-cross-origin">`

[specification](https://www.w3.org/TR/referrer-policy/#referrer-policies), [workaround for \<meta name="referrer" content="origin"\>](https://github.com/DevExpress/testcafe-hammerhead/blob/a5f8127a1c571280b792d61424b6ab33da2724f9/src/processing/resources/page.js#L102)

**Comment by miherlosev** [comment]
Fixed. Now we set the `unsafe-url` value for this.
