### ISSUE TITLE
Wrong proxing Function.prototype.toString that was overriden in customer script

### ISSUE THREAD

**Issue by helen-dikareva** [DevExpress/testcafe-hammerhead#999]
Only in Chrome on iPad.

Page from SC Infinite page T461403:
https://staging.lostmy.name/personalized-products/lost-my-name-book/preview?customisation_locale=en-GB&gender=boy&name=Chris&phototype=type-iii

Reproduced with hammerhead playground, sometimes chrome closes during opening this page in playground.

**Comment by miherlosev** [comment]
I'm working on this

**Comment by miherlosev** [comment]
I think I reproduced the issue on desktop version ()
see [video](http://screencast.com/t/bRTmqAHdj9)

**Comment by helen-dikareva** [comment]
Cool, it's event better
